// Generated for مطعم أبو الزلف (Abou El Zelouf) — Istanbul. Source: abou-elzelouf.com (images downloaded locally)
const abouStore = {
 "id": 24,
 "name": "مطعم أبو الزلف",
 "category": "مطاعم",
 "image": "/assets/photos/abou/cover.jpg",
 "coverImage": "/assets/photos/abou/cover.jpg",
 "logoImage": "/assets/photos/abou/cover.jpg",
 "logo": "أ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "40 - 70 دقيقة",
 "distance": 18,
 "location": {
  "lat": 41.0258,
  "lng": 28.6772
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=Abou+El+Zelouf+Restaurant+Istanbul",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم أبو الزلف — مطبخ شرقي وغربي في إسطنبول: الفطور والشوربات والمقبلات الباردة والساخنة، المشاوي والمأكولات على الفحم، الشاورما والسندويشات، الأطباق الشرقية والغربية، الحلويات والعصائر والمشروبات. الأسماء والأسعار كما في القائمة الرسمية للمطعم.",
 "address": "إسطنبول، تركيا",
 "phone": "+90 552 252 35 23",
 "whatsapp": "+90 552 252 35 23",
 "email": "",
 "website": "https://www.abou-elzelouf.com/",
 "sourceUrl": "https://www.abou-elzelouf.com/en",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const abouProductCatalog = [
 {
  "sourceId": "abou-2",
  "name": "فطور الضيعة شخص",
  "image": "/assets/photos/abou/items/item-001.webp",
  "price": 425,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "فطور الضيعة شخص من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-3",
  "name": "فول بحمض وزيت",
  "image": "/assets/photos/abou/items/item-002.webp",
  "price": 225,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "فول بحمض وزيت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-4",
  "name": "فول بالطحينه",
  "image": "/assets/photos/abou/items/item-003.webp",
  "price": 225,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "فول بالطحينه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-5",
  "name": "فتة بالسمنة",
  "image": "/assets/photos/abou/items/item-004.webp",
  "price": 250,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "فتة بالسمنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-6",
  "name": "فتة بالزيت",
  "image": "/assets/photos/abou/items/item-005.webp",
  "price": 250,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "فتة بالزيت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-7",
  "name": "( ٩ حبات ) صحن فلافل",
  "image": "/assets/photos/abou/items/item-006.webp",
  "price": 170,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "( ٩ حبات ) صحن فلافل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-8",
  "name": "بيض سادة",
  "image": "/assets/photos/abou/items/item-007.webp",
  "price": 170,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "بيض سادة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-9",
  "name": "بيض مع خضار",
  "image": "/assets/photos/abou/items/item-008.webp",
  "price": 185,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "بيض مع خضار من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-10",
  "name": "جظ مظ",
  "image": "/assets/photos/abou/items/item-009.webp",
  "price": 185,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "جظ مظ من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-11",
  "name": "بيض مع قشقوان",
  "image": "/assets/photos/abou/items/item-010.webp",
  "price": 185,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "بيض مع قشقوان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-12",
  "name": "بيض مع سجق",
  "image": "/assets/photos/abou/items/item-011.webp",
  "price": 185,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "بيض مع سجق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-13",
  "name": "صحن جبنة",
  "image": "/assets/photos/abou/items/item-012.webp",
  "price": 150,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "صحن جبنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-14",
  "name": "صحن مكدوس",
  "image": "/assets/photos/abou/items/item-013.webp",
  "price": 170,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "صحن مكدوس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-15",
  "name": "صحن لبنة مع الخضار",
  "image": "/assets/photos/abou/items/item-014.webp",
  "price": 150,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "صحن لبنة مع الخضار من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-16",
  "name": "صحن قشطة وعسل",
  "image": "/assets/photos/abou/items/item-015.webp",
  "price": 150,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "صحن قشطة وعسل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-17",
  "name": "صحن مربى",
  "image": "/assets/photos/abou/items/item-016.webp",
  "price": 150,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "صحن مربى من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-18",
  "name": "صحن زيتون",
  "image": "/assets/photos/abou/items/item-017.webp",
  "price": 135,
  "unit": "",
  "category": "منفطر ومنحكي",
  "available": true,
  "featured": false,
  "description": "صحن زيتون من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-75",
  "name": "شوربة العدس",
  "image": "/assets/photos/abou/items/item-018.webp",
  "price": 135,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة العدس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-76",
  "name": "شوربة الفطر",
  "image": "/assets/photos/abou/items/item-019.webp",
  "price": 150,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة الفطر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-77",
  "name": "شوربة الذرة",
  "image": "/assets/photos/abou/items/item-020.webp",
  "price": 150,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة الذرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-47",
  "name": "فتوش الاكابر",
  "image": "/assets/photos/abou/items/item-021.webp",
  "price": 250,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "فتوش الاكابر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-48",
  "name": "تبولة الحلوين",
  "image": "/assets/photos/abou/items/item-022.webp",
  "price": 250,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "تبولة الحلوين من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-49",
  "name": "سلطة شرقية وطنية",
  "image": "/assets/photos/abou/items/item-023.webp",
  "price": 225,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "سلطة شرقية وطنية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-50",
  "name": "سلطة روكا",
  "image": "/assets/photos/abou/items/item-024.webp",
  "price": 250,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "سلطة روكا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-51",
  "name": "سلطة ميكس",
  "image": "/assets/photos/abou/items/item-025.webp",
  "price": 360,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "سلطة ميكس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-52",
  "name": "حمص ناعم",
  "image": "/assets/photos/abou/items/item-026.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "حمص ناعم من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-53",
  "name": "حمص بيروتي",
  "image": "/assets/photos/abou/items/item-027.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "حمص بيروتي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-54",
  "name": "حمص باللحمة",
  "image": "/assets/photos/abou/items/item-028.webp",
  "price": 340,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "حمص باللحمة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-55",
  "name": "متبل يا حيف",
  "image": "/assets/photos/abou/items/item-029.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "متبل يا حيف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-56",
  "name": "بابا غنوج",
  "image": "/assets/photos/abou/items/item-030.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "بابا غنوج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-57",
  "name": "ماما محمرة",
  "image": "/assets/photos/abou/items/item-031.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "ماما محمرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-58",
  "name": "يالانجي ( ٥ حبات )",
  "image": "/assets/photos/abou/items/item-032.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "يالانجي ( ٥ حبات ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-59",
  "name": "مقبلات ميكس",
  "image": "/assets/photos/abou/items/item-033.webp",
  "price": 390,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "مقبلات ميكس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-60",
  "name": "سلطة زيتون",
  "image": "/assets/photos/abou/items/item-034.webp",
  "price": 200,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "سلطة زيتون من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-61",
  "name": "سلطة دايت",
  "image": "/assets/photos/abou/items/item-035.webp",
  "price": 390,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "سلطة دايت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-62",
  "name": "صحن سرفيس",
  "image": "/assets/photos/abou/items/item-036.webp",
  "price": 100,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "صحن سرفيس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-64",
  "name": "كريم ثوم",
  "image": "/assets/photos/abou/items/item-037.webp",
  "price": 95,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "كريم ثوم من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-270",
  "name": "فتوش برو ماكس",
  "image": "/assets/photos/abou/items/item-038.webp",
  "price": 290,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "فتوش برو ماكس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-276",
  "name": "سلطة الراهب",
  "image": "/assets/photos/abou/items/item-039.webp",
  "price": 290,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "سلطة الراهب من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-277",
  "name": "حمص مع محمرة",
  "image": "/assets/photos/abou/items/item-040.webp",
  "price": 215,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "حمص مع محمرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-278",
  "name": "متبل مع بابا غنوج",
  "image": "/assets/photos/abou/items/item-041.webp",
  "price": 215,
  "unit": "",
  "category": "المقبلات الباردة",
  "available": true,
  "featured": false,
  "description": "متبل مع بابا غنوج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-65",
  "name": "بطاطا كلاسيك",
  "image": "/assets/photos/abou/items/item-042.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "بطاطا كلاسيك من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-69",
  "name": "كبة مقلية",
  "image": "/assets/photos/abou/items/item-043.webp",
  "price": 145,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "كبة مقلية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-70",
  "name": "كبة مشوية",
  "image": "/assets/photos/abou/items/item-044.webp",
  "price": 170,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "كبة مشوية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-71",
  "name": "رول سجق",
  "image": "/assets/photos/abou/items/item-045.webp",
  "price": 305,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "رول سجق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-72",
  "name": "جبنة مشوية",
  "image": "/assets/photos/abou/items/item-046.webp",
  "price": 170,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "جبنة مشوية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-73",
  "name": "برك جبنة",
  "image": "/assets/photos/abou/items/item-047.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "برك جبنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-74",
  "name": "بطاطا حرة",
  "image": "/assets/photos/abou/items/item-048.webp",
  "price": 240,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "بطاطا حرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-272",
  "name": "بطاطا مع بشاميل و قشقوان",
  "image": "/assets/photos/abou/items/item-049.webp",
  "price": 340,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "بطاطا مع بشاميل و قشقوان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-274",
  "name": "مفركة البطاطا",
  "image": "/assets/photos/abou/items/item-050.webp",
  "price": 335,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "مفركة البطاطا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-275",
  "name": "مفركة الفطر",
  "image": "/assets/photos/abou/items/item-051.webp",
  "price": 335,
  "unit": "",
  "category": "المقبلات الساخنة",
  "available": true,
  "featured": false,
  "description": "مفركة الفطر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-113",
  "name": "فروج عالفحم ( شخص )",
  "image": "/assets/photos/abou/items/item-052.webp",
  "price": 485,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "فروج عالفحم ( شخص ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-114",
  "name": "فروج عالفحم ( شخصين )",
  "image": "/assets/photos/abou/items/item-053.webp",
  "price": 920,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "فروج عالفحم ( شخصين ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-115",
  "name": "شيش طاووق ( وجبة )",
  "image": "/assets/photos/abou/items/item-054.webp",
  "price": 460,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-116",
  "name": "شيش طاووق ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-055.webp",
  "price": 770,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-117",
  "name": "شيش طاووق ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-056.webp",
  "price": 1540,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-118",
  "name": "كباب حلبي ( وجبة )",
  "image": "/assets/photos/abou/items/item-057.webp",
  "price": 570,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب حلبي ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-119",
  "name": "كباب حلبي ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-058.webp",
  "price": 1130,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب حلبي ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-120",
  "name": "كباب حلبي ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-059.webp",
  "price": 2260,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب حلبي ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-121",
  "name": "كباب مع بقدونس ( وجبة )",
  "image": "/assets/photos/abou/items/item-060.webp",
  "price": 570,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب مع بقدونس ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-122",
  "name": "كباب مع بقدونس ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-061.webp",
  "price": 1130,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب مع بقدونس ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-123",
  "name": "كباب مع بقدونس ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-062.webp",
  "price": 2260,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب مع بقدونس ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-124",
  "name": "كباب اضنة ( وجبة )",
  "image": "/assets/photos/abou/items/item-063.webp",
  "price": 570,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب اضنة ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-125",
  "name": "كباب اضنة ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-064.webp",
  "price": 1130,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب اضنة ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-126",
  "name": "كباب اضنة ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-065.webp",
  "price": 2260,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب اضنة ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-127",
  "name": "شقف مشوية ( وجبة )",
  "image": "/assets/photos/abou/items/item-066.webp",
  "price": 730,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "شقف مشوية ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-128",
  "name": "شقف مشوية ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-067.webp",
  "price": 1600,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "شقف مشوية ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-129",
  "name": "شقف مشوية ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-068.webp",
  "price": 3200,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "شقف مشوية ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-130",
  "name": "كبة قصابية ( وجبة )",
  "image": "/assets/photos/abou/items/item-069.webp",
  "price": 570,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كبة قصابية ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-131",
  "name": "كبة قصابية ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-070.webp",
  "price": 1130,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كبة قصابية ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-132",
  "name": "كبة قصابية ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-071.webp",
  "price": 2260,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كبة قصابية ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-133",
  "name": "مشاوي مشكلة ( وجبة )",
  "image": "/assets/photos/abou/items/item-072.webp",
  "price": 650,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "مشاوي مشكلة ( وجبة ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-134",
  "name": "مشاوي مشكلة ( ٥٠٠ غرام )",
  "image": "/assets/photos/abou/items/item-073.webp",
  "price": 1200,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "مشاوي مشكلة ( ٥٠٠ غرام ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-135",
  "name": "مشاوي مشكلة ( ١ كغ )",
  "image": "/assets/photos/abou/items/item-074.webp",
  "price": 2400,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "مشاوي مشكلة ( ١ كغ ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-136",
  "name": "لحمة بالصينية - 500 غرام",
  "image": "/assets/photos/abou/items/item-075.webp",
  "price": 1130,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "لحمة بالصينية - 500 غرام من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-137",
  "name": "لحمة بالصينية - 1000 غرام",
  "image": "/assets/photos/abou/items/item-076.webp",
  "price": 2260,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "لحمة بالصينية - 1000 غرام من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-138",
  "name": "معجوقة",
  "image": "/assets/photos/abou/items/item-077.webp",
  "price": 750,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "معجوقة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-139",
  "name": "مبرومة أبو الزلف",
  "image": "/assets/photos/abou/items/item-078.webp",
  "price": 800,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "مبرومة أبو الزلف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-269",
  "name": "وجبة كبب مشكلة",
  "image": "/assets/photos/abou/items/item-079.webp",
  "price": 680,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "وجبة كبب مشكلة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-281",
  "name": "كباب بقلاوة مع العسل",
  "image": "/assets/photos/abou/items/item-080.webp",
  "price": 600,
  "unit": "",
  "category": "كش وشوي",
  "available": true,
  "featured": false,
  "description": "كباب بقلاوة مع العسل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-140",
  "name": "عرايس غنم",
  "image": "/assets/photos/abou/items/item-081.webp",
  "price": 545,
  "unit": "",
  "category": "خبزة على الفحم",
  "available": true,
  "featured": false,
  "description": "عرايس غنم من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-141",
  "name": "توشكا مشوية",
  "image": "/assets/photos/abou/items/item-082.webp",
  "price": 575,
  "unit": "",
  "category": "خبزة على الفحم",
  "available": true,
  "featured": false,
  "description": "توشكا مشوية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-142",
  "name": "سجق على الفحم",
  "image": "/assets/photos/abou/items/item-083.webp",
  "price": 575,
  "unit": "",
  "category": "خبزة على الفحم",
  "available": true,
  "featured": false,
  "description": "سجق على الفحم من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-143",
  "name": "ماريا مشوية",
  "image": "/assets/photos/abou/items/item-084.webp",
  "price": 545,
  "unit": "",
  "category": "خبزة على الفحم",
  "available": true,
  "featured": false,
  "description": "ماريا مشوية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-78",
  "name": "شاورما دجاج مشوية",
  "image": "/assets/photos/abou/items/item-085.webp",
  "price": 355,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج مشوية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-79",
  "name": "شاورما لحمة مشوية",
  "image": "/assets/photos/abou/items/item-086.webp",
  "price": 420,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما لحمة مشوية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-80",
  "name": "شاورما ميكس",
  "image": "/assets/photos/abou/items/item-087.webp",
  "price": 390,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما ميكس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-144",
  "name": "سندويش شيش طاووق",
  "image": "/assets/photos/abou/items/item-088.webp",
  "price": 190,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش شيش طاووق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-145",
  "name": "سندويش شاورما دجاج",
  "image": "/assets/photos/abou/items/item-089.webp",
  "price": 190,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما دجاج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-146",
  "name": "سندويش شاورما لحمة",
  "image": "/assets/photos/abou/items/item-090.webp",
  "price": 225,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما لحمة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-147",
  "name": "سندويش كريسبي",
  "image": "/assets/photos/abou/items/item-091.webp",
  "price": 190,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش كريسبي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-148",
  "name": "سندويش زنجر",
  "image": "/assets/photos/abou/items/item-092.webp",
  "price": 190,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش زنجر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-149",
  "name": "سندويش فاهيتا",
  "image": "/assets/photos/abou/items/item-093.webp",
  "price": 190,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش فاهيتا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-150",
  "name": "سندويش مكسيكانو",
  "image": "/assets/photos/abou/items/item-094.webp",
  "price": 190,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش مكسيكانو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-151",
  "name": "سندويش كباب",
  "image": "/assets/photos/abou/items/item-095.webp",
  "price": 215,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش كباب من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-152",
  "name": "سندويش كباب أضنة",
  "image": "/assets/photos/abou/items/item-096.webp",
  "price": 215,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش كباب أضنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-153",
  "name": "سندويش كباب مع بقدونس",
  "image": "/assets/photos/abou/items/item-097.webp",
  "price": 215,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش كباب مع بقدونس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-154",
  "name": "سندويش بتاتة",
  "image": "/assets/photos/abou/items/item-098.webp",
  "price": 120,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش بتاتة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-260",
  "name": "سندويش سجق",
  "image": "/assets/photos/abou/items/item-099.webp",
  "price": 215,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش سجق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-261",
  "name": "سندويش خاروف",
  "image": "/assets/photos/abou/items/item-100.webp",
  "price": 250,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش خاروف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-262",
  "name": "سندويش صاصيجو",
  "image": "/assets/photos/abou/items/item-101.webp",
  "price": 215,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "سندويش صاصيجو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-265",
  "name": "وجبة برغر لحم مع بطاطا",
  "image": "/assets/photos/abou/items/item-102.webp",
  "price": 405,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "وجبة برغر لحم مع بطاطا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-266",
  "name": "وجبة برجر دجاج مع بطاطا",
  "image": "/assets/photos/abou/items/item-103.webp",
  "price": 330,
  "unit": "",
  "category": "السندويش الخارجي",
  "available": true,
  "featured": false,
  "description": "وجبة برجر دجاج مع بطاطا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-282",
  "name": "وجبة سندويش كرسبي",
  "image": "/assets/photos/abou/items/item-104.webp",
  "price": 280,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش كرسبي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-283",
  "name": "وجبة سندويش زنجر",
  "image": "/assets/photos/abou/items/item-105.webp",
  "price": 280,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش زنجر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-284",
  "name": "وجبة سندويش مكسيكانو",
  "image": "/assets/photos/abou/items/item-106.webp",
  "price": 280,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش مكسيكانو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-285",
  "name": "وجبة سندويش فاهيتا",
  "image": "/assets/photos/abou/items/item-107.webp",
  "price": 280,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش فاهيتا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-286",
  "name": "وجبة سندويش سجق",
  "image": "/assets/photos/abou/items/item-108.webp",
  "price": 315,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش سجق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-287",
  "name": "وجبة سندويش خاروف",
  "image": "/assets/photos/abou/items/item-109.webp",
  "price": 340,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش خاروف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-288",
  "name": "وجبة سندويش صاصيجو",
  "image": "/assets/photos/abou/items/item-110.webp",
  "price": 315,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش صاصيجو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-290",
  "name": "وجبة سندويش شيش طاووق",
  "image": "/assets/photos/abou/items/item-111.webp",
  "price": 280,
  "unit": "",
  "category": "وجبات السندويش",
  "available": true,
  "featured": false,
  "description": "وجبة سندويش شيش طاووق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-81",
  "name": "مندي لحم للاكابر",
  "image": "/assets/photos/abou/items/item-112.webp",
  "price": 685,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "مندي لحم للاكابر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-82",
  "name": "كبسة لحم جدّي",
  "image": "/assets/photos/abou/items/item-113.webp",
  "price": 685,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "كبسة لحم جدّي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-83",
  "name": "مندي مع فروج مشوي",
  "image": "/assets/photos/abou/items/item-114.webp",
  "price": 530,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "مندي مع فروج مشوي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-84",
  "name": "مندي دجاج بالي بالك",
  "image": "/assets/photos/abou/items/item-115.webp",
  "price": 530,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "مندي دجاج بالي بالك من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-85",
  "name": "كبسة دجاج ستّي",
  "image": "/assets/photos/abou/items/item-116.webp",
  "price": 530,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "كبسة دجاج ستّي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-86",
  "name": "كبسة مع فروج مشوي",
  "image": "/assets/photos/abou/items/item-117.webp",
  "price": 530,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "كبسة مع فروج مشوي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-87",
  "name": "كبة لبنية",
  "image": "/assets/photos/abou/items/item-118.webp",
  "price": 610,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "كبة لبنية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-88",
  "name": "شاكرية",
  "image": "/assets/photos/abou/items/item-119.webp",
  "price": 685,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "شاكرية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-89",
  "name": "يبرق بالدهن بيغرق",
  "image": "/assets/photos/abou/items/item-120.webp",
  "price": 710,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "يبرق بالدهن بيغرق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-90",
  "name": "كباب هندي",
  "image": "/assets/photos/abou/items/item-121.webp",
  "price": 685,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "كباب هندي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-91",
  "name": "شيش برك",
  "image": "/assets/photos/abou/items/item-122.webp",
  "price": 570,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "شيش برك من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-92",
  "name": "باشا وعساكره",
  "image": "/assets/photos/abou/items/item-123.webp",
  "price": 570,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "باشا وعساكره من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-93",
  "name": "لحمة بالخضار بالفخارة مع رز",
  "image": "/assets/photos/abou/items/item-124.webp",
  "price": 730,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "لحمة بالخضار بالفخارة مع رز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-94",
  "name": "دجاج بالخضار بالفخارة مع رز",
  "image": "/assets/photos/abou/items/item-125.webp",
  "price": 530,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "دجاج بالخضار بالفخارة مع رز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-95",
  "name": "منسف دجاج ( ٤ أشخاص )",
  "image": "/assets/photos/abou/items/item-126.webp",
  "price": 2100,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "منسف دجاج ( ٤ أشخاص ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-96",
  "name": "منسف لحم ( ٤ أشخاص )",
  "image": "/assets/photos/abou/items/item-127.webp",
  "price": 2800,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "منسف لحم ( ٤ أشخاص ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-97",
  "name": "صحن رز ابيض",
  "image": "/assets/photos/abou/items/item-128.webp",
  "price": 165,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "صحن رز ابيض من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-98",
  "name": "صحن رز مندي",
  "image": "/assets/photos/abou/items/item-129.webp",
  "price": 165,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "صحن رز مندي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-99",
  "name": "صحن رز كبسة",
  "image": "/assets/photos/abou/items/item-130.webp",
  "price": 165,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "صحن رز كبسة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-264",
  "name": "وجبة نقانق بالفخارة",
  "image": "/assets/photos/abou/items/item-131.webp",
  "price": 660,
  "unit": "",
  "category": "أكلات شرقية",
  "available": true,
  "featured": false,
  "description": "وجبة نقانق بالفخارة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-100",
  "name": "دجاج فاهيتا",
  "image": "/assets/photos/abou/items/item-132.webp",
  "price": 495,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "دجاج فاهيتا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-101",
  "name": "دجاج بوفالو",
  "image": "/assets/photos/abou/items/item-133.webp",
  "price": 495,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "دجاج بوفالو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-102",
  "name": "دجاج مكسيكانو",
  "image": "/assets/photos/abou/items/item-134.webp",
  "price": 495,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "دجاج مكسيكانو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-103",
  "name": "دجاج بالكريمة والفطر",
  "image": "/assets/photos/abou/items/item-135.webp",
  "price": 495,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "دجاج بالكريمة والفطر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-104",
  "name": "دجاج بالكاري",
  "image": "/assets/photos/abou/items/item-136.webp",
  "price": 495,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "دجاج بالكاري من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-105",
  "name": "دجاج باربيكيو",
  "image": "/assets/photos/abou/items/item-137.webp",
  "price": 495,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "دجاج باربيكيو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-106",
  "name": "كوردوان بلو",
  "image": "/assets/photos/abou/items/item-138.webp",
  "price": 525,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "كوردوان بلو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-107",
  "name": "كساديا دجاج",
  "image": "/assets/photos/abou/items/item-139.webp",
  "price": 525,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "كساديا دجاج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-108",
  "name": "كساديا لحمة",
  "image": "/assets/photos/abou/items/item-140.webp",
  "price": 650,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "كساديا لحمة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-109",
  "name": "كريسبي ( ٤ قطع )",
  "image": "/assets/photos/abou/items/item-141.webp",
  "price": 475,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "كريسبي ( ٤ قطع ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-110",
  "name": "زنجر ( ٤ قطع )",
  "image": "/assets/photos/abou/items/item-142.webp",
  "price": 475,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "زنجر ( ٤ قطع ) من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-111",
  "name": "فوتوتشيني",
  "image": "/assets/photos/abou/items/item-143.webp",
  "price": 370,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "فوتوتشيني من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-112",
  "name": "وجبة كريسبي اطفال",
  "image": "/assets/photos/abou/items/item-144.webp",
  "price": 320,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "وجبة كريسبي اطفال من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-235",
  "name": "فوتوتشيني دجاج",
  "image": "/assets/photos/abou/items/item-145.webp",
  "price": 450,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "فوتوتشيني دجاج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-267",
  "name": "وجبة برغر لحم مع بطاطا",
  "image": "/assets/photos/abou/items/item-146.webp",
  "price": 405,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "وجبة برغر لحم مع بطاطا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-268",
  "name": "وجبة برجر دجاج مع بطاطا",
  "image": "/assets/photos/abou/items/item-147.webp",
  "price": 330,
  "unit": "",
  "category": "أكلات غربية",
  "available": true,
  "featured": false,
  "description": "وجبة برجر دجاج مع بطاطا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-19",
  "name": "بيتزا فطر مع قشقوان - كبيرة",
  "image": "/assets/photos/abou/items/item-148.webp",
  "price": 440,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا فطر مع قشقوان - كبيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-20",
  "name": "بيتزا فطر مع قشقوان - صغيرة",
  "image": "/assets/photos/abou/items/item-149.webp",
  "price": 230,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا فطر مع قشقوان - صغيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-21",
  "name": "بيتزا مارجريتا - كبيرة",
  "image": "/assets/photos/abou/items/item-150.webp",
  "price": 405,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا مارجريتا - كبيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-22",
  "name": "بيتزا مارجريتا - صغيرة",
  "image": "/assets/photos/abou/items/item-151.webp",
  "price": 215,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا مارجريتا - صغيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-23",
  "name": "بيتزا حبش مدخن - كبير",
  "image": "/assets/photos/abou/items/item-152.webp",
  "price": 440,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا حبش مدخن - كبير من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-24",
  "name": "بيتزا حبش مدخن - صغيرة",
  "image": "/assets/photos/abou/items/item-153.webp",
  "price": 230,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا حبش مدخن - صغيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-25",
  "name": "بيتزا سجق - كبير",
  "image": "/assets/photos/abou/items/item-154.webp",
  "price": 450,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا سجق - كبير من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-26",
  "name": "بيتزا سجق - صغيرة",
  "image": "/assets/photos/abou/items/item-155.webp",
  "price": 235,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا سجق - صغيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-27",
  "name": "بيتزا الفصول الاربعة - كبير",
  "image": "/assets/photos/abou/items/item-156.webp",
  "price": 450,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا الفصول الاربعة - كبير من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-28",
  "name": "بيتزا الفصول الاربعة - صغيرة",
  "image": "/assets/photos/abou/items/item-157.webp",
  "price": 235,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا الفصول الاربعة - صغيرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-29",
  "name": "بيتزا مكسيكانو",
  "image": "/assets/photos/abou/items/item-158.webp",
  "price": 450,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا مكسيكانو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-30",
  "name": "بيتزا فاهيتا",
  "image": "/assets/photos/abou/items/item-159.webp",
  "price": 450,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "بيتزا فاهيتا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-31",
  "name": "منقوشة زعتر",
  "image": "/assets/photos/abou/items/item-160.webp",
  "price": 155,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة زعتر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-32",
  "name": "منقوشة محمرة",
  "image": "/assets/photos/abou/items/item-161.webp",
  "price": 160,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة محمرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-33",
  "name": "منقوشة محمرة مع قشقوان",
  "image": "/assets/photos/abou/items/item-162.webp",
  "price": 175,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة محمرة مع قشقوان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-34",
  "name": "منقوشة محمرة قشقوان أبو الزلف",
  "image": "/assets/photos/abou/items/item-163.webp",
  "price": 300,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة محمرة قشقوان أبو الزلف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-35",
  "name": "منقوشة زعتر مع قشقوان",
  "image": "/assets/photos/abou/items/item-164.webp",
  "price": 170,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة زعتر مع قشقوان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-37",
  "name": "منقوشة زعتر مع قشقوان وخضرة",
  "image": "/assets/photos/abou/items/item-165.webp",
  "price": 175,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة زعتر مع قشقوان وخضرة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-38",
  "name": "منقوشة زعتر قشقوان أبو الزلف",
  "image": "/assets/photos/abou/items/item-166.webp",
  "price": 300,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة زعتر قشقوان أبو الزلف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-39",
  "name": "منقوشة جبنة قشقوان",
  "image": "/assets/photos/abou/items/item-167.webp",
  "price": 175,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة جبنة قشقوان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-40",
  "name": "منقوشة قشقوان مع دجاج",
  "image": "/assets/photos/abou/items/item-168.webp",
  "price": 185,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة قشقوان مع دجاج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-41",
  "name": "منقوشة قشقوان مع حبش مدخن",
  "image": "/assets/photos/abou/items/item-169.webp",
  "price": 225,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة قشقوان مع حبش مدخن من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-42",
  "name": "منقوشة قشقوان مع سجق",
  "image": "/assets/photos/abou/items/item-170.webp",
  "price": 190,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة قشقوان مع سجق من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-43",
  "name": "منقوشة لبنة",
  "image": "/assets/photos/abou/items/item-171.webp",
  "price": 160,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة لبنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-44",
  "name": "منقوشة لبنة مع زعتر",
  "image": "/assets/photos/abou/items/item-172.webp",
  "price": 180,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة لبنة مع زعتر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-45",
  "name": "منقوشة لبنة مع الخضار",
  "image": "/assets/photos/abou/items/item-173.webp",
  "price": 175,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة لبنة مع الخضار من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-46",
  "name": "صفيحة أبو الزلف",
  "image": "/assets/photos/abou/items/item-174.webp",
  "price": 270,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "صفيحة أبو الزلف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-63",
  "name": "زبدية لبن وخيار",
  "image": "/assets/photos/abou/items/item-175.webp",
  "price": 90,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "زبدية لبن وخيار من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-271",
  "name": "منقوشة جبنة بيضة",
  "image": "/assets/photos/abou/items/item-176.webp",
  "price": 175,
  "unit": "",
  "category": "الفرن",
  "available": true,
  "featured": false,
  "description": "منقوشة جبنة بيضة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-164",
  "name": "برتقان",
  "image": "/assets/photos/abou/items/item-177.webp",
  "price": 200,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "برتقان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-165",
  "name": "اناناس",
  "image": "/assets/photos/abou/items/item-178.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "اناناس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-166",
  "name": "اناناس وفريز",
  "image": "/assets/photos/abou/items/item-179.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "اناناس وفريز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-167",
  "name": "فريز",
  "image": "/assets/photos/abou/items/item-180.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "فريز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-168",
  "name": "رمان",
  "image": "/assets/photos/abou/items/item-181.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "رمان من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-169",
  "name": "برتقال وفريز",
  "image": "/assets/photos/abou/items/item-182.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "برتقال وفريز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-170",
  "name": "بولو",
  "image": "/assets/photos/abou/items/item-183.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "بولو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-171",
  "name": "بلو سي",
  "image": "/assets/photos/abou/items/item-184.webp",
  "price": 216,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "بلو سي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-172",
  "name": "فيرجن موهيتو",
  "image": "/assets/photos/abou/items/item-185.webp",
  "price": 170,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "فيرجن موهيتو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-173",
  "name": "آبل موهيتو",
  "image": "/assets/photos/abou/items/item-186.webp",
  "price": 150,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "آبل موهيتو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-279",
  "name": "جزر",
  "image": "/assets/photos/abou/items/item-187.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "جزر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-280",
  "name": "تفاح",
  "image": "/assets/photos/abou/items/item-188.webp",
  "price": 220,
  "unit": "",
  "category": "تازا يا تازا",
  "available": true,
  "featured": false,
  "description": "تفاح من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-222",
  "name": "سلطة فواكه عسل",
  "image": "/assets/photos/abou/items/item-189.webp",
  "price": 275,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه عسل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-223",
  "name": "سلطة فواكه شوكولا",
  "image": "/assets/photos/abou/items/item-190.webp",
  "price": 275,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه شوكولا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-224",
  "name": "سلطة فواكه دايت",
  "image": "/assets/photos/abou/items/item-191.webp",
  "price": 240,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه دايت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-226",
  "name": "صحن جبس احمر",
  "image": "/assets/photos/abou/items/item-192.webp",
  "price": 200,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "صحن جبس احمر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-227",
  "name": "صحن جبس احمر مع جبنة",
  "image": "/assets/photos/abou/items/item-193.webp",
  "price": 225,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "صحن جبس احمر مع جبنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-196",
  "name": "وافل شوكولا",
  "image": "/assets/photos/abou/items/item-194.webp",
  "price": 245,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "وافل شوكولا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-197",
  "name": "وافل فواكه",
  "image": "/assets/photos/abou/items/item-195.webp",
  "price": 285,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "وافل فواكه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-198",
  "name": "سوفليه",
  "image": "/assets/photos/abou/items/item-196.webp",
  "price": 225,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "سوفليه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-201",
  "name": "بنانا سبليت",
  "image": "/assets/photos/abou/items/item-197.webp",
  "price": 225,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "بنانا سبليت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-202",
  "name": "توتي فروتي",
  "image": "/assets/photos/abou/items/item-198.webp",
  "price": 225,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "توتي فروتي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-203",
  "name": "كريب شوكولا",
  "image": "/assets/photos/abou/items/item-199.webp",
  "price": 245,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "كريب شوكولا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-204",
  "name": "كرب فواكة وشوكولا",
  "image": "/assets/photos/abou/items/item-200.webp",
  "price": 285,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "كرب فواكة وشوكولا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-206",
  "name": "طابة بوظة",
  "image": "/assets/photos/abou/items/item-201.webp",
  "price": 90,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "طابة بوظة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-209",
  "name": "كاتمار",
  "image": "/assets/photos/abou/items/item-202.webp",
  "price": 245,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "كاتمار من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-210",
  "name": "نابلسية",
  "image": "/assets/photos/abou/items/item-203.webp",
  "price": 225,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "نابلسية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-291",
  "name": "معمول بجبنة",
  "image": "/assets/photos/abou/items/item-204.webp",
  "price": 200,
  "unit": "",
  "category": "حلي ضرسك",
  "available": true,
  "featured": false,
  "description": "معمول بجبنة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-155",
  "name": "كازوزة سودا",
  "image": "/assets/photos/abou/items/item-205.webp",
  "price": 80,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "كازوزة سودا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-156",
  "name": "كازوزة برتقالي",
  "image": "/assets/photos/abou/items/item-206.webp",
  "price": 80,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "كازوزة برتقالي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-157",
  "name": "كازوزة بيضا",
  "image": "/assets/photos/abou/items/item-207.webp",
  "price": 80,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "كازوزة بيضا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-158",
  "name": "كازوزة دايت",
  "image": "/assets/photos/abou/items/item-208.webp",
  "price": 80,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "كازوزة دايت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-159",
  "name": "صودا بأنواعها",
  "image": "/assets/photos/abou/items/item-209.webp",
  "price": 70,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "صودا بأنواعها من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-160",
  "name": "ريد بول",
  "image": "/assets/photos/abou/items/item-210.webp",
  "price": 195,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "ريد بول من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-161",
  "name": "عيران",
  "image": "/assets/photos/abou/items/item-211.webp",
  "price": 70,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "عيران من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-162",
  "name": "تشورشيل",
  "image": "/assets/photos/abou/items/item-212.webp",
  "price": 100,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "تشورشيل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-163",
  "name": "مي بوظة",
  "image": "/assets/photos/abou/items/item-213.webp",
  "price": 35,
  "unit": "",
  "category": "بل ريقك",
  "available": true,
  "featured": false,
  "description": "مي بوظة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-174",
  "name": "قهوة غلي منظومة",
  "image": "/assets/photos/abou/items/item-214.webp",
  "price": 110,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "قهوة غلي منظومة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-175",
  "name": "قهوة غلي دبل",
  "image": "/assets/photos/abou/items/item-215.webp",
  "price": 150,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "قهوة غلي دبل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-176",
  "name": "قهوة تركية",
  "image": "/assets/photos/abou/items/item-216.webp",
  "price": 110,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "قهوة تركية من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-177",
  "name": "قهوة تركية دبل",
  "image": "/assets/photos/abou/items/item-217.webp",
  "price": 150,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "قهوة تركية دبل من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-178",
  "name": "اسبريسو الوسوف",
  "image": "/assets/photos/abou/items/item-218.webp",
  "price": 115,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "اسبريسو الوسوف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-179",
  "name": "دبل اكسبريس",
  "image": "/assets/photos/abou/items/item-219.webp",
  "price": 155,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "دبل اكسبريس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-180",
  "name": "نسكافيه",
  "image": "/assets/photos/abou/items/item-220.webp",
  "price": 115,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "نسكافيه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-181",
  "name": "موكا",
  "image": "/assets/photos/abou/items/item-221.webp",
  "price": 155,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "موكا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-182",
  "name": "هوت شوكليت",
  "image": "/assets/photos/abou/items/item-222.webp",
  "price": 140,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "هوت شوكليت من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-183",
  "name": "كابوتشينوووو",
  "image": "/assets/photos/abou/items/item-223.webp",
  "price": 140,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "كابوتشينوووو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-184",
  "name": "نسكافيه مع حليب",
  "image": "/assets/photos/abou/items/item-224.webp",
  "price": 140,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "نسكافيه مع حليب من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-185",
  "name": "اميريكان كوفي",
  "image": "/assets/photos/abou/items/item-225.webp",
  "price": 140,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "اميريكان كوفي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-186",
  "name": "كافيه لاتيه",
  "image": "/assets/photos/abou/items/item-226.webp",
  "price": 140,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "كافيه لاتيه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-187",
  "name": "سحلب",
  "image": "/assets/photos/abou/items/item-227.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "سحلب من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-188",
  "name": "شاي اكرك عجم",
  "image": "/assets/photos/abou/items/item-228.webp",
  "price": 50,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي اكرك عجم من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-189",
  "name": "شاي بفنجان نانتي",
  "image": "/assets/photos/abou/items/item-229.webp",
  "price": 65,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي بفنجان نانتي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-190",
  "name": "شاي أخضر",
  "image": "/assets/photos/abou/items/item-230.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي أخضر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-191",
  "name": "زهورات",
  "image": "/assets/photos/abou/items/item-231.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "زهورات من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-192",
  "name": "كمون وليمون",
  "image": "/assets/photos/abou/items/item-232.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "كمون وليمون من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-193",
  "name": "ليمون ونعناع",
  "image": "/assets/photos/abou/items/item-233.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "ليمون ونعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-194",
  "name": "بابونج",
  "image": "/assets/photos/abou/items/item-234.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "بابونج من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-195",
  "name": "زنجبيل وليمون",
  "image": "/assets/photos/abou/items/item-235.webp",
  "price": 125,
  "unit": "",
  "category": "مشاريب ساخنة",
  "available": true,
  "featured": false,
  "description": "زنجبيل وليمون من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-228",
  "name": "فرابوتشينو",
  "image": "/assets/photos/abou/items/item-236.webp",
  "price": 180,
  "unit": "",
  "category": "قهوة باردة",
  "available": true,
  "featured": false,
  "description": "فرابوتشينو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-229",
  "name": "شوكولا مو",
  "image": "/assets/photos/abou/items/item-237.webp",
  "price": 195,
  "unit": "",
  "category": "قهوة باردة",
  "available": true,
  "featured": false,
  "description": "شوكولا مو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-230",
  "name": "ايس لاتيه",
  "image": "/assets/photos/abou/items/item-238.webp",
  "price": 150,
  "unit": "",
  "category": "قهوة باردة",
  "available": true,
  "featured": false,
  "description": "ايس لاتيه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-231",
  "name": "ايس أميركان كوفي",
  "image": "/assets/photos/abou/items/item-239.webp",
  "price": 150,
  "unit": "",
  "category": "قهوة باردة",
  "available": true,
  "featured": false,
  "description": "ايس أميركان كوفي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-232",
  "name": "ايس موكا",
  "image": "/assets/photos/abou/items/item-240.webp",
  "price": 150,
  "unit": "",
  "category": "قهوة باردة",
  "available": true,
  "featured": false,
  "description": "ايس موكا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-212",
  "name": "حليب وموز",
  "image": "/assets/photos/abou/items/item-241.webp",
  "price": 235,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "حليب وموز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-213",
  "name": "كوكتيل فواكه",
  "image": "/assets/photos/abou/items/item-242.webp",
  "price": 260,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "كوكتيل فواكه من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-214",
  "name": "حليب وموز وفريز",
  "image": "/assets/photos/abou/items/item-243.webp",
  "price": 260,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "حليب وموز وفريز من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-215",
  "name": "حليب وموز واناناس",
  "image": "/assets/photos/abou/items/item-244.webp",
  "price": 260,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "حليب وموز واناناس من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-216",
  "name": "ميلك شيك",
  "image": "/assets/photos/abou/items/item-245.webp",
  "price": 260,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "ميلك شيك من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-217",
  "name": "موز وحليب وشوكولا",
  "image": "/assets/photos/abou/items/item-246.webp",
  "price": 260,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب وشوكولا من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-218",
  "name": "موز وحليب وقشطة وعسل ومكسرات",
  "image": "/assets/photos/abou/items/item-247.webp",
  "price": 320,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب وقشطة وعسل ومكسرات من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-219",
  "name": "قشاطي",
  "image": "/assets/photos/abou/items/item-248.webp",
  "price": 380,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "قشاطي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-220",
  "name": "امبراطور",
  "image": "/assets/photos/abou/items/item-249.webp",
  "price": 420,
  "unit": "",
  "category": "كوكتيلات",
  "available": true,
  "featured": false,
  "description": "امبراطور من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-233",
  "name": "تفاحتين نخلة",
  "image": "/assets/photos/abou/items/item-250.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "تفاحتين نخلة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-234",
  "name": "تبديل راس أركيلة",
  "image": "/assets/photos/abou/items/item-251.webp",
  "price": 250,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "تبديل راس أركيلة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-236",
  "name": "تفاحتين فاخر",
  "image": "/assets/photos/abou/items/item-252.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "تفاحتين فاخر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-237",
  "name": "عنب فاخر",
  "image": "/assets/photos/abou/items/item-253.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "عنب فاخر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-238",
  "name": "عنب نعناع",
  "image": "/assets/photos/abou/items/item-254.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "عنب نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-239",
  "name": "ليمون نعناع",
  "image": "/assets/photos/abou/items/item-255.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "ليمون نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-240",
  "name": "ليمون",
  "image": "/assets/photos/abou/items/item-256.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "ليمون من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-241",
  "name": "برتقال",
  "image": "/assets/photos/abou/items/item-257.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "برتقال من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-242",
  "name": "برتقال نعناع",
  "image": "/assets/photos/abou/items/item-258.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "برتقال نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-243",
  "name": "بلوبري",
  "image": "/assets/photos/abou/items/item-259.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "بلوبري من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-244",
  "name": "بلوبري نعناع",
  "image": "/assets/photos/abou/items/item-260.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "بلوبري نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-245",
  "name": "بطيخ مع فراولة",
  "image": "/assets/photos/abou/items/item-261.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "بطيخ مع فراولة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-246",
  "name": "علكة ونعناع",
  "image": "/assets/photos/abou/items/item-262.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "علكة ونعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-247",
  "name": "علكة وقرفة",
  "image": "/assets/photos/abou/items/item-263.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "علكة وقرفة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-248",
  "name": "مستكة",
  "image": "/assets/photos/abou/items/item-264.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "مستكة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-249",
  "name": "بطيخ",
  "image": "/assets/photos/abou/items/item-265.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "بطيخ من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-250",
  "name": "بطيخ مع نعناع",
  "image": "/assets/photos/abou/items/item-266.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "بطيخ مع نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-251",
  "name": "ليدي كلر",
  "image": "/assets/photos/abou/items/item-267.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "ليدي كلر من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-252",
  "name": "لوف 66",
  "image": "/assets/photos/abou/items/item-268.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "لوف 66 من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-253",
  "name": "بيشمش شافتلي",
  "image": "/assets/photos/abou/items/item-269.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "بيشمش شافتلي من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-254",
  "name": "فواكة",
  "image": "/assets/photos/abou/items/item-270.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "فواكة من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-255",
  "name": "دي جافو",
  "image": "/assets/photos/abou/items/item-271.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "دي جافو من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-256",
  "name": "نعناع",
  "image": "/assets/photos/abou/items/item-272.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-257",
  "name": "فواكة مع نعناع",
  "image": "/assets/photos/abou/items/item-273.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "فواكة مع نعناع من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "abou-258",
  "name": "خلطة ابو الزلف",
  "image": "/assets/photos/abou/items/item-274.webp",
  "price": 490,
  "unit": "",
  "category": "الأراكيل",
  "available": true,
  "featured": false,
  "description": "خلطة ابو الزلف من مطعم أبو الزلف.",
  "imageFit": "cover",
  "options": []
 }
];

const abouProducts = abouProductCatalog
  .map((product, index) => ({
    ...product,
    id: 35001 + index,
    storeId: abouStore.id
  }))
  // الأراكيل category removed by request; filter after id-map so remaining ids stay aligned with the cloud
  .filter(product => product.category !== "الأراكيل");

const abouDeliverySettings = {
  [abouStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
