// Generated for مطعم أفغان كباب (Afgan Kebap) — Esenyurt/Beylikduzu, Istanbul. Source: afgankebap.com
const afganStore = {
 "id": 17,
 "name": "مطعم أفغان كباب",
 "category": "مطاعم",
 "image": "/assets/photos/afgan/cover.jpg",
 "coverImage": "/assets/photos/afgan/cover.jpg",
 "logoImage": "/assets/photos/afgan/logo.png",
 "logo": "أ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 200,
 "time": "45 - 75 دقيقة",
 "distance": 24.0,
 "location": {
  "lat": 41.004,
  "lng": 28.63
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=Afgan+Kebap+Restaurant+Beylikduzu+Esenyurt+Istanbul",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم أفغان كباب — أول مطبخ أفغاني في إسنيورت/بيليك دوزو بإسطنبول: برياني (بيلاف) باللحم، كباب التكة الأفغاني، المومو (دامبلنغ)، المشاوي والصحون واليخنات والمقبلات. أسماء الأطباق كما في القائمة الرسمية للمطعم.",
 "address": "حي الجمهورية، شارع ناظم حكمت، 2066 Sk. 17/A، بيليك دوزو OSB / إسنيورت، إسطنبول",
 "phone": "+90 555 080 46 40",
 "whatsapp": "+90 555 080 46 40",
 "email": "",
 "website": "https://www.afgankebap.com/",
 "sourceUrl": "https://www.afgankebap.com/menu",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسنيورت",
  "بيليك دوزو",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const afganProductCatalog = [
 {
  "sourceId": "pilav-meat-single",
  "name": "Pilav & Meat (Single)",
  "image": "/assets/photos/afgan/products/item-001.webp",
  "price": 550,
  "unit": "",
  "category": "الأطباق الكلاسيكية",
  "available": true,
  "featured": true,
  "description": "Basmati rice excellently steamed over well-selected imported raisins, carrots and well-butchered chunks of lamb meat. 1 serving is rice for 1 person and 1 chunk of lamb.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afgan-kebap-tikka",
  "name": "Afgan Kebap Tikka",
  "image": "/assets/photos/afgan/products/item-002.webp",
  "price": 600,
  "unit": "",
  "category": "الأطباق الكلاسيكية",
  "available": true,
  "featured": true,
  "description": "Finely chosen boneless parts of lamb amazingly marinated, and delicately cut into pieces. 1 skewer consists of 3 pieces of lamb and 1 tail fat. 1 serving is 5 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dumplings-momos",
  "name": "Dumplings (Momos)",
  "image": "/assets/photos/afgan/products/item-003.webp",
  "price": 310,
  "unit": "",
  "category": "الأطباق الكلاسيكية",
  "available": true,
  "featured": true,
  "description": "Home-made recipe of minced lamb stuffed into dough and timely steamed in a special-layered cooker, served with tomato sauce and yoghurt toppings. 1 serving is 7 pieces.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-meat-double",
  "name": "Pilav & Meat (Double)",
  "image": "/assets/photos/afgan/products/item-004.webp",
  "price": 870,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins, carrots and well-butchered lamb chunks. 1 serving is rice for 1 person and 2 lamb chunks.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-lamb-shank",
  "name": "Pilav & Lamb Shank",
  "image": "/assets/photos/afgan/products/item-005.webp",
  "price": 950,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": true,
  "description": "Basmati rice excellently steamed over well-selected imported raisins, carrots and well-butchered lamb chunks. 1 serving is rice for 1 person and 1 lamb shank.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "chicken-biryani",
  "name": "Chicken Biryani",
  "image": "/assets/photos/afgan/products/item-006.webp",
  "price": 400,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice cooked in premium imported spices and served with fine-chosen chicken thighs (hindquarter). 1 serving is rice for 1 person and 1 thigh.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-half-roast-chicken",
  "name": "Pilav & Half Roast Chicken",
  "image": "/assets/photos/afgan/products/item-007.webp",
  "price": 400,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with well-done roast chicken. 1 serving is rice for 1 person and 0.5 chicken.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-half-charcoal-chicken",
  "name": "Pilav & Half Charcoal Chicken",
  "image": "/assets/photos/afgan/products/item-008.webp",
  "price": 440,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with well-done charcoal chicken. 1 serving is rice for 1 person and 0.5 chicken.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-afgan-kebap-tikka",
  "name": "Pilav & Afgan Kebap Tikka",
  "image": "/assets/photos/afgan/products/item-009.webp",
  "price": 540,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with savour and juicy Afgan Kebap Tikka. 1 serving is rice for 1 person and 3 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-mix-barbecue",
  "name": "Pilav & Mix Barbecue",
  "image": "/assets/photos/afgan/products/item-010.webp",
  "price": 540,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with ultimate combination of mix barbecue. 1 serving is rice for 1 person and 3 skewers (Afgan Kebap tikka, chicken cube, minced lamb).",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-ground-minced-lamb-barbecue",
  "name": "Pilav & Ground Minced Lamb Barbecue",
  "image": "/assets/photos/afgan/products/item-011.webp",
  "price": 540,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with ground minced lamb barbecue. 1 serving is rice for 1 person and 2 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-minced-lamb-barbecue",
  "name": "Pilav & Minced Lamb Barbecue",
  "image": "/assets/photos/afgan/products/item-012.webp",
  "price": 540,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with minced lamb barbecue. 1 serving is rice for 1 person and 3 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-chicken-cube-barbecue",
  "name": "Pilav & Chicken Cube Barbecue",
  "image": "/assets/photos/afgan/products/item-013.webp",
  "price": 540,
  "unit": "",
  "category": "البرياني والأرز",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with chicken cube barbecue. 1 serving is rice for 1 person and 2 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "minced-lamb-barbecue",
  "name": "Minced Lamb Barbecue",
  "image": "/assets/photos/afgan/products/item-014.webp",
  "price": 540,
  "unit": "",
  "category": "المشاوي",
  "available": true,
  "featured": true,
  "description": "Known as Shami Kebab in the subcontinent. Carefully chosen part of lamb is minced with fine-selection of spices giving a pleasant aroma to lamb and tomato cubes, barbecued on low charcoal fire. 1 serving is 4 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "chicken-cube-barbecue",
  "name": "Chicken Cube Barbecue",
  "image": "/assets/photos/afgan/products/item-015.webp",
  "price": 540,
  "unit": "",
  "category": "المشاوي",
  "available": true,
  "featured": false,
  "description": "Known as Chicken Tikka in the subcontinent. Premium chicken breast marinated with a home-made recipe of imported spices, barbecued on high charcoal fire. 1 serving is 3 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ground-minced-lamb-barbecue",
  "name": "Ground Minced Lamb Barbecue",
  "image": "/assets/photos/afgan/products/item-016.webp",
  "price": 540,
  "unit": "",
  "category": "المشاوي",
  "available": true,
  "featured": false,
  "description": "Known as Kabab Koobideh in Persia. Finely chopped and minced lamb with home-made recipe, giving a mellow texture to lamb and tomato, barbecued on low charcoal fire. 1 serving is 3 skewers and 0.25 tomato.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mix-barbecue",
  "name": "Mix Barbecue",
  "image": "/assets/photos/afgan/products/item-017.webp",
  "price": 540,
  "unit": "",
  "category": "المشاوي",
  "available": true,
  "featured": true,
  "description": "An ultimate combination of Afgan Kebap tikka, minced lamb, ground minced lamb and chicken cube. Barbecued at once on low charcoal fire, giving the irresistible eating experience. 1 serving is 4 skewers.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "half-roast-chicken-fries-chips",
  "name": "Half Roast Chicken & Fries (Chips)",
  "image": "/assets/photos/afgan/products/item-018.webp",
  "price": 310,
  "unit": "",
  "category": "المشاوي",
  "available": true,
  "featured": false,
  "description": "Premium selection of chicken marinated, roasted on low fire giving a full-flavoured texture to the chicken. 1 serving is 0.5 chicken and fries (chips).",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "half-charcoal-chicken-fries-chips",
  "name": "Half Charcoal Chicken & Fries (Chips)",
  "image": "/assets/photos/afgan/products/item-019.webp",
  "price": 360,
  "unit": "",
  "category": "المشاوي",
  "available": true,
  "featured": false,
  "description": "Premium selection of chicken marinated into home-made marination recipe, barbecued on low charcoal fire giving a distinct taste to the chicken. 1 serving is 0.5 chicken and fries (chips).",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-mix-barbecue-family",
  "name": "Pilav & Mix Barbecue (Family)",
  "image": "/assets/photos/afgan/products/item-020.webp",
  "price": 2700,
  "unit": "",
  "category": "الصحون",
  "available": true,
  "featured": true,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with 4 ultimate selection of mix barbecue (Afgan Kebap tikka, minced lamb, ground minced lamb and chicken cube). Optimal choice for barbecue and pilav preferring groups. 1 serving is rice for 5-6 persons and 14 skewers of mix barbecue.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pilav-mix-barbecue-4-persons",
  "name": "Pilav & Mix Barbecue (4 Persons)",
  "image": "/assets/photos/afgan/products/item-021.webp",
  "price": 2100,
  "unit": "",
  "category": "الصحون",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with 4 ultimate selection of mix barbecue (Afgan Kebap tikka, minced lamb, ground minced lamb and chicken cube). Optimal choice for barbecue and pilav preferring groups. 1 serving is rice for 4 persons and 11 skewers of mix barbecue.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mix-barbecue-1-kg",
  "name": "Mix Barbecue (1 kg)",
  "image": "/assets/photos/afgan/products/item-022.webp",
  "price": 2100,
  "unit": "",
  "category": "الصحون",
  "available": true,
  "featured": true,
  "description": "4 ultimate combination of mix barbecue (Afgan Kebap tikka, minced lamb, ground minced lamb, chicken cube) - barbecued altogether on low charcoal fire giving undeniable savour and fries (chips). 1 serving is 1 kg.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afgan-kebap-family-4-persons",
  "name": "Afgan Kebap Family (4 Persons)",
  "image": "/assets/photos/afgan/products/item-023.webp",
  "price": 2300,
  "unit": "",
  "category": "الصحون",
  "available": true,
  "featured": true,
  "description": "A novel combination of Afgan Kebap enterprise. Lamb Shank and Mix Barbecue onto Pilav. Optimal choice for 'All-in-One' preferring groups. 1 serving is rice for 4 persons, 1 lamb shank, 8 skewers of mix barbecue, 1 kidney beans, 1 salad and Afghan naan.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "charcoal-family-4-persons",
  "name": "Charcoal Family (4 Persons)",
  "image": "/assets/photos/afgan/products/item-024.webp",
  "price": 1200,
  "unit": "",
  "category": "الصحون",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with charcoal chicken. Optimal choice for charcoal chicken preferring groups. 1 serving is rice for 4 persons, 1 whole chicken, 1 lt. Coca-Cola, 1 hummus, 1 fries (chips), 1 salad, 1 garlic, 1 hot sauce and Afghan naan.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "jumbo-family-6-persons",
  "name": "Jumbo Family (6 Persons)",
  "image": "/assets/photos/afgan/products/item-025.webp",
  "price": 1650,
  "unit": "",
  "category": "الصحون",
  "available": true,
  "featured": false,
  "description": "Basmati rice excellently steamed over well-selected imported raisins and carrots. Served with roast chicken and charcoal chicken. Optimal choice for groups preferring both the chicken grills. 1 serving is rice for 6 persons, 1 roast chicken, 0.5 charcoal chicken, 1 lt. Coca-Cola, 1 hummus, 1 fries (chips), 1 salad, 1 garlic, 1 hot sauce and Afghan naan.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "chicken-curry-stew",
  "name": "Chicken Curry Stew",
  "image": "/assets/photos/afgan/products/item-026.webp",
  "price": 440,
  "unit": "",
  "category": "اليخنات",
  "available": true,
  "featured": false,
  "description": "Premium selection of finely-cut chicken pieces cooked with fresh ingredients and imported spices. Simmered on low heat, giving an inviting taste to the curry stew. 1 serving is for 1 person.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "onion-and-lamb-stew",
  "name": "Onion and Lamb Stew",
  "image": "/assets/photos/afgan/products/item-027.webp",
  "price": 570,
  "unit": "",
  "category": "اليخنات",
  "available": true,
  "featured": true,
  "description": "Fine-cut pieces of lamb and top-below layered of onions cooked with home-made recipe and spices, giving a savour taste to the stew. 1 serving is for 1 person.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "meat-balls-gravy-stew",
  "name": "Meat Balls Gravy Stew",
  "image": "/assets/photos/afgan/products/item-028.webp",
  "price": 440,
  "unit": "",
  "category": "اليخنات",
  "available": true,
  "featured": false,
  "description": "Minced lamb mixed with subtle spices, made into round shapes, braised with consistent rich sauce, giving a tasteful gravy texture to the stew. 1 serving is for 1 person.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kidney-beans-gravy-stew",
  "name": "Kidney Beans Gravy Stew",
  "image": "/assets/photos/afgan/products/item-029.webp",
  "price": 250,
  "unit": "",
  "category": "اليخنات",
  "available": true,
  "featured": true,
  "description": "Imported kidneys beans baked with sauce, giving a pleasant gravy texture to the stew. Endless eating experience. 1 serving is for 1 person.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "hummus",
  "name": "Hummus",
  "image": "/assets/photos/afgan/products/item-030.webp",
  "price": 130,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": false,
  "description": "A popular dip appetiser around the world, originating from the Middle East. Prepared with mashed chick peas and toasted seasame. Dressed with olive oil and sumac.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "french-fries",
  "name": "French Fries",
  "image": "/assets/photos/afgan/products/item-031.webp",
  "price": 150,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": false,
  "description": "French-inspired frying technique used for the premium selection of finger-shaped cut potato. Dressed with spices.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "yoghurt-cucumber-salad",
  "name": "Yoghurt-Cucumber Salad",
  "image": "/assets/photos/afgan/products/item-032.webp",
  "price": 130,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": true,
  "description": "Known as Tzatziki in the West and Cacık in Turkey. Prepared with strained yoghurt and cucumber. Dressed with complementary ingredients.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "greek-salad",
  "name": "Greek Salad",
  "image": "/assets/photos/afgan/products/item-033.webp",
  "price": 180,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": false,
  "description": "Prepared with lettuce, tomato, olive, onion, cucumber and feta cheese. Dressed with complementary ingredients.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afghan-salad",
  "name": "Afghan Salad",
  "image": "/assets/photos/afgan/products/item-034.webp",
  "price": 130,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": false,
  "description": "Known as Chopan Salad in Turkey and extensively. Prepared with onion, tomato and cucumber. Dressed with spices and lemon.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afgan-kebap-soup",
  "name": "Afgan Kebap Soup",
  "image": "/assets/photos/afgan/products/item-035.webp",
  "price": 130,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": true,
  "description": "Afgan Kebap inspired of chicken-vegetable stock soup. Prepared with pieces of chicken, vegetables and cornflour. Simmered on low heat, giving a gravy texture to the soup.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "hot-sauce-chutney",
  "name": "Hot Sauce (Chutney)",
  "image": "/assets/photos/afgan/products/item-036.webp",
  "price": 130,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": true,
  "description": "A hot and spicy dip. Prepared with tomato sauce, chilli pepper and home-made dressing recipe.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afghan-ice-cream-double",
  "name": "Afghan Ice Cream, Double",
  "image": "/assets/photos/afgan/products/item-037.webp",
  "price": 230,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": false,
  "description": "Known as Sheeryakh in Afghanistan. Premium organic milk boiled for several hours with imported ingredients. Prepared in traditional pots with special technique. Served in ice-cold and pistachio crumbs topping. 1 serving is 4 scoops.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afghan-ice-cream-single",
  "name": "Afghan Ice Cream, Single",
  "image": "/assets/photos/afgan/products/item-038.webp",
  "price": 140,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": false,
  "description": "Known as Sheeryakh in Afghanistan. Premium organic milk boiled for several hours with imported ingredients. Prepared in traditional pots with special technique. Served in ice-cold and pistachio crumbs topping. 1 serving is 2 scoops.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afghan-milk-cream-250-grams",
  "name": "Afghan Milk Cream, 250 grams",
  "image": "/assets/photos/afgan/products/item-039.webp",
  "price": 250,
  "unit": "",
  "category": "المقبلات والحلويات",
  "available": true,
  "featured": true,
  "description": "Known as Kaymak in Afghanistan. Premium organic milk boiled on low heat for several hours, giving a texture on top of boiled milk used as cream. Prepared in the most authentic Afghan technique.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "zerhisar-ayran",
  "name": "Özerhisar Ayran",
  "image": "/assets/photos/afgan/products/item-040.webp",
  "price": 70,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": true,
  "description": "Özerhisar Ayran من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "coca-cola-can",
  "name": "Coca-Cola Can",
  "image": "/assets/photos/afgan/products/item-041.webp",
  "price": 80,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Coca-Cola Can من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "sprite-can",
  "name": "Sprite Can",
  "image": "/assets/photos/afgan/products/item-042.webp",
  "price": 80,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Sprite Can من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fanta-can",
  "name": "Fanta Can",
  "image": "/assets/photos/afgan/products/item-043.webp",
  "price": 80,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Fanta Can من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "uluda-mineral-water",
  "name": "Uludağ Mineral Water",
  "image": "/assets/photos/afgan/products/item-044.webp",
  "price": 20,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": true,
  "description": "Uludağ Mineral Water من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "turkish-black-tea",
  "name": "Turkish Black Tea",
  "image": "/assets/photos/afgan/products/item-045.webp",
  "price": 25,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Turkish Black Tea من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afghan-green-tea-thermos",
  "name": "Afghan Green Tea (Thermos)",
  "image": "/assets/photos/afgan/products/item-046.webp",
  "price": 100,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": true,
  "description": "Afghan Green Tea (Thermos) من مطعم أفغان كباب.",
  "imageFit": "cover",
  "options": []
 }
];

const afganProducts = afganProductCatalog.map((product, index) => ({
  ...product,
  id: 17001 + index,
  storeId: afganStore.id
}));

const afganDeliverySettings = {
  [afganStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
