// Generated from the official Ala Gardoner (الأغر شاورما) menu site http://menu.alagardoner.com on 2026-06-15.
// 5 branches in Istanbul sharing one menu (30 items). Each branch is its own store with its own WhatsApp number.
// Coordinates geocoded (street-level, OpenStreetMap) on 2026-06-15; mapUrl is a precise coordinate pin.
const alagarBranches = [
 {
  "id": 26,
  "name": "مطعم الأغر شاورما - كايا شهير",
  "branchName": "كايا شهير",
  "branchGroup": "alagar",
  "category": "مطاعم",
  "image": "/assets/photos/alagar/logo.jpg",
  "coverImage": "/assets/photos/alagar/logo.jpg",
  "logoImage": "/assets/photos/alagar/logo.jpg",
  "logo": "أ",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 35,
  "minOrder": 150,
  "time": "40 - 70 دقيقة",
  "distance": 14,
  "location": {
   "lat": 41.123853,
   "lng": 28.772243
  },
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.123853,28.772243",
  "open": true,
  "featured": true,
  "hasOffer": false,
  "description": "فرع كايا شهير من مطعم الأغر شاورما (Ala Gardoner) في باشاك شهير بإسطنبول: شاورما اللحم والدجاج، السندويشات والوجبات العربية، الصرر والشرايح والمناسف، وقسم الغربي (زنجر، كريسبي، برغر الأطفال). الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
  "address": "KAYABAŞI MAHALLESI ADNAN MENDERES BULVARI PARK MAVERA 1 A03 BLOK NO: 10 CO, 34494 Başakşehir/İstanbul، تركيا",
  "phone": "+90 552 733 22 11",
  "whatsapp": "+90 552 733 22 11",
  "email": "",
  "website": "http://menu.alagardoner.com/",
  "sourceUrl": "http://menu.alagardoner.com/select-branch/1",
  "hours": "يومياً — يرجى تأكيد أوقات العمل عبر واتساب الفرع",
  "areas": [
   "باشاك شهير",
   "إسطنبول",
   "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام من الفرع",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true,
  "sourceBranded": true
 },
 {
  "id": 27,
  "name": "مطعم الأغر شاورما - اسنيورت",
  "branchName": "اسنيورت",
  "branchGroup": "alagar",
  "category": "مطاعم",
  "image": "/assets/photos/alagar/logo.jpg",
  "coverImage": "/assets/photos/alagar/logo.jpg",
  "logoImage": "/assets/photos/alagar/logo.jpg",
  "logo": "أ",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 35,
  "minOrder": 150,
  "time": "30 - 55 دقيقة",
  "distance": 16,
  "location": {
   "lat": 41.034901,
   "lng": 28.678696
  },
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.034901,28.678696",
  "open": true,
  "featured": false,
  "hasOffer": false,
  "description": "فرع اسنيورت من مطعم الأغر شاورما (Ala Gardoner) في إسنيورت بإسطنبول: شاورما اللحم والدجاج، السندويشات والوجبات العربية، الصرر والشرايح والمناسف، وقسم الغربي (زنجر، كريسبي، برغر الأطفال). الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
  "address": "Merkez, 1103. Sk. NO:11, 34517 Esenyurt/İstanbul، تركيا",
  "phone": "+90 538 883 22 29",
  "whatsapp": "+90 538 883 22 29",
  "email": "",
  "website": "http://menu.alagardoner.com/",
  "sourceUrl": "http://menu.alagardoner.com/select-branch/2",
  "hours": "يومياً — يرجى تأكيد أوقات العمل عبر واتساب الفرع",
  "areas": [
   "إسنيورت",
   "إسطنبول",
   "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام من الفرع",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true,
  "sourceBranded": true
 },
 {
  "id": 28,
  "name": "مطعم الأغر شاورما - بيليك دوزو",
  "branchName": "بيليك دوزو",
  "branchGroup": "alagar",
  "category": "مطاعم",
  "image": "/assets/photos/alagar/logo.jpg",
  "coverImage": "/assets/photos/alagar/logo.jpg",
  "logoImage": "/assets/photos/alagar/logo.jpg",
  "logo": "أ",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 35,
  "minOrder": 150,
  "time": "30 - 55 دقيقة",
  "distance": 17,
  "location": {
   "lat": 41.024084,
   "lng": 28.644626
  },
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.024084,28.644626",
  "open": true,
  "featured": false,
  "hasOffer": false,
  "description": "فرع بيليك دوزو من مطعم الأغر شاورما (Ala Gardoner) في إسنيورت بإسطنبول: شاورما اللحم والدجاج، السندويشات والوجبات العربية، الصرر والشرايح والمناسف، وقسم الغربي (زنجر، كريسبي، برغر الأطفال). الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
  "address": "Cumhuriyet, Necip Fazıl Kısakürek Cd No:75, 34515 Esenyurt/İstanbul، تركيا",
  "phone": "+90 532 459 57 77",
  "whatsapp": "+90 532 459 57 77",
  "email": "",
  "website": "http://menu.alagardoner.com/",
  "sourceUrl": "http://menu.alagardoner.com/select-branch/3",
  "hours": "يومياً — يرجى تأكيد أوقات العمل عبر واتساب الفرع",
  "areas": [
   "إسنيورت",
   "إسطنبول",
   "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام من الفرع",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true,
  "sourceBranded": true
 },
 {
  "id": 29,
  "name": "مطعم الأغر شاورما - الفاتح",
  "branchName": "الفاتح",
  "branchGroup": "alagar",
  "category": "مطاعم",
  "image": "/assets/photos/alagar/logo.jpg",
  "coverImage": "/assets/photos/alagar/logo.jpg",
  "logoImage": "/assets/photos/alagar/logo.jpg",
  "logo": "أ",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 35,
  "minOrder": 150,
  "time": "35 - 60 دقيقة",
  "distance": 6,
  "location": {
   "lat": 41.019002,
   "lng": 28.946256
  },
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.019002,28.946256",
  "open": true,
  "featured": false,
  "hasOffer": false,
  "description": "فرع الفاتح من مطعم الأغر شاورما (Ala Gardoner) في الفاتح بإسطنبول: شاورما اللحم والدجاج، السندويشات والوجبات العربية، الصرر والشرايح والمناسف، وقسم الغربي (زنجر، كريسبي، برغر الأطفال). الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
  "address": "Akşemsettin, Akdeniz Cd. 82/A, 34080 Fatih/İstanbul، تركيا",
  "phone": "+90 555 556 50 00",
  "whatsapp": "+90 555 556 50 00",
  "email": "",
  "website": "http://menu.alagardoner.com/",
  "sourceUrl": "http://menu.alagardoner.com/select-branch/4",
  "hours": "يومياً — يرجى تأكيد أوقات العمل عبر واتساب الفرع",
  "areas": [
   "الفاتح",
   "إسطنبول",
   "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام من الفرع",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true,
  "sourceBranded": true
 },
 {
  "id": 30,
  "name": "مطعم الأغر شاورما - شيرين ايفلر",
  "branchName": "شيرين ايفلر",
  "branchGroup": "alagar",
  "category": "مطاعم",
  "image": "/assets/photos/alagar/logo.jpg",
  "coverImage": "/assets/photos/alagar/logo.jpg",
  "logoImage": "/assets/photos/alagar/logo.jpg",
  "logo": "أ",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 35,
  "minOrder": 150,
  "time": "35 - 60 دقيقة",
  "distance": 9,
  "location": {
   "lat": 40.992854,
   "lng": 28.844323
  },
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=40.992854,28.844323",
  "open": true,
  "featured": false,
  "hasOffer": false,
  "description": "فرع شيرين ايفلر من مطعم الأغر شاورما (Ala Gardoner) في شيرين ايفلر بإسطنبول: شاورما اللحم والدجاج، السندويشات والوجبات العربية، الصرر والشرايح والمناسف، وقسم الغربي (زنجر، كريسبي، برغر الأطفال). الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
  "address": "ŞİRİNEVLER MAH. GEDİZ SK. ÜNAL APT NO: 7 B, BAHÇELİEVLER/İSTANBUL، تركيا",
  "phone": "+90 553 851 33 31",
  "whatsapp": "+90 553 851 33 31",
  "email": "",
  "website": "http://menu.alagardoner.com/",
  "sourceUrl": "http://menu.alagardoner.com/select-branch/5",
  "hours": "يومياً — يرجى تأكيد أوقات العمل عبر واتساب الفرع",
  "areas": [
   "شيرين ايفلر",
   "إسطنبول",
   "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام من الفرع",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true,
  "sourceBranded": true
 }
];

const alagarProductCatalog = [
 {
  "sourceId": "1",
  "name": "اصبع شاورما",
  "image": "/assets/photos/alagar/items/item-001.jpg",
  "price": 175,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "اصبع شاورما من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "2",
  "name": "سندويشة لحم عادي",
  "image": "/assets/photos/alagar/items/item-002.jpg",
  "price": 300,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "سندويشة لحم عادي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "3",
  "name": "سندويشة دبل",
  "image": "/assets/photos/alagar/items/item-003.jpg",
  "price": 375,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "سندويشة دبل من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4",
  "name": "وجبة عربي عادي",
  "image": "/assets/photos/alagar/items/item-004.jpg",
  "price": 415,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "وجبة عربي عادي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "5",
  "name": "وجبة عربي دبل",
  "image": "/assets/photos/alagar/items/item-005.jpg",
  "price": 700,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "وجبة عربي دبل من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "6",
  "name": "وجبة الأغر",
  "image": "/assets/photos/alagar/items/item-006.jpg",
  "price": 700,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "وجبة الأغر من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "7",
  "name": "صرة الأغر",
  "image": "/assets/photos/alagar/items/item-007.jpg",
  "price": 525,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "صرة الأغر من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "8",
  "name": "شرايح لحم 200غ",
  "image": "/assets/photos/alagar/items/item-008.jpg",
  "price": 575,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "شرايح لحم 200غ من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "9",
  "name": "عربي عائلي",
  "image": "/assets/photos/alagar/items/item-009.jpg",
  "price": 2750,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "عربي عائلي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "10",
  "name": "منسف شاورما",
  "image": "/assets/photos/alagar/items/item-010.jpg",
  "price": 3300,
  "unit": "",
  "category": "اللحم",
  "available": true,
  "featured": false,
  "description": "منسف شاورما من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "11",
  "name": "اصبع شاورما",
  "image": "/assets/photos/alagar/items/item-011.jpg",
  "price": 120,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "اصبع شاورما من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "12",
  "name": "سندويشة عادي",
  "image": "/assets/photos/alagar/items/item-012.jpg",
  "price": 175,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "سندويشة عادي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "13",
  "name": "سندويشة دبل",
  "image": "/assets/photos/alagar/items/item-013.jpg",
  "price": 225,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "سندويشة دبل من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "14",
  "name": "وجبة عربي عادي",
  "image": "/assets/photos/alagar/items/item-014.jpg",
  "price": 280,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "وجبة عربي عادي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "15",
  "name": "وجبة عربي دبل",
  "image": "/assets/photos/alagar/items/item-015.jpg",
  "price": 460,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "وجبة عربي دبل من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "16",
  "name": "وجبة الأغر",
  "image": "/assets/photos/alagar/items/item-016.jpg",
  "price": 490,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "وجبة الأغر من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "17",
  "name": "صرة الأغر",
  "image": "/assets/photos/alagar/items/item-017.jpg",
  "price": 400,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "صرة الأغر من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "18",
  "name": "شرايح 200غ",
  "image": "/assets/photos/alagar/items/item-018.jpg",
  "price": 350,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "شرايح 200غ من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "19",
  "name": "عربي عائلي",
  "image": "/assets/photos/alagar/items/item-019.jpg",
  "price": 1650,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "عربي عائلي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "20",
  "name": "منسف شاورما دجاج",
  "image": "/assets/photos/alagar/items/item-020.jpg",
  "price": 2100,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "منسف شاورما دجاج من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "42",
  "name": "عائلي ميكس",
  "image": "/assets/photos/alagar/items/item-021.jpg",
  "price": 2200,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "عائلي ميكس من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "116",
  "name": "وجبة الاطفال",
  "image": "/assets/photos/alagar/items/item-022.jpg",
  "price": 175,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "وجبة الاطفال من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "118",
  "name": "زنجر",
  "image": "/assets/photos/alagar/items/item-023.jpg",
  "price": 425,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "زنجر من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "119",
  "name": "كريسبي",
  "image": "/assets/photos/alagar/items/item-024.jpg",
  "price": 425,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "كريسبي من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "126",
  "name": "شاورما صمون",
  "image": "/assets/photos/alagar/items/item-025.jpg",
  "price": 210,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما صمون من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "127",
  "name": "سندويشة كريسبي - زنجر",
  "image": "/assets/photos/alagar/items/item-026.jpg",
  "price": 240,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "سندويشة كريسبي - زنجر من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "128",
  "name": "بطاطا مع قشقوان",
  "image": "/assets/photos/alagar/items/item-027.jpg",
  "price": 185,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "بطاطا مع قشقوان من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "129",
  "name": "برغر اطفال",
  "image": "/assets/photos/alagar/items/item-028.jpg",
  "price": 175,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "برغر اطفال من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "150",
  "name": "جامبو الاغر 1",
  "image": "/assets/photos/alagar/items/item-029.jpg",
  "price": 1700,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "جامبو الاغر 1 من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "151",
  "name": "جامبو الاغر 2",
  "image": "/assets/photos/alagar/items/item-030.jpg",
  "price": 2000,
  "unit": "",
  "category": "قسم الغربي",
  "available": true,
  "featured": false,
  "description": "جامبو الاغر 2 من مطعم الأغر شاورما.",
  "imageFit": "cover",
  "options": []
 }
];

const alagarProducts = alagarBranches.flatMap((store, branchIndex) => alagarProductCatalog.map((product, productIndex) => ({
  ...product,
  id: 700001 + (branchIndex * 1000) + productIndex,
  storeId: store.id
})));

const alagarDeliverySettings = Object.fromEntries(alagarBranches.map(store => [store.id, {
  mode: "distance",
  fixedFee: store.delivery,
  ratePerKm: 15,
  prepMinutes: 30,
  maxRoundTripKm: 120
}]));
