// Generated for شركة الأحدب (ALAHDAB) — سوبر ماركت عربي, Molla Gürani, Fatih, İstanbul.
// Source: Shopier store https://www.shopier.com/ALAHDAB (search_product API). Prices in TL.
// NOTE: full catalog kept for the Supabase push; loadCatalogFromSupabase() overwrites at runtime.
const alahdabStore = {
 "id": 81,
 "name": "شركة الأحدب",
 "category": "سوبر ماركت",
 "image": "/assets/photos/alahdab/cover.jpg",
 "coverImage": "/assets/photos/alahdab/cover.jpg",
 "logoImage": "/assets/photos/alahdab/logo.jpg",
 "logo": "أ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 30,
 "minOrder": 150,
 "time": "45 - 90 دقيقة",
 "distance": 0,
 "location": { "lat": 41.0114592, "lng": 28.9425936 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=%D8%B4%D8%B1%D9%83%D8%A9%20%D8%A7%D9%84%D8%A3%D8%AD%D8%AF%D8%A8%20ALAHDAB&query_place_id=ChIJtZz1yi-6yhQRRVIuhgmYdaA",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "شركة الأحدب — سوبر ماركت عربي في منطقة الفاتح بإسطنبول، يقدّم منتجات غذائية عربية وشامية أصيلة: بهارات وتوابل، معلبات ومخللات، أجبان وسمن وزيوت، طحينة وحلاوة، قهوة وشاي ومتّة، كسكس وأرز، مشروبات وسناكس، إضافة إلى مواد التنظيف وأغذية الأطفال والحيوانات. يوصل إلى بابك.",
 "address": "حي مُلا غوراني، الفاتح، إسطنبول، تركيا",
 "phone": "+90 507 001 87 07",
 "whatsapp": "+90 507 001 87 07",
 "email": "",
 "website": "https://www.shopier.com/ALAHDAB",
 "sourceUrl": "https://www.shopier.com/ALAHDAB",
 "hours": "مفتوح ٢٤ ساعة",
 "areas": [ "الفاتح", "إسطنبول", "مناطق التوصيل حسب المسافة" ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const alahdabFullCatalog = [
 // لحوم
  { name: "لحم غنم صافي", price: 900, category: "لحوم", unit: "", image: "/assets/photos/alahdab/38179235.jpg" },
 // منوعات
  { name: "لعبة Labubu الأصلية", price: 1850, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37983540.jpg" },
  { name: "عسل ابيض اصلي 250 غرام", price: 425, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37660104.jpg" },
  { name: "1 كيلو تشكيلة سورية", price: 950, oldPrice: 1400, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37633731.jpg" },
  { name: "فلافل حنيف الاصلي 400 غرام", price: 125, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37632911.jpg" },
  { name: "معمول بدون سكر", price: 355, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37628461.jpg" },
  { name: "BISCOFF LOTUS بسكويت 125 غرام", price: 210, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37581549.jpg" },
  { name: "BISCOFF LOTUS", price: 400, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37581454.jpg" },
  { name: "CLEAR شامبو", price: 285, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37577250.jpg" },
  { name: "اصنص مانجو", price: 485, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37567933.jpg" },
  { name: "ابو قوس", price: 165, category: "منوعات", unit: "", image: "/assets/photos/alahdab/37521388.jpg" },
 // شاي
  { name: "شاي تفاح", price: 280, category: "شاي", unit: "", image: "/assets/photos/alahdab/37662328.jpg" },
  { name: "شاي ماتشا الأصلية 20 حبة", price: 400, category: "شاي", unit: "", image: "/assets/photos/alahdab/37662106.jpg" },
  { name: "شاي الغزالين 200 غرام", price: 300, category: "شاي", unit: "", image: "/assets/photos/alahdab/37631305.jpg" },
  { name: "شاي الوزة 200 غرام", price: 300, category: "شاي", unit: "", image: "/assets/photos/alahdab/37631275.jpg" },
  { name: "شاي احمد 200 غرام", price: 285, category: "شاي", unit: "", image: "/assets/photos/alahdab/37630697.jpg" },
  { name: "شاي جيهان الأصلية معطر 200 غرام", price: 235, category: "شاي", unit: "", image: "/assets/photos/alahdab/37630076.jpg" },
  { name: "شاي محمود اسود 200 غرام", price: 235, category: "شاي", unit: "", image: "/assets/photos/alahdab/37630025.jpg" },
  { name: "شاي راىس الحصان الأصلية 140 غرام", price: 365, category: "شاي", unit: "", image: "/assets/photos/alahdab/37629370.jpg" },
  { name: "شاي Lipton الأصلية", price: 285, category: "شاي", unit: "", image: "/assets/photos/alahdab/37629293.jpg" },
  { name: "شاي الربيع الأصلية 450 غرام", price: 330, category: "شاي", unit: "", image: "/assets/photos/alahdab/37629232.jpg" },
  { name: "شاي الملوك 400 غرام", price: 350, category: "شاي", unit: "", image: "/assets/photos/alahdab/37628916.jpg" },
  { name: "شاي الروحة 400 غرام", price: 375, category: "شاي", unit: "", image: "/assets/photos/alahdab/37628768.jpg" },
  { name: "شاي الكبوس 200 غرام", price: 220, category: "شاي", unit: "", image: "/assets/photos/alahdab/37552187.jpg" },
  { name: "شاي احمد AHMAD TEA", price: 250, category: "شاي", unit: "", image: "/assets/photos/alahdab/37545952.jpg" },
  { name: "شاي السبع", price: 220, category: "شاي", unit: "", image: "/assets/photos/alahdab/37527098.jpg" },
 // بخور وعطور
  { name: "ماء الزهر الطبيعي مستخرج من زهر الناريج", price: 285, category: "بخور وعطور", unit: "", image: "/assets/photos/alahdab/37661134.jpg" },
  { name: "ماء الورد الاصلي مستخرج من الورد الجوري الدمشقي", price: 285, category: "بخور وعطور", unit: "", image: "/assets/photos/alahdab/37661009.jpg" },
  { name: "مبخرة إلكترونية سعودية", price: 1850, category: "بخور وعطور", unit: "", image: "/assets/photos/alahdab/37659498.jpg" },
  { name: "افخم انواع البخور", price: 500, category: "بخور وعطور", unit: "", image: "/assets/photos/alahdab/37658430.jpg" },
 // سناكس ونودلز
  { name: "Raffaello 150 G", price: 225, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37660897.jpg" },
  { name: "Biscof Lotus", price: 155, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37551712.jpg" },
  { name: "BOUNTY شكلاتة", price: 85, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37545187.jpg" },
  { name: "LION شكلاة", price: 100, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37545169.jpg" },
  { name: "FLUTES الاصلي", price: 85, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37545128.jpg" },
  { name: "GALAXY الاصلي", price: 85, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37545071.jpg" },
  { name: "Pringles", price: 295, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37542525.jpg" },
  { name: "شكلاتة دبي الأصلية", price: 170, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37525445.jpg" },
  { name: "الاندومي الكوري الاصلي", price: 150, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37525399.jpg" },
  { name: "TAKİS الأصلي", price: 165, category: "سناكس ونودلز", unit: "", image: "/assets/photos/alahdab/37524697.jpg" },
 // بهارات
  { name: "زعفران اصلي 1 غرام", price: 310, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37660851.jpg" },
  { name: "لبان ذكر 100 غرام", price: 160, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37658376.jpg" },
  { name: "بصل مطحون 100 غرام", price: 60, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37658118.jpg" },
  { name: "ثوم مطحون 100 غرام", price: 60, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37658108.jpg" },
  { name: "بذور الكتان 100 غرام", price: 65, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657999.jpg" },
  { name: "ورد جوري 100 غرام", price: 185, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657914.jpg" },
  { name: "بهار جبنة تشيدر 100 غرام", price: 80, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657737.jpg" },
  { name: "بذور الشيا 100 غرام", price: 90, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657527.jpg" },
  { name: "زنجبيل 100 غرام", price: 65, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657481.jpg" },
  { name: "سماق مطحون 100 غرام", price: 90, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657457.jpg" },
  { name: "فليفلة مطحونة 100 غرام", price: 85, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657434.jpg" },
  { name: "جوزة الطيب 100 غرام", price: 125, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657414.jpg" },
  { name: "كركم 100 غرام", price: 55, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657381.jpg" },
  { name: "بابونج 100 غرام", price: 350, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37657256.jpg" },
  { name: "زعتر فلسطيني أخضر 400 غرام", price: 265, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37632840.jpg" },
  { name: "زعتر حنيف اكسترا 500 غرام", price: 165, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37632756.jpg" },
  { name: "Knoorr بهارات", price: 365, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37577612.jpg" },
  { name: "زعتر العرجاوي الاصلي", price: 385, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37552509.jpg" },
  { name: "كاري المختار", price: 160, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37552461.jpg" },
  { name: "خلطة البشاميل MAGGI", price: 75, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37552444.jpg" },
  { name: "سبع بهارات 100 غرام", price: 75, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37544184.jpg" },
  { name: "كاري 100 غرام", price: 45, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37542373.jpg" },
  { name: "قرفة 100 غرام", price: 50, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37542122.jpg" },
  { name: "ماجي دجاج الأصلية", price: 35, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37542083.jpg" },
  { name: "هال 100 غرام EXSTRA", price: 290, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37542008.jpg" },
  { name: "كزبرة 100 غرام", price: 55, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37541750.jpg" },
  { name: "بهار حب 100 غرام", price: 85, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37541730.jpg" },
  { name: "كمون 100 غرام", price: 75, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37541718.jpg" },
  { name: "بهار كبسة سوريا 100 غرام", price: 65, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37541509.jpg" },
  { name: "بهار كبسة الاسناد الاصلي السعودي", price: 325, category: "بهارات", unit: "", image: "/assets/photos/alahdab/37541307.jpg" },
 // صلصات ومخللات
  { name: "قشطة قيمر Kdd 125 غرام × 4", price: 250, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37660750.jpg" },
  { name: "جميد حجر نصف كيلو", price: 450, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37581815.jpg" },
  { name: "جميد سائل 1 كيلو", price: 685, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37581691.jpg" },
  { name: "مايونيز MAZOLA 1 كيلو", price: 900, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37581647.jpg" },
  { name: "صاص البدوي الاصلي", price: 200, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37580146.jpg" },
  { name: "صاصا الين الاصلي", price: 165, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37578084.jpg" },
  { name: "خل البدوي الأبيض", price: 185, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577938.jpg" },
  { name: "خل البدوي الاصلي طبيعي 100%", price: 195, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577925.jpg" },
  { name: "TBASCO الاصلي 60 Ml", price: 285, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577900.jpg" },
  { name: "شطة رنا الأصلية 155", price: 155, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577877.jpg" },
  { name: "شطة غلوريا الاصليه", price: 155, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577860.jpg" },
  { name: "مربا قرع طبيعي", price: 385, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577791.jpg" },
  { name: "مايونيز 330 غرام", price: 100, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577575.jpg" },
  { name: "كتشب TATA 390 غرام", price: 100, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37577558.jpg" },
  { name: "شطة GLORIA", price: 125, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37552659.jpg" },
  { name: "ملوخية مفرزة بسمة", price: 150, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37544193.jpg" },
  { name: "ملوخية بلدية نظيفة جاهزة لل طبخ", price: 210, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37544163.jpg" },
  { name: "مكدوس جديد 600غ", price: 220, category: "صلصات ومخللات", unit: "", image: "/assets/photos/alahdab/37540951.jpg" },
 // مشروبات
  { name: "TANG برتقال الاصلي", price: 455, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37660583.jpg" },
  { name: "ظروف عصير TANG 375 غرام", price: 250, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37627703.jpg" },
  { name: "SUNQUICK برتقال", price: 500, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37581618.jpg" },
  { name: "Mountain Dew", price: 75, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37547643.jpg" },
  { name: "عصير ميرندا", price: 65, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37547567.jpg" },
  { name: "BARBICAN الاصلي", price: 150, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37544846.jpg" },
  { name: "شراب VIMTO", price: 355, category: "مشروبات", unit: "", image: "/assets/photos/alahdab/37524349.jpg" },
 // قهوة
  { name: "فناجين قهوة 12 حبة", price: 2850, oldPrice: 3650, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37659077.jpg" },
  { name: "مصب قهوه نحاس اصلي حجم كبير", price: 2500, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37658972.jpg" },
  { name: "100 غرام قهوة CLASIC الأصلية", price: 485, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37632734.jpg" },
  { name: "COFFEE MATE", price: 325, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37632319.jpg" },
  { name: "NESCAFE GOLD الأصلية 100 غرام", price: 450, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37631871.jpg" },
  { name: "بن الحموي الاصلي", price: 295, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37631842.jpg" },
  { name: "بن خلدون الاصلي 500 غرام", price: 1400, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37631733.jpg" },
  { name: "قهوة معتوق الأصلية 200 غرام", price: 400, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37631702.jpg" },
  { name: "قهوة النجار الأصلية", price: 450, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37631644.jpg" },
  { name: "قهوة دومينغو الاصلي 200 غرام", price: 200, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37631592.jpg" },
  { name: "بن الشامي الاصلي", price: 650, category: "قهوة", unit: "", image: "/assets/photos/alahdab/37552618.jpg" },
 // أغذية حيوانات
  { name: "طون قطط PURINA GOURMET", price: 125, category: "أغذية حيوانات", unit: "", image: "/assets/photos/alahdab/37658625.jpg" },
  { name: "تراب قطط بدون رائحة 10 L", price: 300, category: "أغذية حيوانات", unit: "", image: "/assets/photos/alahdab/37658601.jpg" },
  { name: "اكل قطط WHISKAS 300 G", price: 285, category: "أغذية حيوانات", unit: "", image: "/assets/photos/alahdab/37658558.jpg" },
  { name: "طعام قطط +1 WHISKAS 300 G", price: 285, category: "أغذية حيوانات", unit: "", image: "/assets/photos/alahdab/37658540.jpg" },
 // معلبات
  { name: "QUAKER كويكرشوفان ابيض", price: 225, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37628681.jpg" },
  { name: "قشطة بوك PUCK", price: 88, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37580905.jpg" },
  { name: "مربا الورد الطبيعي", price: 200, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37577772.jpg" },
  { name: "فول بلدنا حبة كبيرة", price: 65, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573687.jpg" },
  { name: "فول مدمس بلدنا", price: 55, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573643.jpg" },
  { name: "فول مدمس هنا", price: 55, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573624.jpg" },
  { name: "فول مدمس الصفوة", price: 55, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573585.jpg" },
  { name: "أمريكان فول مدمس الاصلي", price: 85, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573567.jpg" },
  { name: "باذنجان Tat", price: 125, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573537.jpg" },
  { name: "سلطة الباذنجان", price: 125, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573527.jpg" },
  { name: "فاصوليا Burcu", price: 100, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573493.jpg" },
  { name: "عسل تمر كربلاء", price: 265, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573157.jpg" },
  { name: "دبس تمر و عنب", price: 225, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37573110.jpg" },
  { name: "ذرة معلبات Tukaş 3×150", price: 150, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37571411.jpg" },
  { name: "فطر مقطع خطيب", price: 65, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37571352.jpg" },
  { name: "تات طماطم 170 غرام", price: 55, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37571332.jpg" },
  { name: "هنا مرتديلا 200 غرام", price: 55, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37571115.jpg" },
  { name: "هنا HOT DOGS", price: 85, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37571055.jpg" },
  { name: "تونة كاملة بالطماطم", price: 215, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37570804.jpg" },
  { name: "تي سي بوي لحم التونة الخفيف TC BOY", price: 220, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37568097.jpg" },
  { name: "طون KARMA الاصلي", price: 125, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37567752.jpg" },
  { name: "طون Joly الاصلي", price: 165, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37567726.jpg" },
  { name: "سردين مغربي", price: 125, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37567702.jpg" },
  { name: "طون بلدنا", price: 75, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37567633.jpg" },
  { name: "SICAN معجون", price: 155, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521985.jpg" },
  { name: "SICAM", price: 105, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521961.jpg" },
  { name: "هريسة تونسية", price: 105, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521947.jpg" },
  { name: "Isabel طون مغربي", price: 250, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521916.jpg" },
  { name: "HotDog التغذية الأصلية", price: 185, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521891.jpg" },
  { name: "زوان دجاج الأصلية", price: 200, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521860.jpg" },
  { name: "التغذية الأصلية دجاج", price: 100, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521814.jpg" },
  { name: "التغذية الأصلية", price: 125, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521660.jpg" },
  { name: "BORDON الأصلية", price: 250, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521589.jpg" },
  { name: "EXTRA CORNED BEEF", price: 295, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521570.jpg" },
  { name: "طون ليو", price: 75, category: "معلبات", unit: "", image: "/assets/photos/alahdab/37521526.jpg" },
 // كسكس
  { name: "السفة الشعيرية الأصلية الكرم 1 كيلو", price: 300, category: "كسكس", unit: "", image: "/assets/photos/alahdab/37628387.jpg" },
  { name: "COUSCOUS mama 1 كيلو", price: 220, category: "كسكس", unit: "", image: "/assets/photos/alahdab/37628254.jpg" },
  { name: "بلبولة TRIA 1 كيلو", price: 320, category: "كسكس", unit: "", image: "/assets/photos/alahdab/37628221.jpg" },
  { name: "COUSCOUS طعامي", price: 235, category: "كسكس", unit: "", image: "/assets/photos/alahdab/37628188.jpg" },
  { name: "شعيرية من مهران، 150 غرام", price: 255, category: "كسكس", unit: "", image: "/assets/photos/alahdab/37628108.jpg" },
 // أغذية أطفال ومعجنات
  { name: "شعرية filiz", price: 55, category: "أغذية أطفال ومعجنات", unit: "", image: "/assets/photos/alahdab/37628270.jpg" },
  { name: "CERELAC قمح الاصلي", price: 450, category: "أغذية أطفال ومعجنات", unit: "", image: "/assets/photos/alahdab/37582774.jpg" },
  { name: "MILO NESTLE الاصلي", price: 350, category: "أغذية أطفال ومعجنات", unit: "", image: "/assets/photos/alahdab/37582156.jpg" },
 // أجبان
  { name: "حليب المدهش الاصلي 400 غرام", price: 300, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37627599.jpg" },
  { name: "حليب PUCK الأصلية 400 غرام", price: 330, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37627364.jpg" },
  { name: "حليب NIDO 350 غ", price: 335, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37627258.jpg" },
  { name: "جبنة ابو الولد ×44", price: 325, oldPrice: 485, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37552390.jpg" },
  { name: "كرافت شيدر", price: 85, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37552304.jpg" },
  { name: "كرافت تشيدر 250 غ", price: 250, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37552135.jpg" },
  { name: "جبنة المراعي الأصلية 200 غرام", price: 185, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37552121.jpg" },
  { name: "جبنة شلل بلدية نصف كيلو", price: 200, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37551840.jpg" },
  { name: "جبنة المراعي الأصلية", price: 385, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37545761.jpg" },
  { name: "جبنة Kiri الاصلية", price: 480, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37545594.jpg" },
  { name: "جبنة PUCK الأصلية 140 غ", price: 185, category: "أجبان", unit: "", image: "/assets/photos/alahdab/37524311.jpg" },
 // حليب وكريمة
  { name: "كريمة طبخ 200 ML", price: 125, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37626701.jpg" },
  { name: "كريمة حلويات 200ML", price: 125, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37626682.jpg" },
  { name: "كريمة طبخ و حلويات HOPLA 1 L", price: 320, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37582061.jpg" },
  { name: "كريم شانتي بالكاكو", price: 125, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37581420.jpg" },
  { name: "كريم كراميل CREAM CARAMEL", price: 95, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37581341.jpg" },
  { name: "جيلة JELLY", price: 55, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37581230.jpg" },
  { name: "المرجان كريمة البندق مع الكاكو 350 غرام", price: 450, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37581007.jpg" },
  { name: "MASTER كريمة الحليب المكثف", price: 185, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37580928.jpg" },
  { name: "الفجر الاصلي حليب مكثف", price: 195, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37580916.jpg" },
  { name: "حليب مكثف NESTLE", price: 210, category: "حليب وكريمة", unit: "", image: "/assets/photos/alahdab/37551540.jpg" },
 // منظفات
  { name: "Dettol الاصلي 500Ml", price: 350, category: "منظفات", unit: "", image: "/assets/photos/alahdab/37581084.jpg" },
  { name: "جل للاستحمام", price: 485, category: "منظفات", unit: "", image: "/assets/photos/alahdab/37577090.jpg" },
  { name: "ثمرة القهوة العربية كثافة CONDITIONER", price: 450, category: "منظفات", unit: "", image: "/assets/photos/alahdab/37577075.jpg" },
  { name: "Vatika للحماية من القشرة", price: 485, category: "منظفات", unit: "", image: "/assets/photos/alahdab/37577040.jpg" },
  { name: "Vatican فاتيكا شامبو مضاد لل للتسير", price: 385, category: "منظفات", unit: "", image: "/assets/photos/alahdab/37577014.jpg" },
  { name: "صابون غار حلبي اصلي", price: 125, category: "منظفات", unit: "", image: "/assets/photos/alahdab/37542404.jpg" },
 // زيوت
  { name: "زيت مغربي اصلي 500 ml", price: 485, category: "زيوت", unit: "", image: "/assets/photos/alahdab/37577304.jpg" },
  { name: "زيت قلي Biryağ 0.5L", price: 85, category: "زيوت", unit: "", image: "/assets/photos/alahdab/37574811.jpg" },
  { name: "زيت زيتون صافي 500ML", price: 250, category: "زيوت", unit: "", image: "/assets/photos/alahdab/37551927.jpg" },
 // طحينة وحلاوة
  { name: "حلاوة مهروسة 350 غرام", price: 140, category: "طحينة وحلاوة", unit: "", image: "/assets/photos/alahdab/37576515.jpg" },
  { name: "طحينة الرحمة 400 غرام", price: 125, category: "طحينة وحلاوة", unit: "", image: "/assets/photos/alahdab/37572950.jpg" },
  { name: "طحينة مهروسة 400 غرام", price: 135, category: "طحينة وحلاوة", unit: "", image: "/assets/photos/alahdab/37571228.jpg" },
  { name: "طحينة علم الدين", price: 255, category: "طحينة وحلاوة", unit: "", image: "/assets/photos/alahdab/37522035.jpg" },
  { name: "راشي الأخوين", price: 255, category: "طحينة وحلاوة", unit: "", image: "/assets/photos/alahdab/37522007.jpg" },
 // سمن وزبدة
  { name: "سمن غنم طبيعي 500 غ", price: 550, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37574584.jpg" },
  { name: "سمنة الأصيل الأصلية 1.150 Lt", price: 515, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37573016.jpg" },
  { name: "VITA 1 L سمنة", price: 195, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37567569.jpg" },
  { name: "سمنة EVET 1.820kg", price: 300, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37567485.jpg" },
  { name: "سمن نباتي بالنكهة الحيوانية الخير 1L", price: 195, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37522502.jpg" },
  { name: "سمن حيواني الحلوب الأصلية 400غ", price: 550, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37522270.jpg" },
  { name: "سمنة حبيبة نباتية اصليه 1L", price: 210, category: "سمن وزبدة", unit: "", image: "/assets/photos/alahdab/37522222.jpg" },
 // خبز صحي
  { name: "ASRIN TANDIRI غبز اسمر صحي", price: 125, category: "خبز صحي", unit: "", image: "/assets/photos/alahdab/37543962.jpg" },
 // متة
  { name: "TARAGUL متة", price: 125, category: "متة", unit: "", image: "/assets/photos/alahdab/37543043.jpg" },
  { name: "متة PİPORE", price: 125, category: "متة", unit: "", image: "/assets/photos/alahdab/37542830.jpg" },
  { name: "متى خارطة الأصلية", price: 125, category: "متة", unit: "", image: "/assets/photos/alahdab/37542817.jpg" },
 // أرز
  { name: "COUSCOUS", price: 165, category: "أرز", unit: "", image: "/assets/photos/alahdab/37524463.jpg" },
  { name: "رز محمود الاصلي", price: 125, category: "أرز", unit: "", image: "/assets/photos/alahdab/37521334.jpg" },
  { name: "رز الشعلان الأصلي", price: 125, category: "أرز", unit: "", image: "/assets/photos/alahdab/37521287.jpg" },
];

const alahdabProductCatalog = [];

const alahdabProducts = (alahdabProductCatalog.length ? alahdabProductCatalog : alahdabFullCatalog).map((product, index) => ({
  ...product,
  available: product.available !== false,
  id: 1650001 + index,
  storeId: alahdabStore.id
}));

const alahdabDeliverySettings = {
  [alahdabStore.id]: { mode: "distance", fixedFee: 30, ratePerKm: 12, prepMinutes: 40, maxRoundTripKm: 140 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { alahdabStore, alahdabProducts, alahdabDeliverySettings };
}
