// Generated for ملحمة ومعجنات العطا (ALATA ET, Kasap-Fırın) — Kayabaşı, Başakşehir/İstanbul.
// Butcher + Levantine pastries/pizza hybrid. Source: trybany.com storefront
// (app.trybany.com/ar/ata-pide-f, entity idString "f"), 118 products across 9
// categories (113 with usable photos). Coords/rating/hours/phone from Google
// Maps (Place ID ChIJ4f94NVOvyhQR1L40QUUXds0, 4.4/130 reviews, phone matches
// WhatsApp exactly).
const alataetStore = {
 "id": 98,
 "name": "ملحمة ومعجنات العطا",
 "category": "ملاحم",
 "image": "/assets/photos/alataet/cover.jpg",
 "coverImage": "/assets/photos/alataet/cover.jpg",
 "logoImage": "/assets/photos/alataet/logo.png",
 "logo": "ع",
 "rating": 4.4,
 "reviews": 130,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": {
  "lat": 41.1171403,
  "lng": 28.7726275
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.1171403,28.7726275",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "ملحمة ومعجنات العطا — ملحمة ومخبز شامي في باشاك شهير يقدّم لحوماً طازجة مقطّعة حسب الطلب (هبرة، فخد، كتف، موزات، لية) إلى جانب فطائر شامية ومعجنات لحم وبيتزا ودجاج ومفرزات ومشروبات. توصيل لمناطق إسطنبول.",
 "address": "Kayabaşı, Evliya Çelebi Cd Park Maver1 Sitesi B1 blok Dükkan :149, 34494 Başakşehir/İstanbul",
 "phone": "+90 552 299 61 27",
 "whatsapp": "+90 552 299 61 27",
 "email": "",
 "website": "",
 "sourceUrl": "https://linktr.ee/ata_et",
 "hours": "يومياً 9:00 ص – 9:00 م (الثلاثاء مغلق)",
 "areas": [
  "باشاك شهير",
  "مناطق إسطنبول حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true,
 "googlePlaceId": "ChIJ4f94NVOvyhQR1L40QUUXds0",
 "googleRating": 4.4,
 "googleReviewsCount": 130,
 "googleMapsUrl": "https://maps.google.com/?cid=14805046411241242324"
};

const alataetFullCatalog = [
  {"name":"زعتر","price":40,"category":"فطائر شامية","image":"/assets/photos/alataet/p001.jpg"},
  {"name":"محمرة","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p002.jpg"},
  {"name":"شيش طاووق","price":60,"category":"فطائر شامية","image":"/assets/photos/alataet/p003.jpg"},
  {"name":"مرتديلا","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p004.jpg"},
  {"name":"سبانغ","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p005.jpg"},
  {"name":"مسخن","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p006.jpg"},
  {"name":"منقوشة ميكس","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p007.jpg"},
  {"name":"ميني بيتزا","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p008.jpg"},
  {"name":"شيش بقشقوان","price":75,"category":"فطائر شامية","image":"/assets/photos/alataet/p009.jpg"},
  {"name":"هوت دوغ","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p010.jpg"},
  {"name":"مرتديلا بالقشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p011.jpg"},
  {"name":"مكسيكي","price":65,"category":"فطائر شامية","image":"/assets/photos/alataet/p012.jpg"},
  {"name":"سنفورة","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p013.jpg"},
  {"name":"قشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p014.jpg"},
  {"name":"لبنة بالخضار","price":65,"category":"فطائر شامية","image":"/assets/photos/alataet/p015.jpg"},
  {"name":"محمرة بقشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p016.jpg"},
  {"name":"زعتر بالخضار","price":55,"category":"فطائر شامية","image":"/assets/photos/alataet/p017.jpg"},
  {"name":"جبنة شامية","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p018.jpg"},
  {"name":"لبنة وزيتون","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p019.jpg"},
  {"name":"زعتر بالقشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p020.jpg"},
  {"name":"سجق","price":85,"category":"فطائر شامية","image":"/assets/photos/alataet/p021.jpg"},
  {"name":"جبنة مسكرة","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p022.jpg","description":"جبنة بيضا وحبة البركة و فستق حلبي"},
  {"name":"لبنة","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p023.jpg"},
  {"name":"سجق تركي وقشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p024.jpg"},
  {"name":"زيتون","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p025.jpg"},
  {"name":"هوت دوغ وقشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p026.jpg"},
  {"name":"جبنة كيري","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p027.jpg"},
  {"name":"سجق وقشقوان","price":100,"category":"فطائر شامية","image":"/assets/photos/alataet/p028.jpg"},
  {"name":"قشقوان وزيتون","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p029.jpg"},
  {"name":"سلامي وقشقوان","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p030.jpg"},
  {"name":"محمرة بالزعتر","price":45,"category":"فطائر شامية","image":"/assets/photos/alataet/p031.jpg"},
  {"name":"قشقوان وفطر","price":50,"category":"فطائر شامية","image":"/assets/photos/alataet/p032.jpg"},
  {"name":"جبنة شامية نص كيلو","price":375,"category":"فطائر شامية","image":"/assets/photos/alataet/p033.jpg","description":"12 قرص"},
  {"name":"صفيحة بالبندورة نص كيلو","price":1050,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p034.jpg","description":"20قرص"},
  {"name":"صفيحة باللبن نصف كيلو","price":1050,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p035.jpg","description":"20 قرص"},
  {"name":"وجبة صفيحة بندورة","price":400,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p036.jpg","description":"6 اقراص"},
  {"name":"وجبة صفيحة لبن","price":400,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p037.jpg","description":"6 اقراص"},
  {"name":"صفيحة لبن لحم غنم قرص","price":75,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p038.jpg"},
  {"name":"صفيحة باللبن اكسترا نصف كيلو","price":1200,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p039.jpg","description":"مع صنوبر بلدي, 20قرص"},
  {"name":"صفيحة بالبندورة اكسترا نصف كيلو","price":1200,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p040.jpg","description":"مع صنوبر بلدي, 20 قرص"},
  {"name":"صفيحة دجاج 1كغ","price":900,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p041.jpg"},
  {"name":"مجرمشة نصف كيلو","price":1100,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p042.jpg"},
  {"name":"مجرمشة بالخضار نص كيلو","price":1150,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p043.jpg"},
  {"name":"وجبة لحمة مجرمشة","price":400,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p044.jpg","description":"4 اقراص"},
  {"name":"شرحات على عجين نصف كيلو","price":1325,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p045.jpg","description":"لحم غنم, 5 قطع"},
  {"name":"رغيف شرحات على عجين اكسترا","price":550,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p046.jpg","description":"لحم غنم بلدي, 150 غرام"},
  {"name":"بيضات وسناسل على عجين","price":160,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p047.jpg"},
  {"name":"بيضات على عجين","price":85,"category":"فطائر اللحوم","image":"/assets/photos/alataet/p048.jpg"},
  {"name":"لحمة مفرومة ناعمة","price":1300,"category":"اللحوم النية","image":"/assets/photos/alataet/p049.jpg","description":"1 كيلو, 70% لحمة, 30% دهنة"},
  {"name":"لحم هبرة","price":1600,"category":"اللحوم النية","image":"/assets/photos/alataet/p050.jpg","description":"1 كيلو"},
  {"name":"هبرة اكسترا مفرومة ناعمة","price":1800,"category":"اللحوم النية","image":"/assets/photos/alataet/p051.jpg","description":"1 كيلو"},
  {"name":"هبرة اكسترا شقف","price":1800,"category":"اللحوم النية","image":"/assets/photos/alataet/p052.jpg","description":"1 كيلو"},
  {"name":"هبرة اكسترا راس العصفور","price":1800,"category":"اللحوم النية","image":"/assets/photos/alataet/p053.jpg","description":"1 كيلو"},
  {"name":"لحمة شرحات","price":1850,"category":"اللحوم النية","image":"/assets/photos/alataet/p054.jpg","description":"1 كيلو, لحم غنم طري جداً"},
  {"name":"هبرة اكسترا مفرومة خشنة","price":1800,"category":"اللحوم النية","image":"/assets/photos/alataet/p055.jpg","description":"1 كيلو"},
  {"name":"لحم موزات","price":1800,"category":"اللحوم النية","image":"/assets/photos/alataet/p056.jpg","description":"1 كيلو"},
  {"name":"فخد بعظمه","price":1000,"category":"اللحوم النية","image":"/assets/photos/alataet/p057.jpg","description":"1 كيلو"},
  {"name":"كتف بعظمه","price":950,"category":"اللحوم النية","image":"/assets/photos/alataet/p058.jpg","description":"1 كيلو"},
  {"name":"رقبة بعظمه","price":875,"category":"اللحوم النية","image":"/assets/photos/alataet/p059.jpg","description":"1 كيلو"},
  {"name":"موزات بعظمه","price":1150,"category":"اللحوم النية","image":"/assets/photos/alataet/p060.jpg","description":"1 كيلو"},
  {"name":"متله بعظمه (ريش)","price":1400,"category":"اللحوم النية","image":"/assets/photos/alataet/p061.jpg","description":"1 كيلو"},
  {"name":"لية شقف","price":580,"category":"اللحوم النية","image":"/assets/photos/alataet/p062.jpg","description":"1 كيلو"},
  {"name":"لية مفرومة","price":580,"category":"اللحوم النية","image":"/assets/photos/alataet/p063.jpg","description":"1 كيلو"},
  {"name":"بيتزا خضار كبير","price":375,"category":"البيتزا","image":"/assets/photos/alataet/p064.jpg"},
  {"name":"بيتزا خضار وسط","price":320,"category":"البيتزا","image":"/assets/photos/alataet/p065.jpg"},
  {"name":"بيتزا مرغريتا كبير","price":375,"category":"البيتزا","image":"/assets/photos/alataet/p066.jpg"},
  {"name":"بيتزا مرغريتا وسط","price":330,"category":"البيتزا","image":"/assets/photos/alataet/p067.jpg"},
  {"name":"بيتزا سلامي كبير","price":420,"category":"البيتزا","image":"/assets/photos/alataet/p068.jpg"},
  {"name":"بيتزا سلامي وسط","price":360,"category":"البيتزا","image":"/assets/photos/alataet/p069.jpg"},
  {"name":"بيتزا العطا وسط","price":375,"category":"البيتزا","image":"/assets/photos/alataet/p070.jpg"},
  {"name":"بيتزا العطا كبير","price":450,"category":"البيتزا","image":"/assets/photos/alataet/p071.jpg"},
  {"name":"بيتزا دجاج كبير","price":420,"category":"البيتزا","image":"/assets/photos/alataet/p072.jpg"},
  {"name":"بيتزا دجاج وسط","price":370,"category":"البيتزا","image":"/assets/photos/alataet/p073.jpg"},
  {"name":"بيتزا سجق كبير","price":400,"category":"البيتزا","image":"/assets/photos/alataet/p074.jpg"},
  {"name":"بيتزا سجق وسط","price":350,"category":"البيتزا","image":"/assets/photos/alataet/p075.jpg"},
  {"name":"بيتزا هوت دوغ كبير","price":420,"category":"البيتزا","image":"/assets/photos/alataet/p076.jpg"},
  {"name":"بيتزا هوت دوغ وسط","price":350,"category":"البيتزا","image":"/assets/photos/alataet/p077.jpg"},
  {"name":"بيتزا اللحوم الباردة كبير","price":415,"category":"البيتزا","image":"/assets/photos/alataet/p078.jpg"},
  {"name":"بيتزا اللحوم الباردة وسط","price":360,"category":"البيتزا","image":"/assets/photos/alataet/p079.jpg"},
  {"name":"بيتزا سواريه","price":25,"category":"سواريه","image":"/assets/photos/alataet/p080.jpg","description":"قطعة واحدة"},
  {"name":"جبنة شامية سواريه","price":23,"category":"سواريه","image":"/assets/photos/alataet/p081.jpg","description":"قطعة واحدة"},
  {"name":"سبانغ سواريه","price":23,"category":"سواريه","image":"/assets/photos/alataet/p082.jpg","description":"قطعة واحدة"},
  {"name":"سجق سواريه","price":30,"category":"سواريه","image":"/assets/photos/alataet/p083.jpg","description":"قطعة واحدة"},
  {"name":"صفيحة سواريه","price":25,"category":"سواريه","image":"/assets/photos/alataet/p084.jpg","description":"قطعة واحدة"},
  {"name":"محمرة سواريه","price":25,"category":"سواريه","image":"/assets/photos/alataet/p085.jpg","description":"قطعة واحدة"},
  {"name":"قشقوان سواريه","price":25,"category":"سواريه","image":"/assets/photos/alataet/p086.jpg","description":"قطعة واحدة"},
  {"name":"زعتر سواريه","price":23,"category":"سواريه","image":"/assets/photos/alataet/p087.jpg","description":"قطعة واحدة"},
  {"name":"كباب هندي نصف كيلو","price":950,"category":"لحومات بالفرن","image":"/assets/photos/alataet/p088.jpg"},
  {"name":"لحمة بالصينية (كفتة) نصف كيلو","price":875,"category":"لحومات بالفرن","image":"/assets/photos/alataet/p089.jpg"},
  {"name":"صدر","price":350,"category":"الدجاج","image":"/assets/photos/alataet/p090.jpg","description":"1 كيلو, يقطع حسب الطلب"},
  {"name":"فخد وردة","price":230,"category":"الدجاج","image":"/assets/photos/alataet/p091.jpg","description":"1 كيلو"},
  {"name":"دبوس","price":200,"category":"الدجاج","image":"/assets/photos/alataet/p092.jpg","description":"1 كيلو"},
  {"name":"دجاجة كاملة","price":185,"category":"الدجاج","image":"/assets/photos/alataet/p093.jpg","description":"1 كيلو"},
  {"name":"شيش متبل","price":500,"category":"الدجاج","image":"/assets/photos/alataet/p094.jpg","description":"1 كيلو"},
  {"name":"كبة","price":600,"category":"المفرزات","image":"/assets/photos/alataet/p095.jpg","description":"لحم غنم بلدي 9 قطع"},
  {"name":"كبة لبنية","price":600,"category":"المفرزات","image":"/assets/photos/alataet/p096.jpg","description":"لحم غنم بلدي, 15 قطعة"},
  {"name":"كبة مشوية","price":550,"category":"المفرزات","image":"/assets/photos/alataet/p097.jpg"},
  {"name":"شيش برك","price":575,"category":"المفرزات","image":"/assets/photos/alataet/p098.jpg","description":"42 قطعة"},
  {"name":"برك باللحمة","price":400,"category":"المفرزات","image":"/assets/photos/alataet/p099.jpg","description":"12 قطعة"},
  {"name":"برك بالجبنة","price":350,"category":"المفرزات","image":"/assets/photos/alataet/p100.jpg","description":"12 قطعة"},
  {"name":"برغر لحم (غنم) 500غ","price":750,"category":"المفرزات","image":"/assets/photos/alataet/p101.jpg","description":"5 قطع"},
  {"name":"برغر دجاج 500غ","price":300,"category":"المفرزات","image":"/assets/photos/alataet/p102.jpg","description":"5 قطع"},
  {"name":"سجق 500 غرام","price":700,"category":"المفرزات","image":"/assets/photos/alataet/p103.jpg","description":"سجق غنم متبل بالطعم الشامي الاصيل"},
  {"name":"cola turka","price":65,"category":"المشروبات","image":"/assets/photos/alataet/p104.jpg"},
  {"name":"7up","price":45,"category":"المشروبات","image":"/assets/photos/alataet/p105.jpg"},
  {"name":"sarıyer","price":40,"category":"المشروبات","image":"/assets/photos/alataet/p106.jpg"},
  {"name":"Cappy Portakal","price":45,"category":"المشروبات","image":"/assets/photos/alataet/p107.jpg"},
  {"name":"Lemon suda","price":20,"category":"المشروبات","image":"/assets/photos/alataet/p108.jpg"},
  {"name":"Elma soda","price":20,"category":"المشروبات","image":"/assets/photos/alataet/p109.jpg"},
  {"name":"Su","price":15,"category":"المشروبات","image":"/assets/photos/alataet/p110.jpg"},
  {"name":"Ayran","price":40,"category":"المشروبات","image":"/assets/photos/alataet/p111.jpg"},
  {"name":"cola turka 1L","price":60,"category":"المشروبات","image":"/assets/photos/alataet/p112.jpg"},
  {"name":"Yedigun 1L","price":60,"category":"المشروبات","image":"/assets/photos/alataet/p113.jpg"}
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const alataetProductCatalog = [];

const alataetProducts = (alataetProductCatalog.length ? alataetProductCatalog : alataetFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1800001 + index,
  storeId: alataetStore.id
}));

const alataetDeliverySettings = {
  [alataetStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 30, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { alataetStore, alataetProducts, alataetDeliverySettings };
}
