// Generated for مطعم البركة - باغجلار (Al-Baraka / Al-Barkah, store 74) — حي يني غون، باغجلار، إسطنبول.
// Levantine restaurant (فلافل/فطائر/بيتزا/فروج مشوي/شاورما/سندويش). Source: tillymenu.com/296/Albarakaflafel
// 126 products (30 with real photos; the rest show as clean no-image cards — the merchant uploaded a
// transparent logo instead of dish photos, so this store is in ALLOW_NO_IMAGE_STORES). Prices in TL.
// NOTE: albarakaProductCatalog is intentionally emptied in the repo (perf) — the full catalog lives in
// Supabase and is pushed via scripts/_scrape/push-store.cjs.
const albarakaStore = {
 "id": 74,
 "name": "مطعم البركة - باغجلار",
 "category": "مطاعم",
 "image": "/assets/photos/albaraka/cover.jpg",
 "coverImage": "/assets/photos/albaraka/cover.jpg",
 "logoImage": "/assets/photos/albaraka/logo.png",
 "logo": "ب",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "40 - 70 دقيقة",
 "distance": 0,
 "location": {
  "lat": 41.0226361,
  "lng": 28.8590918
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=Al-BARKAH%20RESTAURANT&query_place_id=ChIJZ9k_tQulyhQRkzLpyNs1s_0",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "مطعم عريق في قلب منطقة باغجلار – يني غون في إسطنبول، يقدّم أشهى المأكولات الشرقية الأصيلة. نختصّ بتقديم الفلافل والفطائر والبيتزا والفروج المشوي والشاورما، محضّرة يومياً من أفضل المكونات الطازجة. نحرص على تقديم نكهات منزلية وجودة عالية وخدمة سريعة — خيار مثالي للعائلات ومحبّي الطعام العربي الأصيل.",
 "address": "حي يني غون، باغجلار، إسطنبول، تركيا",
 "phone": "+90 534 512 74 70",
 "whatsapp": "+90 534 512 74 70",
 "email": "",
 "website": "https://tillymenu.com/296/Albarakaflafel",
 "sourceUrl": "https://tillymenu.com/296/Albarakaflafel",
 "hours": "",
 "areas": [
  "باغجلار",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

// Full catalog used ONLY for the Supabase push; emptied in the committed repo (see note above).
const albarakaFullCatalog = [
 {"name":"جبنة بالنعناع","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69222.jpg","sourceId":"69222"},
 {"name":"جبنة بيروتية","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69221.jpg","sourceId":"69221"},
 {"name":"بيتزا سواريه","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69223.jpg","sourceId":"69223"},
 {"name":"شيش طاووق","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69224.jpg","sourceId":"69224"},
 {"name":"سجق","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69227.jpg","sourceId":"69227"},
 {"name":"سنفورة سجق","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69228.jpg","sourceId":"69228"},
 {"name":"سنفورة مرتديلا","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69229.jpg","sourceId":"69229"},
 {"name":"جبنة ميكس","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69230.jpg","sourceId":"69230"},
 {"name":"قشوان","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69231.jpg","sourceId":"69231"},
 {"name":"محمرة","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69232.jpg","sourceId":"69232"},
 {"name":"زعتر","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69233.jpg","sourceId":"69233"},
 {"name":"سنفورة شيش","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69234.jpg","sourceId":"69234"},
 {"name":"لحمة بالخضار","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69235.jpg","sourceId":"69235"},
 {"name":"لحمة بدبس الرمان","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69236.jpg","sourceId":"69236"},
 {"name":"مرتديلا وقشوان","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69237.jpg","sourceId":"69237"},
 {"name":"شوكلاه","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69238.jpg","sourceId":"69238"},
 {"name":"جبنة شرائح مع نعناع","price":40,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69239.jpg","sourceId":"69239"},
 {"name":"جبنة شامية","price":35,"category":"فطائر و معجنات","unit":"قطعة","image":"/assets/photos/albaraka/69240.jpg","sourceId":"69240"},
 {"name":"بيتزا خضار","price":300,"category":"بيتزا","unit":"قطعة","image":"/assets/photos/albaraka/69225.jpg","sourceId":"69225","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,50]}]},
 {"name":"بيتزا سجق و فطر","price":300,"category":"بيتزا","unit":"قطعة","image":"/assets/photos/albaraka/69226.jpg","sourceId":"69226","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,50]}]},
 {"name":"بيتزا تشكن","price":300,"category":"بيتزا","unit":"قطعة","image":"","sourceId":"69241","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,50]}]},
 {"name":"بيتزا الفصول","price":300,"category":"بيتزا","unit":"قطعة","image":"/assets/photos/albaraka/69242.jpg","sourceId":"69242","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,50]}]},
 {"name":"بيتزا مارغريتا","price":300,"category":"بيتزا","unit":"قطعة","image":"/assets/photos/albaraka/69243.jpg","sourceId":"69243","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,100]}]},
 {"name":"بيتزا سبيشل","price":300,"category":"بيتزا","unit":"قطعة","image":"/assets/photos/albaraka/69244.jpg","sourceId":"69244","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,50]}]},
 {"name":"محشية الاطراف","price":350,"category":"بيتزا","unit":"قطعة","image":"/assets/photos/albaraka/69245.jpg","sourceId":"69245","options":[{"name":"الحجم","values":["وسط","عائلي"],"extra":[0,75]}]},
 {"name":"صحن فتة بالسمنة","price":225,"category":"اطباق الفطور","unit":"طبق","image":"/assets/photos/albaraka/69246.jpg","sourceId":"69246"},
 {"name":"صحن فتة بالزيت","price":200,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69247"},
 {"name":"صحن حمص ناعم","price":185,"category":"اطباق الفطور","unit":"طبق","image":"/assets/photos/albaraka/69248.jpg","sourceId":"69248"},
 {"name":"صحن فول بطحينة","price":160,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69249"},
 {"name":"صحن فول بالحمض","price":160,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69250"},
 {"name":"صحن حمص حب بطحينة","price":185,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69251"},
 {"name":"صحن فلافل","price":100,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69252","options":[{"name":"الكمية","values":["5","9"],"extra":[0,100]}]},
 {"name":"صحن فلافل عربي فرط","price":275,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69253"},
 {"name":"صحن متبل","price":225,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69254"},
 {"name":"صحن بابا غنوج","price":225,"category":"اطباق الفطور","unit":"طبق","image":"","sourceId":"69255"},
 {"name":"وجبة بطاطا مقلية","price":100,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69257","options":[{"name":"الحجم","values":["صغير","وسط","كبير"],"extra":[0,75,100]}]},
 {"name":"وجبة فلافل عربي","price":275,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69258"},
 {"name":"وجبة فلافل سوبر","price":300,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69259"},
 {"name":"وجبة عجة","price":200,"category":"وجبات","unit":"وجبة","image":"/assets/photos/albaraka/69261.jpg","sourceId":"69261","options":[{"name":"الحجم","values":["صغير","كبير"],"extra":[0,100]}]},
 {"name":"وجبة مكسيكانو","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69262"},
 {"name":"وجبة فاهيتا","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69263"},
 {"name":"وجبة زنجر","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69264"},
 {"name":"وجبة كريسبي","price":350,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69265"},
 {"name":"وجبة شيش","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69266"},
 {"name":"وجبة كريسبي عائلية","price":500,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69268"},
 {"name":"وجبة اسكالوب","price":375,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69270"},
 {"name":"وجبة ناغيت","price":375,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69271"},
 {"name":"شيش طاووق","price":450,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69272","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,350]}]},
 {"name":"وجبة توشكا","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69273"},
 {"name":"وجبة ماريا","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69274"},
 {"name":"وجبة بروستد","price":350,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69275"},
 {"name":"وجبة البركة (الخاصة للشخص)","price":200,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69276"},
 {"name":"وجبة سجق","price":325,"category":"وجبات","unit":"وجبة","image":"","sourceId":"69277"},
 {"name":"مسبحة بيروتية","price":225,"category":"وجبات","unit":"وجبة","image":"","sourceId":"73083"},
 {"name":"فروج مشوي","price":275,"category":"فروج مشوي","unit":"طبق","image":"","sourceId":"69278","description":"مع بطاطا و رز و ثوم و مخلل","options":[{"name":"الحجم","values":["نصف","حبة كاملة"],"extra":[0,225]}]},
 {"name":"فروج مشوي سادة","price":200,"category":"فروج مشوي","unit":"طبق","image":"/assets/photos/albaraka/69323.jpg","sourceId":"69323","options":[{"name":"الحجم","values":["نصف","حبة كاملة"],"extra":[0,100]}]},
 {"name":"وجبة منسف","price":500,"category":"فروج مشوي","unit":"طبق","image":"/assets/photos/albaraka/69324.jpg","sourceId":"69324","options":[{"name":"الحجم","values":["نصف","حبة كاملة"],"extra":[0,500]}]},
 {"name":"وجبة شاورما عربي دبل","price":350,"category":"شاورما","unit":"وجبة","image":"","sourceId":"69325"},
 {"name":"وجبة شاورما أصابع","price":400,"category":"شاورما","unit":"وجبة","image":"","sourceId":"69326"},
 {"name":"وجبة شاورما عربي عادي","price":250,"category":"شاورما","unit":"وجبة","image":"","sourceId":"69327"},
 {"name":"وجبة شاورما البركة","price":500,"category":"شاورما","unit":"وجبة","image":"","sourceId":"69328"},
 {"name":"شاورما شرحات","price":450,"category":"شاورما","unit":"وجبة","image":"","sourceId":"69329","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,449]}]},
 {"name":"كيلو شاورما","price":550,"category":"شاورما","unit":"وجبة","image":"","sourceId":"73084","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,550]}]},
 {"name":"شاورما اكسترا عادي","price":300,"category":"شاورما","unit":"وجبة","image":"","sourceId":"73953"},
 {"name":"شاورما بانيه","price":350,"category":"شاورما","unit":"وجبة","image":"","sourceId":"73954"},
 {"name":"كريسبي","price":155,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69330","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,5,20]}]},
 {"name":"زنجر","price":155,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69331","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,5,10]}]},
 {"name":"مكسيكي","price":155,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69332","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,5,10]}]},
 {"name":"فاهيتا","price":155,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69333","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,5,10]}]},
 {"name":"شيش طاووق","price":140,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69334","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,5,10]}]},
 {"name":"برغر","price":150,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69335","options":[{"name":"سندويش","values":["عادي","دبل"],"extra":[0,60]}]},
 {"name":"شاورما","price":145,"category":"صندويش الغربي","unit":"سندويش","image":"","sourceId":"69336","options":[{"name":"سندويش","values":["عادي","دبل"],"extra":[0,20]}]},
 {"name":"فلافل","price":115,"category":"صندويش","unit":"سندويش","image":"","sourceId":"69337","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,10,20]}]},
 {"name":"عجة","price":115,"category":"صندويش","unit":"سندويش","image":"","sourceId":"69338","options":[{"name":"سندويش","values":["عادي","دبل"],"extra":[0,10]}]},
 {"name":"بطاطا","price":115,"category":"صندويش","unit":"سندويش","image":"","sourceId":"69339","options":[{"name":"سندويش","values":["عادي","دبل","صمون"],"extra":[0,10,20]}]},
 {"name":"لحم بعجين","price":125,"category":"صندويش","unit":"سندويش","image":"","sourceId":"69340","options":[{"name":"سندويش","values":["عادي","دبل"],"extra":[0,40]}]},
 {"name":"كبة مقلية","price":150,"category":"صندويش","unit":"سندويش","image":"","sourceId":"69341","options":[{"name":"سندويش","values":["عادي","دبل"],"extra":[0,75]}]},
 {"name":"قلوبات","price":115,"category":"صندويش","unit":"سندويش","image":"","sourceId":"73085","options":[{"name":"سندويش","values":["عادي","دبل"],"extra":[0,10]}]},
 {"name":"فول بطحينة","price":125,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69342","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,125]}]},
 {"name":"فول بحمض","price":125,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69343","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,125]}]},
 {"name":"فول سادة","price":100,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69344","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,100]}]},
 {"name":"حمص حب بطحينه","price":100,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69345","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,100]}]},
 {"name":"حمص ناعم","price":200,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69346","description":"900 غرام"},
 {"name":"فتة","price":125,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69347","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,125]}]},
 {"name":"حمص حب","price":125,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69348","options":[{"name":"الوزن","values":["نصف كيلو","كيلو"],"extra":[0,125]}]},
 {"name":"قرص الفلافل","price":9,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69349"},
 {"name":"كريم ثوم","price":95,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69350"},
 {"name":"سلطة روسية","price":95,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69351"},
 {"name":"مخلل","price":200,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69352"},
 {"name":"خبز سياحي","price":25,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69353"},
 {"name":"سرفيس اكسترا","price":100,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69354"},
 {"name":"قرص لحم بعجين اسود","price":35,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69355"},
 {"name":"قرص لحم بعجن احمر","price":35,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69356"},
 {"name":"لحم بعجين اسود","price":350,"category":"المتفرقات","unit":"طبق","image":"/assets/photos/albaraka/69357.jpg","sourceId":"69357"},
 {"name":"لحم بعجين احمر","price":350,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69358"},
 {"name":"تبلة فلافل جاهزة","price":150,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69359"},
 {"name":"كبة مقلية","price":65,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69360"},
 {"name":"اجرة خبز اللحم بعجين","price":7,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69361"},
 {"name":"اجرة خبز الفطيرة","price":12,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69362"},
 {"name":"800 غرام كريم ثوم","price":180,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69794"},
 {"name":"450 غرام كريم ثوم","price":120,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69795"},
 {"name":"200 غرام كريم ثوم","price":65,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69796"},
 {"name":"900 غرام حمص ناعم","price":180,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69797"},
 {"name":"450 غرام حمص ناعم","price":120,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69798"},
 {"name":"200 غرام حمص ناعم","price":65,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69799"},
 {"name":"مخلل مشكل","price":15,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69800","options":[{"name":"الوزن","values":["100 غرام","نصف كيلو","كيلو"],"extra":[0,60,135]}]},
 {"name":"800 غرام سلطة روسية","price":180,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69801"},
 {"name":"450 غرام سلطة روسية","price":120,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69802"},
 {"name":"200 غرام سلطة روسية","price":65,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69803"},
 {"name":"800 غرام طرطور فلافل","price":160,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69804"},
 {"name":"4400 غرام طرطور فلافل","price":80,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69805"},
 {"name":"100 غرام طرطور فلافل","price":20,"category":"المتفرقات","unit":"طبق","image":"","sourceId":"69806"},
 {"name":"بيبسي تنك","price":50,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69363"},
 {"name":"بيبسي لتر","price":70,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69364"},
 {"name":"بيبسي عائلي","price":85,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69365"},
 {"name":"سبرايت تنك","price":55,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69366"},
 {"name":"سبرايت لتر","price":45,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69367"},
 {"name":"سبرايت عائلي","price":65,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69368"},
 {"name":"فانتا تنك","price":55,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69369"},
 {"name":"فانتا 1 لتر","price":45,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69370"},
 {"name":"فانتا عائلي","price":65,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69371"},
 {"name":"عيران","price":15,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69372","options":[{"name":"الحجم","values":["صغير","كبير"],"extra":[0,10]}]},
 {"name":"عصير سلس","price":25,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69373"},
 {"name":"مياه معدنية","price":10,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69374","options":[{"name":"الحجم","values":["صغير","كبير"],"extra":[0,5]}]},
 {"name":"شاي","price":20,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"69375"},
 {"name":"كولا تركي تنك","price":35,"category":"المشروبات","unit":"مشروب","image":"","sourceId":"73086"}
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const albarakaProductCatalog = [];

const albarakaProducts = (albarakaProductCatalog.length ? albarakaProductCatalog : albarakaFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1580001 + index,
  storeId: albarakaStore.id
}));

const albarakaDeliverySettings = {
  [albarakaStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { albarakaStore, albarakaProducts, albarakaDeliverySettings };
}
