// Generated from the official Alfursan (مطعم الفرسان) Yemeksepeti menu — Şişli/Elmadağ, İstanbul.
// Source: Delivery Hero food-bff (vendor s9tp). 143 items with the restaurant's own photos;
// prices in Turkish Lira. Item/category names are as published on Yemeksepeti (Turkish).
const alfursanStore = {
 "id": 48,
 "name": "مطعم الفرسان",
 "category": "مطاعم",
 "image": "/assets/photos/alfursan/cover.jpg",
 "coverImage": "/assets/photos/alfursan/cover.jpg",
 "logoImage": "/assets/photos/alfursan/logo2.jpg",
 "logo": "ا",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "35 - 60 دقيقة",
 "distance": 5,
 "location": {
  "lat": 41.0420418,
  "lng": 28.9862006
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.0420418,28.9862006",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم الفرسان: مطعم سوري وعربي في شيشلي (إلمَداغ) يقدّم المندي والكبسة والمدفون والمشاوي والكباب والدجاج والفطور العربي والسندويشات والبيتزا والأطباق الشرقية والسلطات والشوربات والحلويات. الأصناف والأسعار كما في القائمة الرسمية.",
 "address": "İnönü Mah. Elmadağ Cad. No:2, 34373 Şişli, İstanbul",
 "phone": "+905364478744",
 "whatsapp": "+905364478744",
 "email": "",
 "website": "https://www.yemeksepeti.com/restaurant/s9tp/alfursan-resturant",
 "sourceUrl": "https://www.yemeksepeti.com/restaurant/s9tp/alfursan-resturant",
 "hours": "الإثنين - السبت 11:30 ص - 11:30 م (الأحد مغلق)",
 "areas": [
  "شيشلي",
  "إلمَداغ",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const alfursanProductCatalog = [
 {
  "sourceId": "f001",
  "name": "حمص بالشاورما",
  "image": "/assets/photos/alfursan/items/f001.jpg",
  "price": 399,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "حمص بالشاورما من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f002",
  "name": "حمص باللحمة",
  "image": "/assets/photos/alfursan/items/f002.jpg",
  "price": 499,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "حمص باللحمة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f003",
  "name": "فول بزيت الزيتون",
  "image": "/assets/photos/alfursan/items/f003.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "فول بزيت الزيتون من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f004",
  "name": "فول باللبن",
  "image": "/assets/photos/alfursan/items/f004.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "فول باللبن من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f005",
  "name": "بليلة بزيت الزيتون",
  "image": "/assets/photos/alfursan/items/f005.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "بليلة بزيت الزيتون من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f006",
  "name": "بليلة باللبن",
  "image": "/assets/photos/alfursan/items/f006.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "بليلة باللبن من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f007",
  "name": "حمص",
  "image": "/assets/photos/alfursan/items/f007.jpg",
  "price": 299,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "حمص من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f008",
  "name": "فتة حمص",
  "image": "/assets/photos/alfursan/items/f008.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "فتة حمص من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f009",
  "name": "متبل",
  "image": "/assets/photos/alfursan/items/f009.jpg",
  "price": 299,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "متبل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f010",
  "name": "بابا غنوج",
  "image": "/assets/photos/alfursan/items/f010.jpg",
  "price": 299,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "بابا غنوج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f011",
  "name": "فلافل (7 حبات)",
  "image": "/assets/photos/alfursan/items/f011.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "فلافل (7 حبات) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f012",
  "name": "فلافل عربي (6 حبات)",
  "image": "/assets/photos/alfursan/items/f012.jpg",
  "price": 329,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "فلافل عربي (6 حبات) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f013",
  "name": "لفّة فلافل",
  "image": "/assets/photos/alfursan/items/f013.jpg",
  "price": 219,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "لفّة فلافل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f014",
  "name": "لفّة فلافل دبل",
  "image": "/assets/photos/alfursan/items/f014.jpg",
  "price": 249,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "لفّة فلافل دبل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f015",
  "name": "فلافل عربي دبل",
  "image": "/assets/photos/alfursan/items/f015.jpg",
  "price": 599,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "فلافل عربي دبل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f016",
  "name": "حمص (حجم صغير)",
  "image": "/assets/photos/alfursan/items/f016.jpg",
  "price": 69,
  "unit": "",
  "category": "مقبلات عربية",
  "available": true,
  "featured": false,
  "description": "حمص (حجم صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f017",
  "name": "سندويش كرسبي",
  "image": "/assets/photos/alfursan/items/f017.jpg",
  "price": 349,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش كرسبي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f018",
  "name": "سندويش مكسيكي",
  "image": "/assets/photos/alfursan/items/f018.jpg",
  "price": 349,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش مكسيكي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f019",
  "name": "سندويش فاهيتا",
  "image": "/assets/photos/alfursan/items/f019.jpg",
  "price": 369,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش فاهيتا من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f020",
  "name": "سندويش فرانسيسكو",
  "image": "/assets/photos/alfursan/items/f020.jpg",
  "price": 369,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش فرانسيسكو من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f021",
  "name": "سندويش شيش طاووق",
  "image": "/assets/photos/alfursan/items/f021.jpg",
  "price": 349,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش شيش طاووق من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f022",
  "name": "سندويش زنجر",
  "image": "/assets/photos/alfursan/items/f022.jpg",
  "price": 369,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش زنجر من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f023",
  "name": "سندويش اسكالوب",
  "image": "/assets/photos/alfursan/items/f023.jpg",
  "price": 349,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش اسكالوب من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f024",
  "name": "سندويش باتسو",
  "image": "/assets/photos/alfursan/items/f024.jpg",
  "price": 219,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش باتسو من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f025",
  "name": "سندويش سوبريم",
  "image": "/assets/photos/alfursan/items/f025.jpg",
  "price": 369,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش سوبريم من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f026",
  "name": "سندويش كرانشي",
  "image": "/assets/photos/alfursan/items/f026.jpg",
  "price": 369,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش كرانشي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f027",
  "name": "سندويش اسكالوب بالقشقوان",
  "image": "/assets/photos/alfursan/items/f027.jpg",
  "price": 369,
  "unit": "",
  "category": "سندويشات",
  "available": true,
  "featured": false,
  "description": "سندويش اسكالوب بالقشقوان من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f028",
  "name": "شيش غنم (200 غ)",
  "image": "/assets/photos/alfursan/items/f028.jpg",
  "price": 899,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "شيش غنم (200 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f029",
  "name": "كباب غنم (200 غ)",
  "image": "/assets/photos/alfursan/items/f029.jpg",
  "price": 899,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "كباب غنم (200 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f030",
  "name": "شيش طاووق (200 غ)",
  "image": "/assets/photos/alfursan/items/f030.jpg",
  "price": 499,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق (200 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f031",
  "name": "كباب دجاج (240 غ)",
  "image": "/assets/photos/alfursan/items/f031.jpg",
  "price": 469,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "كباب دجاج (240 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f032",
  "name": "دجاج مشوي مع البطاطا (نصف)",
  "image": "/assets/photos/alfursan/items/f032.jpg",
  "price": 569,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "دجاج مشوي مع البطاطا (نصف) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f033",
  "name": "دجاج مشوي مع الرز (نصف)",
  "image": "/assets/photos/alfursan/items/f033.jpg",
  "price": 599,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "دجاج مشوي مع الرز (نصف) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f034",
  "name": "مشاوي مشكّلة",
  "image": "/assets/photos/alfursan/items/f034.jpg",
  "price": 1699,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "مشاوي مشكّلة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f035",
  "name": "أجنحة دجاج مشوية (250 غ)",
  "image": "/assets/photos/alfursan/items/f035.jpg",
  "price": 499,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "أجنحة دجاج مشوية (250 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f036",
  "name": "دجاج مشوي (نصف)",
  "image": "/assets/photos/alfursan/items/f036.jpg",
  "price": 649,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "دجاج مشوي (نصف) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f037",
  "name": "شيش طاووق على الرز",
  "image": "/assets/photos/alfursan/items/f037.jpg",
  "price": 539,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق على الرز من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f038",
  "name": "كباب دجاج (1 كغ)",
  "image": "/assets/photos/alfursan/items/f038.jpg",
  "price": 1099,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "كباب دجاج (1 كغ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f039",
  "name": "شيش طاووق (500 غ)",
  "image": "/assets/photos/alfursan/items/f039.jpg",
  "price": 629,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق (500 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f040",
  "name": "شيش طاووق (1 كغ)",
  "image": "/assets/photos/alfursan/items/f040.jpg",
  "price": 1199,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "شيش طاووق (1 كغ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f041",
  "name": "كباب دجاج (500 غ)",
  "image": "/assets/photos/alfursan/items/f041.jpg",
  "price": 599,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "كباب دجاج (500 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f042",
  "name": "شيش غنم (1 كغ)",
  "image": "/assets/photos/alfursan/items/f042.jpg",
  "price": 3999,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "شيش غنم (1 كغ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f044",
  "name": "كباب غنم (1 كغ)",
  "image": "/assets/photos/alfursan/items/f044.jpg",
  "price": 3899,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "كباب غنم (1 كغ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f045",
  "name": "كباب غنم (500 غ)",
  "image": "/assets/photos/alfursan/items/f045.jpg",
  "price": 1999,
  "unit": "",
  "category": "الكباب والمشاوي",
  "available": true,
  "featured": false,
  "description": "كباب غنم (500 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f046",
  "name": "لفّة شاورما دجاج",
  "image": "/assets/photos/alfursan/items/f046.jpg",
  "price": 229,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "لفّة شاورما دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f048",
  "name": "شاورما دجاج عربي",
  "image": "/assets/photos/alfursan/items/f048.jpg",
  "price": 349,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج عربي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f049",
  "name": "شاورما دجاج عربي دبل",
  "image": "/assets/photos/alfursan/items/f049.jpg",
  "price": 629,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج عربي دبل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f050",
  "name": "شاورما دجاج عربي بالقشقوان",
  "image": "/assets/photos/alfursan/items/f050.jpg",
  "price": 499,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج عربي بالقشقوان من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f051",
  "name": "شاورما دجاج على الرز",
  "image": "/assets/photos/alfursan/items/f051.jpg",
  "price": 599,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج على الرز من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f052",
  "name": "شاورما دجاج بالصمون",
  "image": "/assets/photos/alfursan/items/f052.jpg",
  "price": 299,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج بالصمون من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f053",
  "name": "شاورما دجاج (220 غ)",
  "image": "/assets/photos/alfursan/items/f053.jpg",
  "price": 599,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج (220 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f054",
  "name": "شاورما بانيه",
  "image": "/assets/photos/alfursan/items/f054.jpg",
  "price": 599,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما بانيه من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f055",
  "name": "فتة شاورما",
  "image": "/assets/photos/alfursan/items/f055.jpg",
  "price": 599,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "فتة شاورما من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f056",
  "name": "شاورما دجاج حار",
  "image": "/assets/photos/alfursan/items/f056.jpg",
  "price": 599,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج حار من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f057",
  "name": "شاورما ميني (50 غ)",
  "image": "/assets/photos/alfursan/items/f057.jpg",
  "price": 139,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما ميني (50 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f058",
  "name": "شاورما عربي بالصمون",
  "image": "/assets/photos/alfursan/items/f058.jpg",
  "price": 379,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما عربي بالصمون من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f059",
  "name": "شاورما دجاج (لـ4 أشخاص)",
  "image": "/assets/photos/alfursan/items/f059.jpg",
  "price": 1449,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج (لـ4 أشخاص) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f060",
  "name": "لفّة شاورما ميني (3 حبات)",
  "image": "/assets/photos/alfursan/items/f060.jpg",
  "price": 499,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "لفّة شاورما ميني (3 حبات) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f061",
  "name": "شاورما دجاج (500 غ)",
  "image": "/assets/photos/alfursan/items/f061.jpg",
  "price": 799,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج (500 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f062",
  "name": "شاورما دجاج (1 كغ)",
  "image": "/assets/photos/alfursan/items/f062.jpg",
  "price": 1549,
  "unit": "",
  "category": "شاورما الدجاج",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج (1 كغ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f063",
  "name": "بيتزا مارغريتا (وسط)",
  "image": "/assets/photos/alfursan/items/f063.jpg",
  "price": 499,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا مارغريتا (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f064",
  "name": "بيتزا أربعة فصول (وسط)",
  "image": "/assets/photos/alfursan/items/f064.jpg",
  "price": 499,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا أربعة فصول (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f065",
  "name": "بيتزا هاواي (وسط)",
  "image": "/assets/photos/alfursan/items/f065.jpg",
  "price": 499,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا هاواي (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f066",
  "name": "بيتزا بالسجق (وسط)",
  "image": "/assets/photos/alfursan/items/f066.jpg",
  "price": 549,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا بالسجق (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f067",
  "name": "بيتزا مكسيكية (وسط)",
  "image": "/assets/photos/alfursan/items/f067.jpg",
  "price": 549,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا مكسيكية (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f068",
  "name": "بيتزا بالتونة (وسط)",
  "image": "/assets/photos/alfursan/items/f068.jpg",
  "price": 549,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا بالتونة (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f069",
  "name": "بيتزا باللحمة (وسط)",
  "image": "/assets/photos/alfursan/items/f069.jpg",
  "price": 699,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا باللحمة (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f070",
  "name": "بيتزا بالشاورما (وسط)",
  "image": "/assets/photos/alfursan/items/f070.jpg",
  "price": 549,
  "unit": "",
  "category": "بيتزا (وسط)",
  "available": true,
  "featured": false,
  "description": "بيتزا بالشاورما (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f071",
  "name": "برغر لحم",
  "image": "/assets/photos/alfursan/items/f071.jpg",
  "price": 449,
  "unit": "",
  "category": "برغر",
  "available": true,
  "featured": false,
  "description": "برغر لحم من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f072",
  "name": "برغر دجاج",
  "image": "/assets/photos/alfursan/items/f072.jpg",
  "price": 349,
  "unit": "",
  "category": "برغر",
  "available": true,
  "featured": false,
  "description": "برغر دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f073",
  "name": "سمك دنيس مشوي",
  "image": "/assets/photos/alfursan/items/f073.jpg",
  "price": 749,
  "unit": "",
  "category": "الأسماك",
  "available": true,
  "featured": false,
  "description": "سمك دنيس مشوي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f074",
  "name": "فيليه سمك",
  "image": "/assets/photos/alfursan/items/f074.jpg",
  "price": 599,
  "unit": "",
  "category": "الأسماك",
  "available": true,
  "featured": false,
  "description": "فيليه سمك من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f075",
  "name": "سندويش فيليه سمك",
  "image": "/assets/photos/alfursan/items/f075.jpg",
  "price": 399,
  "unit": "",
  "category": "الأسماك",
  "available": true,
  "featured": false,
  "description": "سندويش فيليه سمك من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f076",
  "name": "دجاج مكسيكي",
  "image": "/assets/photos/alfursan/items/f076.jpg",
  "price": 579,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج مكسيكي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f077",
  "name": "دجاج زنجر",
  "image": "/assets/photos/alfursan/items/f077.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج زنجر من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f078",
  "name": "فاهيتا دجاج",
  "image": "/assets/photos/alfursan/items/f078.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "فاهيتا دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f079",
  "name": "دجاج فرانسيسكو",
  "image": "/assets/photos/alfursan/items/f079.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج فرانسيسكو من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f080",
  "name": "دجاج مقرمش (نصف)",
  "image": "/assets/photos/alfursan/items/f080.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج مقرمش (نصف) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f081",
  "name": "اسكالوب دجاج",
  "image": "/assets/photos/alfursan/items/f081.jpg",
  "price": 579,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "اسكالوب دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f082",
  "name": "دجاج سوبريم",
  "image": "/assets/photos/alfursan/items/f082.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج سوبريم من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f083",
  "name": "كوردون بلو",
  "image": "/assets/photos/alfursan/items/f083.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "كوردون بلو من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f084",
  "name": "كرسبي",
  "image": "/assets/photos/alfursan/items/f084.jpg",
  "price": 579,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "كرسبي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f085",
  "name": "أفخاذ دجاج مقرمشة",
  "image": "/assets/photos/alfursan/items/f085.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "أفخاذ دجاج مقرمشة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f086",
  "name": "دجاج بصلصة الكاري",
  "image": "/assets/photos/alfursan/items/f086.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج بصلصة الكاري من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f087",
  "name": "دجاج كرانشي",
  "image": "/assets/photos/alfursan/items/f087.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "دجاج كرانشي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f088",
  "name": "فيليه دجاج بالثوم",
  "image": "/assets/photos/alfursan/items/f088.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "فيليه دجاج بالثوم من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f089",
  "name": "اسكالوب بالقشقوان",
  "image": "/assets/photos/alfursan/items/f089.jpg",
  "price": 599,
  "unit": "",
  "category": "الأطباق الرئيسية",
  "available": true,
  "featured": false,
  "description": "اسكالوب بالقشقوان من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f090",
  "name": "ملوخية باللحمة",
  "image": "/assets/photos/alfursan/items/f090.jpg",
  "price": 1049,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "ملوخية باللحمة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f091",
  "name": "لحمة باللبن",
  "image": "/assets/photos/alfursan/items/f091.jpg",
  "price": 1049,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "لحمة باللبن من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f092",
  "name": "كبسة دجاج",
  "image": "/assets/photos/alfursan/items/f092.jpg",
  "price": 579,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "كبسة دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f093",
  "name": "كبسة لحمة",
  "image": "/assets/photos/alfursan/items/f093.jpg",
  "price": 1299,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "كبسة لحمة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f094",
  "name": "مندي دجاج",
  "image": "/assets/photos/alfursan/items/f094.jpg",
  "price": 579,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "مندي دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f095",
  "name": "مندي لحمة",
  "image": "/assets/photos/alfursan/items/f095.jpg",
  "price": 1299,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "مندي لحمة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f096",
  "name": "ملوخية دجاج",
  "image": "/assets/photos/alfursan/items/f096.jpg",
  "price": 599,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "ملوخية دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f097",
  "name": "رز أبيض",
  "image": "/assets/photos/alfursan/items/f097.jpg",
  "price": 299,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "رز أبيض من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f098",
  "name": "شيش برك شامي",
  "image": "/assets/photos/alfursan/items/f098.jpg",
  "price": 1049,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "شيش برك شامي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f099",
  "name": "كبة باللبن",
  "image": "/assets/photos/alfursan/items/f099.jpg",
  "price": 1049,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "كبة باللبن من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f100",
  "name": "رز أصفر (حجم صغير)",
  "image": "/assets/photos/alfursan/items/f100.jpg",
  "price": 149,
  "unit": "",
  "category": "المطبخ الشرقي",
  "available": true,
  "featured": false,
  "description": "رز أصفر (حجم صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f101",
  "name": "لفّة بطاطا",
  "image": "/assets/photos/alfursan/items/f101.jpg",
  "price": 199,
  "unit": "",
  "category": "اللفائف",
  "available": true,
  "featured": false,
  "description": "لفّة بطاطا من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f102",
  "name": "لفّة كباب دجاج دبل",
  "image": "/assets/photos/alfursan/items/f102.jpg",
  "price": 399,
  "unit": "",
  "category": "اللفائف",
  "available": true,
  "featured": false,
  "description": "لفّة كباب دجاج دبل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f103",
  "name": "لفّة كباب غنم",
  "image": "/assets/photos/alfursan/items/f103.jpg",
  "price": 459,
  "unit": "",
  "category": "اللفائف",
  "available": true,
  "featured": false,
  "description": "لفّة كباب غنم من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f104",
  "name": "لفّة شيش غنم",
  "image": "/assets/photos/alfursan/items/f104.jpg",
  "price": 459,
  "unit": "",
  "category": "اللفائف",
  "available": true,
  "featured": false,
  "description": "لفّة شيش غنم من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f105",
  "name": "سلطة كول سلو",
  "image": "/assets/photos/alfursan/items/f105.jpg",
  "price": 299,
  "unit": "",
  "category": "السلطات",
  "available": true,
  "featured": false,
  "description": "سلطة كول سلو من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f106",
  "name": "سلطة جرجير",
  "image": "/assets/photos/alfursan/items/f106.jpg",
  "price": 299,
  "unit": "",
  "category": "السلطات",
  "available": true,
  "featured": false,
  "description": "سلطة جرجير من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f107",
  "name": "سلطة موسمية",
  "image": "/assets/photos/alfursan/items/f107.jpg",
  "price": 299,
  "unit": "",
  "category": "السلطات",
  "available": true,
  "featured": false,
  "description": "سلطة موسمية من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f108",
  "name": "تبولة",
  "image": "/assets/photos/alfursan/items/f108.jpg",
  "price": 299,
  "unit": "",
  "category": "السلطات",
  "available": true,
  "featured": false,
  "description": "تبولة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f109",
  "name": "فتوش",
  "image": "/assets/photos/alfursan/items/f109.jpg",
  "price": 299,
  "unit": "",
  "category": "السلطات",
  "available": true,
  "featured": false,
  "description": "فتوش من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f110",
  "name": "شوربة عدس",
  "image": "/assets/photos/alfursan/items/f110.jpg",
  "price": 119,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة عدس من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f111",
  "name": "شوربة ذرة",
  "image": "/assets/photos/alfursan/items/f111.jpg",
  "price": 149,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة ذرة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f112",
  "name": "شوربة فطر",
  "image": "/assets/photos/alfursan/items/f112.jpg",
  "price": 149,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة فطر من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f113",
  "name": "شوربة دجاج",
  "image": "/assets/photos/alfursan/items/f113.jpg",
  "price": 209,
  "unit": "",
  "category": "الشوربات",
  "available": true,
  "featured": false,
  "description": "شوربة دجاج من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f114",
  "name": "كبة مقلية (حبة)",
  "image": "/assets/photos/alfursan/items/f114.jpg",
  "price": 159,
  "unit": "",
  "category": "أطباق أخرى",
  "available": true,
  "featured": false,
  "description": "كبة مقلية (حبة) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f115",
  "name": "كبة مشوية (حبة)",
  "image": "/assets/photos/alfursan/items/f115.jpg",
  "price": 159,
  "unit": "",
  "category": "أطباق أخرى",
  "available": true,
  "featured": false,
  "description": "كبة مشوية (حبة) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f116",
  "name": "بوريك بالقشقوان (حبة)",
  "image": "/assets/photos/alfursan/items/f116.jpg",
  "price": 69,
  "unit": "",
  "category": "الإضافات الجانبية",
  "available": true,
  "featured": false,
  "description": "بوريك بالقشقوان (حبة) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f117",
  "name": "خبز لافاش (6 حبات)",
  "image": "/assets/photos/alfursan/items/f117.jpg",
  "price": 69,
  "unit": "",
  "category": "الإضافات الجانبية",
  "available": true,
  "featured": false,
  "description": "خبز لافاش (6 حبات) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f118",
  "name": "بطاطا مقلية (وسط)",
  "image": "/assets/photos/alfursan/items/f118.jpg",
  "price": 269,
  "unit": "",
  "category": "الإضافات الجانبية",
  "available": true,
  "featured": false,
  "description": "بطاطا مقلية (وسط) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f119",
  "name": "بطاطا مقلية (صغير)",
  "image": "/assets/photos/alfursan/items/f119.jpg",
  "price": 129,
  "unit": "",
  "category": "الإضافات الجانبية",
  "available": true,
  "featured": false,
  "description": "بطاطا مقلية (صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f120",
  "name": "مخلل خيار",
  "image": "/assets/photos/alfursan/items/f120.jpg",
  "price": 49,
  "unit": "",
  "category": "الإضافات الجانبية",
  "available": true,
  "featured": false,
  "description": "مخلل خيار من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f121",
  "name": "مخلل فلفل",
  "image": "/assets/photos/alfursan/items/f121.jpg",
  "price": 49,
  "unit": "",
  "category": "الإضافات الجانبية",
  "available": true,
  "featured": false,
  "description": "مخلل فلفل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f122",
  "name": "كوكا كولا (33 سل)",
  "image": "/assets/photos/alfursan/items/f122.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "كوكا كولا (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f123",
  "name": "فانتا (33 سل)",
  "image": "/assets/photos/alfursan/items/f123.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "فانتا (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f124",
  "name": "سبرايت (33 سل)",
  "image": "/assets/photos/alfursan/items/f124.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "سبرايت (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f125",
  "name": "عصير برتقال سيلس (25 سل)",
  "image": "/assets/photos/alfursan/items/f125.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "عصير برتقال سيلس (25 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f126",
  "name": "بيبسي (33 سل)",
  "image": "/assets/photos/alfursan/items/f126.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "بيبسي (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f127",
  "name": "بيبسي ماكس (33 سل)",
  "image": "/assets/photos/alfursan/items/f127.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "بيبسي ماكس (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f128",
  "name": "عيران (20 سل)",
  "image": "/assets/photos/alfursan/items/f128.jpg",
  "price": 49,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "عيران (20 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f129",
  "name": "ماء (50 سل)",
  "image": "/assets/photos/alfursan/items/f129.jpg",
  "price": 19,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "ماء (50 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f130",
  "name": "فانتا (1 لتر)",
  "image": "/assets/photos/alfursan/items/f130.jpg",
  "price": 139,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "فانتا (1 لتر) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f131",
  "name": "سبرايت (1 لتر)",
  "image": "/assets/photos/alfursan/items/f131.jpg",
  "price": 139,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "سبرايت (1 لتر) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f132",
  "name": "بيبسي (1 لتر)",
  "image": "/assets/photos/alfursan/items/f132.jpg",
  "price": 139,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "بيبسي (1 لتر) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f133",
  "name": "بيبسي (2 لتر)",
  "image": "/assets/photos/alfursan/items/f133.jpg",
  "price": 179,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "بيبسي (2 لتر) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f134",
  "name": "كولا توركا (33 سل)",
  "image": "/assets/photos/alfursan/items/f134.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "كولا توركا (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f135",
  "name": "تشاملجة برتقال (33 سل)",
  "image": "/assets/photos/alfursan/items/f135.jpg",
  "price": 99,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "تشاملجة برتقال (33 سل) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f136",
  "name": "صلصة طحينة",
  "image": "/assets/photos/alfursan/items/f136.jpg",
  "price": 59,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "صلصة طحينة من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f137",
  "name": "صلصة المشاوي",
  "image": "/assets/photos/alfursan/items/f137.jpg",
  "price": 49,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "صلصة المشاوي من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f138",
  "name": "صلصة ثوم (120 غ)",
  "image": "/assets/photos/alfursan/items/f138.jpg",
  "price": 59,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "صلصة ثوم (120 غ) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f139",
  "name": "كول سلو (صغير)",
  "image": "/assets/photos/alfursan/items/f139.jpg",
  "price": 59,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "كول سلو (صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f140",
  "name": "صلصة كوكتيل",
  "image": "/assets/photos/alfursan/items/f140.jpg",
  "price": 59,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "صلصة كوكتيل من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f141",
  "name": "صلصة الرز (حجم صغير)",
  "image": "/assets/photos/alfursan/items/f141.jpg",
  "price": 49,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "صلصة الرز (حجم صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f142",
  "name": "صلصة حارة (صغير)",
  "image": "/assets/photos/alfursan/items/f142.jpg",
  "price": 49,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "صلصة حارة (صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f143",
  "name": "دبس رمان (صغير)",
  "image": "/assets/photos/alfursan/items/f143.jpg",
  "price": 49,
  "unit": "",
  "category": "الصلصات",
  "available": true,
  "featured": false,
  "description": "دبس رمان (صغير) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 }
];

const alfursanProducts = alfursanProductCatalog.map((product, index) => ({
  ...product,
  id: 1320001 + index,
  storeId: alfursanStore.id
}));

const alfursanDeliverySettings = {
  [alfursanStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 30, maxRoundTripKm: 120 }
};
