// Generated from the official Alfursan (مطعم الفرسان) Yemeksepeti menu — Şişli/Elmadağ, İstanbul.
// Source: Delivery Hero food-bff (vendor s9tp). 143 items with the restaurant's own photos;
// prices in Turkish Lira. Item/category names are as published on Yemeksepeti (Turkish).
const alfursanStore = {
 "id": 48,
 "name": "مطعم الفرسان",
 "category": "مطاعم",
 "image": "/assets/photos/alfursan/cover.jpg",
 "coverImage": "/assets/photos/alfursan/cover.jpg",
 "logoImage": "/assets/photos/alfursan/logo.jpg",
 "logo": "ا",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "35 - 60 دقيقة",
 "distance": 5,
 "location": {
  "lat": 41.0420418,
  "lng": 28.9862006
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.0420418,28.9862006",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم الفرسان: مطعم سوري وعربي في شيشلي (إلمَداغ) يقدّم المندي والكبسة والمدفون والمشاوي والكباب والدجاج والفطور العربي والسندويشات والبيتزا والأطباق الشرقية والسلطات والشوربات والحلويات. الأصناف والأسعار كما في القائمة الرسمية.",
 "address": "İnönü Mah. Elmadağ Cad. No:2, 34373 Şişli, İstanbul",
 "phone": "+905364478744",
 "whatsapp": "+905364478744",
 "email": "",
 "website": "https://www.yemeksepeti.com/restaurant/s9tp/alfursan-resturant",
 "sourceUrl": "https://www.yemeksepeti.com/restaurant/s9tp/alfursan-resturant",
 "hours": "الإثنين - السبت 11:30 ص - 11:30 م (الأحد مغلق)",
 "areas": [
  "شيشلي",
  "إلمَداغ",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const alfursanProductCatalog = [
 {
  "sourceId": "f001",
  "name": "Dönerli humus",
  "image": "/assets/photos/alfursan/items/f001.jpg",
  "price": 399,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Dönerli humus من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f002",
  "name": "Etli humus",
  "image": "/assets/photos/alfursan/items/f002.jpg",
  "price": 499,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Etli humus من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f003",
  "name": "Zeytinyağlı Bakla",
  "image": "/assets/photos/alfursan/items/f003.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Zeytinyağlı Bakla من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f004",
  "name": "Yoğurtlu Bakla",
  "image": "/assets/photos/alfursan/items/f004.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Yoğurtlu Bakla من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f005",
  "name": "Zeytinyağlı Nohut",
  "image": "/assets/photos/alfursan/items/f005.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Zeytinyağlı Nohut من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f006",
  "name": "Yoğurtlu Nohut",
  "image": "/assets/photos/alfursan/items/f006.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Yoğurtlu Nohut من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f007",
  "name": "Humus",
  "image": "/assets/photos/alfursan/items/f007.jpg",
  "price": 299,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Humus من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f008",
  "name": "Nohutlu Fatte",
  "image": "/assets/photos/alfursan/items/f008.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Nohutlu Fatte من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f009",
  "name": "Mütebbel",
  "image": "/assets/photos/alfursan/items/f009.jpg",
  "price": 299,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Mütebbel من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f010",
  "name": "Babagannuş",
  "image": "/assets/photos/alfursan/items/f010.jpg",
  "price": 299,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Babagannuş من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f011",
  "name": "Falafel (7 Adet)",
  "image": "/assets/photos/alfursan/items/f011.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Falafel (7 Adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f012",
  "name": "Arap Falafel (6 Adet)",
  "image": "/assets/photos/alfursan/items/f012.jpg",
  "price": 329,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Arap Falafel (6 Adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f013",
  "name": "Falafel Dürüm",
  "image": "/assets/photos/alfursan/items/f013.jpg",
  "price": 219,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Falafel Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f014",
  "name": "Double Falafel Dürüm",
  "image": "/assets/photos/alfursan/items/f014.jpg",
  "price": 249,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Double Falafel Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f015",
  "name": "Double Arap Falafel",
  "image": "/assets/photos/alfursan/items/f015.jpg",
  "price": 599,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Double Arap Falafel من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f016",
  "name": "Humus (Küçük Boy)",
  "image": "/assets/photos/alfursan/items/f016.jpg",
  "price": 69,
  "unit": "",
  "category": "Arap Kahvaltılıkları",
  "available": true,
  "featured": false,
  "description": "Humus (Küçük Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f017",
  "name": "Crispy Sandviç",
  "image": "/assets/photos/alfursan/items/f017.jpg",
  "price": 349,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Crispy Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f018",
  "name": "Mexican Sandviç",
  "image": "/assets/photos/alfursan/items/f018.jpg",
  "price": 349,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Mexican Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f019",
  "name": "Fajita Sandviç",
  "image": "/assets/photos/alfursan/items/f019.jpg",
  "price": 369,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Fajita Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f020",
  "name": "Francesco Sandviç",
  "image": "/assets/photos/alfursan/items/f020.jpg",
  "price": 369,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Francesco Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f021",
  "name": "Tavuk Şiş Sandviç",
  "image": "/assets/photos/alfursan/items/f021.jpg",
  "price": 349,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Tavuk Şiş Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f022",
  "name": "Zinger Sandviç",
  "image": "/assets/photos/alfursan/items/f022.jpg",
  "price": 369,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Zinger Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f023",
  "name": "Eskalope Sandviç",
  "image": "/assets/photos/alfursan/items/f023.jpg",
  "price": 349,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Eskalope Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f024",
  "name": "Patso Sandviç",
  "image": "/assets/photos/alfursan/items/f024.jpg",
  "price": 219,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Patso Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f025",
  "name": "Süpreme Sandviç",
  "image": "/assets/photos/alfursan/items/f025.jpg",
  "price": 369,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Süpreme Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f026",
  "name": "Kranşy Sandviç",
  "image": "/assets/photos/alfursan/items/f026.jpg",
  "price": 369,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Kranşy Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f027",
  "name": "Kaşarlı Eskalop Sandviç",
  "image": "/assets/photos/alfursan/items/f027.jpg",
  "price": 369,
  "unit": "",
  "category": "Sandviçler",
  "available": true,
  "featured": false,
  "description": "Kaşarlı Eskalop Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f028",
  "name": "Kuzu Şiş (200 gr.)",
  "image": "/assets/photos/alfursan/items/f028.jpg",
  "price": 899,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Kuzu Şiş (200 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f029",
  "name": "Kuzu Kebap (200 gr.)",
  "image": "/assets/photos/alfursan/items/f029.jpg",
  "price": 899,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Kuzu Kebap (200 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f030",
  "name": "Tavuk Şiş (200 gr.)",
  "image": "/assets/photos/alfursan/items/f030.jpg",
  "price": 499,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Tavuk Şiş (200 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f031",
  "name": "Tavuk Kebap (240 gr.)",
  "image": "/assets/photos/alfursan/items/f031.jpg",
  "price": 469,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Tavuk Kebap (240 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f032",
  "name": "Patatesli Izgara Tavuk (Yarım)",
  "image": "/assets/photos/alfursan/items/f032.jpg",
  "price": 569,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Patatesli Izgara Tavuk (Yarım) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f033",
  "name": "Pilavlı Izgara Tavuk (Yarım)",
  "image": "/assets/photos/alfursan/items/f033.jpg",
  "price": 599,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Pilavlı Izgara Tavuk (Yarım) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f034",
  "name": "Karışık Izgara",
  "image": "/assets/photos/alfursan/items/f034.jpg",
  "price": 1699,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Karışık Izgara من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f035",
  "name": "Izgara Tavuk Kanat (250 gr.)",
  "image": "/assets/photos/alfursan/items/f035.jpg",
  "price": 499,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Izgara Tavuk Kanat (250 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f036",
  "name": "Izgara Tavuk (Yarım)",
  "image": "/assets/photos/alfursan/items/f036.jpg",
  "price": 649,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Izgara Tavuk (Yarım) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f037",
  "name": "Pilav Üstü Tavuk Şiş",
  "image": "/assets/photos/alfursan/items/f037.jpg",
  "price": 539,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Pilav Üstü Tavuk Şiş من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f038",
  "name": "Tavuk Kebap (1 kg.)",
  "image": "/assets/photos/alfursan/items/f038.jpg",
  "price": 1099,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Tavuk Kebap (1 kg.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f039",
  "name": "Tavuk Şiş (500 gr.)",
  "image": "/assets/photos/alfursan/items/f039.jpg",
  "price": 629,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Tavuk Şiş (500 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f040",
  "name": "Tavuk Şiş (1 kg.)",
  "image": "/assets/photos/alfursan/items/f040.jpg",
  "price": 1199,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Tavuk Şiş (1 kg.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f041",
  "name": "Tavuk Kebap (500 gr.)",
  "image": "/assets/photos/alfursan/items/f041.jpg",
  "price": 599,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Tavuk Kebap (500 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f042",
  "name": "Kuzu Şiş (1 kg.)",
  "image": "/assets/photos/alfursan/items/f042.jpg",
  "price": 3999,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Kuzu Şiş (1 kg.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f044",
  "name": "Kuzu Kebap (1 kg.)",
  "image": "/assets/photos/alfursan/items/f044.jpg",
  "price": 3899,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Kuzu Kebap (1 kg.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f045",
  "name": "Kuzu Kebap (500 gr.)",
  "image": "/assets/photos/alfursan/items/f045.jpg",
  "price": 1999,
  "unit": "",
  "category": "Kebaplar & Izgaralar",
  "available": true,
  "featured": false,
  "description": "Kuzu Kebap (500 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f046",
  "name": "Tavuk Döner Dürüm",
  "image": "/assets/photos/alfursan/items/f046.jpg",
  "price": 229,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Tavuk Döner Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f048",
  "name": "Arap Tavuk Döner",
  "image": "/assets/photos/alfursan/items/f048.jpg",
  "price": 349,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Arap Tavuk Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f049",
  "name": "Double Arap Tavuk Döner",
  "image": "/assets/photos/alfursan/items/f049.jpg",
  "price": 629,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Double Arap Tavuk Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f050",
  "name": "Kaşarlı Arap Tavuk Döner",
  "image": "/assets/photos/alfursan/items/f050.jpg",
  "price": 499,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Kaşarlı Arap Tavuk Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f051",
  "name": "Pilav Üstü Tavuk Döner",
  "image": "/assets/photos/alfursan/items/f051.jpg",
  "price": 599,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Pilav Üstü Tavuk Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f052",
  "name": "Somun Ekmek Arası Tavuk Döner",
  "image": "/assets/photos/alfursan/items/f052.jpg",
  "price": 299,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Somun Ekmek Arası Tavuk Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f053",
  "name": "Tavuk Döner (220 gr.)",
  "image": "/assets/photos/alfursan/items/f053.jpg",
  "price": 599,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Tavuk Döner (220 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f054",
  "name": "Pane Döner",
  "image": "/assets/photos/alfursan/items/f054.jpg",
  "price": 599,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Pane Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f055",
  "name": "Döner Fette",
  "image": "/assets/photos/alfursan/items/f055.jpg",
  "price": 599,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Döner Fette من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f056",
  "name": "Acılı Tavuk Döner",
  "image": "/assets/photos/alfursan/items/f056.jpg",
  "price": 599,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Acılı Tavuk Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f057",
  "name": "Mini Döner (50 gr.)",
  "image": "/assets/photos/alfursan/items/f057.jpg",
  "price": 139,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Mini Döner (50 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f058",
  "name": "Somun Arab Döner",
  "image": "/assets/photos/alfursan/items/f058.jpg",
  "price": 379,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Somun Arab Döner من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f059",
  "name": "Tavuk Döner (4 Kişilik)",
  "image": "/assets/photos/alfursan/items/f059.jpg",
  "price": 1449,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Tavuk Döner (4 Kişilik) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f060",
  "name": "Mini Döner Dürüm (3 Adet)",
  "image": "/assets/photos/alfursan/items/f060.jpg",
  "price": 499,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Mini Döner Dürüm (3 Adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f061",
  "name": "Tavuk Döner (500 gr.)",
  "image": "/assets/photos/alfursan/items/f061.jpg",
  "price": 799,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Tavuk Döner (500 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f062",
  "name": "Tavuk Döner (1 kg.)",
  "image": "/assets/photos/alfursan/items/f062.jpg",
  "price": 1549,
  "unit": "",
  "category": "Tavuk Dönerler",
  "available": true,
  "featured": false,
  "description": "Tavuk Döner (1 kg.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f063",
  "name": "Margherita Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f063.jpg",
  "price": 499,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Margherita Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f064",
  "name": "Dört Mevsim Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f064.jpg",
  "price": 499,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Dört Mevsim Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f065",
  "name": "Hawaii Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f065.jpg",
  "price": 499,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Hawaii Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f066",
  "name": "Sucuklu Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f066.jpg",
  "price": 549,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Sucuklu Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f067",
  "name": "Mexican Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f067.jpg",
  "price": 549,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Mexican Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f068",
  "name": "Ton Balıklı Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f068.jpg",
  "price": 549,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Ton Balıklı Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f069",
  "name": "Etli Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f069.jpg",
  "price": 699,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Etli Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f070",
  "name": "Dönerli Pizza (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f070.jpg",
  "price": 549,
  "unit": "",
  "category": "Pizzalar (Orta Boy)",
  "available": true,
  "featured": false,
  "description": "Dönerli Pizza (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f071",
  "name": "Et Burger",
  "image": "/assets/photos/alfursan/items/f071.jpg",
  "price": 449,
  "unit": "",
  "category": "Burgerler",
  "available": true,
  "featured": false,
  "description": "Et Burger من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f072",
  "name": "Tavuk Burger",
  "image": "/assets/photos/alfursan/items/f072.jpg",
  "price": 349,
  "unit": "",
  "category": "Burgerler",
  "available": true,
  "featured": false,
  "description": "Tavuk Burger من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f073",
  "name": "Izgara Çipura",
  "image": "/assets/photos/alfursan/items/f073.jpg",
  "price": 749,
  "unit": "",
  "category": "Balıklar",
  "available": true,
  "featured": false,
  "description": "Izgara Çipura من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f074",
  "name": "Fileto Balık",
  "image": "/assets/photos/alfursan/items/f074.jpg",
  "price": 599,
  "unit": "",
  "category": "Balıklar",
  "available": true,
  "featured": false,
  "description": "Fileto Balık من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f075",
  "name": "Fileto Balık Sandviç",
  "image": "/assets/photos/alfursan/items/f075.jpg",
  "price": 399,
  "unit": "",
  "category": "Balıklar",
  "available": true,
  "featured": false,
  "description": "Fileto Balık Sandviç من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f076",
  "name": "Mexican Tavuk",
  "image": "/assets/photos/alfursan/items/f076.jpg",
  "price": 579,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Mexican Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f077",
  "name": "Zinger Tavuk",
  "image": "/assets/photos/alfursan/items/f077.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Zinger Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f078",
  "name": "Tavuk Fajita",
  "image": "/assets/photos/alfursan/items/f078.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Tavuk Fajita من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f079",
  "name": "Francesco Tavuk",
  "image": "/assets/photos/alfursan/items/f079.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Francesco Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f080",
  "name": "Çıtır Tavuk (Yarım)",
  "image": "/assets/photos/alfursan/items/f080.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Çıtır Tavuk (Yarım) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f081",
  "name": "Escalope Tavuk",
  "image": "/assets/photos/alfursan/items/f081.jpg",
  "price": 579,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Escalope Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f082",
  "name": "Supreme Tavuk",
  "image": "/assets/photos/alfursan/items/f082.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Supreme Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f083",
  "name": "Cordon Bleu",
  "image": "/assets/photos/alfursan/items/f083.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Cordon Bleu من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f084",
  "name": "Crispy",
  "image": "/assets/photos/alfursan/items/f084.jpg",
  "price": 579,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Crispy من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f085",
  "name": "Çıtır Tavuk Budu",
  "image": "/assets/photos/alfursan/items/f085.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Çıtır Tavuk Budu من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f086",
  "name": "Köri Soslu Tavuk",
  "image": "/assets/photos/alfursan/items/f086.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Köri Soslu Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f087",
  "name": "Crunchy Tavuk",
  "image": "/assets/photos/alfursan/items/f087.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Crunchy Tavuk من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f088",
  "name": "Sarımsaklı Tavuk Bonfile",
  "image": "/assets/photos/alfursan/items/f088.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Sarımsaklı Tavuk Bonfile من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f089",
  "name": "Kaşarlı Eskalop",
  "image": "/assets/photos/alfursan/items/f089.jpg",
  "price": 599,
  "unit": "",
  "category": "Ana Yemekler",
  "available": true,
  "featured": false,
  "description": "Kaşarlı Eskalop من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f090",
  "name": "Etli molokiye",
  "image": "/assets/photos/alfursan/items/f090.jpg",
  "price": 1049,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Etli molokiye من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f091",
  "name": "Yoğurtlu et",
  "image": "/assets/photos/alfursan/items/f091.jpg",
  "price": 1049,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Yoğurtlu et من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f092",
  "name": "Tavuklu Kebse",
  "image": "/assets/photos/alfursan/items/f092.jpg",
  "price": 579,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Tavuklu Kebse من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f093",
  "name": "Etli Kebse",
  "image": "/assets/photos/alfursan/items/f093.jpg",
  "price": 1299,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Etli Kebse من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f094",
  "name": "Tavuklu Mendi",
  "image": "/assets/photos/alfursan/items/f094.jpg",
  "price": 579,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Tavuklu Mendi من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f095",
  "name": "Etli Mendi",
  "image": "/assets/photos/alfursan/items/f095.jpg",
  "price": 1299,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Etli Mendi من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f096",
  "name": "Tavuklu Molehiya",
  "image": "/assets/photos/alfursan/items/f096.jpg",
  "price": 599,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Tavuklu Molehiya من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f097",
  "name": "Sade Pilav",
  "image": "/assets/photos/alfursan/items/f097.jpg",
  "price": 299,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Sade Pilav من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f098",
  "name": "Şam Mantısı",
  "image": "/assets/photos/alfursan/items/f098.jpg",
  "price": 1049,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Şam Mantısı من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f099",
  "name": "Yoğurtlu İçli Köfte",
  "image": "/assets/photos/alfursan/items/f099.jpg",
  "price": 1049,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Yoğurtlu İçli Köfte من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f100",
  "name": "Sade Sarı Pilav (Küçük Boy)",
  "image": "/assets/photos/alfursan/items/f100.jpg",
  "price": 149,
  "unit": "",
  "category": "Doğu Mutfağı",
  "available": true,
  "featured": false,
  "description": "Sade Sarı Pilav (Küçük Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f101",
  "name": "Patates Dürüm",
  "image": "/assets/photos/alfursan/items/f101.jpg",
  "price": 199,
  "unit": "",
  "category": "Dürümler",
  "available": true,
  "featured": false,
  "description": "Patates Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f102",
  "name": "Duble Tavuk Kebap Dürüm",
  "image": "/assets/photos/alfursan/items/f102.jpg",
  "price": 399,
  "unit": "",
  "category": "Dürümler",
  "available": true,
  "featured": false,
  "description": "Duble Tavuk Kebap Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f103",
  "name": "Kuzu Kebap Dürüm",
  "image": "/assets/photos/alfursan/items/f103.jpg",
  "price": 459,
  "unit": "",
  "category": "Dürümler",
  "available": true,
  "featured": false,
  "description": "Kuzu Kebap Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f104",
  "name": "Kuzu Şiş Dürüm",
  "image": "/assets/photos/alfursan/items/f104.jpg",
  "price": 459,
  "unit": "",
  "category": "Dürümler",
  "available": true,
  "featured": false,
  "description": "Kuzu Şiş Dürüm من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f105",
  "name": "Coleslaw Salata",
  "image": "/assets/photos/alfursan/items/f105.jpg",
  "price": 299,
  "unit": "",
  "category": "Salatalar",
  "available": true,
  "featured": false,
  "description": "Coleslaw Salata من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f106",
  "name": "Roka Salatası",
  "image": "/assets/photos/alfursan/items/f106.jpg",
  "price": 299,
  "unit": "",
  "category": "Salatalar",
  "available": true,
  "featured": false,
  "description": "Roka Salatası من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f107",
  "name": "Mevsim Salata",
  "image": "/assets/photos/alfursan/items/f107.jpg",
  "price": 299,
  "unit": "",
  "category": "Salatalar",
  "available": true,
  "featured": false,
  "description": "Mevsim Salata من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f108",
  "name": "Tabule Salata",
  "image": "/assets/photos/alfursan/items/f108.jpg",
  "price": 299,
  "unit": "",
  "category": "Salatalar",
  "available": true,
  "featured": false,
  "description": "Tabule Salata من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f109",
  "name": "Fatuş Salata",
  "image": "/assets/photos/alfursan/items/f109.jpg",
  "price": 299,
  "unit": "",
  "category": "Salatalar",
  "available": true,
  "featured": false,
  "description": "Fatuş Salata من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f110",
  "name": "Mercimek Çorbası",
  "image": "/assets/photos/alfursan/items/f110.jpg",
  "price": 119,
  "unit": "",
  "category": "Çorbalar",
  "available": true,
  "featured": false,
  "description": "Mercimek Çorbası من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f111",
  "name": "Mısır Çorbası",
  "image": "/assets/photos/alfursan/items/f111.jpg",
  "price": 149,
  "unit": "",
  "category": "Çorbalar",
  "available": true,
  "featured": false,
  "description": "Mısır Çorbası من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f112",
  "name": "Mantar Çorbası",
  "image": "/assets/photos/alfursan/items/f112.jpg",
  "price": 149,
  "unit": "",
  "category": "Çorbalar",
  "available": true,
  "featured": false,
  "description": "Mantar Çorbası من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f113",
  "name": "Tavuk Çorbası",
  "image": "/assets/photos/alfursan/items/f113.jpg",
  "price": 209,
  "unit": "",
  "category": "Çorbalar",
  "available": true,
  "featured": false,
  "description": "Tavuk Çorbası من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f114",
  "name": "Kızartma İçli Köfte (Adet)",
  "image": "/assets/photos/alfursan/items/f114.jpg",
  "price": 159,
  "unit": "",
  "category": "Diğer Lezzetler",
  "available": true,
  "featured": false,
  "description": "Kızartma İçli Köfte (Adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f115",
  "name": "Közde İçli Köfte (Adet)",
  "image": "/assets/photos/alfursan/items/f115.jpg",
  "price": 159,
  "unit": "",
  "category": "Diğer Lezzetler",
  "available": true,
  "featured": false,
  "description": "Közde İçli Köfte (Adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f116",
  "name": "Kaşarlı Börek(adet)",
  "image": "/assets/photos/alfursan/items/f116.jpg",
  "price": 69,
  "unit": "",
  "category": "Yan Ürünler",
  "available": true,
  "featured": false,
  "description": "Kaşarlı Börek(adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f117",
  "name": "Lavaş (6 Adet)",
  "image": "/assets/photos/alfursan/items/f117.jpg",
  "price": 69,
  "unit": "",
  "category": "Yan Ürünler",
  "available": true,
  "featured": false,
  "description": "Lavaş (6 Adet) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f118",
  "name": "Patates Kızartması (Orta Boy)",
  "image": "/assets/photos/alfursan/items/f118.jpg",
  "price": 269,
  "unit": "",
  "category": "Yan Ürünler",
  "available": true,
  "featured": false,
  "description": "Patates Kızartması (Orta Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f119",
  "name": "Patates Kızartması (Küçük)",
  "image": "/assets/photos/alfursan/items/f119.jpg",
  "price": 129,
  "unit": "",
  "category": "Yan Ürünler",
  "available": true,
  "featured": false,
  "description": "Patates Kızartması (Küçük) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f120",
  "name": "Salatalık Turşusu",
  "image": "/assets/photos/alfursan/items/f120.jpg",
  "price": 49,
  "unit": "",
  "category": "Yan Ürünler",
  "available": true,
  "featured": false,
  "description": "Salatalık Turşusu من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f121",
  "name": "Biber Turşusu",
  "image": "/assets/photos/alfursan/items/f121.jpg",
  "price": 49,
  "unit": "",
  "category": "Yan Ürünler",
  "available": true,
  "featured": false,
  "description": "Biber Turşusu من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f122",
  "name": "Coca-Cola (33 cl.)",
  "image": "/assets/photos/alfursan/items/f122.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Coca-Cola (33 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f123",
  "name": "Fanta (33 cl.)",
  "image": "/assets/photos/alfursan/items/f123.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Fanta (33 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f124",
  "name": "Sprite (33 cl.)",
  "image": "/assets/photos/alfursan/items/f124.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Sprite (33 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f125",
  "name": "Seles Portakal (25 cl)",
  "image": "/assets/photos/alfursan/items/f125.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Seles Portakal (25 cl) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f126",
  "name": "Pepsi (33 cl.)",
  "image": "/assets/photos/alfursan/items/f126.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Pepsi (33 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f127",
  "name": "Pepsi Max (33cl.)",
  "image": "/assets/photos/alfursan/items/f127.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Pepsi Max (33cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f128",
  "name": "Ayran (20 cl.)",
  "image": "/assets/photos/alfursan/items/f128.jpg",
  "price": 49,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Ayran (20 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f129",
  "name": "Su (50 cl.)",
  "image": "/assets/photos/alfursan/items/f129.jpg",
  "price": 19,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Su (50 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f130",
  "name": "Fanta (1 L.)",
  "image": "/assets/photos/alfursan/items/f130.jpg",
  "price": 139,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Fanta (1 L.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f131",
  "name": "Sprite (1 L.)",
  "image": "/assets/photos/alfursan/items/f131.jpg",
  "price": 139,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Sprite (1 L.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f132",
  "name": "Pepsi (1 L.)",
  "image": "/assets/photos/alfursan/items/f132.jpg",
  "price": 139,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Pepsi (1 L.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f133",
  "name": "Pepsi (2 L.)",
  "image": "/assets/photos/alfursan/items/f133.jpg",
  "price": 179,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Pepsi (2 L.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f134",
  "name": "Cola Turka (33 cl.)",
  "image": "/assets/photos/alfursan/items/f134.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Cola Turka (33 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f135",
  "name": "Çamlıca Portakal (33 cl.)",
  "image": "/assets/photos/alfursan/items/f135.jpg",
  "price": 99,
  "unit": "",
  "category": "İçecekler",
  "available": true,
  "featured": false,
  "description": "Çamlıca Portakal (33 cl.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f136",
  "name": "Tahin sosu",
  "image": "/assets/photos/alfursan/items/f136.jpg",
  "price": 59,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Tahin sosu من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f137",
  "name": "Izgara sosu",
  "image": "/assets/photos/alfursan/items/f137.jpg",
  "price": 49,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Izgara sosu من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f138",
  "name": "Sarımsak Sos (120 gr.)",
  "image": "/assets/photos/alfursan/items/f138.jpg",
  "price": 59,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Sarımsak Sos (120 gr.) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f139",
  "name": "Coleslaw (Küçük)",
  "image": "/assets/photos/alfursan/items/f139.jpg",
  "price": 59,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Coleslaw (Küçük) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f140",
  "name": "Kokteyl Sos",
  "image": "/assets/photos/alfursan/items/f140.jpg",
  "price": 59,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Kokteyl Sos من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f141",
  "name": "Pilav Sosu (Küçük Boy)",
  "image": "/assets/photos/alfursan/items/f141.jpg",
  "price": 49,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Pilav Sosu (Küçük Boy) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f142",
  "name": "Acı Sos (Küçük)",
  "image": "/assets/photos/alfursan/items/f142.jpg",
  "price": 49,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Acı Sos (Küçük) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f143",
  "name": "Nar Ekşisi (Küçük)",
  "image": "/assets/photos/alfursan/items/f143.jpg",
  "price": 49,
  "unit": "",
  "category": "Soslar",
  "available": true,
  "featured": false,
  "description": "Nar Ekşisi (Küçük) من مطعم الفرسان.",
  "imageFit": "cover",
  "options": []
 }
];

const alfursanProducts = alfursanProductCatalog.map((product, index) => ({
  ...product,
  id: 1320001 + index,
  storeId: alfursanStore.id
}));

const alfursanDeliverySettings = {
  [alfursanStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 30, maxRoundTripKm: 120 }
};
