// Generated from the official Al Sultan Sweets store on 2026-06-12.
const alsultanBranches = [
  {
    "id": 6,
    "name": "حلويات السلطان العالمية - الفاتح",
    "branchName": "الفاتح",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-6.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-6.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "30 - 50 دقيقة",
    "distance": 0.6,
    "location": {
      "lat": 41.0205403,
      "lng": 28.9420939
    },
    "mapUrl": "https://maps.app.goo.gl/QggF8qZNDHoLrwpT9",
    "open": true,
    "featured": true,
    "hasOffer": false,
    "offer": "",
    "description": "فرع الفاتح من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Akşemsettin, Balipaşa Cd No:150, D:F, 34080 Fatih/İstanbul, تركيا",
    "phone": "+90 552 322 31 02",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "الفاتح",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 7,
    "name": "حلويات السلطان العالمية - باشاك شهير",
    "branchName": "باشاك شهير",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-7.jpeg",
    "coverImage": "/assets/photos/alsultan/branches/branch-7.jpeg",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "45 - 70 دقيقة",
    "distance": 18.8,
    "location": {
      "lat": 41.1181509,
      "lng": 28.7744114
    },
    "mapUrl": "https://maps.app.goo.gl/ekyosaNoyxo6snvZ7",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع باشاك شهير من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "BULVARI CD B 7, 9001, 34494 Başakşehir/İstanbul, تركيا",
    "phone": "+90 531 265 66 37",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "باشاك شهير",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 8,
    "name": "حلويات السلطان العالمية - يوسف باشا",
    "branchName": "يوسف باشا",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-8.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-8.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "30 - 50 دقيقة",
    "distance": 1,
    "location": {
      "lat": 41.0104561,
      "lng": 28.9462547
    },
    "mapUrl": "https://maps.app.goo.gl/dw87tkY3h3c5Ziif9",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع يوسف باشا من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Topkapı, Turgut Özal Millet Cd. NO: 22a, Fatih/İstanbul, تركيا",
    "phone": "+90 506 041 44 25",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "يوسف باشا",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 9,
    "name": "حلويات السلطان العالمية - بيليكدوزو",
    "branchName": "بيليكدوزو",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-9.jpeg",
    "coverImage": "/assets/photos/alsultan/branches/branch-9.jpeg",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "60 - 90 دقيقة",
    "distance": 29,
    "location": {
      "lat": 41.0097042,
      "lng": 28.6254008
    },
    "mapUrl": "https://maps.app.goo.gl/aSszHjd2qQuyeZcb6",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع بيليكدوزو من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Pınartepe, Nöbet Sk. No:34, 34500 Büyükçekmece/İstanbul, تركيا",
    "phone": "+90 552 738 69 91",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "بيليكدوزو",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 10,
    "name": "حلويات السلطان العالمية - بهشة شهير",
    "branchName": "بهشة شهير",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-10.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-10.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "60 - 90 دقيقة",
    "distance": 25,
    "location": {
      "lat": 41.0583329,
      "lng": 28.6691247
    },
    "mapUrl": "https://maps.app.goo.gl/pN5c3DbB1TQ8E6P46",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع بهشة شهير من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Koza, Hoşdere Yolu 3M59+8JW 25A, Esenyurt/İstanbul, تركيا",
    "phone": "+90 501 108 51 00",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "بهشة شهير",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 11,
    "name": "حلويات السلطان العالمية - سلطان غازي",
    "branchName": "سلطان غازي",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-11.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-11.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "45 - 70 دقيقة",
    "distance": 14,
    "location": {
      "lat": 41.112023,
      "lng": 28.8482417
    },
    "mapUrl": "https://maps.app.goo.gl/V9XUuyotzkidJDD78",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع سلطان غازي من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "MAHMUTBEY CD.NO: 76 ŞANTİYE, Malkoçoğlu, İstanbul, تركيا",
    "phone": "+90 552 322 31 05",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "سلطان غازي",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  }
];

const alsultanProductCatalog = [
  {
    "sourceId": 7646,
    "name": "قهوة السلطان سادة 250 غرام",
    "image": "/assets/photos/alsultan/products/7646.png",
    "price": 270,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "القهوة والشوكولا",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم القهوة والشوكولا.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%82%d9%87%d9%88%d8%a9-%d8%a7%d9%84%d8%b3%d9%84%d8%b7%d8%a7%d9%86-%d8%b3%d8%a7%d8%af%d8%a9-250-%d8%ba%d8%b1%d8%a7%d9%85/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7373,
    "name": "وجبة كبة لبنية 10 حبات",
    "image": "/assets/photos/alsultan/products/7373.jpeg",
    "price": 960,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%88%d8%ac%d8%a8%d8%a9-%d9%84%d8%a8%d9%86%d9%8a%d8%a9-10-%d8%ad%d8%a8%d8%a7%d8%aa/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7370,
    "name": "وجبة حراء بأصبعو",
    "image": "/assets/photos/alsultan/products/7370.jpeg",
    "price": 420,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "مقبلات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم مقبلات.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%88%d8%ac%d8%a8%d8%a9-%d8%ad%d8%b1%d8%a7%d8%a1-%d8%a8%d8%a3%d8%b5%d8%a8%d8%b9%d9%88/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7358,
    "name": "يالنجي",
    "image": "/assets/photos/alsultan/products/7358.webp",
    "price": 290,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "مقبلات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم مقبلات.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%8a%d8%a7%d9%84%d9%86%d8%ac%d9%8a/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7156,
    "name": "كبة مشوية",
    "image": "/assets/photos/alsultan/products/7156.webp",
    "price": 110,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "مقبلات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم مقبلات.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d8%a8%d8%a9-%d9%85%d8%b4%d9%88%d9%8a%d8%a9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7154,
    "name": "كبة مقلية",
    "image": "/assets/photos/alsultan/products/7154.webp",
    "price": 100,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "مقبلات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم مقبلات.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d8%a8%d8%a9-%d9%85%d9%82%d9%84%d9%8a%d8%a9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7152,
    "name": "شوربة عدس",
    "image": "/assets/photos/alsultan/products/7152.webp",
    "price": 125,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "شوربات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم شوربات.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b4%d9%88%d8%b1%d8%a8%d8%a9-%d8%b9%d8%af%d8%b3/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7150,
    "name": "برك لحمة",
    "image": "/assets/photos/alsultan/products/7150.webp",
    "price": 47,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "مقبلات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم مقبلات.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d8%b1%d9%83-%d9%84%d8%ad%d9%85%d8%a9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 7145,
    "name": "برك جبنة",
    "image": "/assets/photos/alsultan/products/7145.webp",
    "price": 36,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "مقبلات",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم مقبلات.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d8%b1%d9%83-%d8%ac%d8%a8%d9%86%d8%a9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6828,
    "name": "كبة لبنية",
    "image": "/assets/photos/alsultan/products/6828.webp",
    "price": 600,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d8%a8%d8%a9-%d9%84%d8%a8%d9%86%d9%8a%d8%a9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6826,
    "name": "مندي لحم",
    "image": "/assets/photos/alsultan/products/6826.webp",
    "price": 700,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d9%86%d8%af%d9%8a-%d9%84%d8%ad%d9%85/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6824,
    "name": "كبسة لحم",
    "image": "/assets/photos/alsultan/products/6824.webp",
    "price": 700,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": true,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d8%a8%d8%b3%d8%a9-%d9%84%d8%ad%d9%85/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6821,
    "name": "كبسة دجاج",
    "image": "/assets/photos/alsultan/products/6821.webp",
    "price": 390,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات دجاج",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات دجاج.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d8%a8%d8%b3%d8%a9-%d8%af%d8%ac%d8%a7%d8%ac-2/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6819,
    "name": "فريكة لحم",
    "image": "/assets/photos/alsultan/products/6819.webp",
    "price": 700,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%81%d8%b1%d9%8a%d9%83%d8%a9-%d9%84%d8%ad%d9%85/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6817,
    "name": "فريكة دجاج",
    "image": "/assets/photos/alsultan/products/6817.webp",
    "price": 390,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات دجاج",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات دجاج.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%81%d8%b1%d9%8a%d9%83%d8%a9-%d8%af%d8%ac%d8%a7%d8%ac/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6815,
    "name": "بازلاء",
    "image": "/assets/photos/alsultan/products/6815.webp",
    "price": 700,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d8%a7%d8%b2%d9%84%d8%a7%d8%a1/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6813,
    "name": "أوزي",
    "image": "/assets/photos/alsultan/products/6813.webp",
    "price": 300,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات لحمة",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات لحمة.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a3%d9%88%d8%b2%d9%8a/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6782,
    "name": "مندي دجاج",
    "image": "/assets/photos/alsultan/products/6782.webp",
    "price": 390,
    "oldPrice": null,
    "unit": "الوجبة",
    "category": "وجبات دجاج",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم وجبات دجاج.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d9%86%d8%af%d9%8a-%d8%af%d8%ac%d8%a7%d8%ac/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6500,
    "name": "علبة أقراص معمول عجوة عدد 18",
    "image": "/assets/photos/alsultan/products/6500.webp",
    "price": 660,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d9%84%d8%a8%d8%a9-%d8%a3%d9%82%d8%b1%d8%a7%d8%b5-%d9%85%d8%b9%d9%85%d9%88%d9%84-%d8%b9%d8%ac%d9%88%d8%a9-%d8%b9%d8%af%d8%af-18/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6462,
    "name": "حلو عربي مشكل فستق وكاجو وجوز 1 كغ",
    "image": "/assets/photos/alsultan/products/6462.png",
    "price": 1700,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-%d9%81%d8%b3%d8%aa%d9%82-%d9%88%d9%83%d8%a7%d8%ac%d9%88-%d9%88%d8%ac%d9%88%d8%b2-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 6402,
    "name": "مبرومة بالفستق 1 كغ",
    "image": "/assets/photos/alsultan/products/6402.png",
    "price": 2350,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%a8%d8%b1%d9%88%d9%85%d8%a9-%d8%a8%d8%a7%d9%84%d9%81%d8%b3%d8%aa%d9%82-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5433,
    "name": "عسل جبلي 475 غ",
    "image": "/assets/photos/alsultan/products/5433.jpg",
    "price": 800,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "عسل السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم عسل السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d8%b3%d9%84-%d8%ac%d8%a8%d9%84%d9%8a-475-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5429,
    "name": "عسل متعدد الأزهار 475 غ",
    "image": "/assets/photos/alsultan/products/5429.jpg",
    "price": 750,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "عسل السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم عسل السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d8%b3%d9%84-%d9%85%d8%aa%d8%b9%d8%af%d8%af-%d8%a7%d9%84%d8%a3%d8%b2%d9%87%d8%a7%d8%b1-475-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5425,
    "name": "عسل الكستناء 475 غ",
    "image": "/assets/photos/alsultan/products/5425.jpg",
    "price": 1500,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "عسل السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم عسل السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d8%b3%d9%84-%d8%a7%d9%84%d9%83%d8%b3%d8%aa%d9%86%d8%a7%d8%a1-475-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5421,
    "name": "عسل حبة البركة 475 غ",
    "image": "/assets/photos/alsultan/products/5421.jpg",
    "price": 850,
    "oldPrice": null,
    "unit": "العلبة",
    "category": "عسل السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم عسل السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d8%b3%d9%84-%d8%ad%d8%a8%d8%a9-%d8%a7%d9%84%d8%a8%d8%b1%d9%83%d8%a9-475-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5417,
    "name": "سمنة السلطان 800 غ",
    "image": "/assets/photos/alsultan/products/5417.jpg",
    "price": 980,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "سمنة السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم سمنة السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b3%d9%85%d9%86%d8%a9-%d8%a7%d9%84%d8%b3%d9%84%d8%b7%d8%a7%d9%86-800-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5402,
    "name": "بيتفور صب 600 غ",
    "image": "/assets/photos/alsultan/products/5402.jpg",
    "price": 575,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d9%8a%d8%aa%d9%81%d9%88%d8%b1-%d8%b5%d8%a8-600-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5394,
    "name": "كيليك فراشة 1 كغ",
    "image": "/assets/photos/alsultan/products/5394.jpg",
    "price": 2000,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات تركية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات تركية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d9%8a%d9%84%d9%8a%d9%83-%d9%81%d8%b1%d8%a7%d8%b4%d8%a9-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5386,
    "name": "ميديا حمراء 1 كغ",
    "image": "/assets/photos/alsultan/products/5386.png",
    "price": 1800,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات تركية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات تركية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d9%8a%d8%af%d9%8a%d8%a7-%d8%ad%d9%85%d8%b1%d8%a7%d8%a1-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5376,
    "name": "حلو عربي علبة موزاييك وسط 1600 غ",
    "image": "/assets/photos/alsultan/products/5376.png",
    "price": 9900,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "هدايا السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم هدايا السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d9%88%d8%b2%d8%a7%d9%8a%d9%8a%d9%83-%d9%88%d8%b3%d8%b7-1600-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5364,
    "name": "حلو عربي علبة موزاييك صغير 800 غ",
    "image": "/assets/photos/alsultan/products/5364.png",
    "price": 8250,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "هدايا السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم هدايا السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d9%88%d8%b2%d8%a7%d9%8a%d9%8a%d9%83-%d8%b5%d8%ba%d9%8a%d8%b1-800-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5353,
    "name": "حلو عربي علبة مخمل 1600 غ",
    "image": "/assets/photos/alsultan/products/5353.jpg",
    "price": 4600,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "هدايا السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم هدايا السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d8%ae%d9%85%d9%84-1600-%d8%ba-2/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5334,
    "name": "حلو عربي مشكل علبة مخمل 400 غ",
    "image": "/assets/photos/alsultan/products/5334.jpg",
    "price": 1050,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "هدايا السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم هدايا السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d8%ae%d9%85%d9%84-400-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5324,
    "name": "حلو عربي علبة مخمل 800 غ",
    "image": "/assets/photos/alsultan/products/5324.png",
    "price": 2700,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "هدايا السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم هدايا السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d8%ae%d9%85%d9%84-1600-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5316,
    "name": "حلو عربي علبة مخمل ملكي 4 كغ",
    "image": "/assets/photos/alsultan/products/5316.png",
    "price": 10700,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "هدايا السلطان",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم هدايا السلطان.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d8%ae%d9%85%d9%84-%d9%85%d9%84%d9%83%d9%8a-4-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5306,
    "name": "كريمة الفستق 200 غ",
    "image": "/assets/photos/alsultan/products/5306.png",
    "price": 320,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "القهوة والشوكولا",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم القهوة والشوكولا.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d8%b1%d9%8a%d9%85%d8%a9-%d8%a7%d9%84%d9%81%d8%b3%d8%aa%d9%82-200-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5298,
    "name": "معمول مشكل 800 غ",
    "image": "/assets/photos/alsultan/products/5298.jpg",
    "price": 1225,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b9%d9%85%d9%88%d9%84-%d9%85%d8%b4%d9%83%d9%84-800-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5290,
    "name": "غريبة صغير 400 غ",
    "image": "/assets/photos/alsultan/products/5290.jpg",
    "price": 455,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ba%d8%b1%d9%8a%d8%a8%d8%a9-%d8%b5%d8%ba%d9%8a%d8%b1-400-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5282,
    "name": "برازق صغير 450 غ",
    "image": "/assets/photos/alsultan/products/5282.png",
    "price": 510,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d8%b1%d8%a7%d8%b2%d9%82-%d8%b5%d8%ba%d9%8a%d8%b1-450-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5274,
    "name": "برازق كبير 700 غ",
    "image": "/assets/photos/alsultan/products/5274.png",
    "price": 775,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d8%b1%d8%a7%d8%b2%d9%82-%d9%83%d8%a8%d9%8a%d8%b1-700-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5264,
    "name": "نواشف مشكل صغير 450 غ",
    "image": "/assets/photos/alsultan/products/5264.png",
    "price": 515,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%86%d9%88%d8%a7%d8%b4%d9%81-%d9%85%d8%b4%d9%83%d9%84-%d8%b5%d8%ba%d9%8a%d8%b1-450-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5254,
    "name": "فيصلية بالفستق 1 كغ",
    "image": "/assets/photos/alsultan/products/5254.png",
    "price": 1950,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%81%d9%8a%d8%b5%d9%84%d9%8a%d8%a9-%d8%a8%d8%a7%d9%84%d9%81%d8%b3%d8%aa%d9%82-1-%d9%83%d8%ba-2/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5245,
    "name": "حلو عربي مشكل علبة 6 قطع",
    "image": "/assets/photos/alsultan/products/5245.png",
    "price": 265,
    "oldPrice": null,
    "unit": "العلبة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-%d8%b9%d9%84%d8%a8%d8%a9-6-%d9%82%d8%b7%d8%b9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5237,
    "name": "قهوة السلطان 250 غ",
    "image": "/assets/photos/alsultan/products/5237.png",
    "price": 290,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "القهوة والشوكولا",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم القهوة والشوكولا.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%82%d9%87%d9%88%d8%a9-%d8%a7%d9%84%d8%b3%d9%84%d8%b7%d8%a7%d9%86-250-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5225,
    "name": "حلقوم تركي 800 غ",
    "image": "/assets/photos/alsultan/products/5225.webp",
    "price": 825,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نوغا وحلقوم",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نوغا وحلقوم.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%82%d9%88%d9%85-%d8%aa%d8%b1%d9%83%d9%8a-800-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5207,
    "name": "جيمجك 1 كغ",
    "image": "/assets/photos/alsultan/products/5207.png",
    "price": 1320,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات تركية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات تركية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ac%d9%8a%d9%85%d8%ac%d9%83-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5197,
    "name": "معمول الصحة والطاقه قطعتين",
    "image": "/assets/photos/alsultan/products/5197.jpg",
    "price": 80,
    "oldPrice": null,
    "unit": "العلبة",
    "category": "حلويات صحية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات صحية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b9%d9%85%d9%88%d9%84-%d8%a7%d9%84%d8%b5%d8%ad%d8%a9-%d9%88%d8%a7%d9%84%d8%b7%d8%a7%d9%82%d9%87-%d9%82%d8%b7%d8%b9%d8%aa%d9%8a%d9%86/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5187,
    "name": "بيتفور سابليه معدن 600 غ",
    "image": "/assets/photos/alsultan/products/5187.png",
    "price": 650,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d9%8a%d8%aa%d9%81%d9%88%d8%b1-%d8%b3%d8%a7%d8%a8%d9%84%d9%8a%d9%87-%d9%85%d8%b9%d8%af%d9%86-600-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5175,
    "name": "نواشف مشكل كبير 800 غ",
    "image": "/assets/photos/alsultan/products/5175.jpg",
    "price": 900,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%86%d9%88%d8%a7%d8%b4%d9%81-%d9%85%d8%b4%d9%83%d9%84-%d9%83%d8%a8%d9%8a%d8%b1-800-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5165,
    "name": "معمول عجوة أيام زمان 750 غ",
    "image": "/assets/photos/alsultan/products/5165.jpg",
    "price": 800,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b9%d9%85%d9%88%d9%84-%d8%b9%d8%ac%d9%88%d8%a9-%d8%a3%d9%8a%d8%a7%d9%85-%d8%b2%d9%85%d8%a7%d9%86-750-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5157,
    "name": "معمول عجوة معدن 750 غ",
    "image": "/assets/photos/alsultan/products/5157.jpg",
    "price": 800,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b9%d9%85%d9%88%d9%84-%d8%b9%d8%ac%d9%88%d8%a9-%d9%85%d8%b9%d8%af%d9%86-750-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5145,
    "name": "معمول فستق معدن 500 غ",
    "image": "/assets/photos/alsultan/products/5145.jpg",
    "price": 1250,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b9%d9%85%d9%88%d9%84-%d9%81%d8%b3%d8%aa%d9%82-%d9%85%d8%b9%d8%af%d9%86-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5133,
    "name": "معمول جوز معدن 500 غ",
    "image": "/assets/photos/alsultan/products/5133.jpg",
    "price": 750,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b9%d9%85%d9%88%d9%84-%d8%ac%d9%88%d8%b2-%d9%85%d8%b9%d8%af%d9%86-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5121,
    "name": "غريبة معدن 500 غ",
    "image": "/assets/photos/alsultan/products/5121.jpg",
    "price": 575,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ba%d8%b1%d9%8a%d8%a8%d8%a9-%d9%85%d8%b9%d8%af%d9%86-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5111,
    "name": "برازق معدن 500 غ",
    "image": "/assets/photos/alsultan/products/5111.jpg",
    "price": 575,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d8%b1%d8%a7%d8%b2%d9%82-%d9%85%d8%b9%d8%af%d9%86-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5101,
    "name": "مشكل نواشف معدن",
    "image": "/assets/photos/alsultan/products/5101.jpg",
    "price": 685,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "نواشف عربية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم نواشف عربية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%85%d8%b4%d9%83%d9%84-%d9%86%d9%88%d8%a7%d8%b4%d9%81-%d9%85%d8%b9%d8%af%d9%86/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5077,
    "name": "عش البلبل فستق 500 غ",
    "image": "/assets/photos/alsultan/products/5077.jpg",
    "price": 1200,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d8%b4-%d8%a7%d9%84%d8%a8%d9%84%d8%a8%d9%84-%d9%81%d8%b3%d8%aa%d9%82-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5067,
    "name": "حلو عربي مشكل علبة 175 غ",
    "image": "/assets/photos/alsultan/products/5067.jpg",
    "price": 350,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-%d8%b9%d9%84%d8%a8%d8%a9-175-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5057,
    "name": "حلو عربي مشكل علبة 4 قطع",
    "image": "/assets/photos/alsultan/products/5057.jpg",
    "price": 175,
    "oldPrice": null,
    "unit": "العلبة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-%d8%b9%d9%84%d8%a8%d8%a9-4-%d9%82%d8%b7%d8%b9/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5045,
    "name": "كول وشكور 500 غ",
    "image": "/assets/photos/alsultan/products/5045.jpg",
    "price": 1200,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d9%83%d9%88%d9%84-%d9%88%d8%b4%d9%83%d9%88%d8%b1-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5033,
    "name": "تمرية بالمكسرات 500غ",
    "image": "/assets/photos/alsultan/products/5033.jpg",
    "price": 870,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%aa%d9%85%d8%b1%d9%8a%d8%a9-%d8%a8%d8%a7%d9%84%d9%85%d9%83%d8%b3%d8%b1%d8%a7%d8%aa-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5021,
    "name": "حلو عربي بالعسل 700 غ",
    "image": "/assets/photos/alsultan/products/5021.jpg",
    "price": 1620,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات صحية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات صحية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%a8%d8%a7%d9%84%d8%b9%d8%b3%d9%84-700-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5013,
    "name": "حلو عربي دايت 400 غ",
    "image": "/assets/photos/alsultan/products/5013.jpg",
    "price": 1200,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات صحية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات صحية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d8%af%d8%a7%d9%8a%d8%aa-400-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 5002,
    "name": "أصابع الفستق 500 غ",
    "image": "/assets/photos/alsultan/products/5002.jpg",
    "price": 1200,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a3%d8%b5%d8%a7%d8%a8%d8%b9-%d8%a7%d9%84%d9%81%d8%b3%d8%aa%d9%82-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4990,
    "name": "أصابع كاجو 500 غ",
    "image": "/assets/photos/alsultan/products/4990.jpg",
    "price": 700,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a3%d8%b5%d8%a7%d8%a8%d8%b9-%d9%83%d8%a7%d8%ac%d9%88-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4979,
    "name": "بلورية بيضاء 500 غ",
    "image": "/assets/photos/alsultan/products/4979.jpg",
    "price": 1250,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a8%d9%84%d9%88%d8%b1%d9%8a%d8%a9-%d8%a8%d9%8a%d8%b6%d8%a7%d8%a1-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4968,
    "name": "اسية فستق 500 غ",
    "image": "/assets/photos/alsultan/products/4968.jpg",
    "price": 1200,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a7%d8%b3%d9%8a%d8%a9-%d9%81%d8%b3%d8%aa%d9%82-500-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4950,
    "name": "حلو عربي فستق فقط 250 غ",
    "image": "/assets/photos/alsultan/products/4950.jpg",
    "price": 625,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%81%d8%b3%d8%aa%d9%82-%d9%81%d9%82%d8%b7-250-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4933,
    "name": "حلو عربي فستق فقط 400 غ",
    "image": "/assets/photos/alsultan/products/4933.jpg",
    "price": 1075,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%81%d8%b3%d8%aa%d9%82-%d9%81%d9%82%d8%b7-400-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4920,
    "name": "حلو عربي فستق فقط 750 غ",
    "image": "/assets/photos/alsultan/products/4920.jpg",
    "price": 1850,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%81%d8%b3%d8%aa%d9%82-%d9%81%d9%82%d8%b7-750-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4910,
    "name": "حلو عربي فستق فقط علبة معدن 1 كغ",
    "image": "/assets/photos/alsultan/products/4910.png",
    "price": 2250,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%81%d8%b3%d8%aa%d9%82-%d9%81%d9%82%d8%b7-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d8%b9%d8%af%d9%86-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4887,
    "name": "حلو عربي مشكل 250 غ",
    "image": "/assets/photos/alsultan/products/4887.jpg",
    "price": 525,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-250-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4877,
    "name": "حلو عربي مشكل 400 غ",
    "image": "/assets/photos/alsultan/products/4877.jpg",
    "price": 900,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-400-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4875,
    "name": "حلو عربي مشكل 750 غ",
    "image": "/assets/photos/alsultan/products/4875.png",
    "price": 1650,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-750-%d8%ba-2/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4826,
    "name": "عش البلبل فستق 1 كغ",
    "image": "/assets/photos/alsultan/products/4826.jpg",
    "price": 2420,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b9%d8%b4-%d8%a7%d9%84%d8%a8%d9%84%d8%a8%d9%84/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4227,
    "name": "أصابع دولما بالفستق 1 كغ",
    "image": "/assets/photos/alsultan/products/4227.png",
    "price": 2000,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات تركية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات تركية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%a3%d8%b5%d8%a7%d8%a8%d8%b9-%d8%af%d9%88%d9%84%d9%85%d8%a7-%d8%a8%d8%a7%d9%84%d9%81%d8%b3%d8%aa%d9%82/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4218,
    "name": "شوكولا دبي السلطان 200 غ",
    "image": "/assets/photos/alsultan/products/4218.png",
    "price": 460,
    "oldPrice": null,
    "unit": "الحصة",
    "category": "القهوة والشوكولا",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم القهوة والشوكولا.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%b4%d9%88%d9%83%d9%88%d9%84%d8%a7-%d8%af%d8%a8%d9%8a-%d8%a7%d9%84%d8%b3%d9%84%d8%b7%d8%a7%d9%86-200-%d8%ba/",
    "sourceBranded": true,
    "options": []
  },
  {
    "sourceId": 4196,
    "name": "حلو عربي مشكل علبة معدن 1 كغ",
    "image": "/assets/photos/alsultan/products/4196.png",
    "price": 1900,
    "oldPrice": null,
    "unit": "العبوة",
    "category": "حلويات شرقية",
    "available": true,
    "featured": false,
    "description": "منتج أصلي من حلويات السلطان العالمية ضمن قسم حلويات شرقية.",
    "sourceUrl": "https://alsultansweets.com/product/%d8%ad%d9%84%d9%88-%d8%b9%d8%b1%d8%a8%d9%8a-%d9%85%d8%b4%d9%83%d9%84-%d8%b9%d9%84%d8%a8%d8%a9-%d9%85%d8%b9%d8%af%d9%86-1-%d9%83%d8%ba/",
    "sourceBranded": true,
    "options": []
  }
];

const alsultanProducts = alsultanBranches.flatMap((store, branchIndex) => alsultanProductCatalog.map((product, productIndex) => ({
  ...product,
  id: 600001 + (branchIndex * 1000) + productIndex,
  storeId: store.id
})));

const alsultanDeliverySettings = Object.fromEntries(alsultanBranches.map(store => [store.id, {
  mode: "distance",
  fixedFee: store.delivery,
  ratePerKm: 15,
  prepMinutes: 25,
  maxRoundTripKm: 120
}]));
