// Generated from the official Al Sultan Sweets store on 2026-06-12.
const alsultanBranches = [
  {
    "id": 6,
    "name": "حلويات السلطان العالمية - الفاتح",
    "branchName": "الفاتح",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-6.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-6.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "30 - 50 دقيقة",
    "distance": 0.6,
    "location": {
      "lat": 41.0205403,
      "lng": 28.9420939
    },
    "mapUrl": "https://maps.app.goo.gl/QggF8qZNDHoLrwpT9",
    "open": true,
    "featured": true,
    "hasOffer": false,
    "offer": "",
    "description": "فرع الفاتح من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Akşemsettin, Balipaşa Cd No:150, D:F, 34080 Fatih/İstanbul, تركيا",
    "phone": "+90 552 322 31 02",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "الفاتح",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 7,
    "name": "حلويات السلطان العالمية - باشاك شهير",
    "branchName": "باشاك شهير",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-7.jpeg",
    "coverImage": "/assets/photos/alsultan/branches/branch-7.jpeg",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "45 - 70 دقيقة",
    "distance": 18.8,
    "location": {
      "lat": 41.1181509,
      "lng": 28.7744114
    },
    "mapUrl": "https://maps.app.goo.gl/ekyosaNoyxo6snvZ7",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع باشاك شهير من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "BULVARI CD B 7, 9001, 34494 Başakşehir/İstanbul, تركيا",
    "phone": "+90 531 265 66 37",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "باشاك شهير",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 8,
    "name": "حلويات السلطان العالمية - يوسف باشا",
    "branchName": "يوسف باشا",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-8.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-8.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "30 - 50 دقيقة",
    "distance": 1,
    "location": {
      "lat": 41.0104561,
      "lng": 28.9462547
    },
    "mapUrl": "https://maps.app.goo.gl/dw87tkY3h3c5Ziif9",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع يوسف باشا من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Topkapı, Turgut Özal Millet Cd. NO: 22a, Fatih/İstanbul, تركيا",
    "phone": "+90 506 041 44 25",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "يوسف باشا",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 9,
    "name": "حلويات السلطان العالمية - بيليكدوزو",
    "branchName": "بيليكدوزو",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-9.jpeg",
    "coverImage": "/assets/photos/alsultan/branches/branch-9.jpeg",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "60 - 90 دقيقة",
    "distance": 29,
    "location": {
      "lat": 41.0097042,
      "lng": 28.6254008
    },
    "mapUrl": "https://maps.app.goo.gl/aSszHjd2qQuyeZcb6",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع بيليكدوزو من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Pınartepe, Nöbet Sk. No:34, 34500 Büyükçekmece/İstanbul, تركيا",
    "phone": "+90 552 738 69 91",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "بيليكدوزو",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 10,
    "name": "حلويات السلطان العالمية - بهشة شهير",
    "branchName": "بهشة شهير",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-10.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-10.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "60 - 90 دقيقة",
    "distance": 25,
    "location": {
      "lat": 41.0583329,
      "lng": 28.6691247
    },
    "mapUrl": "https://maps.app.goo.gl/pN5c3DbB1TQ8E6P46",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع بهشة شهير من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "Koza, Hoşdere Yolu 3M59+8JW 25A, Esenyurt/İstanbul, تركيا",
    "phone": "+90 501 108 51 00",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "بهشة شهير",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  },
  {
    "id": 11,
    "name": "حلويات السلطان العالمية - سلطان غازي",
    "branchName": "سلطان غازي",
    "branchGroup": "alsultan",
    "category": "حلويات",
    "image": "/assets/photos/alsultan/branches/branch-11.webp",
    "coverImage": "/assets/photos/alsultan/branches/branch-11.webp",
    "logoImage": "/assets/photos/alsultan/logo-arabic.png",
    "logo": "س",
    "rating": 0,
    "reviews": 0,
    "newStore": true,
    "delivery": 30,
    "minOrder": 150,
    "time": "45 - 70 دقيقة",
    "distance": 14,
    "location": {
      "lat": 41.112023,
      "lng": 28.8482417
    },
    "mapUrl": "https://maps.app.goo.gl/V9XUuyotzkidJDD78",
    "open": true,
    "featured": false,
    "hasOffer": false,
    "offer": "",
    "description": "فرع سلطان غازي من حلويات السلطان العالمية، يقدم الحلويات الشرقية والتركية والنواشف والهدايا والقهوة ومنتجات السلطان الأصلية.",
    "address": "MAHMUTBEY CD.NO: 76 ŞANTİYE, Malkoçoğlu, İstanbul, تركيا",
    "phone": "+90 552 322 31 05",
    "website": "https://alsultansweets.com",
    "sourceUrl": "https://alsultansweets.com/shop/",
    "hours": "يرجى تأكيد أوقات العمل مباشرة عبر واتساب الفرع",
    "areas": [
      "سلطان غازي",
      "إسطنبول",
      "مناطق التوصيل حسب المسافة"
    ],
    "fulfillment": "توصيل واستلام من الفرع",
    "subscription": "احترافي",
    "orderCount": 0,
    "sourceBranded": true
  }
];

const alsultanProductCatalog = [];

const alsultanProducts = alsultanBranches.flatMap((store, branchIndex) => alsultanProductCatalog.map((product, productIndex) => ({
  ...product,
  id: 600001 + (branchIndex * 1000) + productIndex,
  storeId: store.id
})));

const alsultanDeliverySettings = Object.fromEntries(alsultanBranches.map(store => [store.id, {
  mode: "distance",
  fixedFee: store.delivery,
  ratePerKm: 15,
  prepMinutes: 25,
  maxRoundTripKm: 120
}]));
