// Generated for مطعم الوادي (Al Wadi) — Istanbul. Source: alwadi.minidine.com (minidine)
const alwadiStore = {
 "id": 21,
 "name": "مطعم الوادي",
 "category": "مطاعم",
 "image": "/assets/photos/alwadi/cover.jpg",
 "coverImage": "/assets/photos/alwadi/cover.jpg",
 "logoImage": "/assets/photos/alwadi/logo.png",
 "logo": "و",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "35 - 65 دقيقة",
 "distance": 18,
 "location": {
  "lat": 41.063546,
  "lng": 28.667504
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.063546,28.667504",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم الوادي — شاورما ومشاوي وأطباق شعبية في إسطنبول: الشاورما بأنواعها وبوكسات الشاورما، قسم الشواية، الأطباق الشعبية، الإضافات والمشروبات. أسماء الأطباق كما في القائمة الرسمية للمطعم.",
 "address": "إسطنبول، تركيا",
 "phone": "+90 505 004 32 33",
 "whatsapp": "+90 505 004 32 33",
 "email": "",
 "website": "https://alwadi.minidine.com/",
 "sourceUrl": "https://alwadi.minidine.com/ar/?branch=alwadi",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const alwadiProductCatalog = [
 {
  "sourceId": "shaorma-mrbaa",
  "name": "شاورما مربعة",
  "image": "/assets/photos/alwadi/items/item-001.png",
  "price": 160,
  "unit": "قطعة",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "خبز تورتالا -شاورما 100جرام-خس-جبنة شيدر سائلة-هالبينو-ثوم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaorma-msksk",
  "name": "شاورما مسقسقة",
  "image": "/assets/photos/alwadi/items/item-002.png",
  "price": 120,
  "unit": "قطعة",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "خبز صاج-شاورما 90 جرام-ثوم-مخلل-سئسئة\r\nبالزيت",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "asbaa-shaorma-1",
  "name": "اصبع شاورما",
  "image": "/assets/photos/alwadi/items/item-003.png",
  "price": 89,
  "unit": "قطعة",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "خبز صاج -شاورما 40 جرام-ثوم-مخلل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "klasyk-shaorma",
  "name": "كلاسيك شاورما",
  "image": "/assets/photos/alwadi/items/item-004.png",
  "price": 120,
  "unit": "قطعة",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "خبز شامي-شاورما 80 جرام-ثوم-مخلل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaorma-frayz",
  "name": "شاورما فرايز",
  "image": "/assets/photos/alwadi/items/item-005.png",
  "price": 160,
  "unit": "قطعة",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "بطاطس -شاورما - خس -جبنة شيدر - قطع هلبينو",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaorma-aloady",
  "name": "شاورما الوادي",
  "image": "/assets/photos/alwadi/items/item-006.png",
  "price": 120,
  "unit": "قطعة",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "خبز شامي-شاورما 80 جرام-خلطةالوادي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaorma-aarby-aloady",
  "name": "شاورما عربي الوادي",
  "image": "/assets/photos/alwadi/items/item-007.png",
  "price": 199,
  "unit": "قطعة",
  "category": "بوكسات الشورما",
  "available": true,
  "featured": false,
  "description": "خبز تورتال-شاورما 90 جرام-ثوم-صوص\r\nخاص-هالبينو-خس مع بطاطا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaorma-aarby-dbl",
  "name": "شاورما عربي دبل",
  "image": "/assets/photos/alwadi/items/item-008.png",
  "price": 260,
  "unit": "قطعة",
  "category": "بوكسات الشورما",
  "available": true,
  "featured": false,
  "description": "خبز صاج-شاورما 120 جرام-ثوم-مخلل\r\nمع بطاطا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shrayh-shaorma-200-ghram",
  "name": "شرائح شاورما 200 غرام",
  "image": "/assets/photos/alwadi/items/item-009.png",
  "price": 250,
  "unit": "قطعة",
  "category": "بوكسات الشورما",
  "available": true,
  "featured": false,
  "description": "شرائح شاورما 200 جرام-ثوم-بطاطا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaorma-aarby",
  "name": "شاورما عربي",
  "image": "/assets/photos/alwadi/items/item-010.png",
  "price": 199,
  "unit": "قطعة",
  "category": "بوكسات الشورما",
  "available": true,
  "featured": false,
  "description": "خبز صاج- شاورما 90 جرام-ثوم-مخلل\r\nمع بطاطا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ft-shaorma-1",
  "name": "فتة شاورما",
  "image": "/assets/photos/alwadi/items/item-011.png",
  "price": 160,
  "unit": "علبة",
  "category": "بوكسات الشورما",
  "available": true,
  "featured": false,
  "description": "فتة شاورما من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shrayh-shaorma-500-ghram",
  "name": "شرائح شاورما 500 غرام",
  "image": "/assets/photos/alwadi/items/item-012.png",
  "price": 550,
  "unit": "قطعة",
  "category": "بوكسات الشورما",
  "available": true,
  "featured": false,
  "description": "شرائح شاورما 500 جرام-ثوم-بطاطا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mnto",
  "name": "منتو",
  "image": "/assets/photos/alwadi/items/item-013.png",
  "price": 180,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "منتو من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "nsf-dgag-shoay-sad",
  "name": "نصف دجاج شواية سادة",
  "image": "/assets/photos/alwadi/items/item-014.png",
  "price": 260,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "نصف دجاج شواية بدون رز",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dgag-shoay-kaml-maa-btats",
  "name": "دجاج شواية كاملة مع بطاطس",
  "image": "/assets/photos/alwadi/items/item-015.png",
  "price": 660,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "حبة دجاج شواية مع بطاطس",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dgag-shoay-kaml-sad",
  "name": "دجاج شواية كاملة سادة",
  "image": "/assets/photos/alwadi/items/item-016.png",
  "price": 520,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "حبة دجاج شواية بدون رز + سحاوق مجانا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "nsf-dgag-shoay-maa-alrz",
  "name": "نصف دجاج شواية مع الرز",
  "image": "/assets/photos/alwadi/items/item-017.png",
  "price": 330,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "نصف دجاج شواية مع رز بخاري - سحاوق مجانا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "rz-sad",
  "name": "رز سادة",
  "image": "/assets/photos/alwadi/items/item-018.png",
  "price": 180,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "رز بخاري سادة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dgag-shoay-kaml-maa-alrz",
  "name": "دجاج شواية كاملة مع الرز",
  "image": "/assets/photos/alwadi/items/item-019.png",
  "price": 660,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "حبة دجاج شواية مع رز + 2 سحاوق مجانا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "nsf-dgag-shoay-maa-btats",
  "name": "نصف دجاج شواية مع بطاطس",
  "image": "/assets/photos/alwadi/items/item-020.png",
  "price": 330,
  "unit": "قطعة",
  "category": "قسم الشواية",
  "available": true,
  "featured": false,
  "description": "نصف دجاج شواية مع بطاطا مقلية",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "sht-har",
  "name": "شطة حارة",
  "image": "/assets/photos/alwadi/items/item-021.png",
  "price": 50,
  "unit": "قطعة",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "شطة سبايسي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "btata-mkly",
  "name": "بطاطا مقلية",
  "image": "/assets/photos/alwadi/items/item-022.png",
  "price": 99,
  "unit": "قطعة",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "بطاطا مقلية من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dkos",
  "name": "دقوس",
  "image": "/assets/photos/alwadi/items/item-023.png",
  "price": 30,
  "unit": "قطعة",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "دقوس من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-khdar",
  "name": "سلطة خضار",
  "image": "/assets/photos/alwadi/items/item-024.png",
  "price": 90,
  "unit": "قطعة",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "سلطة خضار بداخلها خيار + طماطم + خس",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "zbady-sad",
  "name": "زبادي سادة",
  "image": "/assets/photos/alwadi/items/item-025.png",
  "price": 50,
  "unit": "قطعة",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "زبادي مع خيار",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-grgyr",
  "name": "سلطة جرجير",
  "image": "/assets/photos/alwadi/items/item-026.png",
  "price": 150,
  "unit": "قطعة",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "سلطة جرجير بداخلها طماطم + بصل + جرجير + زيت زيتون",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fryzby-tot-azrk",
  "name": "فريزبي توت ازرق",
  "image": "/assets/photos/alwadi/items/item-027.jpeg",
  "price": 50,
  "unit": "قنينة",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "فريزبي توت ازرق من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maaa-16",
  "name": "ماء",
  "image": "/assets/photos/alwadi/items/item-028.png",
  "price": 10,
  "unit": "قنينة",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "ماء من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kodrd",
  "name": "كودرد",
  "image": "/assets/photos/alwadi/items/item-029.jpeg",
  "price": 50,
  "unit": "كيس",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "كودرد من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fryzby-lymon-naanaaa",
  "name": "فريزبي ليمون نعناع",
  "image": "/assets/photos/alwadi/items/item-030.jpeg",
  "price": 50,
  "unit": "قنينة",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "فريزبي ليمون نعناع من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aayran-12",
  "name": "عيران",
  "image": "/assets/photos/alwadi/items/item-031.png",
  "price": 50,
  "unit": "قنينة",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "عيران من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fryzby-tfah-aanb",
  "name": "فريزبي تفاح عنب",
  "image": "/assets/photos/alwadi/items/item-032.jpeg",
  "price": 50,
  "unit": "قنينة",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "فريزبي تفاح عنب من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mshrob-ghazy-1",
  "name": "مشروب غازي",
  "image": "/assets/photos/alwadi/items/item-033.png",
  "price": 50,
  "unit": "قنينة",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "مشروب غازي من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aaryk-ksht-aasl",
  "name": "عريكة قشطة عسل",
  "image": "/assets/photos/alwadi/items/item-034.png",
  "price": 259,
  "unit": "صحن",
  "category": "قسم الشعبيات",
  "available": true,
  "featured": false,
  "description": "عريكة قشطة عسل من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maasobb-ksht",
  "name": "معصوبب قشطة",
  "image": "/assets/photos/alwadi/items/item-035.png",
  "price": 259,
  "unit": "صحن",
  "category": "قسم الشعبيات",
  "available": true,
  "featured": false,
  "description": "معصوبب قشطة من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aaryk-aloady",
  "name": "عريكة الوادي",
  "image": "/assets/photos/alwadi/items/item-036.png",
  "price": 279,
  "unit": "صحن",
  "category": "قسم الشعبيات",
  "available": true,
  "featured": false,
  "description": "عريكة الوادي من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maasob-ksht-aasl",
  "name": "معصوب قشطة عسل",
  "image": "/assets/photos/alwadi/items/item-037.png",
  "price": 269,
  "unit": "صحن",
  "category": "قسم الشعبيات",
  "available": true,
  "featured": false,
  "description": "معصوب قشطة عسل من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maasob-mlky-1",
  "name": "معصوب ملكي",
  "image": "/assets/photos/alwadi/items/item-038.png",
  "price": 279,
  "unit": "صحن",
  "category": "قسم الشعبيات",
  "available": true,
  "featured": false,
  "description": "معصوب ملكي من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maasob-sag",
  "name": "معصوب صاج",
  "image": "/assets/photos/alwadi/items/item-039.png",
  "price": 259,
  "unit": "صحن",
  "category": "قسم الشعبيات",
  "available": true,
  "featured": false,
  "description": "معصوب صاج من مطعم الوادي.",
  "imageFit": "cover",
  "options": []
 }
];

const alwadiProducts = alwadiProductCatalog.map((product, index) => ({
  ...product,
  id: 31001 + index,
  storeId: alwadiStore.id
}));

const alwadiDeliverySettings = {
  [alwadiStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 30, maxRoundTripKm: 120 }
};
