// Generated for ماركت أيهم (EYHEM MARKET) — Bizimevler 6, Ispartakule, Avcılar/İstanbul.
// Arabic/Syrian supermarket. Source: WhatsApp Business catalog (wa.me/c/905066477688),
// 142 products with real photos. The merchant published NO prices anywhere in the
// catalog (neither in list rows nor in the product Details panel), so every product is
// priceOnRequest — the storefront shows "السعر عند الطلب" + a direct WhatsApp order
// button instead of an add-to-cart button (same mechanism as كنافة البراء store 68).
// Google Maps match: "(EYHEM MARKET) ماركت ايهم بزم 6 ميترو اسبارتكولا" 4.4★/21,
// coords confirmed against the merchant's own Maps pin shared on their WhatsApp profile.

const ayhamStore = {
 "id": 112,
 "name": "ماركت أيهم",
 "category": "سوبر ماركت",
 "image": "/assets/photos/ayham/cover.jpg",
 "coverImage": "/assets/photos/ayham/cover.jpg",
 "logoImage": "/assets/photos/ayham/logo.jpg",
 "logo": "أ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 0,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": {
  "lat": 41.0623572,
  "lng": 28.707586
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.0623572,28.707586",
 "open": true,
 "featured": false,
 "hasOffer": false,
 "offer": "",
 "priceOnRequest": true,
 "description": "ماركت أيهم — سوبر ماركت في بيزم إيفلر 6 (إسبارتكولة) يقدّم جميع المنتجات العربية والأجنبية والمونة السورية: خضار جاهزة، بقوليات، معلبات، أجبان وألبان، منظفات ومستلزمات منزلية. الأسعار والطلب عبر واتساب.",
 "address": "Bizimevler 6, Ispartakule, Tahtakale, Avcılar/İstanbul",
 "phone": "+90 506 647 76 88",
 "whatsapp": "+90 506 647 76 88",
 "email": "",
 "website": "",
 "sourceUrl": "https://wa.me/c/905066477688",
 "hours": "يومياً من الساعة 10:00 صباحاً حتى 10:00 مساءً",
 "areas": [
  "إسبارتكولة",
  "أفجلار",
  "باشاك شهير",
  "مناطق إسطنبول حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true,
 "googlePlaceId": "ChIJ_UBe38KnyhQRV_IanHlfcqk",
 "googleRating": 4.4,
 "googleReviewsCount": 21,
 "googleMapsUrl": "https://maps.google.com/?cid=12209926515669529175"
};

const ayhamFullCatalog = [
  {"name":"كوسا محفورة","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p001.jpg"},
  {"name":"ملفوف مسلوق مقطع","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p002.jpg"},
  {"name":"كزبرة خضرا مفرومة","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p003.jpg"},
  {"name":"يالنجي مطبوخ بيتوتي جاهز","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p022.jpg"},
  {"name":"زهرة مقطفة","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p030.jpg"},
  {"name":"ورق عنب ب لحم الغنم العواس","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p048.jpg"},
  {"name":"بقدونس مفروم","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p066.jpg"},
  {"name":"ثوم مقشر فريش","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p078.jpg"},
  {"name":"سبانخ منضف مفروم","price":0,"priceOnRequest":true,"category":"خضار جاهزة","image":"/assets/photos/ayham/p107.jpg"},
  {"name":"رز الريف وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p007.jpg"},
  {"name":"برغل خشن وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p008.jpg"},
  {"name":"معكرونة Filiz Kalem","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p009.jpg"},
  {"name":"سميد خشن وزن 500 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p020.jpg"},
  {"name":"فول حب ناشف وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p026.jpg"},
  {"name":"رز مكسر وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p027.jpg"},
  {"name":"معكرونة Filiz Spaghetti","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p028.jpg"},
  {"name":"معكرونة Filiz burgu","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p033.jpg"},
  {"name":"رز كبسة 555 الفاخر وزن 4,5 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p036.jpg"},
  {"name":"ذرة بوشار وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p047.jpg"},
  {"name":"عدس احمر وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p051.jpg"},
  {"name":"اندومي خضار","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p053.jpg"},
  {"name":"برغل ناعم وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p056.jpg"},
  {"name":"أندومي شعيرية","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p059.jpg"},
  {"name":"رز كبسة محمود وزن 4 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p069.jpg"},
  {"name":"فاصوليا حب بيضا وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p072.jpg"},
  {"name":"طحين اسمر وزن 1 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p073.jpg"},
  {"name":"شعيرية Filiz","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p074.jpg"},
  {"name":"اندومي دجاج","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p081.jpg"},
  {"name":"حمص حب ناشف وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p082.jpg"},
  {"name":"ملح صخري وزن 1,5 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p088.jpg"},
  {"name":"طحين قمحة كاملة وزن 1 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p089.jpg"},
  {"name":"برغل عمقي اسمر وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p092.jpg"},
  {"name":"اندومي خضار كاسة","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p093.jpg"},
  {"name":"رز كبسة 555 الفاخر وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p094.jpg"},
  {"name":"عدس أخضر وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p099.jpg"},
  {"name":"ملح طعام وزن 500 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p104.jpg"},
  {"name":"كُسكُسي حبة وسط","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p110.jpg"},
  {"name":"رز لويال الذهبي وزن 10 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p112.jpg"},
  {"name":"طحين ابيض وزن 1 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p114.jpg"},
  {"name":"رز محمود وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p125.jpg"},
  {"name":"رز بنجابي الوعل وزن 5 كغ","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p128.jpg"},
  {"name":"رز لويال الذهبي وزن 900 غرام","price":0,"priceOnRequest":true,"category":"قسم البقوليات","image":"/assets/photos/ayham/p135.jpg"},
  {"name":"خل أبيض","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p004.jpg"},
  {"name":"صلصة صويا","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p005.jpg"},
  {"name":"كتشب Burgu (حلو)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p006.jpg"},
  {"name":"ماء زهر الاموي","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p016.jpg"},
  {"name":"خل التفاح طبيعي عضوي 100%","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p023.jpg"},
  {"name":"مايونيز Burgu","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p024.jpg"},
  {"name":"تونا ليو الأصلي (حار)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p034.jpg"},
  {"name":"كتشب Burgu (حار)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p039.jpg"},
  {"name":"سردين مغربي جولي (حار)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p041.jpg"},
  {"name":"فطر مقطع","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p042.jpg"},
  {"name":"اناناس مقطع","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p044.jpg"},
  {"name":"حمص حب معلب","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p045.jpg"},
  {"name":"تونا كو (حار)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p049.jpg"},
  {"name":"ذرة معلبة بورجو","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p058.jpg"},
  {"name":"فول مدمس الصفوة حبة عريضة","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p061.jpg"},
  {"name":"خردل هاينيز","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p067.jpg"},
  {"name":"فاصوليا بورجو بيضاء","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p080.jpg"},
  {"name":"ماء ورد الاموي","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p090.jpg"},
  {"name":"دبس رمان تركي","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p095.jpg"},
  {"name":"دبس بندورة Tat","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p098.jpg"},
  {"name":"صاص ئالين (بارد)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p111.jpg"},
  {"name":"ترمس حلو","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p117.jpg"},
  {"name":"باربونيا بورجو","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p118.jpg"},
  {"name":"فاصوليا حمراء بورجو بالزيت","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p126.jpg"},
  {"name":"فول مدمس الصفوة","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p129.jpg"},
  {"name":"تونا كو (حلو)","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p132.jpg"},
  {"name":"دبس رمان سوري ممتاز","price":0,"priceOnRequest":true,"category":"معلبات مواد غذائية","image":"/assets/photos/ayham/p139.jpg"},
  {"name":"جبنة برغر شيدر شرائح","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p010.jpg"},
  {"name":"زيتون أسود وزن 700 gr","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p011.jpg"},
  {"name":"زيتون بدون عجو بتبلة الجزر والفليفلة واليمون","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p012.jpg"},
  {"name":"لبن غنم العمري 2 كغ","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p017.jpg"},
  {"name":"جبنة شلل وزن نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p031.jpg"},
  {"name":"لبنة مدعبلة مع زيت (فليفلة)","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p032.jpg"},
  {"name":"جبنة كرات صغيرة موزريلا وزن نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p035.jpg"},
  {"name":"مرتديلا هنا وسط 380 غرام","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p037.jpg"},
  {"name":"لبن ايشم وزن 1 كغ","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p038.jpg"},
  {"name":"زبدة لورباك مملحة وزن 200gr","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p043.jpg"},
  {"name":"لبنة مدعبلة مع زيت (حبة بركة)","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p050.jpg"},
  {"name":"جبنة مضفرة وزن نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p052.jpg"},
  {"name":"لبنة مدعبلة مع زيت (سادة)","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p055.jpg"},
  {"name":"لبنة مدعبلة مع زيت (نعناع)","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p057.jpg"},
  {"name":"لبنة مدعبلة بدون زيت صحن مشكل","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p065.jpg"},
  {"name":"جبنة مسنرة وزن نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p071.jpg"},
  {"name":"جبنة شلل بقرية كاملة الدسم وزن 750gr","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p079.jpg"},
  {"name":"جبنة شركسي خاصة للحلويات وزن نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p084.jpg"},
  {"name":"لبن ايشم نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p085.jpg"},
  {"name":"جبنة بيضا تركية","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p086.jpg"},
  {"name":"لبنة بقرية بلدية","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p087.jpg"},
  {"name":"قشطة حموية العمري","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p102.jpg"},
  {"name":"لبنة تركية ايشم","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p103.jpg"},
  {"name":"قشطة شامية العمري","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p105.jpg"},
  {"name":"زيتون بدون عجو بتبلة الزعتر الاخضر واليمون","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p115.jpg"},
  {"name":"لبنة مدعبلة مع زيت (مشكلة)","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p116.jpg"},
  {"name":"كريمة طبخ","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p120.jpg"},
  {"name":"زبدة لورباك غير مملحة وزن 200 غرام","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p121.jpg"},
  {"name":"جبنة حلوم وزن نصف كيلو","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p127.jpg"},
  {"name":"جبنة كرات موزريلا وزن نصف كيلو خاص للحلويات","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p130.jpg"},
  {"name":"لبن غنم العمري 1 كغ","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p137.jpg"},
  {"name":"جبنة قشقوان وزن 400gr.","price":0,"priceOnRequest":true,"category":"اصنافنا في الثلاجه","image":"/assets/photos/ayham/p140.jpg"},
  {"name":"سائل جلي فيفو 4 كغ","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p013.jpg"},
  {"name":"سائل جلي نورا لافندر","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p014.jpg"},
  {"name":"معطر ملابس يومش الأصفر","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p015.jpg"},
  {"name":"دواء غسيل مدار 4 كغ","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p018.jpg"},
  {"name":"سائل يدين فيفو","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p021.jpg"},
  {"name":"سائل جلي نورا ألترا","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p029.jpg"},
  {"name":"ملمع زجاج","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p046.jpg"},
  {"name":"سائل جلي نورا باليمون","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p060.jpg"},
  {"name":"معطر ملابس بينغو","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p070.jpg"},
  {"name":"معطر ملابس ومعطر أرضيات ديوكس","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p083.jpg"},
  {"name":"روح الملح (فلاش)","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p091.jpg"},
  {"name":"معطر ملابس يومش الأزرق","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p096.jpg"},
  {"name":"معطر أرضيات ديتول","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p109.jpg"},
  {"name":"عملاق ديوكس","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p113.jpg"},
  {"name":"كلور دوميستوس الاخضر","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p123.jpg"},
  {"name":"معطر ملابس يومش الزهري","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p124.jpg"},
  {"name":"مسحوق غسيل سارتيكس 1 كغ","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p133.jpg"},
  {"name":"كلور حجم لتر","price":0,"priceOnRequest":true,"category":"قسم المنظفات","image":"/assets/photos/ayham/p142.jpg"},
  {"name":"بلسم شعر İpek","price":0,"priceOnRequest":true,"category":"العناية الشخصية","image":"/assets/photos/ayham/p025.jpg"},
  {"name":"شامبو اليدور","price":0,"priceOnRequest":true,"category":"العناية الشخصية","image":"/assets/photos/ayham/p075.jpg"},
  {"name":"صابون غار عمر فاضل","price":0,"priceOnRequest":true,"category":"العناية الشخصية","image":"/assets/photos/ayham/p097.jpg"},
  {"name":"صابون ديتول","price":0,"priceOnRequest":true,"category":"العناية الشخصية","image":"/assets/photos/ayham/p100.jpg"},
  {"name":"شامبو كلير","price":0,"priceOnRequest":true,"category":"العناية الشخصية","image":"/assets/photos/ayham/p134.jpg"},
  {"name":"شامبو اليدور ازرق","price":0,"priceOnRequest":true,"category":"العناية الشخصية","image":"/assets/photos/ayham/p138.jpg"},
  {"name":"طحينة مهروسة ابناء عم وزن 400 غرام","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p019.jpg"},
  {"name":"حلاوة فرط سورية بالفستق","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p040.jpg"},
  {"name":"كاسترد التونسا","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p062.jpg"},
  {"name":"حلاوة مهروسة ابناء عم وزن 700 غرام","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p068.jpg"},
  {"name":"حلاوة مهروسة وزن 350 غرام","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p076.jpg"},
  {"name":"حلاوة رويال سادة وزن 350 غرام","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p136.jpg"},
  {"name":"طحينة مهروسة ابناء عم وزن 700 غرام","price":0,"priceOnRequest":true,"category":"حلاوة وطحينة","image":"/assets/photos/ayham/p141.jpg"},
  {"name":"حمص بطحينة العجمي","price":0,"priceOnRequest":true,"category":"مقبلات جاهزة","image":"/assets/photos/ayham/p063.jpg"},
  {"name":"متبل باذنجان العجمي","price":0,"priceOnRequest":true,"category":"مقبلات جاهزة","image":"/assets/photos/ayham/p064.jpg"},
  {"name":"كريم ثوم العجمي","price":0,"priceOnRequest":true,"category":"مقبلات جاهزة","image":"/assets/photos/ayham/p101.jpg"},
  {"name":"حمص بطحينة العجمي (حجم صغير)","price":0,"priceOnRequest":true,"category":"مقبلات جاهزة","image":"/assets/photos/ayham/p122.jpg"},
  {"name":"محمرة الملك","price":0,"priceOnRequest":true,"category":"مقبلات جاهزة","image":"/assets/photos/ayham/p131.jpg"},
  {"name":"مدة سفرك","price":0,"priceOnRequest":true,"category":"مستلزمات منزلية","image":"/assets/photos/ayham/p054.jpg"},
  {"name":"ورق زبدة","price":0,"priceOnRequest":true,"category":"مستلزمات منزلية","image":"/assets/photos/ayham/p077.jpg"},
  {"name":"ورق قصدير ألمنيوم","price":0,"priceOnRequest":true,"category":"مستلزمات منزلية","image":"/assets/photos/ayham/p106.jpg"},
  {"name":"مدة سفرة نايلون","price":0,"priceOnRequest":true,"category":"مستلزمات منزلية","image":"/assets/photos/ayham/p108.jpg"},
  {"name":"أكياس قمامة حجم كبير","price":0,"priceOnRequest":true,"category":"مستلزمات منزلية","image":"/assets/photos/ayham/p119.jpg"},
];

// Emptied in the repo for payload size — the live catalog is read from Supabase.
// See the perf note in CLAUDE.md / [[adding-a-restaurant]].
const ayhamProductCatalog = [];

const ayhamProducts = ayhamProductCatalog.map((p, i) => ({
  ...p,
  id: 1920001 + i,
  storeId: ayhamStore.id,
  available: true,
}));

const ayhamDeliverySettings = {
  [ayhamStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 30, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ayhamStore, ayhamFullCatalog, ayhamProducts, ayhamDeliverySettings };
}
