// Generated for مطعم آزال (AZAL) — Esenyurt, Istanbul. Source: menu.akillikurye.com (akillikurye)
const azalStore = {
 "id": 23,
 "name": "مطعم آزال",
 "category": "مطاعم",
 "image": "/assets/photos/azal/cover.jpg",
 "coverImage": "/assets/photos/azal/cover.jpg",
 "logoImage": "/assets/photos/azal/logo.jpg",
 "logo": "آ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "40 - 70 دقيقة",
 "distance": 17,
 "location": {
  "lat": 41.014951,
  "lng": 28.650778
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.014951,28.650778",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم آزال — مطبخ شرقي في إسنيورت بإسطنبول: المقبلات والأسماك واللحوم والدجاج والقلايات والمخبوزات والعصائر والمشروبات. أسماء الأطباق والأسعار كما في القائمة الرسمية للمطعم.",
 "address": "Mevlana, Yıldırım Beyazıt Cd. No:2, إسنيورت، إسطنبول",
 "phone": "+90 535 450 63 71",
 "whatsapp": "+90 535 450 63 71",
 "email": "",
 "website": "https://menu.akillikurye.com/mtaam-AZAL",
 "sourceUrl": "https://menu.akillikurye.com/mtaam-AZAL",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسنيورت",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const azalProductCatalog = [
 {
  "sourceId": "azal-1",
  "name": "شوربة مرق",
  "image": "/assets/photos/azal/items/item-001.jpeg",
  "price": 50,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "شوربة مرق",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-2",
  "name": "سلطة عربية",
  "image": "/assets/photos/azal/items/item-002.jpeg",
  "price": 155,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة عربية",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-3",
  "name": "فتوش",
  "image": "/assets/photos/azal/items/item-003.jpeg",
  "price": 165,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "فتوش",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-4",
  "name": "سلطة يمنية",
  "image": "/assets/photos/azal/items/item-004.jpeg",
  "price": 155,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة يمنية",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-5",
  "name": "تبولة",
  "image": "/assets/photos/azal/items/item-005.jpeg",
  "price": 165,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "تبولة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-6",
  "name": "سحاوق",
  "image": "/assets/photos/azal/items/item-006.jpeg",
  "price": 15,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "سحاوق",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-7",
  "name": "سحاوق جبن",
  "image": "/assets/photos/azal/items/item-007.jpeg",
  "price": 30,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "سحاوق جبن",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-8",
  "name": "حمص",
  "image": "/assets/photos/azal/items/item-008.jpeg",
  "price": 100,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "حمص",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-9",
  "name": "بطاطس مقلي",
  "image": "/assets/photos/azal/items/item-009.jpeg",
  "price": 150,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "بطاطس مقلي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-10",
  "name": "سلطه يونانيه",
  "image": "/assets/photos/azal/items/item-010.jpg",
  "price": 165,
  "unit": "",
  "category": "المقبلات",
  "available": true,
  "featured": false,
  "description": "undefined",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-11",
  "name": "سمك مقلي",
  "image": "/assets/photos/azal/items/item-011.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "سمك مقلي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-12",
  "name": "سمك صنعاء",
  "image": "/assets/photos/azal/items/item-012.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "سمك صنعاء",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-13",
  "name": "سمك موفا",
  "image": "/assets/photos/azal/items/item-013.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "سمك موفا",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-14",
  "name": "صانونة سمك",
  "image": "/assets/photos/azal/items/item-014.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "صانونة سمك",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-15",
  "name": "صانونة جمبري",
  "image": "/assets/photos/azal/items/item-015.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "صانونة جمبري",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-16",
  "name": "صيادية سمك",
  "image": "/assets/photos/azal/items/item-016.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "صيادية سمك",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-17",
  "name": "جمبري مقلي",
  "image": "/assets/photos/azal/items/item-017.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "جمبري مقلي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-18",
  "name": "عقدة جمبري",
  "image": "/assets/photos/azal/items/item-018.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "عقدة جمبري",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-19",
  "name": "عقدة سمك",
  "image": "/assets/photos/azal/items/item-019.jpeg",
  "price": 490,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "عقدة سمك",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-20",
  "name": "لحم مندي",
  "image": "/assets/photos/azal/items/item-020.jpeg",
  "price": 635,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم مندي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-21",
  "name": "لحم حضرمي",
  "image": "/assets/photos/azal/items/item-021.jpeg",
  "price": 640,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم حضرمي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-22",
  "name": "لحم مضغوط",
  "image": "/assets/photos/azal/items/item-022.jpeg",
  "price": 635,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم مضغوط",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-23",
  "name": "لحم مدفون",
  "image": "/assets/photos/azal/items/item-023.jpeg",
  "price": 635,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم مدفون",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-24",
  "name": "ملوخية لحم",
  "image": "/assets/photos/azal/items/item-024.jpeg",
  "price": 595,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "ملوخية لحم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-25",
  "name": "لحم برمة",
  "image": "/assets/photos/azal/items/item-025.jpeg",
  "price": 640,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم برمة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-26",
  "name": "عقدة لحم",
  "image": "/assets/photos/azal/items/item-026.jpeg",
  "price": 595,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "عقدة لحم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-27",
  "name": "صانونة لحم",
  "image": "/assets/photos/azal/items/item-027.jpeg",
  "price": 595,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "صانونة لحم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-28",
  "name": "بامية لحم",
  "image": "/assets/photos/azal/items/item-028.jpeg",
  "price": 595,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "بامية لحم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-29",
  "name": "دجاج مندي",
  "image": "/assets/photos/azal/items/item-029.jpeg",
  "price": 355,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج مندي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-30",
  "name": "دجاج مضغوط",
  "image": "/assets/photos/azal/items/item-030.jpeg",
  "price": 355,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج مضغوط",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-31",
  "name": "دجاج مظبي",
  "image": "/assets/photos/azal/items/item-031.jpeg",
  "price": 375,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج مظبي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-32",
  "name": "دجاج مدفون",
  "image": "/assets/photos/azal/items/item-032.jpeg",
  "price": 355,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج مدفون",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-33",
  "name": "رز سادة",
  "image": "/assets/photos/azal/items/item-033.png",
  "price": 150,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "رز سادة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-34",
  "name": "ملوخية دجاج",
  "image": "/assets/photos/azal/items/item-034.jpeg",
  "price": 335,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "ملوخية دجاج",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-35",
  "name": "بامية دجاج",
  "image": "/assets/photos/azal/items/item-035.jpeg",
  "price": 335,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "بامية دجاج",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-36",
  "name": "صانونة دجاج",
  "image": "/assets/photos/azal/items/item-036.jpeg",
  "price": 335,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "صانونة دجاج",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-37",
  "name": "عقدة دجاج",
  "image": "/assets/photos/azal/items/item-037.jpeg",
  "price": 335,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "عقدة دجاج",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-38",
  "name": "سلتة",
  "image": "/assets/photos/azal/items/item-038.jpeg",
  "price": 350,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "سلتة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-39",
  "name": "سلتة صنعاء",
  "image": "/assets/photos/azal/items/item-039.jpeg",
  "price": 440,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "سلتة صنعاء",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-40",
  "name": "فتة مرق",
  "image": "/assets/photos/azal/items/item-040.jpeg",
  "price": 150,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فتة مرق",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-41",
  "name": "لحم صغار",
  "image": "/assets/photos/azal/items/item-041.jpeg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "لحم صغار",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-42",
  "name": "كبدة",
  "image": "/assets/photos/azal/items/item-042.jpeg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "كبدة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-43",
  "name": "لحم مفروم",
  "image": "/assets/photos/azal/items/item-043.jpeg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "لحم مفروم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-44",
  "name": "مثلوث لحم",
  "image": "/assets/photos/azal/items/item-044.jpeg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "مثلوث لحم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-45",
  "name": "سلتة بالتونة",
  "image": "/assets/photos/azal/items/item-045.jpeg",
  "price": 350,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "سلتة بالتونة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-46",
  "name": "بامية سادة",
  "image": "/assets/photos/azal/items/item-046.jpeg",
  "price": 235,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "بامية سادة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-47",
  "name": "بيض عيون",
  "image": "/assets/photos/azal/items/item-047.jpeg",
  "price": 200,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "بيض عيون",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-48",
  "name": "لحسة",
  "image": "/assets/photos/azal/items/item-048.jpeg",
  "price": 250,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "لحسة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-49",
  "name": "فتة صنعاء",
  "image": "/assets/photos/azal/items/item-049.jpeg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فتة صنعاء",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-50",
  "name": "كباب صنعاء",
  "image": "/assets/photos/azal/items/item-050.jpg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "كباب صنعاء",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-51",
  "name": "فاصوليا ناشف",
  "image": "/assets/photos/azal/items/item-051.jpeg",
  "price": 229,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فاصوليا ناشف",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-52",
  "name": "فاصوليا حرضة",
  "image": "/assets/photos/azal/items/item-052.jpeg",
  "price": 229,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فاصوليا حرضة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-53",
  "name": "فاصوليا بالبيض",
  "image": "/assets/photos/azal/items/item-053.jpeg",
  "price": 250,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فاصوليا بالبيض",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-54",
  "name": "مشكل فرن",
  "image": "/assets/photos/azal/items/item-054.jpeg",
  "price": 279,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "مشكل فرن",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-55",
  "name": "مشكل خضار",
  "image": "/assets/photos/azal/items/item-055.jfif",
  "price": 270,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "مشكل خضار",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-56",
  "name": "ملوخية سادة",
  "image": "/assets/photos/azal/items/item-056.jpeg",
  "price": 270,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "ملوخية سادة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-57",
  "name": "تونة حرضة",
  "image": "/assets/photos/azal/items/item-057.jpeg",
  "price": 275,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "تونة حرضة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-58",
  "name": "فول حرضة",
  "image": "/assets/photos/azal/items/item-058.jpeg",
  "price": 229,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فول حرضة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-59",
  "name": "شكشوكة",
  "image": "/assets/photos/azal/items/item-059.jpeg",
  "price": 229,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "شكشوكة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-60",
  "name": "أومليت",
  "image": "/assets/photos/azal/items/item-060.jpeg",
  "price": 150,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "أومليت",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-61",
  "name": "فحسة",
  "image": "/assets/photos/azal/items/item-061.jpeg",
  "price": 450,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فحسة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-62",
  "name": "خبز ملوح",
  "image": "/assets/photos/azal/items/item-062.jpeg",
  "price": 65,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "خبز ملوح",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-63",
  "name": "خبز ملوح دبل",
  "image": "/assets/photos/azal/items/item-063.jpeg",
  "price": 95,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "خبز ملوح دبل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-64",
  "name": "خبز رطب",
  "image": "/assets/photos/azal/items/item-064.jpeg",
  "price": 75,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "خبز رطب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-65",
  "name": "خبز رطب بالعسل",
  "image": "/assets/photos/azal/items/item-065.jpeg",
  "price": 95,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "خبز رطب بالعسل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-66",
  "name": "عريكة عادي",
  "image": "/assets/photos/azal/items/item-066.jpeg",
  "price": 210,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "عريكة عادي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-67",
  "name": "عريكة ملكي",
  "image": "/assets/photos/azal/items/item-067.jpeg",
  "price": 220,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "عريكة ملكي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-68",
  "name": "معصوب",
  "image": "/assets/photos/azal/items/item-068.jpeg",
  "price": 210,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "معصوب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-69",
  "name": "معصوب ملكي",
  "image": "/assets/photos/azal/items/item-069.jpeg",
  "price": 220,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "معصوب ملكي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-70",
  "name": "فتة تمر",
  "image": "/assets/photos/azal/items/item-070.jpeg",
  "price": 185,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "فتة تمر",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-71",
  "name": "فتة موز",
  "image": "/assets/photos/azal/items/item-071.jpeg",
  "price": 185,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "فتة موز",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-72",
  "name": "فتة عسل",
  "image": "/assets/photos/azal/items/item-072.jpeg",
  "price": 175,
  "unit": "",
  "category": "المخبوزات",
  "available": true,
  "featured": false,
  "description": "فتة عسل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-73",
  "name": "تفاح",
  "image": "/assets/photos/azal/items/item-073.jpeg",
  "price": 85,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "تفاح",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-74",
  "name": "تفاح اخضر",
  "image": "/assets/photos/azal/items/item-074.jpeg",
  "price": 85,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "تفاح اخضر",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-75",
  "name": "كيوي سادة",
  "image": "/assets/photos/azal/items/item-075.jpeg",
  "price": 130,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "كيوي سادة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-76",
  "name": "كيوي بالاناناس",
  "image": "/assets/photos/azal/items/item-076.png",
  "price": 140,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "كيوي بالاناناس",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-77",
  "name": "فراولة",
  "image": "/assets/photos/azal/items/item-077.jpeg",
  "price": 150,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "فراولة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-78",
  "name": "فراولة بالحليب",
  "image": "/assets/photos/azal/items/item-078.png",
  "price": 159,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "فراولة بالحليب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-79",
  "name": "بطيخ",
  "image": "/assets/photos/azal/items/item-079.png",
  "price": 99,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "بطيخ",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-80",
  "name": "مانغو",
  "image": "/assets/photos/azal/items/item-080.jpeg",
  "price": 165,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "مانغو",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-81",
  "name": "مانجو بالحليب",
  "image": "/assets/photos/azal/items/item-081.png",
  "price": 169,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "مانجو بالحليب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-82",
  "name": "مانجو بالموز",
  "image": "/assets/photos/azal/items/item-082.jpeg",
  "price": 165,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "مانجو بالموز",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-83",
  "name": "زنجبيل",
  "image": "/assets/photos/azal/items/item-083.png",
  "price": 100,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "زنجبيل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-84",
  "name": "زنجبيل بالعسل",
  "image": "/assets/photos/azal/items/item-084.png",
  "price": 110,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "زنجبيل بالعسل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-85",
  "name": "زنجبيل بالحليب",
  "image": "/assets/photos/azal/items/item-085.png",
  "price": 120,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "زنجبيل بالحليب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-86",
  "name": "عرائسي",
  "image": "/assets/photos/azal/items/item-086.jpeg",
  "price": 250,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "عرائسي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-87",
  "name": "كوكتيل",
  "image": "/assets/photos/azal/items/item-087.jpeg",
  "price": 170,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "كوكتيل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-88",
  "name": "ليمون بالحليب",
  "image": "/assets/photos/azal/items/item-088.png",
  "price": 140,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "ليمون بالحليب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-89",
  "name": "ليمون",
  "image": "/assets/photos/azal/items/item-089.jpeg",
  "price": 130,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "ليمون",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-90",
  "name": "برتقال",
  "image": "/assets/photos/azal/items/item-090.jpeg",
  "price": 160,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "برتقال",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-91",
  "name": "موز بالحليب",
  "image": "/assets/photos/azal/items/item-091.png",
  "price": 130,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "موز بالحليب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-92",
  "name": "افوكادو بالحليب",
  "image": "/assets/photos/azal/items/item-092.png",
  "price": 179,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "افوكادو بالحليب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-93",
  "name": "افوكادو بالحليب و العسل",
  "image": "/assets/photos/azal/items/item-093.jpeg",
  "price": 185,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "افوكادو بالحليب و العسل",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-94",
  "name": "شاي احمر",
  "image": "/assets/photos/azal/items/item-094.jpeg",
  "price": 20,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "شاي احمر",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-95",
  "name": "شاي احمر يمني",
  "image": "/assets/photos/azal/items/item-095.jpeg",
  "price": 30,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "شاي احمر يمني",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-96",
  "name": "شاي عدني",
  "image": "/assets/photos/azal/items/item-096.png",
  "price": 60,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "شاي عدني",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-97",
  "name": "شاي كرك",
  "image": "/assets/photos/azal/items/item-097.png",
  "price": 60,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "شاي كرك",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-98",
  "name": "كولا تركية",
  "image": "/assets/photos/azal/items/item-098.png",
  "price": 70,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "كولا تركية",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-99",
  "name": "عيران",
  "image": "/assets/photos/azal/items/item-099.png",
  "price": 40,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "عيران",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-100",
  "name": "ماء صغير",
  "image": "/assets/photos/azal/items/item-100.png",
  "price": 15,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "ماء صغير",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-101",
  "name": "نعناع سادة",
  "image": "/assets/photos/azal/items/item-101.png",
  "price": 25,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "نعناع سادة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-102",
  "name": "قهوة تركي",
  "image": "/assets/photos/azal/items/item-102.jpeg",
  "price": 80,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "قهوة تركي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-103",
  "name": "قهوة يمني",
  "image": "/assets/photos/azal/items/item-103.png",
  "price": 85,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "قهوة يمني",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "azal-104",
  "name": "بن بالحليب",
  "image": "/assets/photos/azal/items/item-104.png",
  "price": 90,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "بن بالحليب",
  "imageFit": "cover",
  "options": []
 }
];

const azalProducts = azalProductCatalog.map((product, index) => ({
  ...product,
  id: 34001 + index,
  storeId: azalStore.id
}));

const azalDeliverySettings = {
  [azalStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
