// Generated for مطعم بيت الشام (Beyt Al-Sham) — Kavaklı, Beylikdüzü, İstanbul.
// Source: WooCommerce Store API (https://beyt-alsham.com/). Tagline: الطعم الشامي الأصيل.
// NOTE: beytProductCatalog is intentionally emptied in the repo (perf) — the full
// catalog lives in Supabase and is pushed via scripts/_scrape/push-store.cjs.
const beytStore = {
 "id": 53,
 "name": "مطعم بيت الشام",
 "category": "مطاعم",
 "image": "/assets/photos/beyt/cover.jpg",
 "coverImage": "/assets/photos/beyt/cover.jpg",
 "logoImage": "/assets/photos/beyt/logo.png",
 "logo": "ب",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "45 - 75 دقيقة",
 "distance": 0,
 "location": {
  "lat": 40.98469,
  "lng": 28.66006
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=40.98469,28.66006",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "مطعم بيت الشام — الطعم الشامي الأصيل. شاورما عربي ودجاج، مناسف ومشاوي شرقية، شاميات (فلافل وحمص وفول)، أطباق غربية (شرحات وشيش طاووك وفيليه سمك وبطاطا)، مع مقبلات وسلطات وشوربات ومشروبات. في بيليك دوزو بإسطنبول — طازج ويصل إلى بابك.",
 "address": "إبراهيم متفرّقة جادّيسي، حي كافاكلي، بيليك دوزو، إسطنبول، تركيا",
 "phone": "+90 539 743 97 99",
 "whatsapp": "+90 539 743 97 99",
 "email": "",
 "website": "https://beyt-alsham.com/",
 "sourceUrl": "https://beyt-alsham.com/",
 "hours": "يومياً",
 "areas": [
  "بيليك دوزو",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

// Full catalog used ONLY for the Supabase push; emptied in the committed repo.
const beytFullCatalog = [
 {"name":"سلطة سيزر Caesar salad","price":350,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1851.jpg","description":""},
 {"name":"وجبة شاورما توشكا","price":340,"category":"قسم الشاورما","unit":"وجبة","image":"/assets/photos/beyt/item-1848.jpg","description":""},
 {"name":"شاورما بيت الشام العائلية","price":1150,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1846.jpg","description":""},
 {"name":"منسف رادني لحم","price":750,"category":"القسم الشرقي","unit":"طبق","image":"/assets/photos/beyt/item-1844.jpg","description":""},
 {"name":"شاورما عربي","price":250,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1810.jpg","description":""},
 {"name":"سبرينغ رول","price":50,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1839.jpg","description":""},
 {"name":"شوربة دجاج","price":175,"category":"المقبلات والمشروبات","unit":"صحن","image":"/assets/photos/beyt/item-1837.jpg","description":""},
 {"name":"شوربة ذرة","price":175,"category":"المقبلات والمشروبات","unit":"صحن","image":"/assets/photos/beyt/item-1835.jpg","description":""},
 {"name":"شوربة عدس","price":150,"category":"المقبلات والمشروبات","unit":"صحن","image":"/assets/photos/beyt/item-1833.jpg","description":""},
 {"name":"سلطة سيزر","price":200,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1831.jpg","description":""},
 {"name":"سلطة تونة","price":200,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1829.jpg","description":""},
 {"name":"كولسلو","price":150,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1827.jpg","description":""},
 {"name":"سلطة جرجير","price":170,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1825.jpg","description":""},
 {"name":"سلطة خضراء","price":170,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1823.jpg","description":""},
 {"name":"صحن بطاطا","price":150,"category":"القسم الغربي","unit":"صحن","image":"/assets/photos/beyt/item-1822.jpg","description":"","options":[{"name":"الحجم","values":["صغير","وسط","كبير"],"extra":[0,0,100]}]},
 {"name":"شيش طاووق","price":400,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1819.jpg","description":""},
 {"name":"شرحات مطفاية لحمة","price":550,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1817.jpg","description":""},
 {"name":"شرحات مطفاية دجاج","price":450,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1815.jpg","description":""},
 {"name":"فيليه سمك","price":450,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1813.jpg","description":""},
 {"name":"ماء","price":20,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1782.jpg","description":""},
 {"name":"ايس تي","price":45,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1780.jpg","description":""},
 {"name":"زيرو تورکا","price":80,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1779.jpg","description":""},
 {"name":"توركا فانتا","price":45,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1777.jpg","description":""},
 {"name":"توركا كولا","price":70,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1775.jpg","description":""},
 {"name":"صودا","price":40,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1773.jpg","description":""},
 {"name":"شاي","price":25,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1771.jpg","description":""},
 {"name":"عيران","price":50,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1769.jpg","description":""},
 {"name":"يلانجي","price":150,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1767.jpg","description":""},
 {"name":"بوريك لحمة","price":60,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1765.jpg","description":""},
 {"name":"بوريك جبنة","price":50,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1763.jpg","description":""},
 {"name":"فتوش","price":170,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1761.jpg","description":""},
 {"name":"تبولة","price":170,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1759.jpg","description":""},
 {"name":"سلطة روسية","price":150,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1757.jpg","description":""},
 {"name":"سلطة شرقية","price":150,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1755.jpg","description":""},
 {"name":"شورية فطر","price":150,"category":"المقبلات والمشروبات","unit":"مشروب","image":"/assets/photos/beyt/item-1753.jpg","description":""},
 {"name":"صحن رز كبسة أو مندي","price":150,"category":"القسم الشرقي","unit":"صحن","image":"/assets/photos/beyt/item-1751.jpg","description":""},
 {"name":"وجبة كبسة ربع دجاجة","price":275,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1749.jpg","description":""},
 {"name":"وجية كيسة نصف دجاجة","price":400,"category":"القسم الشرقي","unit":"طبق","image":"/assets/photos/beyt/item-1747.jpg","description":""},
 {"name":"وجبة كبسة دجاجة كاملة","price":650,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1745.jpg","description":""},
 {"name":"وجبة مندي ربع دجاجة","price":250,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1743.jpg","description":""},
 {"name":"وجبة مندي نصف دجاجة","price":350,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1741.jpg","description":""},
 {"name":"وجبة مندي دجاجة كاملة","price":650,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1739.jpg","description":""},
 {"name":"وجبة مندي لحمة","price":625,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1737.jpg","description":""},
 {"name":"وجبة كبسة لحمة","price":625,"category":"القسم الشرقي","unit":"وجبة","image":"/assets/photos/beyt/item-1735.jpg","description":""},
 {"name":"ورق عنب مع شرحات","price":590,"category":"القسم الشرقي","unit":"طبق","image":"/assets/photos/beyt/item-1733.jpg","description":""},
 {"name":"كبة مشوية","price":140,"category":"القسم الشرقي","unit":"طبق","image":"/assets/photos/beyt/item-1731.jpg","description":""},
 {"name":"كبة لبنية","price":375,"category":"القسم الشرقي","unit":"طبق","image":"/assets/photos/beyt/item-1729.jpg","description":""},
 {"name":"كبة مقلية غنم","price":100,"category":"القسم الشرقي","unit":"طبق","image":"/assets/photos/beyt/item-1727.jpg","description":""},
 {"name":"كيلو شاورما","price":990,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1719.jpg","description":""},
 {"name":"شاورما فرط","price":340,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1716.jpg","description":"","options":[{"name":"الحجم","values":["وجبة","نصف كيلو"],"extra":[0,160]}]},
 {"name":"شاورما اصابع","price":450,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1714.jpg","description":""},
 {"name":"شاورما عربي اكسترا","price":340,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1712.jpg","description":""},
 {"name":"شاورما عربي ديل","price":380,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1710.jpg","description":""},
 {"name":"شاورما عربي","price":190,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1707.jpg","description":""},
 {"name":"شاورما صغير","price":90,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1705.jpg","description":""},
 {"name":"شاورما صمون","price":170,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1703.jpg","description":""},
 {"name":"ساندویش شاورما دبل","price":170,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1702.jpg","description":""},
 {"name":"ساندویش شاورما","price":140,"category":"قسم الشاورما","unit":"طبق","image":"/assets/photos/beyt/item-1699.jpg","description":""},
 {"name":"فتة باللحمة","price":480,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1696.jpg","description":""},
 {"name":"فتة بالمكسرات","price":280,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1694.jpg","description":""},
 {"name":"فتة زيت","price":260,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1692.jpg","description":""},
 {"name":"فتة سمنة","price":175,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1690.jpg","description":""},
 {"name":"صحن متبل","price":150,"category":"قسم الشاميات","unit":"صحن","image":"/assets/photos/beyt/item-1688.jpg","description":""},
 {"name":"حمص ناعم","price":150,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1686.jpg","description":""},
 {"name":"حمص حب بطحينة","price":175,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1684.jpg","description":""},
 {"name":"حمص حب بالزيت","price":175,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1682.jpg","description":""},
 {"name":"فول بطحينة","price":175,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1680.jpg","description":""},
 {"name":"فول بالزيت","price":175,"category":"قسم الشاميات","unit":"طبق","image":"/assets/photos/beyt/item-1678.jpg","description":""},
 {"name":"وجبة فلافل","price":150,"category":"قسم الشاميات","unit":"وجبة","image":"/assets/photos/beyt/item-1677.jpg","description":"","options":[{"name":"الحجم","values":["8 أقراص","كبيرة"],"extra":[0,70]}]},
 {"name":"وجبة فلافل عربي","price":240,"category":"قسم الشاميات","unit":"وجبة","image":"/assets/photos/beyt/item-1675.jpg","description":""},
 {"name":"ساندويش فلافل دبل","price":140,"category":"قسم الشاميات","unit":"ساندويش","image":"/assets/photos/beyt/item-1671.jpg","description":""},
 {"name":"ساندويش فلافل","price":120,"category":"قسم الشاميات","unit":"ساندويش","image":"/assets/photos/beyt/item-1669.jpg","description":""},
 {"name":"وجبة دبابيس مقلية","price":400,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1663.jpg","description":""},
 {"name":"وجبة بروستد","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1660.jpg","description":""},
 {"name":"وجبة كوردون بلو","price":450,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1658.jpg","description":""},
 {"name":"وجبة سوبريم","price":450,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1656.jpg","description":""},
 {"name":"وجبة سكالوب بالجبنة","price":390,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1654.jpg","description":""},
 {"name":"وجية سكالوب","price":350,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1652.jpg","description":""},
 {"name":"وجبة زنجر","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1650.jpg","description":""},
 {"name":"وجبة كرانشي","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1648.jpg","description":""},
 {"name":"وجبة كريسي","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1645.jpg","description":""},
 {"name":"وجبة فرانشيسكو","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1643.jpg","description":""},
 {"name":"وجبة مكسيكانو","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1641.jpg","description":""},
 {"name":"وجبة فاهيتا","price":350,"category":"القسم الغربي","unit":"وجبة","image":"/assets/photos/beyt/item-1639.jpg","description":""},
 {"name":"برغر دجاج","price":290,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1637.jpg","description":""},
 {"name":"برغر لحم","price":400,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1635.jpg","description":""},
 {"name":"ساندويش بطاطا","price":140,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1632.jpg","description":"","options":[{"name":"الإضافة","values":["بدون جبنة","مع جبنة"],"extra":[0,10]}]},
 {"name":"ساندویش سوبریم","price":250,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1630.jpg","description":""},
 {"name":"ساندویش سكالوب بالجبنة","price":220,"category":"القسم الغربي","unit":"طبق","image":"/assets/photos/beyt/item-1628.jpg","description":""},
 {"name":"ساندويش سكالوب","price":220,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1626.jpg","description":""},
 {"name":"ساندويش زنجر","price":230,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1624.jpg","description":""},
 {"name":"ساندويش كرانشي","price":220,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1621.jpg","description":""},
 {"name":"ساندويش كريسبي","price":230,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1619.jpg","description":""},
 {"name":"ساندويش فرانسيسكو","price":220,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1617.jpg","description":""},
 {"name":"ساندويش مكسيكانو","price":230,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1615.jpg","description":""},
 {"name":"ساندويش فاهيتا","price":240,"category":"القسم الغربي","unit":"ساندويش","image":"/assets/photos/beyt/item-1613.jpg","description":""}
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const beytProductCatalog = [];

const beytProducts = (beytProductCatalog.length ? beytProductCatalog : beytFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1370001 + index,
  storeId: beytStore.id
}));

const beytDeliverySettings = {
  [beytStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 35, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { beytStore, beytProducts, beytDeliverySettings };
}
