// Generated for مطعم بايت هاوس (BiteHaus) — Esenyurt, Istanbul. Source: bitehaus.minidine.com (minidine)
const bitehausStore = {
 "id": 25,
 "name": "مطعم بايت هاوس",
 "category": "مطاعم",
 "image": "/assets/photos/bitehaus/cover.png",
 "coverImage": "/assets/photos/bitehaus/cover.png",
 "logoImage": "/assets/photos/bitehaus/logo.png",
 "logo": "ب",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "40 - 70 دقيقة",
 "distance": 17,
 "location": {
  "lat": 41.0103227,
  "lng": 28.6808228
 },
 "mapUrl": "https://maps.app.goo.gl/PSw2uBK3TxYLdsxQ9",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم بايت هاوس (BiteHaus) في إسنيورت بإسطنبول: الوجبات والساندويتش والبرجر والبيتزا والشاورما والراب والريزو وأطباق البيت الخاصة، مع الصوصات والإضافات والمشروبات. أسماء الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
 "address": "Near, Zafer, 175. Sk., 34513 Esenyurt/İstanbul، إسطنبول، تركيا",
 "phone": "+90 531 747 02 30",
 "whatsapp": "+90 531 747 02 30",
 "email": "",
 "website": "https://bitehaus.minidine.com/ar/categories/?branch=bitehaus",
 "sourceUrl": "https://bitehaus.minidine.com/ar/categories/?branch=bitehaus",
 "hours": "يومياً 12:30 ظهراً – 11:30 مساءً (الجمعة من 12:00 ظهراً)",
 "areas": [
  "إسنيورت",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const bitehausProductCatalog = [
 {
  "sourceId": "5389e0b9-867f-4c2b-bc8f-4c49d038fa82",
  "name": "Zinger sweet chilli meal",
  "image": "/assets/photos/bitehaus/items/item-001.jpeg",
  "price": 345,
  "unit": "",
  "category": "الوجبات",
  "available": true,
  "featured": false,
  "description": "Zinger sweet chilli meal من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "5c747db6-180e-48a8-b225-b0e7e32c5c00",
  "name": "باربيكيو بايت هاوس سناك",
  "image": "/assets/photos/bitehaus/items/item-002.jpeg",
  "price": 415,
  "unit": "",
  "category": "الوجبات",
  "available": true,
  "featured": false,
  "description": "باربيكيو بايت هاوس سناك من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "75b141c1-6472-4329-a24e-0637a28aebb0",
  "name": "bitehaus snack calssic",
  "image": "/assets/photos/bitehaus/items/item-003.jpeg",
  "price": 400,
  "unit": "",
  "category": "الوجبات",
  "available": true,
  "featured": false,
  "description": "bitehaus snack calssic من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "0498511b-f5ee-4062-ae61-93714bc3537f",
  "name": "BBQ tender meal",
  "image": "/assets/photos/bitehaus/items/item-004.jpeg",
  "price": 345,
  "unit": "",
  "category": "الوجبات",
  "available": true,
  "featured": false,
  "description": "BBQ tender meal من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "c3d5ff75-ecc7-4325-b688-2ac1aa9a1675",
  "name": "tinder meal",
  "image": "/assets/photos/bitehaus/items/item-005.jpeg",
  "price": 335,
  "unit": "",
  "category": "الوجبات",
  "available": true,
  "featured": false,
  "description": "tinder meal من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4a3c7e47-e4cb-40af-9ac2-60f097aa2c0a",
  "name": "Tender sandwich",
  "image": "/assets/photos/bitehaus/items/item-006.jpeg",
  "price": 245,
  "unit": "",
  "category": "الساندويتش",
  "available": true,
  "featured": false,
  "description": "Tender sandwich من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "98819940-1a20-40e7-bb42-853b82b73596",
  "name": "Hot mexican sandwich",
  "image": "/assets/photos/bitehaus/items/item-007.jpeg",
  "price": 245,
  "unit": "",
  "category": "الساندويتش",
  "available": true,
  "featured": false,
  "description": "Hot mexican sandwich من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f0862df1-f656-4d5a-a31e-0d800bce1f79",
  "name": "Fajita sandwich",
  "image": "/assets/photos/bitehaus/items/item-008.jpeg",
  "price": 245,
  "unit": "",
  "category": "الساندويتش",
  "available": true,
  "featured": false,
  "description": "Fajita sandwich من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "3eda618f-0f54-4f1a-947e-d1698e392b4d",
  "name": "Cheddar potato sandwich",
  "image": "/assets/photos/bitehaus/items/item-009.jpeg",
  "price": 180,
  "unit": "",
  "category": "الساندويتش",
  "available": true,
  "featured": false,
  "description": "Cheddar potato sandwich من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "7d3326d3-edbb-46c0-94eb-ad058211d3ba",
  "name": "Zinger sandwich",
  "image": "/assets/photos/bitehaus/items/item-010.jpeg",
  "price": 245,
  "unit": "",
  "category": "الساندويتش",
  "available": true,
  "featured": false,
  "description": "Zinger sandwich من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f04db40b-be63-4a0b-b6e9-190fc0c38698",
  "name": "dynamite burger",
  "image": "/assets/photos/bitehaus/items/item-011.jpeg",
  "price": 360,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "tender burger zinger dynamite with potato and dynamite + sweet chili +bitehaus  +cheddar sauces",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "45715b09-1fff-4a54-872c-f1d36b6caf08",
  "name": "sweet chili tender burger",
  "image": "/assets/photos/bitehaus/items/item-012.jpeg",
  "price": 350,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "sweet chili tender burger and potato with sweet chili sauce",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f277f6ee-d119-4e8f-9b9c-28cd0e25b94f",
  "name": "تيندر برغر",
  "image": "/assets/photos/bitehaus/items/item-013.jpeg",
  "price": 345,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "تيندر برغر من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "302b13cc-d58f-496f-9c06-2d471b618103",
  "name": "honey cheddar tender burger",
  "image": "/assets/photos/bitehaus/items/item-014.jpeg",
  "price": 360,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "honey cheddar tender burger with potato and honey +cheddar sauces",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "2c79b8e7-d580-4f09-a225-3d6b63ac64af",
  "name": "smash burjer",
  "image": "/assets/photos/bitehaus/items/item-015.jpeg",
  "price": 420,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "smash burjer من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "e60f3532-4a99-4ee1-afaf-bd1b6de2fcad",
  "name": "BBQ Tender burger",
  "image": "/assets/photos/bitehaus/items/item-016.jpeg",
  "price": 360,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "BBQ tender burger with potato and BQQ sauce",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "e414625e-a433-46f7-a518-4fd555738e81",
  "name": "calssic tender burger",
  "image": "/assets/photos/bitehaus/items/item-017.jpeg",
  "price": 340,
  "unit": "",
  "category": "البرجر",
  "available": true,
  "featured": false,
  "description": "tender burger with potato and bitehaus sauce",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "22ca9080-c7fd-45c0-aa91-56e1c340cf5b",
  "name": "شاورما بيتزا كبير",
  "image": "/assets/photos/bitehaus/items/item-018.jpeg",
  "price": 650,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "شاورما بيتزا كبير من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ed12b3d9-c358-433b-8167-45e2a49a42f2",
  "name": "Hot mexican Pizza",
  "image": "/assets/photos/bitehaus/items/item-019.jpeg",
  "price": 420,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "Hot mexican Pizza من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "2d1ac305-13f4-49d8-8ed1-690b1f51c195",
  "name": "TRIPLE CHEASE PIZZA LARGE",
  "image": "/assets/photos/bitehaus/items/item-020.jpeg",
  "price": 570,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "TRIPLE CHEASE PIZZA LARGE من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "8fac2181-6384-40c6-a43d-890166f1c090",
  "name": "Fajita pizza",
  "image": "/assets/photos/bitehaus/items/item-021.jpeg",
  "price": 410,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "Fajita pizza من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "6dee744a-4aa3-4989-9603-2cb03dae3b3f",
  "name": "PEPPORENI PIZZA LARGE",
  "image": "/assets/photos/bitehaus/items/item-022.jpeg",
  "price": 470,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "PEPPORENI PIZZA LARGE من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "d5905669-0756-44b9-9bc1-ca59464c5cba",
  "name": "crunchy pizza LARGE",
  "image": "/assets/photos/bitehaus/items/item-023.jpeg",
  "price": 495,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "crunchy pizza LARGE من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "5c3cd292-7fba-4c2c-b2f4-634cad1a8895",
  "name": "Vegetable pizza",
  "image": "/assets/photos/bitehaus/items/item-024.jpeg",
  "price": 395,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "Vegetable pizza من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ab460424-69fe-4218-9175-ef3da6f459c5",
  "name": "Margarita pizza",
  "image": "/assets/photos/bitehaus/items/item-025.jpeg",
  "price": 390,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "Margarita pizza من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4a820f00-5e33-4123-89a3-c1d5cf45120e",
  "name": "BBQ CHICKEN PIZZA LARGE",
  "image": "/assets/photos/bitehaus/items/item-026.jpeg",
  "price": 495,
  "unit": "",
  "category": "البيتزا",
  "available": true,
  "featured": false,
  "description": "BBQ CHICKEN PIZZA LARGE من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dbe0f42b-ddbe-4b8f-b80c-12974f708205",
  "name": "Nuggets 7 pieces",
  "image": "/assets/photos/bitehaus/items/item-027.jpeg",
  "price": 150,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "Nuggets 7 pieces من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "91512b57-e65d-4457-9815-4d79b400d25b",
  "name": "spicy cheddar potato",
  "image": "/assets/photos/bitehaus/items/item-028.jpeg",
  "price": 180,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "spicy cheddar potato من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dc171bd5-84db-4387-889c-e84911137e03",
  "name": "Onion rings",
  "image": "/assets/photos/bitehaus/items/item-029.jpeg",
  "price": 150,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "Onion rings من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "76ba966f-695b-44f7-9e27-1a56f3e16bbf",
  "name": "cheddar bitehaus potato",
  "image": "/assets/photos/bitehaus/items/item-030.jpeg",
  "price": 210,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "cheddar bitehaus potato من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "081a501e-8a4a-46de-8098-bc70bd24d7fb",
  "name": "smul potatoe",
  "image": "/assets/photos/bitehaus/items/item-031.jpg",
  "price": 130,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "smul potatoe من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "420b775f-8b8e-43f8-a2b2-36151b91cc71",
  "name": "اصابع موزريلا 7 قطع",
  "image": "/assets/photos/bitehaus/items/item-032.jpeg",
  "price": 150,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "اصابع موزريلا 7 قطع من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "61c50de8-2eaf-4ec9-a051-95ae8cfdcfb7",
  "name": "honey cheddar potato",
  "image": "/assets/photos/bitehaus/items/item-033.jpeg",
  "price": 180,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "honey cheddar potato من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "45800189-f451-433d-89de-86173d274a8f",
  "name": "Potato add-on",
  "image": "/assets/photos/bitehaus/items/item-034.jpeg",
  "price": 20,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "Potato add-on من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4f8f5b48-a242-4461-854a-ff809d5ea786",
  "name": "Large potatoe",
  "image": "/assets/photos/bitehaus/items/item-035.jpg",
  "price": 160,
  "unit": "",
  "category": "الاضافات",
  "available": true,
  "featured": false,
  "description": "Large potatoe من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "86648274-ca2c-41d9-b0dc-1c12dc0ad4bc",
  "name": "شاورما عائلي 3 اشخاص",
  "image": "/assets/photos/bitehaus/items/item-036.jpg",
  "price": 1075,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما عائلي 3 اشخاص من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "57794532-6382-4106-91ce-7a371636e007",
  "name": "شاورما شرائح 250 غرام",
  "image": "/assets/photos/bitehaus/items/item-037.jpg",
  "price": 400,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما شرائح 250 غرام من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "43e2651b-1016-4755-a0d9-31f9e20c992e",
  "name": "شاورما عربي",
  "image": "/assets/photos/bitehaus/items/item-038.jpeg",
  "price": 270,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما عربي من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "51384009-8481-4547-8cd8-d7c6a1fc6ea8",
  "name": "شاورما ساندويتش",
  "image": "/assets/photos/bitehaus/items/item-039.jpeg",
  "price": 175,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما ساندويتش من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4ade5f15-d905-422f-a048-f213be9c9d92",
  "name": "شاورما ساندويتش دبل",
  "image": "/assets/photos/bitehaus/items/item-040.jpeg",
  "price": 250,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما ساندويتش دبل من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f4eab68d-87a8-4b77-96cc-0867e0f41b92",
  "name": "شاورما خبز صمون",
  "image": "/assets/photos/bitehaus/items/item-041.jpeg",
  "price": 220,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما خبز صمون من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "6cac905d-d335-43bf-8bdf-33ca239c0b45",
  "name": "شاورما شرائح 1000 غرام",
  "image": "/assets/photos/bitehaus/items/item-042.jpeg",
  "price": 1100,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما شرائح 1000 غرام من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "c493a969-8b28-4515-94f6-bcc71b6c5ed5",
  "name": "شاورما شرائح مع رز",
  "image": "/assets/photos/bitehaus/items/item-043.jpeg",
  "price": 350,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما شرائح مع رز من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "8ddbb6b2-e0cd-460c-bd71-03dc39cb3102",
  "name": "شاورما عربي دبل",
  "image": "/assets/photos/bitehaus/items/item-044.jpeg",
  "price": 395,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما عربي دبل من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "61ede442-abbb-4a78-81bd-e84d140bb8ce",
  "name": "شاورما عربي اكسترا",
  "image": "/assets/photos/bitehaus/items/item-045.jpeg",
  "price": 360,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما عربي اكسترا من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "a1a46d81-77b2-41b1-b153-53789ebeb16f",
  "name": "شاورما سوبر  1/5",
  "image": "/assets/photos/bitehaus/cover.png",
  "price": 370,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما سوبر  1/5 من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "a79d7d63-fbe3-4b6e-b43a-bf00f8bdd791",
  "name": "شاورما خبز صاج",
  "image": "/assets/photos/bitehaus/items/item-047.jpeg",
  "price": 195,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما خبز صاج من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "d720aae8-8cc9-4481-9c46-160b466edaf4",
  "name": "شاورما عائلي 5 اشخاص",
  "image": "/assets/photos/bitehaus/items/item-048.jpeg",
  "price": 1300,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما عائلي 5 اشخاص من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "77c15a75-e55c-4274-805b-92e4c8430b30",
  "name": "شاورما شرائح 500 غرام",
  "image": "/assets/photos/bitehaus/items/item-049.jpg",
  "price": 550,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما شرائح 500 غرام من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "5f9acd7b-f34b-4b01-a737-ad4b89ee6449",
  "name": "شاورما بانيه",
  "image": "/assets/photos/bitehaus/items/item-050.jpeg",
  "price": 395,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما بانيه من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "348a1bc3-130e-4284-ba0e-ba4065500588",
  "name": "شاورما اصابع",
  "image": "/assets/photos/bitehaus/items/item-051.jpeg",
  "price": 100,
  "unit": "",
  "category": "الشاورما",
  "available": true,
  "featured": false,
  "description": "شاورما اصابع من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "8e7fa437-d082-423f-a195-423ae5c62364",
  "name": "اصافه فطر",
  "image": "/assets/photos/bitehaus/items/item-052.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "اصافه فطر من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "6444972a-63af-438d-8c59-ed7a26df8f09",
  "name": "Dynamite sauce",
  "image": "/assets/photos/bitehaus/items/item-053.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Dynamite sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "8ec063b9-a342-4f8a-b037-49ca0bd20403",
  "name": "Honey cheddar sauce",
  "image": "/assets/photos/bitehaus/items/item-054.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Honey cheddar sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "0992144d-6a98-47df-bf2e-fd13dcf82f6b",
  "name": "BBQ Sauce",
  "image": "/assets/photos/bitehaus/items/item-055.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "BBQ Sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1cbf5cbe-4d84-427a-a226-129b555a84ba",
  "name": "Garlic sauce 250gr",
  "image": "/assets/photos/bitehaus/items/item-056.jpeg",
  "price": 110,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Garlic sauce 250gr من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1fb83ce2-9393-433d-96a5-334179afccb0",
  "name": "BiteHaus Sauce",
  "image": "/assets/photos/bitehaus/items/item-057.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "BiteHaus Sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "e4970f91-df30-44cd-872f-c783e4aaa5ef",
  "name": "ketchup with honey sauce",
  "image": "/assets/photos/bitehaus/items/item-058.jpeg",
  "price": 0,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "ketchup with honey sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "5ae22e0b-e1dd-4ab4-a58d-8a083f371e14",
  "name": "Sweet chilli sauce",
  "image": "/assets/photos/bitehaus/items/item-059.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Sweet chilli sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4601b998-7f93-4ee3-84f7-da2659490cea",
  "name": "Cheddar add-on",
  "image": "/assets/photos/bitehaus/items/item-060.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Cheddar add-on من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "875749e5-ac87-4f54-bec5-13d4f4bcc1a5",
  "name": "Garlic sauce 150g",
  "image": "/assets/photos/bitehaus/items/item-061.jpeg",
  "price": 70,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Garlic sauce 150g من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "d255e42f-a00f-4b89-8de8-3dffc1652bcd",
  "name": "Mozzarella add-on",
  "image": "/assets/photos/bitehaus/items/item-062.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Mozzarella add-on من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4cdd9e4b-bf8e-42d9-8e4d-d0dca4f6358a",
  "name": "Cheddar sauce",
  "image": "/assets/photos/bitehaus/items/item-063.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Cheddar sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1f13daad-4ad0-460d-96f4-c8a6e39a0422",
  "name": "Garlic sauce",
  "image": "/assets/photos/bitehaus/items/item-064.jpeg",
  "price": 30,
  "unit": "",
  "category": "الصوصات",
  "available": true,
  "featured": false,
  "description": "Garlic sauce من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4a6b80f7-b5e0-4bb5-9f75-43c3ca673bc4",
  "name": "Fanta",
  "image": "/assets/photos/bitehaus/items/item-065.jpeg",
  "price": 60,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Fanta من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "97a6aa79-e813-499e-a880-ca195dabab28",
  "name": "صودا توت",
  "image": "/assets/photos/bitehaus/cover.png",
  "price": 45,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "صودا توت من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "0d2cf32b-433b-422f-8c55-903758214bf8",
  "name": "Small ayran",
  "image": "/assets/photos/bitehaus/items/item-067.jpeg",
  "price": 25,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Small ayran من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "9b3c5e10-72c6-4787-8acc-c5fef34afa68",
  "name": "Veneeto",
  "image": "/assets/photos/bitehaus/items/item-068.jpeg",
  "price": 55,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Veneeto من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ffa79397-c531-4295-9f15-4bf2a5cf306f",
  "name": "Large ayran",
  "image": "/assets/photos/bitehaus/items/item-069.jpeg",
  "price": 35,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Large ayran من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "c3d1a3dc-0861-410e-9c3a-8dd9902ddb5f",
  "name": "ببسي",
  "image": "/assets/photos/bitehaus/cover.png",
  "price": 60,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "ببسي من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f6851f4c-30fa-4580-afdc-494d147fed72",
  "name": "Lemonade",
  "image": "/assets/photos/bitehaus/items/item-071.jpeg",
  "price": 45,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Lemonade من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "874404cb-f444-4df9-b563-23102efa4fff",
  "name": "Kola",
  "image": "/assets/photos/bitehaus/items/item-072.jpeg",
  "price": 60,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Kola من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "b89b8596-726e-4f44-81a5-f2383fc8f0ac",
  "name": "صودا ليمون",
  "image": "/assets/photos/bitehaus/cover.png",
  "price": 45,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "صودا ليمون من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "600f184a-9863-4383-bebe-9970f0539220",
  "name": "Water",
  "image": "/assets/photos/bitehaus/items/item-074.jpeg",
  "price": 15,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "Water من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "46f04aac-09f2-4435-a5a9-48711b871e70",
  "name": "bitehaus cheddar snack",
  "image": "/assets/photos/bitehaus/items/item-075.jpeg",
  "price": 410,
  "unit": "",
  "category": "Bite House Special",
  "available": true,
  "featured": false,
  "description": "bitehaus cheddar snack من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "cd866145-777e-41bb-8292-c3bbb955c212",
  "name": "calssic tender wrap",
  "image": "/assets/photos/bitehaus/items/item-076.jpeg",
  "price": 335,
  "unit": "",
  "category": "Bite House Special",
  "available": true,
  "featured": false,
  "description": "calssic tender wrap with potato + cheddar and bitehaus sauces",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "df887b31-3b7f-4801-9557-fc30f01c179b",
  "name": "BBQ Tender snack",
  "image": "/assets/photos/bitehaus/items/item-077.jpeg",
  "price": 345,
  "unit": "",
  "category": "Bite House Special",
  "available": true,
  "featured": false,
  "description": "BBQ Tender snack من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "45b7b6b8-3350-4e8a-a1bf-3a087f44d331",
  "name": "bitehaus sweet chili snack",
  "image": "/assets/photos/bitehaus/items/item-078.jpeg",
  "price": 420,
  "unit": "",
  "category": "Bite House Special",
  "available": true,
  "featured": false,
  "description": "bitehaus sweet chili snack من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "cc1a447b-83fe-4b28-8c50-6a0e301e9a2b",
  "name": "BBQ Bitehaus snack",
  "image": "/assets/photos/bitehaus/items/item-079.jpeg",
  "price": 410,
  "unit": "",
  "category": "Bite House Special",
  "available": true,
  "featured": false,
  "description": "BBQ Bitehaus snack من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "f7f99e68-68ad-423d-9583-fe8539eec59e",
  "name": "rizo BBQ and sweet chilli",
  "image": "/assets/photos/bitehaus/items/item-080.jpeg",
  "price": 345,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo BBQ and sweet chilli من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "cf70d6d5-2f9b-4c00-9912-d7a259d7a6c5",
  "name": "rizo cheddar",
  "image": "/assets/photos/bitehaus/items/item-081.jpeg",
  "price": 345,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo cheddar من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "44493013-6c00-4357-b018-c29239e38260",
  "name": "rizo BBQ",
  "image": "/assets/photos/bitehaus/items/item-082.jpeg",
  "price": 400,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo BBQ من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fa926188-594b-481b-a6b0-a50de4275618",
  "name": "rizo cheddar and sweet chilli",
  "image": "/assets/photos/bitehaus/items/item-083.jpeg",
  "price": 345,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo cheddar and sweet chilli من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "2d64386e-f289-4b9f-b199-d449f318509f",
  "name": "rizo bitehaus special",
  "image": "/assets/photos/bitehaus/items/item-084.jpeg",
  "price": 345,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo bitehaus special من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "d771fa9c-b62a-4a1e-9a62-4576657f5815",
  "name": "rizo sweet chilli",
  "image": "/assets/photos/bitehaus/items/item-085.jpeg",
  "price": 345,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo sweet chilli من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "069e4a69-b12a-4590-90a8-1f9038ee9763",
  "name": "rizo bitehaus and sweet chilli",
  "image": "/assets/photos/bitehaus/items/item-086.jpeg",
  "price": 345,
  "unit": "",
  "category": "الريزو",
  "available": true,
  "featured": false,
  "description": "rizo bitehaus and sweet chilli من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "70549d9b-26c2-428b-8284-8c0b55b2a75d",
  "name": "honey cheddar wrap",
  "image": "/assets/photos/bitehaus/items/item-087.jpeg",
  "price": 335,
  "unit": "",
  "category": "الراب",
  "available": true,
  "featured": false,
  "description": "honey cheddar wrap من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "02df54ef-da0b-43c1-8e4e-4fa6e13d83b3",
  "name": "sweet chilli tender wrap",
  "image": "/assets/photos/bitehaus/items/item-088.jpeg",
  "price": 275,
  "unit": "",
  "category": "الراب",
  "available": true,
  "featured": false,
  "description": "sweet chilli tender wrap من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "a23a6232-1251-4c6f-ad7c-587f64020dd6",
  "name": "classic potato wrap",
  "image": "/assets/photos/bitehaus/items/item-089.jpeg",
  "price": 195,
  "unit": "",
  "category": "الراب",
  "available": true,
  "featured": false,
  "description": "classic potato wrap من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "42ff6e12-efac-4e2c-81d7-9f67c71a9172",
  "name": "classic tender wrap",
  "image": "/assets/photos/bitehaus/items/item-090.jpeg",
  "price": 275,
  "unit": "",
  "category": "الراب",
  "available": true,
  "featured": false,
  "description": "classic tender wrap من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "78887052-73ba-4898-bd6b-b40450e5e135",
  "name": "cheddar potato wrap",
  "image": "/assets/photos/bitehaus/items/item-091.jpeg",
  "price": 200,
  "unit": "",
  "category": "الراب",
  "available": true,
  "featured": false,
  "description": "cheddar potato wrap من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "c11f9a41-94d9-4b7a-8250-b3626444e1bd",
  "name": "BBQ tender wrap",
  "image": "/assets/photos/bitehaus/items/item-092.jpeg",
  "price": 335,
  "unit": "",
  "category": "الراب",
  "available": true,
  "featured": false,
  "description": "BBQ tender wrap من مطعم بايت هاوس.",
  "imageFit": "cover",
  "options": []
 }
];

const bitehausProducts = bitehausProductCatalog.map((product, index) => ({
  ...product,
  id: 36001 + index,
  storeId: bitehausStore.id
}));

const bitehausDeliverySettings = {
  [bitehausStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
