// Generated for حلويات عز الدين (Izz Al-Din Tatlici) — Esenyurt, Istanbul.
const ezzedineStore = {
  "id": 13,
  "name": "حلويات عز الدين",
  "category": "حلويات",
  "image": "/assets/photos/ezzedine/cover.jpg",
  "coverImage": "/assets/photos/ezzedine/cover.jpg",
  "logoImage": "/assets/photos/ezzedine/logo.png",
  "logo": "ع",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 30,
  "minOrder": 250,
  "time": "40 - 60 دقيقة",
  "distance": 22.5,
  "location": {
    "lat": 41.0293,
    "lng": 28.676
  },
  "mapUrl": "https://maps.app.goo.gl/aYg1Qc3ZVrCxqboy7",
  "open": true,
  "featured": true,
  "hasOffer": false,
  "description": "حلويات عز الدين متخصّصة بالحلويات العربية الفاخرة: البقلاوة والوربات بالفستق والقشطة، المعمول والغريبة والبرازق، إضافة إلى الكاتو والتشكيلات العربية، بنكهة عربية أصيلة وجودة عالية.",
  "address": "إنجيرتبه، شارع باغلار تشيشمه رقم 1، إسنيورت، إسطنبول",
  "phone": "+90 555 097 77 93",
  "whatsapp": "+90 555 097 77 93",
  "email": "",
  "website": "",
  "sourceUrl": "https://maps.app.goo.gl/aYg1Qc3ZVrCxqboy7",
  "hours": "يرجى تأكيد أوقات العمل عبر واتساب",
  "areas": [
    "إسنيورت",
    "إسطنبول",
    "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true
};

const ezzedineProductCatalog = [
  {
    "sourceId": "harisa_mikserat",
    "name": "هريسة مكسرات",
    "image": "/assets/photos/ezzedine/products/harisa_mikserat.webp",
    "price": 650,
    "unit": "كيلو",
    "category": "طلبيات يومية",
    "available": true,
    "featured": true,
    "description": "هريسة مكسرات من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "harisa_fistik",
    "name": "هريسة فستق",
    "image": "/assets/photos/ezzedine/products/harisa_fistik.webp",
    "price": 700,
    "unit": "كيلو",
    "category": "طلبيات يومية",
    "available": true,
    "featured": true,
    "description": "هريسة فستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "ajamiyya",
    "name": "عجمية",
    "image": "/assets/photos/ezzedine/products/ajamiyya.webp",
    "price": 540,
    "unit": "كيلو",
    "category": "طلبيات يومية",
    "available": true,
    "featured": false,
    "description": "عجمية من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "namoura",
    "name": "نمورة بالقشطة والفستق",
    "image": "/assets/photos/ezzedine/products/namoura.webp",
    "price": 540,
    "unit": "كيلو",
    "category": "طلبيات يومية",
    "available": true,
    "featured": true,
    "description": "نمورة بالقشطة والفستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "warbat_kashta",
    "name": "وربات قشطة",
    "image": "/assets/photos/ezzedine/products/warbat_kashta.webp",
    "price": 540,
    "unit": "كيلو",
    "category": "طلبيات يومية",
    "available": true,
    "featured": false,
    "description": "وربات قشطة من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "taj_almalik",
    "name": "تاج الملك",
    "image": "/assets/photos/ezzedine/products/taj_almalik.webp",
    "price": 90,
    "unit": "قطعة",
    "category": "طلبيات يومية",
    "available": true,
    "featured": false,
    "description": "تاج الملك من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "halawa_fishta",
    "name": "حلاوة فشطة",
    "image": "/assets/photos/ezzedine/products/halawa_fishta.webp",
    "price": 500,
    "unit": "كيلو",
    "category": "حلويات بالقشطة",
    "available": true,
    "featured": false,
    "description": "حلاوة فشطة من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "halawa_fishta_fistik",
    "name": "حلاوة فشطة وفستق",
    "image": "/assets/photos/ezzedine/products/halawa_fishta_fistik.webp",
    "price": 550,
    "unit": "كيلو",
    "category": "حلويات بالقشطة",
    "available": true,
    "featured": true,
    "description": "حلاوة فشطة وفستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "warbat_halabi",
    "name": "وربات حلبي",
    "image": "/assets/photos/ezzedine/products/warbat_halabi.webp",
    "price": 380,
    "unit": "كيلو",
    "category": "حلويات بالقشطة",
    "available": true,
    "featured": false,
    "description": "وربات حلبي من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "halawa_halabi",
    "name": "حلاوة حلبي",
    "image": "/assets/photos/ezzedine/products/halawa_halabi.webp",
    "price": 285,
    "unit": "كيلو",
    "category": "حلويات بالقشطة",
    "available": true,
    "featured": false,
    "description": "حلاوة حلبي من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "faysaliyya_fistik",
    "name": "فيصلية بالفستق",
    "image": "/assets/photos/ezzedine/products/faysaliyya_fistik.webp",
    "price": 1300,
    "unit": "كيلو",
    "category": "حلويات بالفستق",
    "available": true,
    "featured": true,
    "description": "فيصلية بالفستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "warbat_fistik",
    "name": "وربات فستق",
    "image": "/assets/photos/ezzedine/products/warbat_fistik.webp",
    "price": 1300,
    "unit": "كيلو",
    "category": "حلويات بالفستق",
    "available": true,
    "featured": true,
    "description": "وربات فستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "ghuraybe_kashta",
    "name": "غريبة بالقشطة",
    "image": "/assets/photos/ezzedine/products/ghuraybe_kashta.webp",
    "price": 540,
    "unit": "كيلو",
    "category": "حلويات بالقشطة",
    "available": true,
    "featured": false,
    "description": "غريبة بالقشطة من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "madlouka_kashta",
    "name": "مدلوقة بالقشطة",
    "image": "/assets/photos/ezzedine/products/madlouka_kashta.webp",
    "price": 540,
    "unit": "كيلو",
    "category": "حلويات بالقشطة",
    "available": true,
    "featured": false,
    "description": "مدلوقة بالقشطة من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "crepe_piece",
    "name": "قطعة كريب",
    "image": "/assets/photos/ezzedine/products/crepe_piece.webp",
    "price": 115,
    "unit": "قطعة",
    "category": "قطع وأطباق",
    "available": true,
    "featured": false,
    "description": "قطعة كريب من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "warbat_piece",
    "name": "قطعة وربات فستق",
    "image": "/assets/photos/ezzedine/products/warbat_piece.webp",
    "price": 125,
    "unit": "قطعة",
    "category": "قطع وأطباق",
    "available": true,
    "featured": false,
    "description": "قطعة وربات فستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "sahn_layali",
    "name": "صحن ليالي لبنان",
    "image": "/assets/photos/ezzedine/products/sahn_layali.webp",
    "price": 250,
    "unit": "صحن",
    "category": "قطع وأطباق",
    "available": true,
    "featured": false,
    "description": "صحن ليالي لبنان من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "piece_kbir",
    "name": "قطعة كبير",
    "image": "/assets/photos/ezzedine/products/piece_kbir.webp",
    "price": 60,
    "unit": "قطعة",
    "category": "قطع وأطباق",
    "available": true,
    "featured": false,
    "description": "قطعة كبير من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "zabadiyya",
    "name": "زبدية محلبية",
    "image": "/assets/photos/ezzedine/products/zabadiyya.webp",
    "price": 100,
    "unit": "قطعة",
    "category": "قطع وأطباق",
    "available": true,
    "featured": false,
    "description": "زبدية محلبية من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "ghuraybe_shamiyya",
    "name": "غريبة شامية",
    "image": "/assets/photos/ezzedine/products/ghuraybe_shamiyya.webp",
    "price": 800,
    "unit": "كيلو",
    "category": "حلويات عربية",
    "available": true,
    "featured": true,
    "description": "غريبة شامية من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "barazek",
    "name": "برازق",
    "image": "/assets/photos/ezzedine/products/barazek.webp",
    "price": 800,
    "unit": "كيلو",
    "category": "حلويات عربية",
    "available": true,
    "featured": false,
    "description": "برازق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "maamoul_joz",
    "name": "معمول جوز",
    "image": "/assets/photos/ezzedine/products/maamoul_joz.webp",
    "price": 1300,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": true,
    "description": "معمول جوز من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "maamoul_ajwa",
    "name": "معمول عجوة",
    "image": "/assets/photos/ezzedine/products/maamoul_ajwa.webp",
    "price": 800,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "معمول عجوة من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "petit_four",
    "name": "بيتيفور",
    "image": "/assets/photos/ezzedine/products/petit_four.webp",
    "price": 800,
    "unit": "كيلو",
    "category": "حلويات عربية",
    "available": true,
    "featured": false,
    "description": "بيتيفور من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "maamoul_fistik",
    "name": "معمول فستق",
    "image": "/assets/photos/ezzedine/products/maamoul_fistik.webp",
    "price": 1800,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": true,
    "description": "معمول فستق من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "akl_arabi_awwal",
    "name": "تشكيلة عربية أولى",
    "image": "/assets/photos/ezzedine/products/akl_arabi_awwal.webp",
    "price": 1900,
    "unit": "كيلو",
    "category": "تشكيلات",
    "available": true,
    "featured": true,
    "description": "تشكيلة عربية أولى من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "akl_arabi_extra",
    "name": "تشكيلة عربية إكسترا",
    "image": "/assets/photos/ezzedine/products/akl_arabi_extra.webp",
    "price": 2000,
    "unit": "كيلو",
    "category": "تشكيلات",
    "available": true,
    "featured": true,
    "description": "تشكيلة عربية إكسترا من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "akl_arabi_kaju",
    "name": "تشكيلة عربية كاجو",
    "image": "/assets/photos/ezzedine/products/akl_arabi_kaju.webp",
    "price": 1750,
    "unit": "كيلو",
    "category": "تشكيلات",
    "available": true,
    "featured": false,
    "description": "تشكيلة عربية كاجو من حلويات عز الدين، تُحضَّر طازجة بمكوّنات مختارة وبنكهة عربية أصيلة.",
    "imageFit": "cover",
    "options": []
  }
];

const ezzedineProducts = ezzedineProductCatalog.map((product, index) => ({
  ...product,
  id: 13001 + index,
  storeId: ezzedineStore.id
}));

const ezzedineDeliverySettings = {
  [ezzedineStore.id]: { mode: "distance", fixedFee: 30, ratePerKm: 15, prepMinutes: 30, maxRoundTripKm: 130 }
};
