// Generated for فريندز (Friends Restaurant & Cafe), Merkez Mahallesi, Avcılar, Istanbul.
// Large multi-cuisine restaurant: chicken/meat shawarma+grills+BBQ by weight, Levantine/Gulf
// rice dishes (mandi/biryani/mansaf/molokhia), western meals & burgers, pizza, Turkish pide,
// Damascene falafel/hummus/fatteh, crepe/waffle/pancake desserts, juices/smoothies/milkshakes,
// combo deals. Source: tillymenu.com/180/friendstr (554 products across 30 categories, all with
// real images) — client API (/backend/public/api/clients/180) returns full menu JSON directly,
// no per-category clicking needed. Item names entered by the merchant were a mix of Turkish/
// English/Arabic; translated to natural Arabic via parallel batch review, cross-checked against
// the source image filenames themselves (many were already descriptive Arabic, e.g. "وجبة-كوسا-بلبن-مع-رز.jpg").
// Location confirmed via Google Maps (place_id ChIJlxJ2YG-hyhQRJKc9qyAtcjI, 3.4★/653 reviews) —
// exact match confirmed by review text mentioning "friends special" XL pizza and "منسف اردني جميد"
// (Jordanian mansaf), both real menu items here. Cover image is the restaurant's own official
// Google-Business-uploaded promo banner (brand logo + Arabic name + category list), not a generic photo.
// Pizza (14 items) has real size variants (small/medium/large/XL) via the options schema.
const friendstrStore = {
 "id": 105,
 "name": "فريندز",
 "category": "مطاعم",
 "image": "/assets/photos/friendstr/cover.jpg",
 "coverImage": "/assets/photos/friendstr/cover.jpg",
 "logoImage": "/assets/photos/friendstr/logo.png",
 "logo": "ف",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 100,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": {
  "lat": 40.97991,
  "lng": 28.7240694
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=40.97991,28.7240694",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "فريندز — مطعم وكافيه كبير في مركز أفجلار يجمع بين المطبخ الشرقي والغربي: شاورما ودجاج مشوي ومشاوي لحم بالكيلو، أطباق شرقية (مندي، برياني، منسف أردني، مقلوبة)، بيتزا وبرغر وسندويشات غربية، فطائر (بيدا) ولحم بعجين، فلافل وحمص وفتة شامية، وحلويات كريب ووافل وبان كيك، بالإضافة لعصائر طبيعية وسموذي وميلك شيك.",
 "address": "Merkez Mahallesi, Reşit Paşa Cd., Talimhane Sok No:20, Avcılar/İstanbul",
 "phone": "+90 530 040 59 15",
 "whatsapp": "+90 530 040 59 15",
 "email": "",
 "website": "https://friends.tr",
 "sourceUrl": "https://tillymenu.com/180/friendstr",
 "hours": "يومياً 10:00 ص – 1:00 ص",
 "areas": [
  "أفجلار",
  "مناطق إسطنبول حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
}

// Full catalog (local images, committed) — used to build friendstrProducts below.
const friendstrFullCatalog = [
  // شاورما دجاج
  {"name":"دونر دجاج","price":150,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0001.jpg"},
  {"name":"دونر دجاج دبل","price":175,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0002.jpg"},
  {"name":"لفة أصابع الدجاج","price":100,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0003.jpg"},
  {"name":"لفة دجاج بالبطاطا","price":165,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0004.jpg"},
  {"name":"لفة دجاج بالبطاطا دبل","price":190,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0005.jpg"},
  {"name":"دونر بخبز الصمون","price":165,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0006.jpg"},
  {"name":"دونر بخبز الصمون دبل","price":190,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0007.jpg"},
  {"name":"صمون دونر بالبطاطا","price":175,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0008.jpg"},
  {"name":"لفة دونر بالجبنة","price":190,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0009.jpg"},
  {"name":"لفة دونر بالجبنة دبل","price":225,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0010.jpg"},
  {"name":"لفة دونر بالخبز الساخن","price":150,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0011.jpg"},
  {"name":"دونر عربي","price":225,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0012.jpg"},
  {"name":"دونر عربي سوبر","price":300,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0013.jpg"},
  {"name":"دونر عربي دبل","price":375,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0014.jpg"},
  {"name":"دونر عربي تريبل","price":500,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0015.jpg"},
  {"name":"صينية دونر لخمسة أشخاص","price":850,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0016.jpg"},
  {"name":"دونر أصابع","price":375,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0017.jpg"},
  {"name":"دونر بالجبنة","price":280,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0018.jpg"},
  {"name":"دونر بالجبنة دبل","price":450,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0019.jpg"},
  {"name":"دونر بانيه","price":325,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0020.jpg"},
  {"name":"دونر ماريا","price":325,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0021.jpg"},
  {"name":"فريندز الخاص","price":300,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0022.jpg"},
  {"name":"فريندز الخاص دبل","price":500,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0023.jpg"},
  {"name":"دونر على الرز","price":325,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0024.jpg"},
  {"name":"دونر 200 غرام","price":325,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0025.jpg"},
  {"name":"دونر 500 غرام","price":500,"category":"شاورما دجاج","image":"/assets/photos/friendstr/p0026.jpg"},
  // دجاج كامل
  {"name":"دجاج روتيسري","price":500,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0027.jpg"},
  {"name":"نصف دجاج روتيسري","price":250,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0028.jpg"},
  {"name":"دجاج روتيسري مع رز","price":650,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0029.jpg"},
  {"name":"نصف دجاج بالفرن","price":450,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0030.jpg"},
  {"name":"دجاج مشوي","price":650,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0031.jpg"},
  {"name":"نصف دجاج مشوي","price":325,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0032.jpg"},
  {"name":"بروستد 4 قطع","price":400,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0033.jpg"},
  {"name":"بروستد أجنحة 8 قطع","price":400,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0034.jpg"},
  {"name":"بروستد ساق دجاج 6 قطع","price":400,"category":"دجاج كامل","image":"/assets/photos/friendstr/p0035.jpg"},
  // دجاج مشاوي
  {"name":"أجنحة دجاج مشوية","price":300,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0036.jpg"},
  {"name":"وجبة شيش طاووق","price":350,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0037.jpg"},
  {"name":"كباب دجاج","price":325,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0038.jpg"},
  {"name":"مشكل مشوي بدون عظم","price":350,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0039.jpg"},
  {"name":"نصف كيلو أجنحة دجاج","price":400,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0040.jpg"},
  {"name":"كيلو أجنحة دجاج","price":800,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0041.jpg"},
  {"name":"نصف كيلو شيش طاووق","price":450,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0042.jpg"},
  {"name":"كيلو شيش طاووق","price":900,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0043.jpg"},
  {"name":"نصف كيلو كباب دجاج","price":400,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0044.jpg"},
  {"name":"كيلو كباب دجاج","price":800,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0045.jpg"},
  {"name":"نصف كيلو دجاج مشكل","price":425,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0046.jpg"},
  {"name":"كيلو دجاج مشكل","price":850,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0047.jpg"},
  {"name":"شيش طاووق","price":225,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0048.jpg"},
  {"name":"شيش طاووق بخبز الصمون","price":250,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0049.jpg"},
  {"name":"كباب دجاج","price":225,"category":"دجاج مشاوي","image":"/assets/photos/friendstr/p0050.jpg"},
  // مشاوي لحم
  {"name":"تشوب شيش","price":550,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0051.jpg"},
  {"name":"كباب لحم","price":450,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0052.jpg"},
  {"name":"كباب بالباذنجان","price":500,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0053.jpg"},
  {"name":"كباب حشحاش","price":500,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0054.jpg"},
  {"name":"كباب بالفستق","price":550,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0055.jpg"},
  {"name":"كفتة شيش","price":500,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0056.jpg"},
  {"name":"لحم مشكل","price":500,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0057.jpg"},
  {"name":"دجاج ولحم مشكل","price":400,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0058.jpg"},
  {"name":"خبز باللحم المشوي","price":500,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0059.jpg"},
  {"name":"مشاوي فريندز","price":550,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0060.jpg"},
  {"name":"نصف كيلو تشوب شيش","price":1100,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0061.jpg"},
  {"name":"كيلو تشوب شيش","price":2200,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0062.jpg"},
  {"name":"نصف كيلو كباب لحم بالباذنجان","price":1000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0063.jpg"},
  {"name":"كيلو كباب لحم بالباذنجان","price":1900,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0064.jpg"},
  {"name":"نصف كيلو كباب حشحاش","price":1000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0065.jpg"},
  {"name":"كيلو كباب حشحاش","price":2000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0066.jpg"},
  {"name":"نصف كيلو كباب لحم","price":900,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0067.jpg"},
  {"name":"كيلو كباب لحم","price":1800,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0068.jpg"},
  {"name":"نصف كيلو كباب بالفستق","price":1100,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0069.jpg"},
  {"name":"كيلو كباب بالفستق","price":2200,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0070.jpg"},
  {"name":"نصف كيلو كفتة شيش","price":1000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0071.jpg"},
  {"name":"كيلو كفتة شيش","price":2000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0072.jpg"},
  {"name":"نصف كيلو لحم ماجوكا","price":1100,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0073.jpg"},
  {"name":"كيلو لحم ماجوكا","price":2200,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0074.jpg"},
  {"name":"نصف كيلو لحم ودجاج مشكل","price":800,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0075.jpg"},
  {"name":"كيلو لحم ودجاج مشكل","price":1600,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0076.jpg"},
  {"name":"نصف كيلو ماريا","price":1000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0077.jpg"},
  {"name":"كيلو ماريا","price":2000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0078.jpg"},
  {"name":"نصف كيلو لحم مشكل","price":1000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0079.jpg"},
  {"name":"كيلو لحم مشكل","price":2000,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0080.jpg"},
  {"name":"لفة كباب لحم","price":250,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0081.jpg"},
  {"name":"لفة تشوب شيش","price":275,"category":"مشاوي لحم","image":"/assets/photos/friendstr/p0082.jpg"},
  // مأكولات عربية
  {"name":"مندي دجاج","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0083.jpg"},
  {"name":"مندي دجاج مشوي","price":475,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0084.jpg"},
  {"name":"مندي لحم","price":600,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0085.jpg"},
  {"name":"رز بخاري بالدجاج","price":1575,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0086.jpg"},
  {"name":"رز بخاري بدجاج مشوي","price":475,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0087.jpg"},
  {"name":"رز بخاري باللحم","price":600,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0088.jpg"},
  {"name":"فريكة بالدجاج","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0089.jpg"},
  {"name":"فريكة بدجاج مشوي","price":475,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0090.jpg"},
  {"name":"فريكة باللحم","price":600,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0091.jpg"},
  {"name":"رز بخاري بالدجاج","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0092.jpg"},
  {"name":"رز بخاري بدجاج مشوي","price":475,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0093.jpg"},
  {"name":"رز بخاري باللحم","price":600,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0094.jpg"},
  {"name":"برياني دجاج","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0095.jpg"},
  {"name":"برياني دجاج مشوي","price":475,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0096.jpg"},
  {"name":"برياني لحم","price":600,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0097.jpg"},
  {"name":"رز بالباذنجان والدجاج","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0098.jpg"},
  {"name":"رز بالباذنجان واللحم","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0099.jpg"},
  {"name":"كفتة باللحم مع الرز","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0100.jpg"},
  {"name":"كوسا بالحليب والرز","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0101.jpg"},
  {"name":"محشي كوسا وباذنجان","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0102.jpg"},
  {"name":"ملوخية بالرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0103.jpg"},
  {"name":"محشي ورق عنب","price":600,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0104.jpg"},
  {"name":"دجاج بمرق اللحم مع الرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0105.jpg"},
  {"name":"أوزي باللحم والمكسرات","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0106.jpg"},
  {"name":"مانتي خاص مع رز أبيض","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0107.jpg"},
  {"name":"بامية باللحم مع رز أبيض","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0108.jpg"},
  {"name":"دجاج فخارية مع الرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0109.jpg"},
  {"name":"كبة باللبن","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0110.jpg"},
  {"name":"رز بالخضار","price":250,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0111.jpg"},
  {"name":"بازلاء بالخضار مع الرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0112.jpg"},
  {"name":"لحم باللبن","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0113.jpg"},
  {"name":"مانتي","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0114.jpg"},
  {"name":"فاصولياء مع رز أبيض","price":475,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0115.jpg"},
  {"name":"دجاج بالفرن مع البطاطا والرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0116.jpg"},
  {"name":"شيش طاووق فخارية مع الرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0117.jpg"},
  {"name":"لحم مع البطاطا والرز الأبيض","price":500,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0118.jpg"},
  {"name":"منسف أردني","price":650,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0119.jpg"},
  {"name":"كباب هندي","price":550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0120.jpg"},
  {"name":"فاصولياء سادة","price":150,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0121.jpg"},
  {"name":"بامية سادة","price":150,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0122.jpg"},
  {"name":"بازلاء باللحم مع الرز","price":450,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0123.jpg"},
  {"name":"مندي دجاج","price":1550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0124.jpg"},
  {"name":"مندي دجاج مشوي","price":1725,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0125.jpg"},
  {"name":"مندي لحم","price":2100,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0126.jpg"},
  {"name":"رز بخاري بالدجاج","price":1550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0127.jpg"},
  {"name":"رز بخاري بدجاج مشوي","price":1725,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0128.jpg"},
  {"name":"رز بخاري باللحم","price":2100,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0129.jpg"},
  {"name":"برياني دجاج","price":1550,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0130.jpg"},
  {"name":"برياني دجاج مشوي","price":1725,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0131.jpg"},
  {"name":"برياني لحم","price":2100,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0132.jpg"},
  {"name":"منسف أردني خاص","price":2250,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0133.jpg"},
  {"name":"منسف لحم ودجاج","price":1950,"category":"مأكولات عربية","image":"/assets/photos/friendstr/p0134.jpg"},
  // وجبات غربية
  {"name":"كوردون بلو","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0135.jpg"},
  {"name":"دجاج مكسيكي","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0136.jpg"},
  {"name":"دجاج مكسيكي مع أرز","price":475,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0137.jpg"},
  {"name":"دجاج فرانسيسكو","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0138.jpg"},
  {"name":"دجاج كاري","price":450,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0139.jpg"},
  {"name":"دجاج كاري مع أرز","price":500,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0140.jpg"},
  {"name":"دجاج صيني","price":400,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0141.jpg"},
  {"name":"دجاج كريسبي","price":400,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0142.jpg"},
  {"name":"دجاج كريسبي أبيض","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0143.jpg"},
  {"name":"إسكالوب بانيه","price":400,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0144.jpg"},
  {"name":"برغر فريندز","price":450,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0145.jpg"},
  {"name":"دجاج الكيف","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0146.jpg"},
  {"name":"دجاج فريندز","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0147.jpg"},
  {"name":"برغر دجاج","price":400,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0148.jpg"},
  {"name":"إسكالوب ميلانيز","price":600,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0149.jpg"},
  {"name":"دجاج سوبريم","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0150.jpg"},
  {"name":"كبدة دجاج","price":350,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0151.jpg"},
  {"name":"دجاج فاهيتا","price":450,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0152.jpg"},
  {"name":"دجاج زنجر","price":400,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0153.jpg"},
  {"name":"دجاج زنجر بلس","price":425,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0154.jpg"},
  {"name":"فيليه لحم","price":600,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0155.jpg"},
  {"name":"برغر بالجبنة","price":550,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0156.jpg"},
  {"name":"برغر لحم عجل فريندز","price":550,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0157.jpg"},
  {"name":"فاهيتا لحم","price":550,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0158.jpg"},
  {"name":"فيلادلفيا لحم","price":600,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0159.jpg"},
  {"name":"كفتة لحم بالخضار","price":500,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0160.jpg"},
  {"name":"لحم فريندز","price":550,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0161.jpg"},
  {"name":"كفتة لحم","price":500,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0162.jpg"},
  {"name":"برغر لحم","price":500,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0163.jpg"},
  {"name":"مستر لحم","price":600,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0164.jpg"},
  {"name":"بوريتو لحم","price":600,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0165.jpg"},
  {"name":"بوريتو لحم مقرمش","price":600,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0166.jpg"},
  {"name":"كودو لحم","price":500,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0167.jpg"},
  {"name":"فتة كريسبي","price":350,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0168.jpg"},
  {"name":"فتة زنجر","price":350,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0169.jpg"},
  {"name":"فتة شاورما","price":350,"category":"وجبات غربية","image":"/assets/photos/friendstr/p0170.jpg"},
  // ستيك لحم
  {"name":"ستيك لحم بالفطر","price":550,"category":"ستيك لحم","image":"/assets/photos/friendstr/p0171.jpg"},
  {"name":"ستيك لحم مشوي","price":550,"category":"ستيك لحم","image":"/assets/photos/friendstr/p0172.jpg"},
  {"name":"ستيك لحم بيكاتا","price":550,"category":"ستيك لحم","image":"/assets/photos/friendstr/p0173.jpg"},
  {"name":"ستيك لحم بالجبنة والخضار","price":550,"category":"ستيك لحم","image":"/assets/photos/friendstr/p0174.jpg"},
  {"name":"ستيك لحم ترياكي","price":550,"category":"ستيك لحم","image":"/assets/photos/friendstr/p0175.jpg"},
  {"name":"ستيك لحم بوفافير","price":550,"category":"ستيك لحم","image":"/assets/photos/friendstr/p0176.jpg"},
  // ستيك دجاج
  {"name":"ستيك دجاج مشوي","price":450,"category":"ستيك دجاج","image":"/assets/photos/friendstr/p0177.jpg"},
  {"name":"ستيك دجاج بالفطر","price":450,"category":"ستيك دجاج","image":"/assets/photos/friendstr/p0178.jpg"},
  {"name":"ستيك دجاج بوفافير","price":450,"category":"ستيك دجاج","image":"/assets/photos/friendstr/p0179.jpg"},
  {"name":"ستيك دجاج أبيض","price":450,"category":"ستيك دجاج","image":"/assets/photos/friendstr/p0180.jpg"},
  {"name":"ستيك دجاج باربكيو","price":450,"category":"ستيك دجاج","image":"/assets/photos/friendstr/p0181.jpg"},
  {"name":"ستيك دجاج إحلامور","price":450,"category":"ستيك دجاج","image":"/assets/photos/friendstr/p0182.jpg"},
  // أطباق سمك
  {"name":"فيليه سمك بالبطاطا","price":450,"category":"أطباق سمك","image":"/assets/photos/friendstr/p0183.jpg"},
  {"name":"فيليه سمك بالرز","price":550,"category":"أطباق سمك","image":"/assets/photos/friendstr/p0184.jpg"},
  // معكرونة
  {"name":"سباغيتي بصوص باشا ميل","price":350,"category":"معكرونة","image":"/assets/photos/friendstr/p0185.jpg"},
  {"name":"سباغيتي بولونيز","price":400,"category":"معكرونة","image":"/assets/photos/friendstr/p0186.jpg"},
  {"name":"فيتوتشيني ألفريدو","price":375,"category":"معكرونة","image":"/assets/photos/friendstr/p0187.jpg"},
  {"name":"فيتوتشيني بصوص باشا ميل","price":350,"category":"معكرونة","image":"/assets/photos/friendstr/p0188.jpg"},
  {"name":"فيتوتشيني بصوص كاكومو","price":400,"category":"معكرونة","image":"/assets/photos/friendstr/p0189.jpg"},
  // سندويشات
  {"name":"برغر","price":300,"category":"سندويشات","image":"/assets/photos/friendstr/p0190.jpg"},
  {"name":"كودو لحم","price":325,"category":"سندويشات","image":"/assets/photos/friendstr/p0191.jpg"},
  {"name":"مستر لحم","price":325,"category":"سندويشات","image":"/assets/photos/friendstr/p0192.jpg"},
  {"name":"بوريتو لحم","price":325,"category":"سندويشات","image":"/assets/photos/friendstr/p0193.jpg"},
  {"name":"فاهيتا لحم","price":325,"category":"سندويشات","image":"/assets/photos/friendstr/p0194.jpg"},
  {"name":"فيلادلفيا لحم","price":325,"category":"سندويشات","image":"/assets/photos/friendstr/p0195.jpg"},
  {"name":"بوريتو لحم","price":325,"category":"سندويشات","image":"/assets/photos/friendstr/p0196.jpg"},
  {"name":"لفة بطاطا","price":125,"category":"سندويشات","image":"/assets/photos/friendstr/p0197.jpg"},
  {"name":"لفة بطاطا دبل","price":150,"category":"سندويشات","image":"/assets/photos/friendstr/p0198.jpg"},
  {"name":"بطاطا بالجبنة","price":175,"category":"سندويشات","image":"/assets/photos/friendstr/p0199.jpg"},
  {"name":"بطاطا بالجبنة دبل","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0200.jpg"},
  {"name":"بطاطا بخبز الصامولي","price":150,"category":"سندويشات","image":"/assets/photos/friendstr/p0201.jpg"},
  {"name":"بطاطا بخبز الصامولي دبل","price":175,"category":"سندويشات","image":"/assets/photos/friendstr/p0202.jpg"},
  {"name":"بطاطا بالجبنة وخبز الصامولي","price":200,"category":"سندويشات","image":"/assets/photos/friendstr/p0203.jpg"},
  {"name":"بطاطا بالجبنة وخبز الصامولي دبل","price":200,"category":"سندويشات","image":"/assets/photos/friendstr/p0204.jpg"},
  {"name":"زنجر","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0205.jpg"},
  {"name":"زنجر بلس","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0206.jpg"},
  {"name":"كريسبي","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0207.jpg"},
  {"name":"كريسبي أبيض","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0208.jpg"},
  {"name":"برغر","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0209.jpg"},
  {"name":"برغر بالجبنة","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0210.jpg"},
  {"name":"برغر فريندز","price":275,"category":"سندويشات","image":"/assets/photos/friendstr/p0211.jpg"},
  {"name":"ستيك دجاج","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0212.jpg"},
  {"name":"فيليه دجاج","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0213.jpg"},
  {"name":"سوبريم","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0214.jpg"},
  {"name":"فاهيتا","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0215.jpg"},
  {"name":"مكسيكي","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0216.jpg"},
  {"name":"كبدة دجاج","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0217.jpg"},
  {"name":"دجاج صيني","price":225,"category":"سندويشات","image":"/assets/photos/friendstr/p0218.jpg"},
  {"name":"فرانسيسكو","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0219.jpg"},
  {"name":"فريندز","price":250,"category":"سندويشات","image":"/assets/photos/friendstr/p0220.jpg"},
  {"name":"فيليه سمك","price":300,"category":"سندويشات","image":"/assets/photos/friendstr/p0221.jpg"},
  // بيتزا
  {"name":"بيتزا الفصول الأربعة","price":250,"category":"بيتزا","image":"/assets/photos/friendstr/p0222.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا الفصول الأربعة المحشوة","price":325,"category":"بيتزا","image":"/assets/photos/friendstr/p0223.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,225]}]},
  {"name":"بيتزا الأجبان","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0224.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا بالفطر","price":250,"category":"بيتزا","image":"/assets/photos/friendstr/p0225.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا مشكلة","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0226.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا مارغريتا","price":250,"category":"بيتزا","image":"/assets/photos/friendstr/p0227.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا دجاج حار","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0228.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا بالدونر","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0229.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا بالسجق","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0230.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا سلامي","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0231.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا تونة","price":325,"category":"بيتزا","image":"/assets/photos/friendstr/p0232.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,150,225]}]},
  {"name":"بيتزا مكسيكية","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0233.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  {"name":"بيتزا باللحمة","price":400,"category":"بيتزا","image":"/assets/photos/friendstr/p0234.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,75,175,250]}]},
  {"name":"بيتزا فريندز","price":300,"category":"بيتزا","image":"/assets/photos/friendstr/p0235.jpg","options":[{"name":"الحجم","values":["صغير","وسط","كبير","كبير جداً"],"extra":[0,50,125,200]}]},
  // فطائر ولحم بعجين
  {"name":"فطيرة شوكولا","price":75,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0236.jpg"},
  {"name":"فطيرة جبنة","price":50,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0237.jpg"},
  {"name":"فطيرة جبنة وكشر","price":70,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0238.jpg"},
  {"name":"فطيرة بالصلصة","price":40,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0239.jpg"},
  {"name":"فطيرة كشر بالصلصة","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0240.jpg"},
  {"name":"فطيرة سبانخ","price":45,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0241.jpg"},
  {"name":"فطيرة سلامي","price":45,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0242.jpg"},
  {"name":"فطيرة سلامي بالكشر","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0243.jpg"},
  {"name":"فطيرة سجق","price":65,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0244.jpg"},
  {"name":"فطيرة توشكا","price":85,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0245.jpg"},
  {"name":"فطيرة دجاج شيش","price":50,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0246.jpg"},
  {"name":"فطيرة دجاج شيش بالكشر","price":70,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0247.jpg"},
  {"name":"فطيرة زيتون أسود","price":40,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0248.jpg"},
  {"name":"فطيرة زيتون أسود وكشر","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0249.jpg"},
  {"name":"فطيرة زيتون أخضر","price":40,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0250.jpg"},
  {"name":"فطيرة زيتون أخضر وكشر","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0251.jpg"},
  {"name":"فطيرة جبنة كيري","price":50,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0252.jpg"},
  {"name":"فطيرة بالكشر","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0253.jpg"},
  {"name":"فطيرة زعتر","price":40,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0254.jpg"},
  {"name":"فطيرة زعتر وكشر","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0255.jpg"},
  {"name":"فطيرة صلصة وزعتر","price":55,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0256.jpg"},
  {"name":"فطيرة لبنة","price":50,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0257.jpg"},
  {"name":"فطيرة لبنة وزعتر","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0258.jpg"},
  {"name":"فطيرة لبنة وزيتون","price":60,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0259.jpg"},
  {"name":"فطيرة مكسيكية","price":55,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0260.jpg"},
  {"name":"فطيرة مكسيكية بالكشر","price":75,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0261.jpg"},
  {"name":"فطيرة سانفورا","price":65,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0262.jpg"},
  {"name":"بيتزا صغيرة","price":50,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0263.jpg"},
  {"name":"فطيرة باللحمة","price":65,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0264.jpg"},
  {"name":"فطيرة لحمة بالكشر","price":80,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0265.jpg"},
  {"name":"فطيرة مكعبات اللحم","price":250,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0266.jpg"},
  {"name":"فطيرة ستيك لحم","price":300,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0267.jpg"},
  {"name":"لحم عجين بالدجاج نصف كيلو","price":425,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0268.jpg"},
  {"name":"لحم عجين بالدجاج كيلو","price":850,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0269.jpg"},
  {"name":"فيليه لحم نصف كيلو","price":1375,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0270.jpg"},
  {"name":"فيليه لحم كيلو","price":2750,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0271.jpg"},
  {"name":"لحم عجين باللحمة نصف كيلو","price":900,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0272.jpg"},
  {"name":"لحم عجين باللحمة كيلو","price":1800,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0273.jpg"},
  {"name":"مكعبات لحم نصف كيلو","price":1250,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0274.jpg"},
  {"name":"مكعبات لحم كيلو","price":2500,"category":"فطائر ولحم بعجين","image":"/assets/photos/friendstr/p0275.jpg"},
  // مقبلات وسلطات
  {"name":"فتوش","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0276.jpg"},
  {"name":"تبولة","price":225,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0277.jpg"},
  {"name":"سلطة موسم","price":225,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0278.jpg"},
  {"name":"سلطة جرجير","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0279.jpg"},
  {"name":"سلطة معكرونة","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0280.jpg"},
  {"name":"سلطة الذرة","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0281.jpg"},
  {"name":"سلطة سيزر","price":300,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0282.jpg"},
  {"name":"سلطة دجاج","price":300,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0283.jpg"},
  {"name":"سلطة روسية","price":225,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0284.jpg"},
  {"name":"سلطة كول سلو","price":200,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0285.jpg"},
  {"name":"سلطة يونانية","price":275,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0286.jpg"},
  {"name":"سلطة تركية","price":225,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0287.jpg"},
  {"name":"سلطة تونة","price":300,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0288.jpg"},
  {"name":"سلطة فريندز","price":300,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0289.jpg"},
  {"name":"سلطة فطر","price":175,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0290.jpg"},
  {"name":"سلطة عدس","price":150,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0291.jpg"},
  {"name":"سلطة دجاج بالكريمة","price":175,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0292.jpg"},
  {"name":"سلطة ذرة","price":150,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0293.jpg"},
  {"name":"كبة (قطعة واحدة)","price":125,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0294.jpg"},
  {"name":"كبة كمرلي (قطعة واحدة)","price":150,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0295.jpg"},
  {"name":"بوريك أصابع بالجبنة (قطعة واحدة)","price":75,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0296.jpg"},
  {"name":"بوريك أصابع باللحمة (قطعة واحدة)","price":100,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0297.jpg"},
  {"name":"طبق أصابع الموزاريلا","price":225,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0298.jpg"},
  {"name":"طبق أصابع البطاطا","price":150,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0299.jpg"},
  {"name":"طبق بطاطا كبير","price":175,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0300.jpg"},
  {"name":"طبق بطاطا بالكشر","price":200,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0301.jpg"},
  {"name":"طبق مازة مشكلة","price":350,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0302.jpg"},
  {"name":"طبق كبة نية","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0303.jpg"},
  {"name":"طبق باذنجان مهروس","price":150,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0304.jpg"},
  {"name":"طبق فجل مهروس","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0305.jpg"},
  {"name":"طبق بابا غنوج","price":200,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0306.jpg"},
  {"name":"طبق حمص","price":150,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0307.jpg"},
  {"name":"طبق حمص بالدونر","price":275,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0308.jpg"},
  {"name":"طبق حمص باللحمة","price":300,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0309.jpg"},
  {"name":"طبق ورق عنب","price":250,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0310.jpg"},
  {"name":"طبق صلصة بالجوز","price":300,"category":"مقبلات وسلطات","image":"/assets/photos/friendstr/p0311.jpg"},
  // مأكولات شامية
  {"name":"فلافل","price":125,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0312.jpg"},
  {"name":"فلافل دبل","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0313.jpg"},
  {"name":"فلافل بخبز صامولي","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0314.jpg"},
  {"name":"فلافل بخبز صامولي دبل","price":175,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0315.jpg"},
  {"name":"فلافل بخبز حطاي","price":125,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0316.jpg"},
  {"name":"فلافل بخبز حطاي دبل","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0317.jpg"},
  {"name":"لفة فلافل بالبطاطا","price":135,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0318.jpg"},
  {"name":"لفة فلافل بالبطاطا دبل","price":175,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0319.jpg"},
  {"name":"صحن فلافل عربي","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0320.jpg"},
  {"name":"صحن فلافل عربي دبل","price":325,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0321.jpg"},
  {"name":"فلافل عربي إضافي","price":350,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0322.jpg"},
  {"name":"فول باللبن","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0323.jpg"},
  {"name":"فول بزيت الزيتون","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0324.jpg"},
  {"name":"حمص حب باللبن","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0325.jpg"},
  {"name":"حمص حب بزيت الزيتون","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0326.jpg"},
  {"name":"فلافل 6 قطع","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0327.jpg"},
  {"name":"فلافل فريندز الخاص","price":250,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0328.jpg"},
  {"name":"فتة باللبن","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0329.jpg"},
  {"name":"فتة بزيت الزيتون","price":200,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0330.jpg"},
  {"name":"فتة بالفستق","price":250,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0331.jpg"},
  {"name":"فتة باللحمة والفستق","price":350,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0332.jpg"},
  {"name":"مازة","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0333.jpg"},
  {"name":"حمص","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0334.jpg"},
  {"name":"حمص باللحمة","price":300,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0335.jpg"},
  {"name":"حمص بالسمن","price":225,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0336.jpg"},
  {"name":"حمص بالدونر","price":250,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0337.jpg"},
  {"name":"باذنجان مهروس","price":150,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0338.jpg"},
  {"name":"باتيرش","price":350,"category":"مأكولات شامية","image":"/assets/photos/friendstr/p0339.jpg"},
  // حلويات وكريب ووافل
  {"name":"كريب فريندز","price":450,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0340.jpg"},
  {"name":"كريب تويكس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0341.jpg"},
  {"name":"كريب نوتيلا","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0342.jpg"},
  {"name":"كريب سنيكرز","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0343.jpg"},
  {"name":"كريب كيت كات","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0344.jpg"},
  {"name":"كريب لوتس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0345.jpg"},
  {"name":"كريب أوريو","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0346.jpg"},
  {"name":"كريب بان كيك صغير","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0347.jpg"},
  {"name":"كريب فيتوتشيني","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0348.jpg"},
  {"name":"كريب بالفواكه","price":375,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0349.jpg"},
  {"name":"وافل فريندز","price":450,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0350.jpg"},
  {"name":"وافل تويكس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0351.jpg"},
  {"name":"وافل نوتيلا","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0352.jpg"},
  {"name":"وافل سنيكرز","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0353.jpg"},
  {"name":"وافل كيت كات","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0354.jpg"},
  {"name":"وافل لوتس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0355.jpg"},
  {"name":"وافل أوريو","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0356.jpg"},
  {"name":"وافل بالفواكه","price":400,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0357.jpg"},
  {"name":"بان كيك فريندز","price":450,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0358.jpg"},
  {"name":"بان كيك تويكس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0359.jpg"},
  {"name":"بان كيك نوتيلا","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0360.jpg"},
  {"name":"بان كيك سنيكرز","price":275,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0361.jpg"},
  {"name":"بان كيك كيت كات","price":275,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0362.jpg"},
  {"name":"بان كيك لوتس","price":275,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0363.jpg"},
  {"name":"بان كيك أوريو","price":275,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0364.jpg"},
  {"name":"بان كيك بالفواكه","price":400,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0365.jpg"},
  {"name":"غوفر فريندز","price":450,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0366.jpg"},
  {"name":"غوفر تويكس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0367.jpg"},
  {"name":"غوفر نوتيلا","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0368.jpg"},
  {"name":"غوفر سنيكرز","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0369.jpg"},
  {"name":"غوفر كيت كات","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0370.jpg"},
  {"name":"غوفر لوتس","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0371.jpg"},
  {"name":"غوفر أوريو","price":350,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0372.jpg"},
  {"name":"غوفر بالفواكه","price":400,"category":"حلويات وكريب ووافل","image":"/assets/photos/friendstr/p0373.jpg"},
  // سلطة فواكه
  {"name":"سلطة فواكه فريندز","price":450,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0374.jpg"},
  {"name":"سلطة فواكه تويكس","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0375.jpg"},
  {"name":"سلطة فواكه نوتيلا","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0376.jpg"},
  {"name":"سلطة فواكه سنيكرز","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0377.jpg"},
  {"name":"سلطة فواكه توتي فروتي","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0378.jpg"},
  {"name":"سلطة فواكه كيت كات","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0379.jpg"},
  {"name":"سلطة فواكه أوريو","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0380.jpg"},
  {"name":"سلطة فواكه كرنش بالحليب","price":375,"category":"سلطة فواكه","image":"/assets/photos/friendstr/p0381.jpg"},
  // إمبراطور
  {"name":"إمبراطور موز وحليب","price":400,"category":"إمبراطور","image":"/assets/photos/friendstr/p0382.jpg"},
  {"name":"إمبراطور موز وحليب وفراولة","price":400,"category":"إمبراطور","image":"/assets/photos/friendstr/p0383.jpg"},
  {"name":"إمبراطور شوكولا خاصة","price":400,"category":"إمبراطور","image":"/assets/photos/friendstr/p0384.jpg"},
  {"name":"إمبراطور قشطة","price":400,"category":"إمبراطور","image":"/assets/photos/friendstr/p0385.jpg"},
  {"name":"قزان حلى مشكل","price":450,"category":"إمبراطور","image":"/assets/photos/friendstr/p0386.jpg"},
  {"name":"إمبراطور فريندز","price":450,"category":"إمبراطور","image":"/assets/photos/friendstr/p0387.jpg"},
  {"name":"إمبراطور فريندز","price":450,"category":"إمبراطور","image":"/assets/photos/friendstr/p0388.jpg"},
  // مشروبات ساخنة
  {"name":"كافيه لاتيه","price":100,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0389.jpg"},
  {"name":"كابتشينو","price":100,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0390.jpg"},
  {"name":"نسكافيه بالحليب","price":100,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0391.jpg"},
  {"name":"أمريكانو","price":125,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0392.jpg"},
  {"name":"ماكياتو","price":100,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0393.jpg"},
  {"name":"موكا","price":100,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0394.jpg"},
  {"name":"شوكولا ساخنة","price":125,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0395.jpg"},
  {"name":"إسبريسو","price":125,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0396.jpg"},
  {"name":"قهوة سورية/تركية","price":75,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0397.jpg"},
  {"name":"زهورات ويانسون","price":85,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0398.jpg"},
  {"name":"شاي","price":35,"category":"مشروبات ساخنة","image":"/assets/photos/friendstr/p0399.jpg"},
  // آيس كريم
  {"name":"موكا شوكولا","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0400.jpg"},
  {"name":"موس فراولة","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0401.jpg"},
  {"name":"موز وتوت","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0402.jpg"},
  {"name":"موز سبليت","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0403.jpg"},
  {"name":"توتي فروتي","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0404.jpg"},
  {"name":"فرابتشينو","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0405.jpg"},
  {"name":"فرابتشينو موكا","price":250,"category":"آيس كريم","image":"/assets/photos/friendstr/p0406.jpg"},
  // عصائر طبيعية
  {"name":"عصير برتقال","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0407.jpg"},
  {"name":"عصير برتقال ومانجو","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0408.jpg"},
  {"name":"عصير برتقال وفراولة","price":200,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0409.jpg"},
  {"name":"عصير مانجو","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0410.jpg"},
  {"name":"عصير فراولة","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0411.jpg"},
  {"name":"عصير كيوي","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0412.jpg"},
  {"name":"عصير كيوي وليمون","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0413.jpg"},
  {"name":"عصير ليمون","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0414.jpg"},
  {"name":"عصير ليمون ونعنع","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0415.jpg"},
  {"name":"عصير أناناس","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0416.jpg"},
  {"name":"عصير برتقال وجزر","price":200,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0417.jpg"},
  {"name":"عصير جزر","price":175,"category":"عصائر طبيعية","image":"/assets/photos/friendstr/p0418.jpg"},
  // فواكه مشكلة بالحليب
  {"name":"أفوكادو","price":250,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0419.jpg"},
  {"name":"أفوكادو وبندق بالقشطة","price":300,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0420.jpg"},
  {"name":"موز بالحليب","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0421.jpg"},
  {"name":"موز وفراولة بالحليب","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0422.jpg"},
  {"name":"فراولة بالحليب","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0423.jpg"},
  {"name":"موز وشوكولا بالحليب","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0424.jpg"},
  {"name":"موز ومانجو بالحليب","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0425.jpg"},
  {"name":"كوكتيل فواكه","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0426.jpg"},
  {"name":"كوكتيل استوائي","price":225,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0427.jpg"},
  {"name":"هاواي","price":200,"category":"فواكه مشكلة بالحليب","image":"/assets/photos/friendstr/p0428.jpg"},
  // سموذي
  {"name":"توت أسود","price":175,"category":"سموذي","image":"/assets/photos/friendstr/p0429.jpg"},
  {"name":"توت أزرق","price":175,"category":"سموذي","image":"/assets/photos/friendstr/p0430.jpg"},
  {"name":"فواكه المزاج","price":175,"category":"سموذي","image":"/assets/photos/friendstr/p0431.jpg"},
  {"name":"مانجو","price":175,"category":"سموذي","image":"/assets/photos/friendstr/p0432.jpg"},
  {"name":"أناناس","price":175,"category":"سموذي","image":"/assets/photos/friendstr/p0433.jpg"},
  {"name":"فراولة","price":175,"category":"سموذي","image":"/assets/photos/friendstr/p0434.jpg"},
  // ميلك شيك
  {"name":"سنيكرز","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0435.jpg"},
  {"name":"مارس","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0436.jpg"},
  {"name":"أوريو","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0437.jpg"},
  {"name":"شوكولا","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0438.jpg"},
  {"name":"حليب","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0439.jpg"},
  {"name":"فانيلا","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0440.jpg"},
  {"name":"فراولة","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0441.jpg"},
  {"name":"سكر","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0442.jpg"},
  {"name":"لوتس","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0443.jpg"},
  {"name":"كراميل","price":200,"category":"ميلك شيك","image":"/assets/photos/friendstr/p0444.jpg"},
  // مشروبات باردة
  {"name":"ببسي 1 لتر","price":85,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0445.jpg"},
  {"name":"ببسي 2.5 لتر","price":100,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0446.jpg"},
  {"name":"ببسي علبة","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0447.jpg"},
  {"name":"سبرايت علبة","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0448.jpg"},
  {"name":"سبرايت 1 لتر","price":81,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0449.jpg"},
  {"name":"فانتا 1 لتر","price":85,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0450.jpg"},
  {"name":"فانتا علبة","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0451.jpg"},
  {"name":"كولا 1 لتر","price":85,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0452.jpg"},
  {"name":"كولا 2.5 لتر","price":110,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0453.jpg"},
  {"name":"كولا زيرو علبة","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0454.jpg"},
  {"name":"ببسي زجاجة","price":45,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0455.jpg"},
  {"name":"ترك كولا علبة 330 مل","price":50,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0456.jpg"},
  {"name":"ترك كولا 1 لتر","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0457.jpg"},
  {"name":"ترك كولا 2.5 لتر","price":90,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0458.jpg"},
  {"name":"كولا علبة","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0459.jpg"},
  {"name":"عيران","price":50,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0460.jpg"},
  {"name":"صودا","price":45,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0461.jpg"},
  {"name":"كولا زجاجة","price":45,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0462.jpg"},
  {"name":"مياه","price":20,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0463.jpg"},
  {"name":"ريد بُل","price":95,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0464.jpg"},
  {"name":"بايسون","price":60,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0465.jpg"},
  {"name":"آيس تي","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0466.jpg"},
  {"name":"ليموناضة","price":75,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0467.jpg"},
  {"name":"كالاب","price":75,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0468.jpg"},
  {"name":"عصير فواكه سيليس","price":70,"category":"مشروبات باردة","image":"/assets/photos/friendstr/p0469.jpg"},
  // عروض فريندز
  {"name":"1 شاورما عربي عادي + 1 عصير طبيعي","price":300,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0470.jpg"},
  {"name":"3 سندويش غربي مشكل + 1 كولا لتر","price":700,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0471.jpg"},
  {"name":"عرض الشاميات","price":750,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0472.jpg"},
  {"name":"1 كيلو كباب دجاج + خبز + لتر كولا","price":800,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0473.jpg"},
  {"name":"1 كيلو شيش دجاج + خبز + لتر كولا","price":850,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0474.jpg"},
  {"name":"3 شاورما لف عرض","price":300,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0475.jpg"},
  {"name":"3 وجبة شاورما عادي","price":450,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0476.jpg"},
  {"name":"3 وجبة شاورما سوبر","price":600,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0477.jpg"},
  {"name":"3 وجبة شاورما دبل","price":750,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0478.jpg"},
  {"name":"3 وجبة شاورما تربل","price":1000,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0479.jpg"},
  {"name":"1 كيلو صفيحة دجاج عرض","price":750,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0480.jpg"},
  {"name":"3 بيتزا الفصول الاربعة وسط عرض","price":600,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0481.jpg"},
  {"name":"3 سندويش زنجر عرض","price":450,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0482.jpg"},
  {"name":"3 سندويش كريسبي عرض","price":450,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0483.jpg"},
  {"name":"3 سندويش فاهيتا عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0484.jpg"},
  {"name":"3 سندويش سوبريم عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0485.jpg"},
  {"name":"3 سندويش برغر دجاج عرض","price":450,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0486.jpg"},
  {"name":"3 سندويش برغر لحم عرض","price":550,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0487.jpg"},
  {"name":"فتة كريسبي + فتة زنجر + فتة شاورما عرض","price":800,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0488.jpg"},
  {"name":"1 فروج عالفحم + خبز + كولا عرض","price":700,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0489.jpg"},
  {"name":"1 فروج غاز + خبز + كولا عرض","price":550,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0490.jpg"},
  {"name":"1 كريب لوتس + 1 وافل فواكيه + غوفر نيوتيلا عرض","price":850,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0491.jpg"},
  {"name":"2 وجبة بروستد + خبز + 1 لتر كولا عرض","price":800,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0492.jpg"},
  {"name":"فتة زنجر عرض","price":300,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0493.jpg"},
  {"name":"فتة شاورما عرض","price":300,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0494.jpg"},
  {"name":"فتة كريسبي عرض","price":300,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0495.jpg"},
  {"name":"3 سندويش فلافل عرض","price":250,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0496.jpg"},
  {"name":"3 سندويش فلافل صاج عرض","price":250,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0497.jpg"},
  {"name":"3 سندويش فلافل صمون عرض","price":300,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0498.jpg"},
  {"name":"وجبة مقلوبة باذنجان لحم","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0499.jpg"},
  {"name":"وجبة اوزي لحم عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0500.jpg"},
  {"name":"منسف مندي او كبسة دجاج 5 اشخاص","price":2500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0501.jpg"},
  {"name":"وجبة سوبريم عرض","price":400,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0502.jpg"},
  {"name":"وجبة كوردون بلو عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0503.jpg"},
  {"name":"نص فروج مسحب مع رز عرض","price":400,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0504.jpg"},
  {"name":"وجبة مندي دجاج عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0505.jpg"},
  {"name":"وجبة كبسة دجاج عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0506.jpg"},
  {"name":"وجبة فريكة دجاج عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0507.jpg"},
  {"name":"3 سلطة فواكيه عرض","price":750,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0508.jpg"},
  {"name":"3 كوكتيل عرض","price":400,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0509.jpg"},
  {"name":"3 عصير طبيعي عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0510.jpg"},
  {"name":"1 جبنة + 1 زعتر + 1 محمرة + 1 مرتديلا + 1 شيش + 1 بيتزا سواريه","price":200,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0511.jpg"},
  {"name":"وجبة كريسبي عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0512.jpg"},
  {"name":"وجبة زنجر عرض","price":350,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0513.jpg"},
  {"name":"وجبة كبة لبنية عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0514.jpg"},
  {"name":"وجبة شيش برك عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0515.jpg"},
  {"name":"وجبة باشا وعساكرو عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0516.jpg"},
  {"name":"3 سندويش كباب لحم عرض","price":500,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0517.jpg"},
  {"name":"3 سندويش كباب دجاج عرض","price":450,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0518.jpg"},
  {"name":"3 سندويش شيش طاوق عرض","price":450,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0519.jpg"},
  {"name":"عرض معجنات","price":250,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0520.jpg"},
  {"name":"وجبة مكس سوبريم رول دجاج او كوردون دجاج","price":400,"category":"عروض فريندز","image":"/assets/photos/friendstr/p0521.jpg"},
  // عصير طبيعي باللتر
  {"name":"لتر عصير طبيعي برتقال","price":450,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0522.jpg"},
  {"name":"لتر عصير طبيعي برتقال وفريز","price":500,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0523.jpg"},
  {"name":"لتر عصير طبيعي برتقال وليمون","price":450,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0524.jpg"},
  {"name":"لتر عصير طبيعي فريز","price":450,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0525.jpg"},
  {"name":"لتر عصير طبيعي مانغا","price":450,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0526.jpg"},
  {"name":"لتر عصير كوكتيل فواكيه","price":500,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0527.jpg"},
  {"name":"لتر عصير طبيعي ليمون ونعنع","price":450,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0528.jpg"},
  {"name":"لتر عصير طبيعي موز وحليب","price":450,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0529.jpg"},
  {"name":"لتر عصير طبيعي موز وحليب وشوكولا","price":500,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0530.jpg"},
  {"name":"لتر عصير افوكادو","price":600,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0531.jpg"},
  {"name":"لتر عصير طبيعي موز وحليب وفريز","price":500,"category":"عصير طبيعي باللتر","image":"/assets/photos/friendstr/p0532.jpg"},
  // بوب كيك
  {"name":"بوب كيك لوتس","price":250,"category":"بوب كيك","image":"/assets/photos/friendstr/p0533.jpg"},
  {"name":"بوب كيك شوكولا","price":250,"category":"بوب كيك","image":"/assets/photos/friendstr/p0534.jpg"},
  {"name":"بوب كيك بستاشيو","price":250,"category":"بوب كيك","image":"/assets/photos/friendstr/p0535.jpg"},
  // خدمات إضافية
  {"name":"ربطة خبز","price":30,"category":"خدمات إضافية","image":"/assets/photos/friendstr/p0536.jpg"},
  {"name":"شوي صينة بالفرن","price":200,"category":"خدمات إضافية","image":"/assets/photos/friendstr/p0537.jpg"},
  {"name":"صمونة طويلة","price":20,"category":"خدمات إضافية","image":"/assets/photos/friendstr/p0538.jpg"},
  {"name":"صمونة مدورة","price":10,"category":"خدمات إضافية","image":"/assets/photos/friendstr/p0539.jpg"},
  // صوصات وإضافات
  {"name":"نص كيلو كريم ثوم","price":150,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0540.jpg"},
  {"name":"نص كيلو سلطة روسية","price":150,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0541.jpg"},
  {"name":"علبة دبس رمان صغيرة","price":25,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0542.jpg"},
  {"name":"علبة دقوس مندي","price":45,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0543.jpg"},
  {"name":"علبة سلطة روسية صغيرة","price":75,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0544.jpg"},
  {"name":"علبة شطة حارة","price":25,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0545.jpg"},
  {"name":"علبة صوص شيدر","price":35,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0546.jpg"},
  {"name":"علبة صوص بروستد","price":35,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0547.jpg"},
  {"name":"علبة طراطور طحينية","price":25,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0548.jpg"},
  {"name":"علبة كريم ثوم كبيرة","price":50,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0549.jpg"},
  {"name":"علبة كريم ثوم صغيرة","price":25,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0550.jpg"},
  {"name":"علبة لبن بخيار","price":40,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0551.jpg"},
  {"name":"علبة مايونيز غربي","price":35,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0552.jpg"},
  {"name":"علبة مخلل خيار","price":25,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0553.jpg"},
  {"name":"علبة مخلل فليفلة","price":25,"category":"صوصات وإضافات","image":"/assets/photos/friendstr/p0554.jpg"},
];

// Repo-bundled override catalog stays empty (FullCatalog above is the real data source).
const friendstrProductCatalog = [];

const friendstrProducts = (friendstrProductCatalog.length ? friendstrProductCatalog : friendstrFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1870001 + index,
  storeId: friendstrStore.id
}));

const friendstrDeliverySettings = {
  [friendstrStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 30, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { friendstrStore, friendstrProducts, friendstrDeliverySettings };
}
