// Generated for غسق ماركت (Ghasaq Market) — Sultaniye/Yenikent, Esenyurt/İstanbul.
// Source: the merchant's own Shopify storefront gasakmarket.com (linked from its WhatsApp Business profile,
// wa.me/c/905358441989). The WhatsApp catalog itself lists only ~46 items, almost none priced, so it was
// used for cross-checking only. 262 products across 15 categories; unavailable and zero-price items excluded.
// Google Places match by phone: place_id ChIJc-QO6UKhyhQR7k4w0vM1TeE. oldPrice = merchant's own compare-at price.
const ghasaqStore = {
 "id": 119,
 "name": "غسق ماركت",
 "category": "سوبر ماركت",
 "image": "/assets/photos/ghasaq/cover.jpg",
 "coverImage": "/assets/photos/ghasaq/cover.jpg",
 "logoImage": "/assets/photos/ghasaq/logo.jpg",
 "logo": "غ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 0,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": { "lat": 41.0340256, "lng": 28.6861564 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.0340256,28.6861564",
 "open": true,
 "featured": false,
 "hasOffer": false,
 "offer": "",
 "description": "غسق ماركت — سوبر ماركت في إسنيورت: خضار وفواكه طازجة، دجاج، ألبان وبيض، توابل وبهارات وعطارة، مشروبات ساخنة وقهوة وشاي، بقوليات وأرز، معلبات، مخبوزات ومجمدات. توصيل حسب المسافة.",
 "address": "Sultaniye (Yenikent), 614. Sk. No:4, 34510 Esenyurt/İstanbul",
 "phone": "+90 535 844 19 89",
 "whatsapp": "+90 535 844 19 89",
 "email": "",
 "website": "https://gasakmarket.com",
 "sourceUrl": "https://wa.me/c/905358441989",
 "hours": "يومياً 10:00 ص – 10:00 م",
 "areas": ["إسنيورت", "مناطق إسطنبول حسب المسافة"],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true,
 "approvalStatus": "pending",
 "googlePlaceId": "ChIJc-QO6UKhyhQR7k4w0vM1TeE",
 "googleRating": 3.7,
 "googleReviewsCount": 409,
 "googleMapsUrl": "https://maps.google.com/?cid=16234691553060212462"
};

const ghasaqFullCatalog = [
  {"name":"قهوة عربية 420غرام سعودية بالزعفران","price":375,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p1.jpg","oldPrice":475},
  {"name":"قهوة مصرية جولد 100جرام","price":95,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p2.jpg","oldPrice":120},
  {"name":"قهوة كلاسيك 100جرام","price":95,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p3.jpg","oldPrice":120},
  {"name":"قهوة عربية مرة (سريعة التحضير)","price":50,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p4.jpg","oldPrice":75},
  {"name":"لبنة من غير لاكتوز (راحات)","price":45,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p5.jpg"},
  {"name":"حليب 1لتر خالي اللاكتوز (راحات)","price":55,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p6.jpg"},
  {"name":"جبنة دومتي فيتا","price":60,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p7.jpg"},
  {"name":"جبنة موزاريلا مبروشة","price":120,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p8.jpg","oldPrice":140},
  {"name":"جبنة المراعي دهن (سائلة)","price":85,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p9.jpg","oldPrice":100},
  {"name":"جبنة مثلثات 24قطعة لافاش كيري","price":120,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p10.jpg","oldPrice":145},
  {"name":"جبنة شطور دهن (سائلة)","price":65,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p11.jpg","oldPrice":75},
  {"name":"جبنة رومي دهن (مصرية)","price":60,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p12.jpg","oldPrice":75},
  {"name":"بن الشام هال اخضر","price":165,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p13.jpg"},
  {"name":"بن الشام هال اكسترا","price":175,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p14.jpg"},
  {"name":"فلفل ابيض مطحون","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p15.jpg"},
  {"name":"محلب حب","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p16.jpg"},
  {"name":"محلب مطحون","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p17.jpg"},
  {"name":"جوزة الطيب حب","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p18.jpg"},
  {"name":"جوزة الطيب مطحونة","price":40,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p19.jpg"},
  {"name":"هال مطحون","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p20.jpg"},
  {"name":"هال حب","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p21.jpg"},
  {"name":"باكمبودر ممتاز للكيك و الحلويات","price":5,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p22.jpg"},
  {"name":"فانيلا ممتازة","price":5,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p23.jpg"},
  {"name":"خميرة فورية","price":30,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p24.jpg"},
  {"name":"مدات (مفرش سفرة)","price":30,"category":"منظفات","image":"/assets/photos/ghasaq/p25.jpg","oldPrice":40},
  {"name":"اكياس قمامة/زبالة (حجم دبل كبير)","price":35,"category":"منظفات","image":"/assets/photos/ghasaq/p26.jpg","oldPrice":45,"description":"ماركة ممتازة"},
  {"name":"اكياس قمامة/زبالة (حجم كبير)","price":35,"category":"منظفات","image":"/assets/photos/ghasaq/p27.jpg","oldPrice":45,"description":"ماركة ممتازة"},
  {"name":"ملح صخري (المخللات ..ورق عنب)","price":20,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p28.jpg","oldPrice":30,"description":"حجم كبير 1.5كيلو"},
  {"name":"حلبة مطحونة","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p29.jpg"},
  {"name":"كزبرة مطحونة","price":25,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p30.jpg"},
  {"name":"ليمون مجفف/لومي (اصفر)","price":25,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p31.jpg"},
  {"name":"فلفل اسود","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p32.jpg"},
  {"name":"بصل مطحون","price":28,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p33.jpg"},
  {"name":"ثوم مطحون","price":28,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p34.jpg"},
  {"name":"جوز هند","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p35.jpg"},
  {"name":"يانسون حب","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p36.jpg"},
  {"name":"يانسون مطحون","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p37.jpg"},
  {"name":"قرفة مطحونة","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p38.jpg"},
  {"name":"نعناع ناشف","price":25,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p39.jpg"},
  {"name":"سمسم اشقر (برازق)","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p40.jpg"},
  {"name":"سمسم محمص زعتر","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p41.jpg"},
  {"name":"سمسم ابيض","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p42.jpg"},
  {"name":"زنجبيل حب","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p43.jpg"},
  {"name":"كمون حب","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p44.jpg"},
  {"name":"بهارات مشكلة (سبع بهارات)","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p45.jpg"},
  {"name":"كاري","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p46.jpg"},
  {"name":"كمون مطحون","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p47.jpg"},
  {"name":"توابل ارز كبسة","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p48.jpg"},
  {"name":"سماق مطحون","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p49.jpg"},
  {"name":"زنجبيل مطحون","price":20,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p50.jpg"},
  {"name":"نكهة خل","price":60,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p51.jpg","oldPrice":70},
  {"name":"نكهة البصل","price":60,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p52.jpg","oldPrice":70},
  {"name":"نكهة باربكيو","price":60,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p53.jpg","oldPrice":70},
  {"name":"نكهة شيدر","price":60,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p54.jpg","oldPrice":70},
  {"name":"نكهة كاتشب","price":60,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p55.jpg","oldPrice":70},
  {"name":"نكهة دجاج","price":60,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p56.jpg","oldPrice":70},
  {"name":"كربونات الصوديوم","price":25,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p57.jpg","oldPrice":35},
  {"name":"حبة البركة (حبة سودا)","price":40,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p58.jpg"},
  {"name":"شمرا (شومر مطحون)","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p59.jpg"},
  {"name":"عصفر","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p60.jpg"},
  {"name":"اوريجانو","price":55,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p61.jpg"},
  {"name":"فستق سوداني (عبيد للطبخ)","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p62.jpg"},
  {"name":"كاجو","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p63.jpg"},
  {"name":"لوز فلق مقشر","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p64.jpg"},
  {"name":"لوز بقشره","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p65.jpg"},
  {"name":"كشك (كشكة)","price":80,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p66.jpg"},
  {"name":"خلطة بروستد","price":80,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p67.jpg"},
  {"name":"خلطة كاملة دجاج كريسبي","price":80,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p68.jpg"},
  {"name":"كشك (كشكة ممتازة)","price":120,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p69.jpg"},
  {"name":"توابل و بهارات اوزي","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p70.jpg","oldPrice":55},
  {"name":"توابل و بهارات رز كبسة","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p71.jpg","oldPrice":55},
  {"name":"توابل و بهارات سجق","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p72.jpg","oldPrice":55},
  {"name":"فلفل اسود حب","price":30,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p73.jpg"},
  {"name":"قرفة عود","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p74.jpg"},
  {"name":"مردقوش","price":55,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p75.jpg"},
  {"name":"ملح (حمض الليمون)","price":25,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p76.jpg","oldPrice":30},
  {"name":"توابل و بهارات فلافل","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p77.jpg","oldPrice":55},
  {"name":"اكليل الجبل (روز ماري)","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p78.jpg"},
  {"name":"توابل تايلندي","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p79.jpg","oldPrice":55},
  {"name":"زبيب من دون بذر","price":35,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p80.jpg"},
  {"name":"جرادة حب","price":75,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p81.jpg"},
  {"name":"شوربة دجاج","price":45,"category":"المعكرونة والاندومي","image":"/assets/photos/ghasaq/p82.jpg","oldPrice":55},
  {"name":"ملح هملايا","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p83.jpg"},
  {"name":"ملح هملايا ناعم","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p84.jpg"},
  {"name":"سكر بني","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p85.jpg"},
  {"name":"توابل مكسيكانو (مكسيكي)","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p86.jpg","oldPrice":55},
  {"name":"توابل برياني","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p87.jpg","oldPrice":55},
  {"name":"توابل و بهارات همبرجر","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p88.jpg","oldPrice":55},
  {"name":"توابل دجاج بالكاري","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p89.jpg","oldPrice":55},
  {"name":"توابل دجاج","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p90.jpg","oldPrice":55},
  {"name":"توابل سمك","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p91.jpg","oldPrice":55},
  {"name":"توابل محاشي (محشي)","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p92.jpg","oldPrice":55},
  {"name":"توابل بطاطا","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p93.jpg","oldPrice":55},
  {"name":"توابل ارز اصفر/مقلوبة (قدرة)","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p94.jpg","oldPrice":55},
  {"name":"توابل مندي مدخن","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p95.jpg","oldPrice":55},
  {"name":"توابل شيش طاووق","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p96.jpg","oldPrice":55},
  {"name":"سبع بهارات (بهارات مشكلة)","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p97.jpg","oldPrice":55},
  {"name":"توابل ارز مبهر","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p98.jpg","oldPrice":55},
  {"name":"توابل لحمة و كباب","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p99.jpg","oldPrice":55},
  {"name":"ورق عنب (يبرق)","price":150,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p100.jpg"},
  {"name":"نعناع اخضر طازج","price":20,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p101.jpg"},
  {"name":"جزر","price":20,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p102.jpg"},
  {"name":"كزبرة خضراء","price":20,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p103.jpg"},
  {"name":"بقدونس","price":10,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p104.jpg"},
  {"name":"فجل احمر","price":20,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p105.jpg"},
  {"name":"بطاطا (بطاطس صغيرة)","price":15,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p106.jpg"},
  {"name":"زنجبيل طازج فريش","price":250,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p107.jpg"},
  {"name":"فليفلة حدة (حارة)","price":75,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p108.jpg"},
  {"name":"فليفلة مدعبلة (دولما)","price":59,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p109.jpg"},
  {"name":"فليفلة حلوة","price":40,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p110.jpg"},
  {"name":"يقطين ابيض","price":45,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p111.jpg"},
  {"name":"كريفون (كريب فروت)","price":35,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p112.jpg"},
  {"name":"ملفوف/ يخنة (كرنب)","price":17,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p113.jpg"},
  {"name":"جرجير (روكا)","price":20,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p114.jpg"},
  {"name":"ثوم مقشر طازج","price":200,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p115.jpg","oldPrice":250},
  {"name":"لفت","price":25,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p116.jpg"},
  {"name":"تمر مصري ممتاز","price":75,"category":"تمور ومكسرات","image":"/assets/photos/ghasaq/p117.jpg","oldPrice":90,"description":"1 كيلو"},
  {"name":"زيتون اخضر طازج","price":140,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p118.jpg"},
  {"name":"فطر (مشروم طازج)","price":70,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p119.jpg","description":"وزن من 400ل600غرام"},
  {"name":"خس","price":25,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p120.jpg"},
  {"name":"سلق طازج","price":20,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p121.jpg"},
  {"name":"سبانخ بالكيلو","price":29,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p122.jpg"},
  {"name":"فول اخضر فريش","price":45,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p123.jpg"},
  {"name":"باذنجان اسود","price":49,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p124.jpg"},
  {"name":"بصل صغير","price":10,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p125.jpg","oldPrice":13},
  {"name":"برتقال للعصير","price":19,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p126.jpg","oldPrice":30},
  {"name":"بذور هال (قلب) 100غرام","price":180,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p127.jpg","oldPrice":220},
  {"name":"حب هال محمص 100غرام","price":180,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p128.jpg","oldPrice":220},
  {"name":"ميلون 48 ظرف","price":225,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p129.jpg","oldPrice":350},
  {"name":"قهوة (بن هال اكسترا 250غرام)","price":175,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p130.jpg","oldPrice":225,"description":"طحن طازج"},
  {"name":"عسل الزهور","price":250,"category":"حلويات وعسل","image":"/assets/photos/ghasaq/p131.jpg","oldPrice":400},
  {"name":"حليب مكثف (نستله)","price":65,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p132.jpg"},
  {"name":"ملونات مندي صفار الزعفران","price":90,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p133.jpg"},
  {"name":"بابونج","price":60,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p134.jpg"},
  {"name":"شاي الكرك (ماسالا)","price":170,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p135.jpg","oldPrice":200},
  {"name":"شاي الربيع 100ظرف","price":210,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p136.jpg","oldPrice":250},
  {"name":"شاي الكرك (عدن)","price":170,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p137.jpg","oldPrice":210},
  {"name":"كب كيك شوكلا و فانيلا طازج يومياً","price":10,"category":"مخبوزات","image":"/assets/photos/ghasaq/p138.jpg","description":"الكميات الحجز قبل بوقت"},
  {"name":"عجينة بيتزا عدد 4 يومياً طازج","price":50,"category":"مخبوزات","image":"/assets/photos/ghasaq/p139.jpg"},
  {"name":"بانوليه طازج يومياً","price":25,"category":"مخبوزات","image":"/assets/photos/ghasaq/p140.jpg","oldPrice":30},
  {"name":"خبز صاج أو خبز شراك عدد 4كبار","price":35,"category":"مخبوزات","image":"/assets/photos/ghasaq/p141.jpg"},
  {"name":"صمون همبرغر عدد 6","price":50,"category":"مخبوزات","image":"/assets/photos/ghasaq/p142.jpg"},
  {"name":"معمول عجوة بنكهة السمن الحيواني","price":230,"category":"مخبوزات","image":"/assets/photos/ghasaq/p143.jpg","oldPrice":275},
  {"name":"برازق شامية ممتازة","price":230,"category":"مخبوزات","image":"/assets/photos/ghasaq/p144.jpg","oldPrice":300},
  {"name":"رز الملوك بسمتي ذهبي 900غرام","price":90,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p145.jpg"},
  {"name":"رز بسمتي اروى 900غرام","price":75,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p146.jpg"},
  {"name":"رز محمود الأصلي 900غرام","price":125,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p147.jpg"},
  {"name":"شاي العروسة 250غرام","price":108,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p148.jpg","oldPrice":125},
  {"name":"شاي الملوك 400غرام","price":210,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p149.jpg","oldPrice":265},
  {"name":"حمص حب","price":65,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p150.jpg"},
  {"name":"فول ناشف (يابس)","price":55,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p151.jpg"},
  {"name":"عدس اسود (عدس مجدرة)","price":65,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p152.jpg"},
  {"name":"عدس احمر ممتاز","price":55,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p153.jpg"},
  {"name":"فريكة نوعية ممتازة","price":90,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p154.jpg"},
  {"name":"رز الريف مكسر","price":30,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p155.jpg"},
  {"name":"ذرة بوشار ممتازة","price":35,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p156.jpg"},
  {"name":"رز الريف الأزرق","price":60,"category":"بقوليات وأرز","image":"/assets/photos/ghasaq/p157.jpg","description":"ممتاز للطبخ و الارز المفلفل"},
  {"name":"مانجو (مانجا شرائح)","price":140,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p158.jpg","description":"1كيلو"},
  {"name":"جوافة ممتازة 1كيلوومن دون بذور","price":160,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p159.jpg","oldPrice":200},
  {"name":"فراولة (فريز مجمد 1كيلو)","price":140,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p160.jpg"},
  {"name":"بطاطا مجمدة ممتازة 2.50كيلو","price":170,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p161.jpg","description":"بطاطس متل المطاعم"},
  {"name":"فول اخضر مجمد","price":60,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p162.jpg","description":"400غرام"},
  {"name":"بامية وسط ممتازة","price":60,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p163.jpg"},
  {"name":"بزالية خضرة مجمدة (بسله)","price":60,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p164.jpg"},
  {"name":"بامية مصرية اصغر حجم (زيرو)","price":80,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p165.jpg","description":"مجمدة/مفرزة"},
  {"name":"ملوخية ناعمة مجمدة (مصرية)","price":50,"category":"خضار وفواكه مجمدة","image":"/assets/photos/ghasaq/p166.jpg","oldPrice":65,"description":"متوفر عرض 3اكياس 120ليرة"},
  {"name":"كريمة (قشطة كاملة الدسم)","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p167.jpg","oldPrice":60,"description":"للطبخ و الحلويات"},
  {"name":"كريمة (قشطة نصف دسم)","price":45,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p168.jpg","oldPrice":50,"description":"للطبخ و الحلويات"},
  {"name":"كرمنتيناةحلوة حلوة من غير بذر","price":25,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p169.jpg","oldPrice":35,"description":"يوسف افندي"},
  {"name":"شبت اخضر","price":10,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p170.jpg","oldPrice":15},
  {"name":"افوكادو حجم كبير","price":50,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p171.jpg","description":"البيع بالحبة"},
  {"name":"افخم مخلل لفت (بنجر)","price":90,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p172.jpg","oldPrice":110,"description":"ممتاز سعر الكيلو"},
  {"name":"عصير سلس برتقال و جزر 1لتر","price":55,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p173.jpg","oldPrice":70},
  {"name":"مانجا سلس 1لتر","price":55,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p174.jpg","oldPrice":70},
  {"name":"عصير جوس 1لتر","price":35,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p175.jpg","oldPrice":45},
  {"name":"عصير جوس 1لتر مانجو (مانجا)","price":35,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p176.jpg","oldPrice":45},
  {"name":"عصير جوس 1لتر فراولة (فريز)","price":35,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p177.jpg","oldPrice":45},
  {"name":"عصير جوس 1لتر دراق (خوخ)","price":35,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p178.jpg","oldPrice":45},
  {"name":"شاي الروحة 400غرام","price":210,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p179.jpg","oldPrice":260},
  {"name":"شاي الملوك 25ظرف","price":55,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p180.jpg"},
  {"name":"شاي الروحة 25ظرف","price":55,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p181.jpg","oldPrice":60},
  {"name":"دونات مغطسة","price":160,"category":"حلويات وعسل","image":"/assets/photos/ghasaq/p182.jpg","oldPrice":240,"description":"24قطعة"},
  {"name":"عيران 1لتر","price":40,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p183.jpg","oldPrice":45},
  {"name":"حليب نصف دسم 1لتر","price":45,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p184.jpg"},
  {"name":"حليب كامل الدسم 1لتر","price":55,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p185.jpg"},
  {"name":"شاي الملوك 100ظرف","price":140,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p186.jpg","oldPrice":175},
  {"name":"بن الحموي اكسترا هال 180غرام","price":180,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p187.jpg","oldPrice":200,"description":"ازرق"},
  {"name":"شاي الملوك بالكيلو","price":60,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p188.jpg","oldPrice":75,"description":"كيس 100غرام"},
  {"name":"شاي الكبوس 200جرام","price":110,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p189.jpg","oldPrice":160},
  {"name":"شوكلا مرة اصابع","price":70,"category":"حلويات وعسل","image":"/assets/photos/ghasaq/p190.jpg","oldPrice":80,"description":"شوكلا عمار 30حبة"},
  {"name":"سمنة الخير بالنكهة الحيوانية 1.75لتر","price":260,"category":"سمنة وزيوت","image":"/assets/photos/ghasaq/p191.jpg","oldPrice":300},
  {"name":"سمنة الخير بالنكهة الحيوانية 1لتر","price":150,"category":"سمنة وزيوت","image":"/assets/photos/ghasaq/p192.jpg","oldPrice":190},
  {"name":"سمنة الخير بالنكهة الحيوانية 4.50لتر","price":540,"category":"سمنة وزيوت","image":"/assets/photos/ghasaq/p193.jpg","oldPrice":650},
  {"name":"سمنة ايفت 2لتر","price":245,"category":"سمنة وزيوت","image":"/assets/photos/ghasaq/p194.jpg","oldPrice":290,"description":"2لتر"},
  {"name":"لبن غنم ممتاز أصلي","price":145,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p195.jpg"},
  {"name":"كمون و ليمون 20 ظرف","price":50,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p196.jpg"},
  {"name":"بابونج 20ظرف ممتاز","price":55,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p197.jpg","oldPrice":75},
  {"name":"زهورات شامية 20ظرف","price":55,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p198.jpg","oldPrice":75},
  {"name":"مستكة ممتازة للطبخ و الحلويات","price":10,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p199.jpg"},
  {"name":"كركديه (شاي احمر)","price":40,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p200.jpg","oldPrice":50},
  {"name":"زهورات ممتازة","price":45,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p201.jpg","oldPrice":60},
  {"name":"ميرمية ممتازة","price":40,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p202.jpg","oldPrice":50},
  {"name":"شطة جلوريا كبير","price":70,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p203.jpg","oldPrice":90},
  {"name":"سمنة ايفت","price":515,"category":"سمنة وزيوت","image":"/assets/photos/ghasaq/p204.jpg","oldPrice":550,"description":"5لتر"},
  {"name":"بن الحموي غامق اكسترا هال 180غرام","price":170,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p205.jpg","oldPrice":190},
  {"name":"بن الحموي وسط سادة 100غرام","price":65,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p206.jpg","oldPrice":85},
  {"name":"شاي الروحة 100ظرف","price":140,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p207.jpg","oldPrice":175},
  {"name":"قوانص (حواصل دجاج)","price":90,"category":"دجاج","image":"/assets/photos/ghasaq/p208.jpg","oldPrice":110,"description":"السعر للكيلو"},
  {"name":"مفروم/كفتة (دجاج)","price":130,"category":"دجاج","image":"/assets/photos/ghasaq/p209.jpg","description":"السعر للكيلو"},
  {"name":"دجاج طازج يومياً","price":80,"category":"دجاج","image":"/assets/photos/ghasaq/p210.jpg","description":"السعر للكيلو"},
  {"name":"توابل ارز اصفر","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p211.jpg","oldPrice":55},
  {"name":"توابل شاورما","price":45,"category":"توابل وبهارات وعطارة","image":"/assets/photos/ghasaq/p212.jpg"},
  {"name":"سمنة فيتا","price":160,"category":"سمنة وزيوت","image":"/assets/photos/ghasaq/p213.jpg","oldPrice":180,"description":"1لتر"},
  {"name":"زهرة (قرنبيط)","price":25,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p214.jpg","oldPrice":40},
  {"name":"اندومي خضار بالليمون5بـ45ليرة","price":10,"category":"المعكرونة والاندومي","image":"/assets/photos/ghasaq/p215.jpg","oldPrice":12},
  {"name":"اندومي دجاج 5حبات45ليرة","price":10,"category":"المعكرونة والاندومي","image":"/assets/photos/ghasaq/p216.jpg","oldPrice":12},
  {"name":"بيض بلدي بصفارين قياس دبل العادي","price":12,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p217.jpg","oldPrice":18,"description":"قياس البيضة XL"},
  {"name":"بيض 30حبة قياس كبير","price":145,"category":"الألبان والبيض","image":"/assets/photos/ghasaq/p218.jpg","oldPrice":190,"description":"قياس لارج طازج يومياً"},
  {"name":"ماء 5لتر 4عبوات","price":120,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p219.jpg","oldPrice":140},
  {"name":"ماء نص لتر","price":120,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p220.jpg","oldPrice":140,"description":"24 عبوة"},
  {"name":"جاست باور 500مل","price":20,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p221.jpg","oldPrice":25},
  {"name":"جاست باور 1لتر","price":30,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p222.jpg","oldPrice":40},
  {"name":"طاقة جاك 500مل","price":25,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p223.jpg","oldPrice":35},
  {"name":"فخد كامل","price":65,"category":"دجاج","image":"/assets/photos/ghasaq/p224.jpg","oldPrice":70},
  {"name":"ليمون فريش","price":39,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p225.jpg","oldPrice":60,"description":"متوفر بلدي كبير"},
  {"name":"اجاص (كمثري)","price":65,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p226.jpg","oldPrice":80},
  {"name":"كابي برتقال 1لتر","price":55,"category":"مشروبات ومياه","image":"/assets/photos/ghasaq/p227.jpg","oldPrice":70},
  {"name":"رمان حلو","price":55,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p228.jpg","oldPrice":75},
  {"name":"كاستا (وردة دجاج)","price":92,"category":"دجاج","image":"/assets/photos/ghasaq/p229.jpg","oldPrice":120},
  {"name":"خبز ابيض سوري (لبناني)","price":15,"category":"مخبوزات","image":"/assets/photos/ghasaq/p230.jpg","oldPrice":20},
  {"name":"شمندر (بنجر)","price":39,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p231.jpg","oldPrice":49},
  {"name":"كيوي","price":55,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p232.jpg","oldPrice":110},
  {"name":"موز مستورد","price":110,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p233.jpg","oldPrice":140},
  {"name":"فلفل احمر حار (حراق)","price":75,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p234.jpg","oldPrice":90},
  {"name":"برتقال","price":39,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p235.jpg","oldPrice":55},
  {"name":"تفاح اصفر","price":65,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p236.jpg","oldPrice":75},
  {"name":"تفاح احمر","price":65,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p237.jpg","oldPrice":80},
  {"name":"خرما/خرمسي/كاكا (درابزين)","price":60,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p238.jpg","oldPrice":75},
  {"name":"بصل ممتاز كبير","price":15,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p239.jpg","oldPrice":20},
  {"name":"ثوم ناشف (يابس بلدي)","price":175,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p240.jpg","oldPrice":200},
  {"name":"فلافل حنيف","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p241.jpg","oldPrice":65},
  {"name":"فول هنا بالكمون","price":25,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p242.jpg","oldPrice":28},
  {"name":"شطة جلوريا","price":25,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p243.jpg","oldPrice":35},
  {"name":"فول هنا سادة","price":25,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p244.jpg","oldPrice":28},
  {"name":"متة خارطة 250غرام البيضاء الأصلية","price":80,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p245.jpg","oldPrice":90},
  {"name":"مرتديلا هنا منكهة 200غرام","price":35,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p246.jpg","oldPrice":40,"description":"جبنة/فطر/مدخنة/سادة"},
  {"name":"متة خارطة 250غرام. الخضراء الأصلية","price":80,"category":"مشروبات ساخنة","image":"/assets/photos/ghasaq/p247.jpg","oldPrice":90},
  {"name":"قشطة قيمر متوفر عرض3علب 90ليرة","price":35,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p248.jpg","oldPrice":50,"description":"125غرام"},
  {"name":"سردين مغربي أصلي","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p249.jpg","oldPrice":70},
  {"name":"ليوس سمك تونا 160غرام (علبة حمراء)","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p250.jpg","oldPrice":70},
  {"name":"ليوس سمك تونا 160غرام (علبة صفراء)","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p251.jpg","oldPrice":70},
  {"name":"سمك تونا حار (حد 160غرام)","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p252.jpg","oldPrice":65},
  {"name":"سمك تونا معلب 160غرام","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p253.jpg","oldPrice":65},
  {"name":"مرتديلا هنا 380غرام","price":55,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p254.jpg","oldPrice":75},
  {"name":"مرتديلا هنا 200غرام","price":35,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p255.jpg","oldPrice":45},
  {"name":"مرتديلا هنا 830غرام","price":110,"category":"معلبات وكونسروة","image":"/assets/photos/ghasaq/p256.jpg","oldPrice":160},
  {"name":"صدر دجاج من دون جلد /مسحب (سعر الكيلو)","price":140,"category":"دجاج","image":"/assets/photos/ghasaq/p257.jpg","oldPrice":180},
  {"name":"كبدة دجاج (سودة)","price":65,"category":"دجاج","image":"/assets/photos/ghasaq/p258.jpg","oldPrice":70},
  {"name":"دبوس دجاج","price":85,"category":"دجاج","image":"/assets/photos/ghasaq/p259.jpg","oldPrice":100},
  {"name":"بطاطا (بطاطس)","price":22,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p260.jpg","oldPrice":28,"description":"مالحة كبيرة للقلي"},
  {"name":"طماطم (بندورة)","price":49,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p261.jpg","oldPrice":60},
  {"name":"خيار بلدي","price":55,"category":"الخضار والفواكه","image":"/assets/photos/ghasaq/p262.jpg","oldPrice":65},
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const ghasaqProductCatalog = [];

const ghasaqProducts = (ghasaqProductCatalog.length ? ghasaqProductCatalog : ghasaqFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1990001 + index,
  storeId: ghasaqStore.id
}));

const ghasaqDeliverySettings = {
  [ghasaqStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 30, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ghasaqStore, ghasaqProducts, ghasaqDeliverySettings };
}
