// Generated for مطاعم حضرموت اليمن (HADRAMOUT YEMEN RESTAURANT) — حي الفاتح، بجانب حديقة يوسف باشا، الفاتح/إسطنبول.
// Authentic Yemeni (Hadhrami) restaurant. Source: qrlist.app/hadrmout2 (qrlist digital menu, native Arabic, prices in TL).
// 156 source items -> 151 products (dropped 5 logo-placeholder/imageless items: 12374,12375,12380,12381,12384).
// Every published product has a unique real photo (a few close variant dishes reuse one source photo under a unique path).
// Coords 41.010928527133,28.947461843491 (qrlist store location, Fatih) + Google place_id ChIJQSKztyi6yhQRjwp3i6jIRM4.
// NOTE: hadramoutProductCatalog is intentionally emptied in the repo (perf) — the full catalog lives in Supabase
// and is pushed via scripts/_scrape/push-store.cjs.

const hadramoutStore = {
 "id": 72,
 "name": "مطاعم حضرموت اليمن",
 "category": "مطاعم",
 "image": "/assets/photos/hadramout/cover.jpg",
 "coverImage": "/assets/photos/hadramout/cover.jpg",
 "logoImage": "/assets/photos/hadramout/logo.png",
 "logo": "ح",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "45 - 75 دقيقة",
 "distance": 0,
 "location": {
  "lat": 41.010928527133,
  "lng": 28.947461843491
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.010929%2C28.947462&query_place_id=ChIJQSKztyi6yhQRjwp3i6jIRM4",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "مطاعم حضرموت اليمن — نكهة يمنية حضرمية أصيلة في قلب الفاتح بإسطنبول. مندي ومضغوط ومظبي وزربيان وبرياني وحنيذ من اللحم والدجاج، ذبائح كاملة، أطباق المطبخ اليمني الشعبية (سلته، فحسة، فاصولية حرضة، فول، كبدة، صالونة، عقدة)، أسماك، ومخبوزات حضرمية (معصوب، عريكة، فتة، خبز ملوّح وخبز رطب بالعسل)، إلى جانب المقبلات والسلطات والعصائر الطبيعية الطازجة والمشروبات الساخنة. توصيل إلى باب منزلك.",
 "address": "حي الفاتح — بجانب حديقة يوسف باشا، إسطنبول، تركيا",
 "phone": "+90 535 401 01 23",
 "whatsapp": "+90 535 401 01 23",
 "email": null,
 "website": "https://qrlist.app/hadrmout2",
 "sourceUrl": "https://qrlist.app/hadrmout2",
 "hours": "10:00 ص - 12:00 م",
 "areas": [
  "الفاتح",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

// Full catalog used ONLY for the Supabase push; emptied in the committed repo (see note above).
const hadramoutFullCatalog = [
 {"name":"خبز رطب مع عسل","price":100,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-657.jpg","sourceId":657},
 {"name":"خبز رطب صغير","price":60,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-658.jpg","sourceId":658},
 {"name":"خبز ملوح دبل","price":70,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-659.jpg","sourceId":659},
 {"name":"خبز ملوح عادي","price":60,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-660.jpg","sourceId":660},
 {"name":"عريكة","price":210,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-663.jpg","sourceId":663},
 {"name":"فتة تمر بالعسل","price":170,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-664.jpg","sourceId":664},
 {"name":"فتة تمر","price":150,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-665.jpg","sourceId":665},
 {"name":"فتة زبيدي","price":150,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-666.jpg","sourceId":666},
 {"name":"فتة موز بالعسل","price":170,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-667.jpg","sourceId":667},
 {"name":"فتة بالموز","price":150,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-668.jpg","sourceId":668},
 {"name":"معصوبه","price":210,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-669.jpg","sourceId":669},
 {"name":"عريكة كرافت","price":250,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-670.jpg","sourceId":670},
 {"name":"معصوبة كرافت","price":250,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-671.jpg","sourceId":671},
 {"name":"خبز رطب كبير","price":70,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-1113.jpg","sourceId":1113},
 {"name":"فتة عسل","price":160,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-12376.jpg","sourceId":12376},
 {"name":"ملوح بالعسل","price":100,"category":"المخبازة","unit":"طبق","image":"/assets/photos/hadramout/m-12377.jpg","sourceId":12377},
 {"name":"بابا غنوج","price":150,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-674.jpg","sourceId":674},
 {"name":"تبولة","price":170,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-675.jpg","sourceId":675},
 {"name":"حمص","price":150,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-676.jpg","sourceId":676},
 {"name":"سلطة جرجير","price":170,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-677.jpg","sourceId":677},
 {"name":"سلطة شرقية","price":170,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-678.jpg","sourceId":678},
 {"name":"سلطة حضرموت","price":300,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-679.jpg","sourceId":679},
 {"name":"صحن فرنسي","price":300,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-680.jpg","sourceId":680},
 {"name":"فتوش","price":170,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-681.jpg","sourceId":681},
 {"name":"متبل","price":150,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-682.jpg","sourceId":682},
 {"name":"محمرة","price":150,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-683.jpg","sourceId":683},
 {"name":"خيار بالبن","price":80,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-685.jpg","sourceId":685},
 {"name":"لبن سادة","price":60,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-686.jpg","sourceId":686},
 {"name":"سحاوق مبسبس","price":30,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-687.jpg","sourceId":687},
 {"name":"سحاوق بالجبن","price":60,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-688.jpg","sourceId":688},
 {"name":"شوربة عدس","price":60,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-689.jpg","sourceId":689},
 {"name":"حمص","price":140,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-1089.jpg","sourceId":1089},
 {"name":"شوربة مرق","price":30,"category":"المقبلات","unit":"طبق","image":"/assets/photos/hadramout/m-1091.jpg","sourceId":1091},
 {"name":"سمك سلمون بدون الرز","price":520,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-661.jpg","sourceId":661},
 {"name":"سمك موفى بدون الرز","price":490,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-662.jpg","sourceId":662},
 {"name":"بامية دجاج","price":300,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-697.jpg","sourceId":697},
 {"name":"بامية سادة","price":220,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-698.jpg","sourceId":698},
 {"name":"بامية لحم","price":360,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-699.jpg","sourceId":699},
 {"name":"دقة لحم","price":320,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-700.jpg","sourceId":700},
 {"name":"سلته","price":320,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-701.jpg","sourceId":701},
 {"name":"شكشوكة","price":170,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-702.jpg","sourceId":702},
 {"name":"صالونة دجاج","price":280,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-703.jpg","sourceId":703},
 {"name":"صالونة سمك","price":390,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-704.jpg","sourceId":704},
 {"name":"صالونة لحم","price":350,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-705.jpg","sourceId":705},
 {"name":"عقدة سمك","price":350,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-706.jpg","sourceId":706},
 {"name":"عقدة لحم","price":330,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-708.jpg","sourceId":708},
 {"name":"فاصولية حرضة سادة","price":200,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-709.jpg","sourceId":709},
 {"name":"فحسة","price":450,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-710.jpg","sourceId":710},
 {"name":"فول حرضة بالدقة","price":270,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-711.jpg","sourceId":711},
 {"name":"فول حرضة سادة","price":190,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-712.jpg","sourceId":712},
 {"name":"كبدة غنم","price":280,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-713.jpg","sourceId":713},
 {"name":"لحم صغار","price":330,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-715.jpg","sourceId":715},
 {"name":"مشكل خضار حرضة","price":200,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-716.jpg","sourceId":716},
 {"name":"مشكل فرن","price":200,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-720.jpg","sourceId":720},
 {"name":"دقة بالبيض","price":260,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-727.jpg","sourceId":727},
 {"name":"سمك سلمون مع الرز","price":560,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-1106.jpg","sourceId":1106},
 {"name":"سمك موفى مع الرز","price":520,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-1107.jpg","sourceId":1107},
 {"name":"عقدة دجاج","price":250,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-1108.jpg","sourceId":1108},
 {"name":"فاصولية حرضة بالتونا","price":220,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-1110.jpg","sourceId":1110},
 {"name":"فاصولية حرضة بالبيض","price":200,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-1111.jpg","sourceId":1111},
 {"name":"بيض بالجبنة","price":200,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-1112.jpg","sourceId":1112},
 {"name":"مكس سلتة فحسة","price":390,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-12370.jpg","sourceId":12370},
 {"name":"بيض مقلي","price":170,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-12371.jpg","sourceId":12371},
 {"name":"بيض ساده","price":170,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-12372.jpg","sourceId":12372},
 {"name":"بيض عيون","price":170,"category":"القلابات والمشكلات","unit":"طبق","image":"/assets/photos/hadramout/m-12373.jpg","sourceId":12373},
 {"name":"برياني دجاج حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-733.jpg","sourceId":733},
 {"name":"برياني لحم 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-734.jpg","sourceId":734},
 {"name":"دجاج حضرموت حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-735.jpg","sourceId":735},
 {"name":"دجاج حنيذ حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-736.jpg","sourceId":736},
 {"name":"دجاج زربيان حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-737.jpg","sourceId":737},
 {"name":"دجاج مظبي حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-738.jpg","sourceId":738},
 {"name":"دجاج مندي حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-739.jpg","sourceId":739},
 {"name":"ذبيحة","price":13000,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-740.jpg","sourceId":740},
 {"name":"لحم الديرة 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-742.jpg","sourceId":742},
 {"name":"لحم حنيذ 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-745.jpg","sourceId":745},
 {"name":"مضغوط دجاج حبة دجاج","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-749.jpg","sourceId":749},
 {"name":"لحم مندي 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1092.jpg","sourceId":1092},
 {"name":"اللحم الحضرمي 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1093.jpg","sourceId":1093},
 {"name":"لحم مضغوط 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1094.jpg","sourceId":1094},
 {"name":"زربيان لحم ثلاث قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1095.jpg","sourceId":1095},
 {"name":"لحم شيباني 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1096.jpg","sourceId":1096},
 {"name":"لحم برم 3 قطع","price":680,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1097.jpg","sourceId":1097},
 {"name":"دجاج مندي نصف دجاجة","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1098.jpg","sourceId":1098},
 {"name":"مضغوط دجاج نصف دجاجة","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1100.jpg","sourceId":1100},
 {"name":"دجاج حنيذ نصف دجاجة","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1101.jpg","sourceId":1101},
 {"name":"دجاج حضرموت نصف دجاجة","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1102.jpg","sourceId":1102},
 {"name":"دجاج مظبي نصف دجاجة","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1103.jpg","sourceId":1103},
 {"name":"برياني دجاج نصف دجاجة","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1104.jpg","sourceId":1104},
 {"name":"نصف دجاجة زربيان","price":340,"category":"المطبخ اليمني","unit":"طبق","image":"/assets/photos/hadramout/m-1105.jpg","sourceId":1105},
 {"name":"سلطة الفواكه","price":300,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-750.jpg","sourceId":750},
 {"name":"عصيرمانجو","price":160,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-751.jpg","sourceId":751},
 {"name":"عصير برتقال","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-752.jpg","sourceId":752},
 {"name":"عصير كيوي","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-753.jpg","sourceId":753},
 {"name":"فريز بالحليب","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-754.jpg","sourceId":754},
 {"name":"موز بالحليب","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-757.jpg","sourceId":757},
 {"name":"موز وحليب وعسل","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-758.jpg","sourceId":758},
 {"name":"موز ومنغا","price":160,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-763.jpg","sourceId":763},
 {"name":"موز ومنغا وافكادو","price":170,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-764.jpg","sourceId":764},
 {"name":"منغا وشمام","price":160,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-767.jpg","sourceId":767},
 {"name":"منغا وفريز","price":160,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-768.jpg","sourceId":768},
 {"name":"منغا وافوكادو","price":170,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-769.jpg","sourceId":769},
 {"name":"منغا بالحليب","price":170,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-770.jpg","sourceId":770},
 {"name":"ليمون بالحليب","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-771.jpg","sourceId":771},
 {"name":"كوكتيل فواكه بالحليب","price":160,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-772.jpg","sourceId":772},
 {"name":"عرايسي حضرموت","price":230,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-774.jpg","sourceId":774},
 {"name":"افكادو بالحليب","price":170,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-776.jpg","sourceId":776},
 {"name":"افكادو بالمكسرات","price":190,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-777.jpg","sourceId":777},
 {"name":"كوكتيل فواكه","price":160,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1114.jpg","sourceId":1114},
 {"name":"افوكادو","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1115.jpg","sourceId":1115},
 {"name":"فراولة","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1116.jpg","sourceId":1116},
 {"name":"عصير الليمون","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1117.jpg","sourceId":1117},
 {"name":"بولو","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1118.jpg","sourceId":1118},
 {"name":"عصير جزر","price":60,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1119.jpg","sourceId":1119},
 {"name":"عصير رمان","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1120.jpg","sourceId":1120},
 {"name":"عصير شمام","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1121.jpg","sourceId":1121},
 {"name":"عصير بطيخ","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1122.jpg","sourceId":1122},
 {"name":"عرائسي","price":230,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1123.jpg","sourceId":1123},
 {"name":"جمايكا","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1124.jpg","sourceId":1124},
 {"name":"عصير تفاح","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1125.jpg","sourceId":1125},
 {"name":"أمبراطور نكهة خاصة","price":180,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1126.jpg","sourceId":1126},
 {"name":"أناناس","price":130,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1128.jpg","sourceId":1128},
 {"name":"أناناس بالبرتقال","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1130.jpg","sourceId":1130},
 {"name":"سلطة فواكه تويكس","price":320,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1131.jpg","sourceId":1131},
 {"name":"سلطة فواكه كيت كات","price":320,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1132.jpg","sourceId":1132},
 {"name":"أناناس بالحليب","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1134.jpg","sourceId":1134},
 {"name":"كيوي بالحليب","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-1135.jpg","sourceId":1135},
 {"name":"موز وحليب","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-12382.jpg","sourceId":12382},
 {"name":"موز حليب وفريز","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-12383.jpg","sourceId":12383},
 {"name":"اناناس باليمون","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-12385.jpg","sourceId":12385},
 {"name":"اناناس بالكيوي","price":140,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-12386.jpg","sourceId":12386},
 {"name":"مانجو بالحليب","price":170,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-12387.jpg","sourceId":12387},
 {"name":"شمام بالحليب","price":150,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-12388.jpg","sourceId":12388},
 {"name":"حبة موز","price":50,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-19245.jpg","sourceId":19245},
 {"name":"أفوكادو وموز وحليب","price":170,"category":"عصائر طبيعية","unit":"كوب","image":"/assets/photos/hadramout/m-20046.jpg","sourceId":20046},
 {"name":"شادي عدني","price":60,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-755.jpg","sourceId":755},
 {"name":"شاي الكبوس","price":30,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-756.jpg","sourceId":756},
 {"name":"شاي أخضر","price":40,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-779.jpg","sourceId":779},
 {"name":"شاي بالليمون","price":30,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-780.jpg","sourceId":780},
 {"name":"قهوة سورية","price":70,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-782.jpg","sourceId":782},
 {"name":"قهوة يمنية","price":70,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-783.jpg","sourceId":783},
 {"name":"قهوة عربية","price":70,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-784.jpg","sourceId":784},
 {"name":"اسبريسو","price":15,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-785.jpg","sourceId":785},
 {"name":"كابتشينو","price":60,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-786.jpg","sourceId":786},
 {"name":"نسكافيه بلاك","price":50,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-787.jpg","sourceId":787},
 {"name":"نسكافيه بالحليب","price":50,"category":"المشروبات الساخنة","unit":"كوب","image":"/assets/photos/hadramout/m-788.jpg","sourceId":788},
 {"name":"ماء","price":20,"category":"مشروبات غازية","unit":"كوب","image":"/assets/photos/hadramout/m-1136.jpg","sourceId":1136},
 {"name":"بيبسي","price":60,"category":"مشروبات غازية","unit":"كوب","image":"/assets/photos/hadramout/m-1137.jpg","sourceId":1137},
 {"name":"عيران","price":40,"category":"مشروبات غازية","unit":"كوب","image":"/assets/photos/hadramout/m-1138.jpg","sourceId":1138},
 {"name":"فانتا تنك","price":60,"category":"مشروبات غازية","unit":"كوب","image":"/assets/photos/hadramout/m-12378.jpg","sourceId":12378},
 {"name":"سفن اب","price":60,"category":"مشروبات غازية","unit":"كوب","image":"/assets/photos/hadramout/m-12379.jpg","sourceId":12379},
 {"name":"بيبسي دايت","price":60,"category":"مشروبات غازية","unit":"كوب","image":"/assets/photos/hadramout/m-20911.jpg","sourceId":20911}
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const hadramoutProductCatalog = [];

const hadramoutProducts = (hadramoutProductCatalog.length ? hadramoutProductCatalog : hadramoutFullCatalog).map((product, index) => ({
  ...product,
  available: product.available !== false,
  id: 1560001 + index,
  storeId: hadramoutStore.id
}));

const hadramoutDeliverySettings = {
  [hadramoutStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 45, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { hadramoutStore, hadramoutProducts, hadramoutDeliverySettings };
}