// Generated from the official Hallab 1881 (Al Hallab) FineDine menu — Nişantaşı/Şişli, İstanbul.
// Source API: api.finedinemenu.com (al-hallab-fisekhane). 237 items with the restaurant's
// own photos and Arabic names; prices in Turkish Lira. Alcohol sections were excluded (97 items).
const hallabStore = {
 "id": 49,
 "name": "حلاب 1881",
 "category": "مطاعم",
 "image": "/assets/photos/hallab/cover.jpg",
 "coverImage": "/assets/photos/hallab/cover.jpg",
 "logoImage": "/assets/photos/hallab/logo.svg",
 "logo": "ح",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 40,
 "minOrder": 200,
 "time": "40 - 70 دقيقة",
 "distance": 6,
 "location": {
  "lat": 41.049979,
  "lng": 28.991473
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.049979,28.991473",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "حلاب 1881 (Al Hallab): مطعم لبناني عريق في نيشانتاشي (شيشلي) يقدّم الفطور اللبناني والمقبلات الباردة والساخنة والمشاوي والفتّة واللحم والمعجنات والسلطات والحلويات اللبنانية الشهيرة والعصائر الطازجة. الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
 "address": "Harbiye Mah., Abdi İpekçi Cad. No:16, 34250 Şişli, İstanbul",
 "phone": "+902122241882",
 "whatsapp": "+905336881819",
 "email": "",
 "website": "https://hallabtr.com/",
 "sourceUrl": "https://qr.finedinemenu.com/al-hallab-fisekhane",
 "hours": "يومياً من الساعة 12:00 ظهراً",
 "areas": [
  "شيشلي",
  "نيشانتاشي",
  "هاربيه",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const hallabProductCatalog = [
 {
  "sourceId": "h001",
  "name": "(الفطور اللبناني (شخصين",
  "image": "/assets/photos/hallab/items/h001.webp",
  "price": 870,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "(الفطور اللبناني (شخصين من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h002",
  "name": "فطور تركي (لشخصين)",
  "image": "/assets/photos/hallab/items/h002.webp",
  "price": 870,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "فطور تركي (لشخصين) من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h003",
  "name": "حمص",
  "image": "/assets/photos/hallab/items/h003.webp",
  "price": 250,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حمص من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h004",
  "name": "حمص سيغنايتشر",
  "image": "/assets/photos/hallab/items/h004.webp",
  "price": 310,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حمص سيغنايتشر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h005",
  "name": "حمص بالفلفل الحار",
  "image": "/assets/photos/hallab/items/h005.webp",
  "price": 275,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حمص بالفلفل الحار من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h006",
  "name": "لبنة سيغنايتشر",
  "image": "/assets/photos/hallab/items/h006.webp",
  "price": 275,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "لبنة سيغنايتشر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h007",
  "name": "لبنة",
  "image": "/assets/photos/hallab/items/h007.webp",
  "price": 230,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "لبنة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h008",
  "name": "مكدوس باذنجان",
  "image": "/assets/photos/hallab/items/h008.webp",
  "price": 230,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "مكدوس باذنجان من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h009",
  "name": "Manakish Zaatar",
  "image": "/assets/photos/hallab/items/h009.webp",
  "price": 105,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "Manakish Zaatar من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h010",
  "name": "Manakish Jibni",
  "image": "/assets/photos/hallab/items/h010.webp",
  "price": 150,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "Manakish Jibni من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h011",
  "name": "Manakish Mix",
  "image": "/assets/photos/hallab/items/h011.webp",
  "price": 155,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "Manakish Mix من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h012",
  "name": "Lam Bejin",
  "image": "/assets/photos/hallab/items/h012.webp",
  "price": 160,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "Lam Bejin من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h013",
  "name": "Trabolsi",
  "image": "/assets/photos/hallab/items/h013.webp",
  "price": 275,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "Trabolsi من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h014",
  "name": "كنافة بالجبنة",
  "image": "/assets/photos/hallab/items/h014.webp",
  "price": 260,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "كنافة بالجبنة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h015",
  "name": "فتة حمص باللحمة",
  "image": "/assets/photos/hallab/items/h015.webp",
  "price": 440,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "فتة حمص باللحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h016",
  "name": "حمص باللحمة",
  "image": "/assets/photos/hallab/items/h016.webp",
  "price": 445,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حمص باللحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h017",
  "name": "حمص بالصنوبر",
  "image": "/assets/photos/hallab/items/h017.webp",
  "price": 390,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حمص بالصنوبر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h018",
  "name": "حمص بليلة",
  "image": "/assets/photos/hallab/items/h018.webp",
  "price": 230,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حمص بليلة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h019",
  "name": "فول",
  "image": "/assets/photos/hallab/items/h019.webp",
  "price": 230,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "فول من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h020",
  "name": "فول بالطحينة",
  "image": "/assets/photos/hallab/items/h020.webp",
  "price": 250,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "فول بالطحينة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h021",
  "name": "فتة حمص",
  "image": "/assets/photos/hallab/items/h021.webp",
  "price": 340,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "فتة حمص من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h022",
  "name": "حلوم سيغنايتشر",
  "image": "/assets/photos/hallab/items/h022.webp",
  "price": 315,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "حلوم سيغنايتشر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h023",
  "name": "جبنة بلدي",
  "image": "/assets/photos/hallab/items/h023.webp",
  "price": 230,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "جبنة بلدي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h024",
  "name": "بيض",
  "image": "/assets/photos/hallab/items/h024.webp",
  "price": 230,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "بيض من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h025",
  "name": "بيض شكشوكة",
  "image": "/assets/photos/hallab/items/h025.webp",
  "price": 250,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "بيض شكشوكة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h026",
  "name": "بيض بالسجق",
  "image": "/assets/photos/hallab/items/h026.webp",
  "price": 310,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "بيض بالسجق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h027",
  "name": "فلافل",
  "image": "/assets/photos/hallab/items/h027.webp",
  "price": 300,
  "unit": "",
  "category": "فطور",
  "available": true,
  "featured": false,
  "description": "فلافل من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h028",
  "name": "برتقال",
  "image": "/assets/photos/hallab/items/h028.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "برتقال من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h029",
  "name": "تفاح",
  "image": "/assets/photos/hallab/items/h029.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "تفاح من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h030",
  "name": "جزر",
  "image": "/assets/photos/hallab/items/h030.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "جزر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h031",
  "name": "Pomegranate Juice",
  "image": "/assets/photos/hallab/items/h031.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "Pomegranate Juice من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h032",
  "name": "ليمون",
  "image": "/assets/photos/hallab/items/h032.webp",
  "price": 105,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "ليمون من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h033",
  "name": "ليمون بالنعناع",
  "image": "/assets/photos/hallab/items/h033.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "ليمون بالنعناع من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h034",
  "name": "Lemonade with Green Apple",
  "image": "/assets/photos/hallab/items/h034.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "Lemonade with Green Apple من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h035",
  "name": "Lemonade with Strawberry",
  "image": "/assets/photos/hallab/items/h035.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "Lemonade with Strawberry من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h036",
  "name": "Ginger Lemonade",
  "image": "/assets/photos/hallab/items/h036.webp",
  "price": 115,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "Ginger Lemonade من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h037",
  "name": "مياه محلية كبيرة",
  "image": "/assets/photos/hallab/items/h037.webp",
  "price": 75,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "مياه محلية كبيرة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h038",
  "name": "مياه غازية",
  "image": "/assets/photos/hallab/items/h038.webp",
  "price": 70,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "مياه غازية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h039",
  "name": "عيران",
  "image": "/assets/photos/hallab/items/h039.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "عيران من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h040",
  "name": "بيبسي",
  "image": "/assets/photos/hallab/items/h040.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "بيبسي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h041",
  "name": "كوكا كولا زيرو",
  "image": "/assets/photos/hallab/items/h041.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "كوكا كولا زيرو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h042",
  "name": "بيبسي دايت",
  "image": "/assets/photos/hallab/items/h042.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "بيبسي دايت من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h043",
  "name": "سبريت",
  "image": "/assets/photos/hallab/items/h043.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "سبريت من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h044",
  "name": "شويبس ماندرين",
  "image": "/assets/photos/hallab/items/h044.webp",
  "price": 105,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "شويبس ماندرين من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h045",
  "name": "شويبس بيتر ليمون",
  "image": "/assets/photos/hallab/items/h045.webp",
  "price": 105,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "شويبس بيتر ليمون من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h046",
  "name": "شويبس تونيك",
  "image": "/assets/photos/hallab/items/h046.webp",
  "price": 105,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "شويبس تونيك من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h047",
  "name": "شاي الخوخ",
  "image": "/assets/photos/hallab/items/h047.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "شاي الخوخ من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h048",
  "name": "شاي الليمون",
  "image": "/assets/photos/hallab/items/h048.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "شاي الليمون من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h049",
  "name": "RedBull Enerji İçeceği",
  "image": "/assets/photos/hallab/items/h049.webp",
  "price": 185,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "RedBull Enerji İçeceği من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h050",
  "name": "Red Bull Sugarfree",
  "image": "/assets/photos/hallab/items/h050.webp",
  "price": 185,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "Red Bull Sugarfree من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h051",
  "name": "شاي",
  "image": "/assets/photos/hallab/items/h051.webp",
  "price": 50,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h052",
  "name": "قهوة تركي",
  "image": "/assets/photos/hallab/items/h052.webp",
  "price": 115,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "قهوة تركي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h053",
  "name": "إسبرسو",
  "image": "/assets/photos/hallab/items/h053.webp",
  "price": 115,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "إسبرسو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h054",
  "name": "كافيه لاتيه",
  "image": "/assets/photos/hallab/items/h054.webp",
  "price": 145,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "كافيه لاتيه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h055",
  "name": "كابوتشينو",
  "image": "/assets/photos/hallab/items/h055.webp",
  "price": 145,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "كابوتشينو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h056",
  "name": "Mocha",
  "image": "/assets/photos/hallab/items/h056.webp",
  "price": 145,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "Mocha من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h057",
  "name": "White Chocolate Mocha",
  "image": "/assets/photos/hallab/items/h057.webp",
  "price": 145,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "White Chocolate Mocha من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h059",
  "name": "أمريكانو",
  "image": "/assets/photos/hallab/items/h059.webp",
  "price": 140,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "أمريكانو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h060",
  "name": "شاي بالاعشاب",
  "image": "/assets/photos/hallab/items/h060.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي بالاعشاب من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h061",
  "name": "Hot Chocolate",
  "image": "/assets/photos/hallab/items/h061.webp",
  "price": 145,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "Hot Chocolate من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h062",
  "name": "Sahlep",
  "image": "/assets/photos/hallab/items/h062.webp",
  "price": 145,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "Sahlep من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h063",
  "name": "شوربة عدس",
  "image": "/assets/photos/hallab/items/h063.webp",
  "price": 145,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "شوربة عدس من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h064",
  "name": "شوربة فطر",
  "image": "/assets/photos/hallab/items/h064.webp",
  "price": 165,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "شوربة فطر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h065",
  "name": "سلطة حرة",
  "image": "/assets/photos/hallab/items/h065.webp",
  "price": 250,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "سلطة حرة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h066",
  "name": "فتوش",
  "image": "/assets/photos/hallab/items/h066.webp",
  "price": 260,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "فتوش من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h067",
  "name": "تبولة",
  "image": "/assets/photos/hallab/items/h067.webp",
  "price": 260,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "تبولة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h068",
  "name": "سلطة جرجير وزعتر",
  "image": "/assets/photos/hallab/items/h068.webp",
  "price": 260,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "سلطة جرجير وزعتر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h069",
  "name": "سلطة يونانية",
  "image": "/assets/photos/hallab/items/h069.webp",
  "price": 305,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "سلطة يونانية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h070",
  "name": "تبولة كينوا",
  "image": "/assets/photos/hallab/items/h070.webp",
  "price": 300,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "تبولة كينوا من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h071",
  "name": "تمر جرجير",
  "image": "/assets/photos/hallab/items/h071.webp",
  "price": 320,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "تمر جرجير من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h072",
  "name": "سلطة سيزار مع الدجاج",
  "image": "/assets/photos/hallab/items/h072.webp",
  "price": 360,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "سلطة سيزار مع الدجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h073",
  "name": "سلطة سيزر بالقريدس",
  "image": "/assets/photos/hallab/items/h073.webp",
  "price": 870,
  "unit": "",
  "category": "سلطات",
  "available": true,
  "featured": false,
  "description": "سلطة سيزر بالقريدس من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h074",
  "name": "مازة رباعي",
  "image": "/assets/photos/hallab/items/h074.webp",
  "price": 730,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "مازة رباعي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h078",
  "name": "متبل",
  "image": "/assets/photos/hallab/items/h078.webp",
  "price": 250,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "متبل من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h079",
  "name": "بابا غنوج",
  "image": "/assets/photos/hallab/items/h079.webp",
  "price": 250,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "بابا غنوج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h080",
  "name": "متبل شمندر",
  "image": "/assets/photos/hallab/items/h080.webp",
  "price": 250,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "متبل شمندر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h081",
  "name": "محمرة",
  "image": "/assets/photos/hallab/items/h081.webp",
  "price": 250,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "محمرة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h082",
  "name": "ورق عنب",
  "image": "/assets/photos/hallab/items/h082.webp",
  "price": 315,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "ورق عنب من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h083",
  "name": "سمكة حرة",
  "image": "/assets/photos/hallab/items/h083.webp",
  "price": 495,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "سمكة حرة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h084",
  "name": "لوبية بالزيت",
  "image": "/assets/photos/hallab/items/h084.webp",
  "price": 300,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "لوبية بالزيت من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h085",
  "name": "سلق بلوبيه",
  "image": "/assets/photos/hallab/items/h085.webp",
  "price": 300,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "سلق بلوبيه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h090",
  "name": "لبن بالخيار",
  "image": "/assets/photos/hallab/items/h090.webp",
  "price": 225,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "لبن بالخيار من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h091",
  "name": "كبيس خيار",
  "image": "/assets/photos/hallab/items/h091.webp",
  "price": 100,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "كبيس خيار من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h092",
  "name": "زيتون مشكل",
  "image": "/assets/photos/hallab/items/h092.webp",
  "price": 100,
  "unit": "",
  "category": "مقبلات باردة",
  "available": true,
  "featured": false,
  "description": "زيتون مشكل من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h093",
  "name": "شاورما لحمة",
  "image": "/assets/photos/hallab/items/h093.webp",
  "price": 485,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "شاورما لحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h094",
  "name": "شاورما دجاج",
  "image": "/assets/photos/hallab/items/h094.webp",
  "price": 475,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "شاورما دجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h097",
  "name": "مقانق",
  "image": "/assets/photos/hallab/items/h097.webp",
  "price": 445,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "مقانق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h098",
  "name": "كبدة دجاج",
  "image": "/assets/photos/hallab/items/h098.webp",
  "price": 435,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "كبدة دجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h099",
  "name": "كبدة غنم مقلية",
  "image": "/assets/photos/hallab/items/h099.webp",
  "price": 455,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "كبدة غنم مقلية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h100",
  "name": "قلاية لحمة بالفطر",
  "image": "/assets/photos/hallab/items/h100.webp",
  "price": 445,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "قلاية لحمة بالفطر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h101",
  "name": "كفته بالرمان",
  "image": "/assets/photos/hallab/items/h101.webp",
  "price": 445,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "كفته بالرمان من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h103",
  "name": "بطاطا حارة",
  "image": "/assets/photos/hallab/items/h103.webp",
  "price": 300,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "بطاطا حارة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h105",
  "name": "لفائف المسخن",
  "image": "/assets/photos/hallab/items/h105.webp",
  "price": 285,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "لفائف المسخن من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h106",
  "name": "كبة حميص سيغنايتشر",
  "image": "/assets/photos/hallab/items/h106.webp",
  "price": 390,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "كبة حميص سيغنايتشر من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h107",
  "name": "كبة لحمة",
  "image": "/assets/photos/hallab/items/h107.webp",
  "price": 285,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "كبة لحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h108",
  "name": "رقاقات جبنة",
  "image": "/assets/photos/hallab/items/h108.webp",
  "price": 275,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "رقاقات جبنة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h109",
  "name": "سمبوسك جبنة",
  "image": "/assets/photos/hallab/items/h109.webp",
  "price": 275,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "سمبوسك جبنة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h110",
  "name": "سمبوسك لحمة",
  "image": "/assets/photos/hallab/items/h110.webp",
  "price": 275,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "سمبوسك لحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h111",
  "name": "معجنات مشكلة",
  "image": "/assets/photos/hallab/items/h111.webp",
  "price": 450,
  "unit": "",
  "category": "مقبلات ساخنة",
  "available": true,
  "featured": false,
  "description": "معجنات مشكلة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h113",
  "name": "فتة باذنجان",
  "image": "/assets/photos/hallab/items/h113.webp",
  "price": 360,
  "unit": "",
  "category": "فتات",
  "available": true,
  "featured": false,
  "description": "فتة باذنجان من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h114",
  "name": "فتة  لحمة",
  "image": "/assets/photos/hallab/items/h114.webp",
  "price": 460,
  "unit": "",
  "category": "فتات",
  "available": true,
  "featured": false,
  "description": "فتة  لحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h116",
  "name": "كبة نية",
  "image": "/assets/photos/hallab/items/h116.webp",
  "price": 435,
  "unit": "",
  "category": "لحمة نية",
  "available": true,
  "featured": false,
  "description": "كبة نية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h117",
  "name": "هبرة نية تابلة",
  "image": "/assets/photos/hallab/items/h117.webp",
  "price": 435,
  "unit": "",
  "category": "لحمة نية",
  "available": true,
  "featured": false,
  "description": "هبرة نية تابلة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h118",
  "name": "كفتة نية",
  "image": "/assets/photos/hallab/items/h118.webp",
  "price": 495,
  "unit": "",
  "category": "لحمة نية",
  "available": true,
  "featured": false,
  "description": "كفتة نية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h119",
  "name": "لوحة نية",
  "image": "/assets/photos/hallab/items/h119.webp",
  "price": 670,
  "unit": "",
  "category": "لحمة نية",
  "available": true,
  "featured": false,
  "description": "لوحة نية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h121",
  "name": "لحم بالعجين تركي",
  "image": "/assets/photos/hallab/items/h121.webp",
  "price": 160,
  "unit": "",
  "category": "معجنات",
  "available": true,
  "featured": false,
  "description": "لحم بالعجين تركي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h126",
  "name": "كتف خروف مشوي",
  "image": "/assets/photos/hallab/items/h126.webp",
  "price": 4895,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "كتف خروف مشوي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h127",
  "name": "خروف محشي",
  "image": "/assets/photos/hallab/items/h127.webp",
  "price": 655,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "خروف محشي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h128",
  "name": "فريكه باللحمة",
  "image": "/assets/photos/hallab/items/h128.webp",
  "price": 655,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "فريكه باللحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h129",
  "name": "برياني لحمة",
  "image": "/assets/photos/hallab/items/h129.webp",
  "price": 655,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "برياني لحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h130",
  "name": "كبه لبنيه مع ارز",
  "image": "/assets/photos/hallab/items/h130.webp",
  "price": 635,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "كبه لبنيه مع ارز من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h131",
  "name": "Oriental Rice w. Chicken",
  "image": "/assets/photos/hallab/items/h131.webp",
  "price": 640,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "Oriental Rice w. Chicken من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h132",
  "name": "برياني دجاج",
  "image": "/assets/photos/hallab/items/h132.webp",
  "price": 640,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "برياني دجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h133",
  "name": "فريكة الدجاج",
  "image": "/assets/photos/hallab/items/h133.webp",
  "price": 640,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "فريكة الدجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h134",
  "name": "دجاج سوبريم",
  "image": "/assets/photos/hallab/items/h134.webp",
  "price": 680,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "دجاج سوبريم من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h135",
  "name": "اسكالوب دجاج",
  "image": "/assets/photos/hallab/items/h135.webp",
  "price": 615,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "اسكالوب دجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h136",
  "name": "أصابع الدجاج المقلية",
  "image": "/assets/photos/hallab/items/h136.webp",
  "price": 605,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "أصابع الدجاج المقلية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h137",
  "name": "دجاج بارميجانا",
  "image": "/assets/photos/hallab/items/h137.webp",
  "price": 645,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "دجاج بارميجانا من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h138",
  "name": "صيادية سمك",
  "image": "/assets/photos/hallab/items/h138.webp",
  "price": 650,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "صيادية سمك من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h139",
  "name": "قريدس بانيه",
  "image": "/assets/photos/hallab/items/h139.webp",
  "price": 1045,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "قريدس بانيه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h140",
  "name": "بامية باللحمة",
  "image": "/assets/photos/hallab/items/h140.webp",
  "price": 640,
  "unit": "",
  "category": "أكلات من المطبخ",
  "available": true,
  "featured": false,
  "description": "بامية باللحمة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h141",
  "name": "مشكل مع طاووق",
  "image": "/assets/photos/hallab/items/h141.webp",
  "price": 825,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "مشكل مع طاووق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h142",
  "name": "كباب لبناني",
  "image": "/assets/photos/hallab/items/h142.webp",
  "price": 605,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كباب لبناني من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h143",
  "name": "أضنة كباب",
  "image": "/assets/photos/hallab/items/h143.webp",
  "price": 605,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "أضنة كباب من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h144",
  "name": "تبسي كباب",
  "image": "/assets/photos/hallab/items/h144.webp",
  "price": 640,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "تبسي كباب من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h145",
  "name": "كباب محشو بالجبنة",
  "image": "/assets/photos/hallab/items/h145.webp",
  "price": 580,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كباب محشو بالجبنة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h146",
  "name": "كباب خشخاش",
  "image": "/assets/photos/hallab/items/h146.webp",
  "price": 615,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كباب خشخاش من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h147",
  "name": "كباب بالفستق",
  "image": "/assets/photos/hallab/items/h147.webp",
  "price": 635,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كباب بالفستق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h148",
  "name": "كباب باتنجان",
  "image": "/assets/photos/hallab/items/h148.webp",
  "price": 605,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كباب باتنجان من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h149",
  "name": "كباب اورفلي",
  "image": "/assets/photos/hallab/items/h149.webp",
  "price": 605,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كباب اورفلي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h150",
  "name": "عرايس",
  "image": "/assets/photos/hallab/items/h150.webp",
  "price": 490,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "عرايس من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h151",
  "name": "شقف لحم مشوي",
  "image": "/assets/photos/hallab/items/h151.webp",
  "price": 825,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "شقف لحم مشوي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h152",
  "name": "ريش غنم",
  "image": "/assets/photos/hallab/items/h152.webp",
  "price": 860,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "ريش غنم من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h153",
  "name": "كبدة غنم مشوية",
  "image": "/assets/photos/hallab/items/h153.webp",
  "price": 785,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "كبدة غنم مشوية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h154",
  "name": "لحم شيشليك",
  "image": "/assets/photos/hallab/items/h154.webp",
  "price": 935,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "لحم شيشليك من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h155",
  "name": "تندرليون ستيك مع صلصة البهار",
  "image": "/assets/photos/hallab/items/h155.webp",
  "price": 935,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "تندرليون ستيك مع صلصة البهار من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h156",
  "name": "شيش طاووق",
  "image": "/assets/photos/hallab/items/h156.webp",
  "price": 605,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "شيش طاووق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h157",
  "name": "نصف دجاج مسحب",
  "image": "/assets/photos/hallab/items/h157.webp",
  "price": 595,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "نصف دجاج مسحب من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h158",
  "name": "جوانح دجاج",
  "image": "/assets/photos/hallab/items/h158.webp",
  "price": 585,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "جوانح دجاج من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h159",
  "name": "فيليه سيباس",
  "image": "/assets/photos/hallab/items/h159.webp",
  "price": 895,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "فيليه سيباس من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h160",
  "name": "جمبري جامبو",
  "image": "/assets/photos/hallab/items/h160.webp",
  "price": 1095,
  "unit": "",
  "category": "مشويات",
  "available": true,
  "featured": false,
  "description": "جمبري جامبو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h161",
  "name": "ارز ابيض",
  "image": "/assets/photos/hallab/items/h161.webp",
  "price": 140,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "ارز ابيض من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h162",
  "name": "ارز بالزعفران",
  "image": "/assets/photos/hallab/items/h162.webp",
  "price": 170,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "ارز بالزعفران من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h163",
  "name": "برغل",
  "image": "/assets/photos/hallab/items/h163.webp",
  "price": 140,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "برغل من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h164",
  "name": "فريكه",
  "image": "/assets/photos/hallab/items/h164.webp",
  "price": 140,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "فريكه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h165",
  "name": "خضار سوتيه",
  "image": "/assets/photos/hallab/items/h165.webp",
  "price": 140,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "خضار سوتيه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h166",
  "name": "بطاطا مقلية",
  "image": "/assets/photos/hallab/items/h166.webp",
  "price": 140,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "بطاطا مقلية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h167",
  "name": "سبانغ سوتيه",
  "image": "/assets/photos/hallab/items/h167.webp",
  "price": 140,
  "unit": "",
  "category": "أطباق جانبية",
  "available": true,
  "featured": false,
  "description": "سبانغ سوتيه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h168",
  "name": "ساندويش فلافل",
  "image": "/assets/photos/hallab/items/h168.webp",
  "price": 450,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "ساندويش فلافل من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h169",
  "name": "لحم بعجين",
  "image": "/assets/photos/hallab/items/h169.webp",
  "price": 440,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "لحم بعجين من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h170",
  "name": "برغر بالجبنة",
  "image": "/assets/photos/hallab/items/h170.webp",
  "price": 495,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "برغر بالجبنة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h171",
  "name": "Chicken Shawarma Wrap Menu",
  "image": "/assets/photos/hallab/items/h171.webp",
  "price": 485,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "Chicken Shawarma Wrap Menu من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h172",
  "name": "Meat Shawarma Wrap Menu",
  "image": "/assets/photos/hallab/items/h172.webp",
  "price": 495,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "Meat Shawarma Wrap Menu من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h173",
  "name": "Wrap Kebab Menu",
  "image": "/assets/photos/hallab/items/h173.webp",
  "price": 495,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "Wrap Kebab Menu من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h174",
  "name": "Lamb Shish Wrap Menu",
  "image": "/assets/photos/hallab/items/h174.webp",
  "price": 540,
  "unit": "",
  "category": "البرغر والسندويشات",
  "available": true,
  "featured": false,
  "description": "Lamb Shish Wrap Menu من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h176",
  "name": "فطيرة الفستق",
  "image": "/assets/photos/hallab/items/h176.webp",
  "price": 320,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فطيرة الفستق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h177",
  "name": "عثملية بالقشطة",
  "image": "/assets/photos/hallab/items/h177.webp",
  "price": 275,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "عثملية بالقشطة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h178",
  "name": "حلاوة الجبن ملفوفة",
  "image": "/assets/photos/hallab/items/h178.webp",
  "price": 275,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "حلاوة الجبن ملفوفة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h179",
  "name": "زنود بالقشطة",
  "image": "/assets/photos/hallab/items/h179.webp",
  "price": 275,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "زنود بالقشطة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h180",
  "name": "معمول بالقشطة",
  "image": "/assets/photos/hallab/items/h180.webp",
  "price": 230,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "معمول بالقشطة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h181",
  "name": "مفروكه",
  "image": "/assets/photos/hallab/items/h181.webp",
  "price": 275,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "مفروكه من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h182",
  "name": "ورد الشام",
  "image": "/assets/photos/hallab/items/h182.webp",
  "price": 275,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "ورد الشام من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h183",
  "name": "بقلاوة مشكلة",
  "image": "/assets/photos/hallab/items/h183.webp",
  "price": 320,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "بقلاوة مشكلة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h184",
  "name": "مهلبية مع فستق",
  "image": "/assets/photos/hallab/items/h184.webp",
  "price": 200,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "مهلبية مع فستق من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h185",
  "name": "الارز بالحليب",
  "image": "/assets/photos/hallab/items/h185.webp",
  "price": 200,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "الارز بالحليب من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h186",
  "name": "بوظة مع غزل البنات",
  "image": "/assets/photos/hallab/items/h186.webp",
  "price": 305,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "بوظة مع غزل البنات من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h187",
  "name": "مغلي",
  "image": "/assets/photos/hallab/items/h187.webp",
  "price": 240,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "مغلي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h188",
  "name": "فوندان شوكولا",
  "image": "/assets/photos/hallab/items/h188.webp",
  "price": 320,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فوندان شوكولا من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h189",
  "name": "قشطة وعسل",
  "image": "/assets/photos/hallab/items/h189.webp",
  "price": 275,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "قشطة وعسل من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h190",
  "name": "فطيرة اللوز",
  "image": "/assets/photos/hallab/items/h190.webp",
  "price": 270,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فطيرة اللوز من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h191",
  "name": "New York Cheesecake",
  "image": "/assets/photos/hallab/items/h191.webp",
  "price": 285,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "New York Cheesecake من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h192",
  "name": "French style creme brulee",
  "image": "/assets/photos/hallab/items/h192.webp",
  "price": 330,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "French style creme brulee من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h193",
  "name": "رازبيري موس",
  "image": "/assets/photos/hallab/items/h193.webp",
  "price": 310,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "رازبيري موس من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h194",
  "name": "تيراميسو",
  "image": "/assets/photos/hallab/items/h194.webp",
  "price": 320,
  "unit": "",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "تيراميسو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h195",
  "name": "فوريست كيس",
  "image": "/assets/photos/hallab/items/h195.webp",
  "price": 265,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "فوريست كيس من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h196",
  "name": "سويت سانرايز",
  "image": "/assets/photos/hallab/items/h196.webp",
  "price": 265,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "سويت سانرايز من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h197",
  "name": "ماريلين",
  "image": "/assets/photos/hallab/items/h197.webp",
  "price": 265,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "ماريلين من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h198",
  "name": "اكسترا ريفراشينغ",
  "image": "/assets/photos/hallab/items/h198.webp",
  "price": 265,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "اكسترا ريفراشينغ من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h199",
  "name": "أوريو سماش",
  "image": "/assets/photos/hallab/items/h199.webp",
  "price": 265,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "أوريو سماش من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h200",
  "name": "باترفلاي",
  "image": "/assets/photos/hallab/items/h200.webp",
  "price": 265,
  "unit": "",
  "category": "عصائر طازجة",
  "available": true,
  "featured": false,
  "description": "باترفلاي من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h210",
  "name": "مياه محلية كبيرة",
  "image": "/assets/photos/hallab/items/h210.webp",
  "price": 75,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "مياه محلية كبيرة من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h211",
  "name": "مياه غازية",
  "image": "/assets/photos/hallab/items/h211.webp",
  "price": 70,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "مياه غازية من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h218",
  "name": "شويبس بيتر ليمون",
  "image": "/assets/photos/hallab/items/h218.webp",
  "price": 105,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "شويبس بيتر ليمون من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h224",
  "name": "Jallab",
  "image": "/assets/photos/hallab/items/h224.webp",
  "price": 150,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "Jallab من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h225",
  "name": "Black Mulberry Juice",
  "image": "/assets/photos/hallab/items/h225.webp",
  "price": 95,
  "unit": "",
  "category": "مشروبات باردة",
  "available": true,
  "featured": false,
  "description": "Black Mulberry Juice من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h329",
  "name": "ماكياتو",
  "image": "/assets/photos/hallab/items/h329.webp",
  "price": 115,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "ماكياتو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "h334",
  "name": "إسبرسو",
  "image": "/assets/photos/hallab/items/h334.webp",
  "price": 115,
  "unit": "",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "إسبرسو من مطعم حلاب 1881.",
  "imageFit": "cover",
  "options": []
 }
];

const hallabProducts = hallabProductCatalog.map((product, index) => ({
  ...product,
  id: 1330001 + index,
  storeId: hallabStore.id
}));

const hallabDeliverySettings = {
  [hallabStore.id]: { mode: "distance", fixedFee: 40, ratePerKm: 15, prepMinutes: 30, maxRoundTripKm: 120 }
};
