// Generated for مطعم الخوالي (Al Khawali) — Fatih, Istanbul. Source: tillymenu.com/75/alkhawali
const khawaliStore = {
 "id": 31,
 "name": "مطعم الخوالي",
 "category": "مطاعم",
 "image": "/assets/photos/khawali/cover.jpg",
 "coverImage": "/assets/photos/khawali/cover.jpg",
 "logoImage": "/assets/photos/khawali/logo.jpg",
 "logo": "خ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "40 - 70 دقيقة",
 "distance": 14,
 "location": {
  "lat": 41.024171,
  "lng": 28.659568
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.024171,28.659568",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم الخوالي في إسنيورت بإسطنبول: متخصّص بالشاورما العربية على أنواعها وساندويتشاتها ووجباتها، مع الدجاج المشوي والساندويتشات الغربية والمقبلات والشاميات والمشروبات. أسماء الأصناف والأسعار كما في القائمة الرسمية للمطعم.",
 "address": "Yeşilkent Mah. 1880. Sk. No:50 A, 34515 Esenyurt/İstanbul",
 "phone": "+90 538 744 81 94",
 "whatsapp": "+90 538 744 81 94",
 "email": "",
 "website": "https://tillymenu.com/75/alkhawali",
 "sourceUrl": "https://tillymenu.com/75/alkhawali",
 "hours": "يومياً على مدار الساعة",
 "areas": [
  "إسنيورت",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const khawaliProductCatalog = [
 {
  "sourceId": "4539",
  "name": "Shawarma Sandwich",
  "image": "/assets/photos/khawali/items/item-001.png",
  "price": 140,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4540",
  "name": "Shawarma with Potatoes",
  "image": "/assets/photos/khawali/items/item-002.png",
  "price": 150,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma with Potatoes من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4541",
  "name": "Shawarma with Double Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-003.png",
  "price": 230,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma with Double Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4542",
  "name": "Saj Shawarma",
  "image": "/assets/photos/khawali/items/item-004.png",
  "price": 140,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Saj Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4543",
  "name": "Shawarma Fingers",
  "image": "/assets/photos/khawali/items/item-005.png",
  "price": 90,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma Fingers من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4544",
  "name": "Shawarma with Double Bread",
  "image": "/assets/photos/khawali/items/item-006.png",
  "price": 180,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma with Double Bread من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4545",
  "name": "Shawarma with Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-007.png",
  "price": 200,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma with Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4546",
  "name": "Shawarma in Pita with Potatoes",
  "image": "/assets/photos/khawali/items/item-008.png",
  "price": 190,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma in Pita with Potatoes من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4547",
  "name": "Super Shawarma",
  "image": "/assets/photos/khawali/items/item-009.png",
  "price": 190,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Super Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4548",
  "name": "Shawarma with Double Bread and Potatoes",
  "image": "/assets/photos/khawali/items/item-010.png",
  "price": 185,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma with Double Bread and Potatoes من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4549",
  "name": "Shawarma Pita with Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-011.png",
  "price": 220,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma Pita with Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4550",
  "name": "Shawarma Pita",
  "image": "/assets/photos/khawali/items/item-012.png",
  "price": 185,
  "unit": "",
  "category": "ساندويتش شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma Pita من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4552",
  "name": "Arabic Super Shawarma with Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-013.png",
  "price": 340,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Super Shawarma with Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4553",
  "name": "Al Khawali Shawarma Meal",
  "image": "/assets/photos/khawali/items/item-014.jpeg",
  "price": 825,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Al Khawali Shawarma Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4554",
  "name": "Arabic Chicken Pita",
  "image": "/assets/photos/khawali/items/item-015.png",
  "price": 250,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Chicken Pita من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4556",
  "name": "Arabic Chicken with Double Pita, Cheese, and Mushrooms",
  "image": "/assets/photos/khawali/items/item-016.png",
  "price": 500,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Chicken with Double Pita, Cheese, and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4557",
  "name": "Arabic Chicken with Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-017.png",
  "price": 280,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Chicken with Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4558",
  "name": "Arabic Double Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-018.png",
  "price": 420,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Double Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4560",
  "name": "Family Shawarma",
  "image": "/assets/photos/khawali/items/item-019.png",
  "price": 1150,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "وجبة عائلي ل ٥ أشخاص",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4562",
  "name": "Shawarma Fingers Meal",
  "image": "/assets/photos/khawali/items/item-020.png",
  "price": 420,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Shawarma Fingers Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4563",
  "name": "Arabic Pita with Cheese and Mushrooms",
  "image": "/assets/photos/khawali/items/item-021.png",
  "price": 300,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Pita with Cheese and Mushrooms من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4564",
  "name": "Arabic Super Chicken Shawarma",
  "image": "/assets/photos/khawali/items/item-022.png",
  "price": 330,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Super Chicken Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4565",
  "name": "1 Kilo Chicken Shawarma",
  "image": "/assets/photos/khawali/items/item-023.png",
  "price": 875,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "1 Kilo Chicken Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4566",
  "name": "Arabic Regular Chicken Shawarma",
  "image": "/assets/photos/khawali/items/item-024.png",
  "price": 240,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Regular Chicken Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4567",
  "name": "Arabic Double Shawarma",
  "image": "/assets/photos/khawali/items/item-025.png",
  "price": 375,
  "unit": "",
  "category": "وجبات شاورما",
  "available": true,
  "featured": false,
  "description": "Arabic Double Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4568",
  "name": "نصف فروج مع بطاطا",
  "image": "/assets/photos/khawali/items/item-026.jpeg",
  "price": 250,
  "unit": "",
  "category": "دجاج مشوي",
  "available": true,
  "featured": false,
  "description": "نصف فروج مع بطاطا من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4569",
  "name": "Whole Chicken",
  "image": "/assets/photos/khawali/items/item-027.jpeg",
  "price": 450,
  "unit": "",
  "category": "دجاج مشوي",
  "available": true,
  "featured": false,
  "description": "Whole Chicken من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4570",
  "name": "Half Chicken with Rice",
  "image": "/assets/photos/khawali/items/item-028.jpeg",
  "price": 250,
  "unit": "",
  "category": "دجاج مشوي",
  "available": true,
  "featured": false,
  "description": "Half Chicken with Rice من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4571",
  "name": "Whole Chicken with Rice",
  "image": "/assets/photos/khawali/items/item-029.jpeg",
  "price": 450,
  "unit": "",
  "category": "دجاج مشوي",
  "available": true,
  "featured": false,
  "description": "Whole Chicken with Rice من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4572",
  "name": "Double Potato Sandwich",
  "image": "/assets/photos/khawali/items/item-030.png",
  "price": 140,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Double Potato Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4573",
  "name": "Mexican Sandwich",
  "image": "/assets/photos/khawali/items/item-031.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Mexican Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4574",
  "name": "Shish Sandwich",
  "image": "/assets/photos/khawali/items/item-032.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Shish Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4575",
  "name": "Potato Sandwich",
  "image": "/assets/photos/khawali/items/item-033.png",
  "price": 120,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Potato Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4576",
  "name": "Kashkaval Cheese Potato Sandwich",
  "image": "/assets/photos/khawali/items/item-034.webp",
  "price": 160,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Kashkaval Cheese Potato Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4577",
  "name": "Potato Pita Sandwich",
  "image": "/assets/photos/khawali/items/item-035.png",
  "price": 130,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Potato Pita Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4578",
  "name": "Escalope Sandwich",
  "image": "/assets/photos/khawali/items/item-036.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Escalope Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4579",
  "name": "Spicy Sandwich",
  "image": "/assets/photos/khawali/items/item-037.jpg",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Spicy Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4580",
  "name": "Zinger Sandwich",
  "image": "/assets/photos/khawali/items/item-038.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Zinger Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4582",
  "name": "Francesco Sandwich",
  "image": "/assets/photos/khawali/items/item-039.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Francesco Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4584",
  "name": "Fajita Sandwich",
  "image": "/assets/photos/khawali/items/item-040.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Fajita Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4585",
  "name": "Crispy Sandwich",
  "image": "/assets/photos/khawali/items/item-041.png",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Crispy Sandwich من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4586",
  "name": "Chicken Cheeseburger",
  "image": "/assets/photos/khawali/items/item-042.jpeg",
  "price": 225,
  "unit": "",
  "category": "ساندويتش غربي",
  "available": true,
  "featured": false,
  "description": "Chicken Cheeseburger من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "7499",
  "name": "Burger meal",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Burger meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4587",
  "name": "Escalope Meal",
  "image": "/assets/photos/khawali/items/item-044.jpeg",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Escalope Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4588",
  "name": "Fajita Meal",
  "image": "/assets/photos/khawali/items/item-045.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Fajita Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4589",
  "name": "Francesco Meal",
  "image": "/assets/photos/khawali/items/item-046.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Francesco Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4590",
  "name": "Shish Meal",
  "image": "/assets/photos/khawali/items/item-047.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Shish Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4591",
  "name": "Crispy Meal",
  "image": "/assets/photos/khawali/items/item-048.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Crispy Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4592",
  "name": "Spicy Meal",
  "image": "/assets/photos/khawali/items/item-049.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Spicy Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4593",
  "name": "Mexicano Meal",
  "image": "/assets/photos/khawali/items/item-050.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Mexicano Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4594",
  "name": "Zinger Meal",
  "image": "/assets/photos/khawali/items/item-051.png",
  "price": 325,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "Zinger Meal من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4595",
  "name": "Potato Plate",
  "image": "/assets/photos/khawali/items/item-052.png",
  "price": 150,
  "unit": "",
  "category": "مقبلات",
  "available": true,
  "featured": false,
  "description": "Potato Plate من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4596",
  "name": "Tabbouleh",
  "image": "/assets/photos/khawali/items/item-053.png",
  "price": 170,
  "unit": "",
  "category": "مقبلات",
  "available": true,
  "featured": false,
  "description": "Tabbouleh من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4597",
  "name": "Hummus with Shawarma",
  "image": "/assets/photos/khawali/items/item-054.jpg",
  "price": 230,
  "unit": "",
  "category": "مقبلات",
  "available": true,
  "featured": false,
  "description": "Hummus with Shawarma من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4598",
  "name": "Fattoush",
  "image": "/assets/photos/khawali/items/item-055.png",
  "price": 170,
  "unit": "",
  "category": "مقبلات",
  "available": true,
  "featured": false,
  "description": "Fattoush من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4599",
  "name": "Seasonal Salad",
  "image": "/assets/photos/khawali/items/item-056.png",
  "price": 170,
  "unit": "",
  "category": "مقبلات",
  "available": true,
  "featured": false,
  "description": "Seasonal Salad من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4608",
  "name": "Fanta",
  "image": "/assets/photos/khawali/items/item-057.jpg",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Fanta من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4609",
  "name": "Coca-Cola Zero 330ml",
  "image": "/assets/photos/khawali/items/item-058.jpg",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Coca-Cola Zero 330ml من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4600",
  "name": "Ayran 1 Liter",
  "image": "/assets/photos/khawali/items/item-059.png",
  "price": 75,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Ayran 1 Liter من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4601",
  "name": "Fanta 1 Liter",
  "image": "/assets/photos/khawali/items/item-060.jpg",
  "price": 75,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Fanta 1 Liter من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4602",
  "name": "Water",
  "image": "/assets/photos/khawali/items/item-061.png",
  "price": 15,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Water من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4603",
  "name": "Sprite 330ml",
  "image": "/assets/photos/khawali/items/item-062.png",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Sprite 330ml من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4604",
  "name": "Pepsi 1 Liter",
  "image": "/assets/photos/khawali/items/item-063.jpg",
  "price": 75,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Pepsi 1 Liter من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4605",
  "name": "Ayran",
  "image": "/assets/photos/khawali/items/item-064.png",
  "price": 40,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Ayran من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4606",
  "name": "Sprite 1 Liter",
  "image": "/assets/photos/khawali/items/item-065.png",
  "price": 75,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Sprite 1 Liter من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "4607",
  "name": "Coca-Cola 330ml",
  "image": "/assets/photos/khawali/items/item-066.png",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "Coca-Cola 330ml من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68072",
  "name": "فلافل سوري",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 80,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فلافل سوري من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68073",
  "name": "فلافل دبل",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 100,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فلافل دبل من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68074",
  "name": "فلافل صاج",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 80,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فلافل صاج من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68075",
  "name": "فلافل عربي",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 150,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فلافل عربي من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68076",
  "name": "فلافل عربي دبل",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 190,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فلافل عربي دبل من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68077",
  "name": "فلافل صمون",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 100,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فلافل صمون من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68078",
  "name": "قرص فلافل",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 5,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "قرص فلافل من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68079",
  "name": "صحن فول بالزيت",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 120,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن فول بالزيت من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68080",
  "name": "صحن فول بطحينة",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 120,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن فول بطحينة من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68081",
  "name": "صحن حمص بالزيت",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 120,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن حمص بالزيت من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68082",
  "name": "صحن حمص باللبن",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 120,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن حمص باللبن من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68083",
  "name": "صحن فلافل",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 110,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن فلافل من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68084",
  "name": "صحن مسبحة",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 120,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن مسبحة من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68085",
  "name": "صحن متبل",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 120,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "صحن متبل من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68086",
  "name": "فتة بالسمنة",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 150,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فتة بالسمنة من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68087",
  "name": "فتة فقسة",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 150,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فتة فقسة من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "68088",
  "name": "فتة مكسرات",
  "image": "/assets/photos/khawali/cover.jpg",
  "price": 210,
  "unit": "",
  "category": "شاميات",
  "available": true,
  "featured": false,
  "description": "فتة مكسرات من مطعم الخوالي.",
  "imageFit": "cover",
  "options": []
 }
];

const khawaliProducts = khawaliProductCatalog.map((product, index) => ({
  ...product,
  id: 37001 + index,
  storeId: khawaliStore.id
}));

const khawaliDeliverySettings = {
  [khawaliStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
