// Generated for مطعم مندي اليمن (Mandi Alyemen) — Şirinevler, Mareşal Fevzi Çakmak 1. Sk. No:7/A, Bahçelievler/İstanbul.
// Yemeni mandi restaurant. Source: mandi-alyemen.minidine.com (miniandmore/minidine v2.2.16 API),
// native Arabic names, prices in TL. 114 products, 111 unique photos + 3 no-image cards.
// Location = the restaurant's own listing from the source site (Şirinevler, 40.992496, 28.846321),
// per the owner's instruction to use the site's address over the earlier Fatih Plus Code.
// NOTE: mandialyemenProductCatalog is intentionally emptied in the repo (perf) — the full catalog
// lives in Supabase and is pushed via scripts/_scrape/push-store.cjs.

const mandialyemenStore = {
 "id": 70,
 "name": "مطعم مندي اليمن",
 "category": "مطاعم",
 "image": "/assets/photos/mandialyemen/cover.jpg",
 "coverImage": "/assets/photos/mandialyemen/cover.jpg",
 "logoImage": "/assets/photos/mandialyemen/logo.png",
 "logo": "م",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "45 - 75 دقيقة",
 "distance": 0,
 "location": {
  "lat": 40.992496,
  "lng": 28.846321
 },
 "mapUrl": "https://maps.app.goo.gl/hhMQpoCS4QfmQg4m9",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "مطعم مندي اليمن — نكهة يمنية أصيلة في شيرين إيفلر بإسطنبول. مندي ومنسف لحم التيس والدجاج، ذبائح وولائم ومناسف كاملة، أطباق بحرية، معصوب وعريكة ومأكولات يمنية متنوعة، إضافةً إلى السلطات والمقبلات والحلويات والعصائر الطازجة. يُقدَّم مع الأرز والصوص اليمني. توصيل إلى باب منزلك.",
 "address": "شيرين إيفلر، شارع Mareşal Fevzi Çakmak 1. Sk. رقم 7/A، باهتشيلي إيفلر، إسطنبول 34188، تركيا",
 "phone": "+90 531 772 19 39",
 "whatsapp": "+90 531 772 19 39",
 "email": "mandialyaman@gmail.com",
 "website": "https://mandi-alyemen.minidine.com",
 "sourceUrl": "https://mandi-alyemen.minidine.com/ar/categories/?branch=mandi-alyemen",
 "hours": "7:00 ص - 1:00 ص",
 "areas": [
  "شيرين إيفلر",
  "باهتشيلي إيفلر",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

// Full catalog used ONLY for the Supabase push; emptied in the committed repo (see note above).
const mandialyemenFullCatalog = [
 {"name":"منسف لحم مندي (ذبيحة تيس)","price":3000,"category":"الذبائح والولائم (مناسف)","unit":"قطعة","image":"/assets/photos/mandialyemen/1.jpg","sourceId":"4801751286584","description":"منسف لحم تيس مندي مع الأرز والصوص اليمني — يُطهى على الطريقة اليمنية الأصيلة. اختر الحجم حسب عدد الأشخاص.","options":[{"name":"الحجم","values":["ربع ذبيحة · 2–2.5كغ · 4–5 أشخاص","نصف ذبيحة · 5كغ · 7–8 أشخاص","ذبيحة كاملة · 10كغ · 10–12 شخص"],"extra":[0,2500,6975]}]},
 {"name":"مندي لحم (قطعة واحدة)","price":450,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/4.jpg","sourceId":"1701775325411","description":"قطعة مندي لحم من الكتف او الفخذ"},
 {"name":"مندي لحم","price":740,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/5.jpg","sourceId":"2491750597975","description":"نفر لحم تيس 3 قطع من الفخذ أو الكتف والرقبة والصدر مع الأرز المندي"},
 {"name":"برم لحم","price":740,"category":"مأكولات لحم","unit":"وجبة","image":"/assets/photos/mandialyemen/6.jpg","sourceId":"8791751185763","description":"نفر لحم تيس 3 قطع من الفخذ أو الكتف والرقبة والصدر مع الأرز و المرق"},
 {"name":"مدفون لحم","price":740,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/7.jpg","sourceId":"7791749725224","description":"نفر لحم تيس 3 قطع من الفخذ أو الكتف والرقبة والصدر مع الأرز المندي والتوابل اليمنية"},
 {"name":"زربيان لحم","price":740,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/8.jpg","sourceId":"801750599783","description":"نفر لحم تيس 3 قطع من الفخذ أو الكتف والرقبة والصدر مع الأرز الزربيان"},
 {"name":"برياني لحم","price":740,"category":"مأكولات لحم","unit":"وجبة","image":"/assets/photos/mandialyemen/9.jpg","sourceId":"5691751194159","description":"نفر لحم تيس 3 قطع من الفخذ أو الكتف والرقبة والصدر مع الأرز البرياني"},
 {"name":"لحم حضرمي","price":740,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/10.jpg","sourceId":"5551750597709","description":"نفر لحم تيس محمر 3 قطع من الفخذ أو الكتف والرقبة والصدر مع الأرز المندي"},
 {"name":"كبدة","price":400,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/11.jpg","sourceId":"6721749725714","description":"كبدة ماعز مع البهارات اليمنية مع الخبز"},
 {"name":"فحسة","price":640,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/12.jpg","sourceId":"9101749725523","description":"لحم بقري مهروس مع المرق والبهارات اليمنية والخبز"},
 {"name":"صانونة لحم","price":500,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/13.jpg","sourceId":"1771749725274","description":"قطع لحم تس مع الصوص اليمني والبهارات اليمنية مع الخبز"},
 {"name":"بامية لحم","price":500,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/14.jpg","sourceId":"4811749725298","description":"طبق باميا مع قطعة لحم تيس بالصوص والبهارات اليمنية مع خبز"},
 {"name":"عقدة لحم","price":500,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/15.jpg","sourceId":"9901749725339","description":"قطع لحم تيس مهروسة مع البهارات اليمنية والخبز"},
 {"name":"فتة لحم","price":400,"category":"مأكولات لحم","unit":"قطعة","image":"/assets/photos/mandialyemen/16.jpg","sourceId":"3871749725356","description":"قطع لحم تيس صغيرة ممزوجة بالخبز والمرق اليمني مع الصوص"},
 {"name":"ملوخية لحم","price":400,"category":"مأكولات لحم","unit":"وجبة","image":"/assets/photos/mandialyemen/17.jpg","sourceId":"2341751191867","description":"طبق ملوخية ناعمة مع قطع لحم تيس بالإضافة للخبز أو الرز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,0]}]},
 {"name":"وجبة ربع دجاج (غنية) مندي","price":290,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/18.jpg","sourceId":"9191776272558","description":"ربع دجاج مع مشكل خضار وسلطة والسحاوق اليمني"},
 {"name":"مندي دجاج","price":380,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/19.jpg","sourceId":"5471749724627","description":"نصف دجاج مندي مع الأرز والصوص اليمني"},
 {"name":"مدفون دجاج","price":380,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/20.jpg","sourceId":"3421749724727","description":"نصف دجاج مدفون مع الأرز المندي مع الصوص اليمني"},
 {"name":"زربيان دجاج","price":380,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/21.jpg","sourceId":"561749724746","description":"نصف دجاج مدفون مع رز الزربيان والصوص اليمني"},
 {"name":"برياني دجاج","price":380,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/22.jpg","sourceId":"5111749724650","description":"نصف دجاج مدفون مع الارز البرياني والصوص اليمني"},
 {"name":"مضبي دجاج","price":380,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/23.jpg","sourceId":"7911749724706","description":"نصف دجاج مشوي على الفحم بالتوابل اليمنية ورز المندي"},
 {"name":"ربع مضبي دجاج","price":260,"category":"مأكولات دجاج","unit":"وجبة","image":"/assets/photos/mandialyemen/24.jpg","sourceId":"8491751201822","description":"ربع دجاج مضبي فخذ أو صدر حسب المتوفر"},
 {"name":"ربع دجاج مندي","price":260,"category":"مأكولات دجاج","unit":"وجبة","image":"/assets/photos/mandialyemen/25.jpg","sourceId":"1081750416830","description":"ربع دجاج مندي صدر أو فخذ حسب المتوفر"},
 {"name":"ربع دجاج برياني","price":260,"category":"مأكولات دجاج","unit":"وجبة","image":"","sourceId":"6881750416925","description":"ربع دجاج برياني صدر أو فخذ حسب المتوفر"},
 {"name":"ربع دجاج زربيان","price":260,"category":"مأكولات دجاج","unit":"وجبة","image":"","sourceId":"9751750417062","description":"ربع دجاج زربيان صدر أو فخذ حسب المتوفر"},
 {"name":"ربع مدفون دجاج","price":260,"category":"مأكولات دجاج","unit":"وجبة","image":"/assets/photos/mandialyemen/28.jpg","sourceId":"4821751201800","description":"ربع دجاج مدفون مع الرز صدر أو فخذ حسب المتوفر"},
 {"name":"تكة دجاج بالكاري","price":430,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/29.jpg","sourceId":"8201749724784","description":"قطع الدجاج المشوي مع صوص التكة بالكاري الحار، مع الخبز أو الرز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,30]}]},
 {"name":"صانونة دجاج","price":310,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/30.jpg","sourceId":"111749724808","description":"قطع دجاج مع الصوص اليمني والبهارات اليمنية مع الخبز"},
 {"name":"بامية دجاج","price":300,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/31.jpg","sourceId":"1771749724823","description":"طبق باميا مع قطعة الدجاج بالصوص والبهارات اليمنية مع خبز"},
 {"name":"عقدة دجاج","price":300,"category":"مأكولات دجاج","unit":"قطعة","image":"/assets/photos/mandialyemen/32.jpg","sourceId":"2251749724852","description":"دجاج مهروس ومطبوخ مع البصل والطماط والفلفل الأخضر يقدم مع الخبز والصوص اليمني"},
 {"name":"ملوخية دجاج","price":300,"category":"مأكولات دجاج","unit":"وجبة","image":"/assets/photos/mandialyemen/33.jpg","sourceId":"8901751191824","description":"ملوخية بالدجاج مع رز أو خبز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,0]}]},
 {"name":"معكرونة بالدجاج","price":300,"category":"مأكولات دجاج","unit":"وجبة","image":"/assets/photos/mandialyemen/34.jpg","sourceId":"8681751208944","description":"طبق معكرونة مطبوخة بالتوابل اليمنية والصوص"},
 {"name":"روبيان بالرز","price":600,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/35.jpg","sourceId":"3841764089511"},
 {"name":"سمك موفا","price":580,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/36.jpg","sourceId":"7251749725416","description":"سمك موفا في الفرن مع البهارات اليمنية مع الخبز او الرز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,0]}]},
 {"name":"سمك مقلي","price":580,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/37.jpg","sourceId":"3551749725387","description":"سمك مقلي ( دنيس ) مع البهرات اليمنية مع الخبز او الرز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,0]}]},
 {"name":"سمك سلمون تركي","price":490,"category":"الاطباق البحرية","unit":"وجبة","image":"/assets/photos/mandialyemen/38.jpg","sourceId":"7081751186563","description":"قطع من سمك السلمون التركي مقلي بالزيت مع الخبز او الرز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,0]}]},
 {"name":"جمبري مقلي","price":580,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/39.jpg","sourceId":"6311749725404","description":"جمبري مقلي بالبهرات اليمنية مع الخبز او الارز"},
 {"name":"صانونة سمك","price":490,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/40.jpg","sourceId":"6631749725476","description":"قطع سمك السلمون مع الصوص مع الخبز او الرز"},
 {"name":"صانونة جمبري","price":550,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/41.jpg","sourceId":"451749725497","description":"جمبري مع مع الصوص اليمني مع الخبز"},
 {"name":"عقدة جمبري","price":580,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/42.jpg","sourceId":"9231749725434","description":"جمبري مع البهارات اليمنية مع الخبز او الرز"},
 {"name":"عقدة سمك","price":450,"category":"الاطباق البحرية","unit":"قطعة","image":"/assets/photos/mandialyemen/43.jpg","sourceId":"8601749725456","description":"سمك السلمون مع البهارات اليمنية مع الخبز او الرز"},
 {"name":"ملوخية","price":250,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/44.jpg","sourceId":"6991754403566","description":"طبق ملوخية ناعمة بالطريقة اليمنية يقدم مع خبز أو رز","options":[{"name":"يُقدّم مع","values":["خبز","رز"],"extra":[0,0]}]},
 {"name":"عصيد يمني","price":280,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/45.jpg","sourceId":"8651749725799","description":"عجينة قمح مطبوخة مع مرق يمني حامض"},
 {"name":"رز سادة مندي","price":150,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/46.jpg","sourceId":"3021754820194","description":"رز سادة بالبهارات اليمنية"},
 {"name":"سلته","price":400,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/47.jpg","sourceId":"7701750597412","description":"خضار مع قطع اللحم مع البهرات اليمنية مع الخبز"},
 {"name":"مكس (سلتة وفحسة)","price":500,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/48.jpg","sourceId":"6151749725653","description":"مزيج من السلتة والفحسة اليمنية مع الخبز"},
 {"name":"مشكل خضار","price":250,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/49.jpg","sourceId":"3191753706888","description":"خضار مشكل مع بهارات يمنية مع الخبز"},
 {"name":"بيض سادة","price":150,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/50.jpg","sourceId":"7431751187211","description":"بيض مقلي مع البهارات اليمنية مع الخبز"},
 {"name":"باميا","price":250,"category":"مأكولات متنوعة","unit":"قطعة","image":"","sourceId":"8651749725936","description":"طبق باميا بالصوص والبهارات اليمنية مع خبز"},
 {"name":"فاصوليا ناشف","price":250,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/52.jpg","sourceId":"4761751364941","description":"فاصولية مهروسة مع بهارات يمنية مع خبز"},
 {"name":"فاصوليا ناشف مع البيض","price":260,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/53.jpg","sourceId":"7081749725592","description":"فاصولية مهروسة مع البيض مع بهارات يمنية مع خبز"},
 {"name":"فاصوليا حرضة","price":250,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/54.jpg","sourceId":"9071749725856","description":"فاصولية مع البهارات اليمنية مع الخبز"},
 {"name":"فول","price":250,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/55.jpg","sourceId":"9181749725572","description":"فول مع بهارات يمنية مع الخبز"},
 {"name":"لحسة (بيض بالجبن السائل)","price":220,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/56.jpg","sourceId":"2951751186166","description":"شكشوكة البيض بالبصل والطماط والفلفل مع الجبن السائل وبهارات يمنية"},
 {"name":"شكشوكة","price":180,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/57.jpg","sourceId":"4131750597694","description":"بيض مع البهارات اليمنية مع الخبز"},
 {"name":"بيض عيون","price":150,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/58.jpg","sourceId":"5461750597427","description":"بيض عيون مع البهارات اليمنية مع الخبز"},
 {"name":"فتة مرق","price":170,"category":"مأكولات متنوعة","unit":"قطعة","image":"/assets/photos/mandialyemen/59.jpg","sourceId":"6951749725837","description":"خبز مع مرق مع بهارات يمنية"},
 {"name":"معكرونة","price":180,"category":"مأكولات متنوعة","unit":"وجبة","image":"/assets/photos/mandialyemen/60.jpg","sourceId":"9241751208906","description":"معكرونة مع بهارات يمنية"},
 {"name":"سلطة عربية (حجم صغير)","price":100,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/61.jpg","sourceId":"3701775060841","description":"صحن سلطة عربية حجم صغير"},
 {"name":"مشكل سلطات","price":220,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/62.jpg","sourceId":"5821749725971","description":"سلطات مشكلة"},
 {"name":"سلطة فتوش","price":170,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/63.jpg","sourceId":"751749726146","description":"بصل وطماط وخيار وخبز فتوش"},
 {"name":"سلطة عربية","price":170,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/64.jpg","sourceId":"2071749726120","description":"بصل وطماط وخيار مع زيت الزيتون"},
 {"name":"سلطة ذرة","price":170,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/65.jpg","sourceId":"9251749726017","description":"بصل وطماط وخيار وذره"},
 {"name":"سلطة جرجير","price":170,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/66.jpg","sourceId":"4211749726093","description":"جرجير وبصل"},
 {"name":"سلطة يونانية","price":170,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/67.jpg","sourceId":"9891749726104","description":"بصل وطماط وخيار وزيتون وجين"},
 {"name":"بطاطا مقلية","price":180,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/68.jpg","sourceId":"901749726218","description":"بطاطا مقلية"},
 {"name":"سحاوق / دقوس","price":40,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/69.jpg","sourceId":"7601750597182","description":"صوص يمني"},
 {"name":"سحاوق / دقوس كبير","price":80,"category":"سلطات ومقبلات","unit":"كوب","image":"/assets/photos/mandialyemen/70.jpg","sourceId":"9331751748568","description":"السحاوق اليمني (دقوس) حجم كبير"},
 {"name":"حلبة يمنية","price":50,"category":"سلطات ومقبلات","unit":"صحن","image":"/assets/photos/mandialyemen/71.jpg","sourceId":"1941751748665","description":"حلبة يمنية"},
 {"name":"سحاوق جبن","price":90,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/72.jpg","sourceId":"4721749726160","description":"صوص يمني بالجبن"},
 {"name":"لبن بالخيار","price":100,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/73.jpg","sourceId":"5381749726239","description":"زبادي وخيار"},
 {"name":"زبادي","price":64,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/74.jpg","sourceId":"3571750597308","oldPrice":80,"description":"زبادي"},
 {"name":"مرق","price":50,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/75.jpg","sourceId":"3171749726258","description":"مرقة لحم"},
 {"name":"شطة رنا/جلوريا","price":50,"category":"سلطات ومقبلات","unit":"علبة","image":"/assets/photos/mandialyemen/76.jpg","sourceId":"7031751210304","description":"شطة"},
 {"name":"حبة موز","price":35,"category":"سلطات ومقبلات","unit":"قطعة","image":"/assets/photos/mandialyemen/77.jpg","sourceId":"6651751226910","description":"حبة موز"},
 {"name":"معصوب ملكي","price":280,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/78.jpg","sourceId":"5331751201541","description":"موز وخبز وجبن وقشطة وعسل","options":[{"name":"إضافات","values":["عادي","بدون زبيب"],"extra":[0,0]}]},
 {"name":"معصوب / عريكة ملكي (حجم صغير)","price":160,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/79.jpg","sourceId":"6651775326215","description":"معصوب ملكي أو عريكة حجم صغير","options":[{"name":"الخيار","values":["معصوب","عريكة"],"extra":[0,0]}]},
 {"name":"عريكة ملكي","price":280,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/80.jpg","sourceId":"5991751201503","description":"تمر وخبز وجبن وقشطة وعسل"},
 {"name":"معصوب عادي","price":250,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/81.jpg","sourceId":"9781749727425","description":"موز وخبز وقشطة وعسل"},
 {"name":"عريكة عادي","price":250,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/82.jpg","sourceId":"2561751201597","description":"تمر وخبز وقشطة وعسل"},
 {"name":"فتة موز","price":220,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/83.jpg","sourceId":"431749727402","description":"تمر وموز وعسل"},
 {"name":"فتة تمر","price":220,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/84.jpg","sourceId":"4941749727135","description":"تمر وخبز وعسل"},
 {"name":"عريكة مكس","price":300,"category":"الحلويات","unit":"قطعة","image":"/assets/photos/mandialyemen/85.jpg","sourceId":"2661749727099","description":"تمر وموز وخبز وقشطة وعسل"},
 {"name":"ملوح (خبز يمني)","price":80,"category":"معجنات","unit":"قطعة","image":"/assets/photos/mandialyemen/86.jpg","sourceId":"651749726299","description":"خبز الملوح اليمني الطازج. صغير يكفي شخصاً، وكبير يكفي شخصين.","options":[{"name":"الحجم","values":["صغير (شخص واحد)","كبير (شخصان)"],"extra":[0,40]}]},
 {"name":"خبز طاوة","price":45,"category":"معجنات","unit":"قطعة","image":"/assets/photos/mandialyemen/87.jpg","sourceId":"3061762801120","description":"خبز القمح اليمني مطبوخ على طاوة الطبخ"},
 {"name":"جمايكا","price":180,"category":"العصائر","unit":"كوب","image":"/assets/photos/mandialyemen/89.jpg","sourceId":"7381753186578","description":"مزيج عصير الأناناس مع البرتقال والثلج مع السكر"},
 {"name":"عصير طبيعي (حجم صغير)","price":100,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/90.jpg","sourceId":"1741775392852","description":"عصير طبيعي حجم صغير العصير الافتراضي كوكتيل، لكن يمكن تبديله باختيار أي نوع"},
 {"name":"عصير مانجو","price":170,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/91.jpg","sourceId":"6721749726656","description":"عصير المانجو الطازج بالثلج. أضِف الحليب حسب رغبتك.","options":[{"name":"الخيار","values":["عادي","بالحليب"],"extra":[0,10]}]},
 {"name":"أفوكادو","price":200,"category":"العصائر","unit":"كوب","image":"/assets/photos/mandialyemen/92.jpg","sourceId":"3871751883957","description":"فاكهة افوكادو مع الماء والثلج والسكر"},
 {"name":"موز بالحليب","price":170,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/94.jpg","sourceId":"4191749726676","description":"فاكهة الموز مع الماء والثلج والسكر والحليب"},
 {"name":"افوكادو بالحليب","price":200,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/95.jpg","sourceId":"9101749726474","description":"فاكهة افوكادو مع الماء والثلج والسكر والحليب"},
 {"name":"أناناس","price":170,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/96.jpg","sourceId":"781749726428","description":"فاكهة الأناناس مع الماء والثلج والسكر"},
 {"name":"فراولة","price":200,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/97.jpg","sourceId":"201749726525","description":"فاكهة افوكادو مع الماء والثلج والسكر"},
 {"name":"فروالة بالحليب","price":200,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/98.jpg","sourceId":"5521749726604","description":"فاكهة الفراولة مع الماء والثلج والسكر وللحليب"},
 {"name":"برتقال كبس","price":170,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/99.jpg","sourceId":"3091749726557","description":"عصارة فاكهة البرتقال"},
 {"name":"كوكتيل","price":170,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/100.jpg","sourceId":"8981749726581","description":"مشكل فوكه مع الماء والثلج والسكر"},
 {"name":"عصير ليمون","price":150,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/101.jpg","sourceId":"4551751189924","description":"فاكهة الليمون مع الماء والثلج والسكر"},
 {"name":"ليمون بالنعناع","price":150,"category":"العصائر","unit":"قطعة","image":"/assets/photos/mandialyemen/102.jpg","sourceId":"941751189900","description":"فاكهة الليمون والنعناع مع الماء والثلج والسكر"},
 {"name":"ليمون بالحليب","price":160,"category":"العصائر","unit":"كوب","image":"/assets/photos/mandialyemen/103.jpg","sourceId":"61751189970","description":"فاكهة الليمون مع الماء والثلج والسكر"},
 {"name":"كولا توركا","price":60,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/104.jpg","sourceId":"7421749726881","description":"330 مل"},
 {"name":"كولا توركا 1 لتر","price":95,"category":"مشروبات باردة","unit":"علبة","image":"/assets/photos/mandialyemen/105.jpg","sourceId":"8651753365543","description":"330 مل","available":false},
 {"name":"Sırma صودا (ماء معدني)","price":30,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/106.jpg","sourceId":"8641773688687","description":"مياه معدنية"},
 {"name":"كولا توركا 2.5 لتر","price":150,"category":"مشروبات باردة","unit":"علبة","image":"/assets/photos/mandialyemen/107.jpg","sourceId":"5351751226809","description":"2.5 لتر"},
 {"name":"عيران كبير","price":40,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/108.jpg","sourceId":"8691749726827","description":"285 مل"},
 {"name":"فيمتو غازي","price":60,"category":"مشروبات باردة","unit":"علبة","image":"/assets/photos/mandialyemen/109.jpg","sourceId":"5911751226897","description":"250 مل"},
 {"name":"بيبسي","price":75,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/110.jpg","sourceId":"921749726718","description":"330 مل"},
 {"name":"ببسي زيرو","price":75,"category":"مشروبات باردة","unit":"علبة","image":"/assets/photos/mandialyemen/111.jpg","sourceId":"8571751226819","description":"صفر سكر 330 مل"},
 {"name":"سفن اب","price":75,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/112.jpg","sourceId":"6391749726745","description":"330 مل"},
 {"name":"فانتا","price":75,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/113.jpg","sourceId":"701749726902","description":"330"},
 {"name":"ماء","price":15,"category":"مشروبات باردة","unit":"قطعة","image":"/assets/photos/mandialyemen/114.jpg","sourceId":"6511749726852","description":"500 مل"},
 {"name":"شاي احمر","price":36,"category":"مشروبات ساخنة","unit":"قطعة","image":"/assets/photos/mandialyemen/115.jpg","sourceId":"7801749727014","oldPrice":40,"description":"ماء، شاي احمر، سكر. وبهارات يمنية","options":[{"name":"إضافات","values":["عادي","نعناع"],"extra":[0,0]}]},
 {"name":"براد شاي عدني / كرك (دلة)","price":350,"category":"مشروبات ساخنة","unit":"كوب","image":"/assets/photos/mandialyemen/116.jpg","sourceId":"4821751748584","description":"شاي يمني بالحليب"},
 {"name":"براد شاي أحمر (دلة)","price":170,"category":"مشروبات ساخنة","unit":"كوب","image":"/assets/photos/mandialyemen/117.jpg","sourceId":"3701751748482","description":"شاي يمني"},
 {"name":"شاي عدني","price":80,"category":"مشروبات ساخنة","unit":"قطعة","image":"/assets/photos/mandialyemen/118.jpg","sourceId":"2261749726992","description":"ماء شاي حليب مكثف سكر وبهارات يمنية"}
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const mandialyemenProductCatalog = [];

const mandialyemenProducts = (mandialyemenProductCatalog.length ? mandialyemenProductCatalog : mandialyemenFullCatalog).map((product, index) => ({
  ...product,
  available: product.available !== false,
  id: 1540001 + index,
  storeId: mandialyemenStore.id
}));

const mandialyemenDeliverySettings = {
  [mandialyemenStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 45, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { mandialyemenStore, mandialyemenProducts, mandialyemenDeliverySettings };
}