// Generated for عصائر أورنج تركيا (Orange Turkey) — Istanbul. Source: app.trybany.com/ar/orange-turkey-166
// Prices are from the official menu (Turkish Lira). Product photos are the shop's own
// branded images; a few items without their own photo fall back to the store cover.
const orangeStore = {
 "id": 34,
 "name": "Orange Turkey",
 "category": "عصائر",
 "image": "/assets/photos/orange/cover.jpg",
 "coverImage": "/assets/photos/orange/cover.jpg",
 "logoImage": "/assets/photos/orange/logo.png",
 "logo": "أ",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 30,
 "minOrder": 100,
 "time": "30 - 55 دقيقة",
 "distance": 12,
 "location": {
  "lat": 41.024084,
  "lng": 28.644626
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.024084,28.644626",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "عصائر أورنج تركيا: عصائر طبيعية طازجة باللتر وبالكأس، أفوكادو، كريب ووافل وبان كيك، ميلك شيك وكوكتيلات وموهيتو، سلطات فواكه ومشروبات ساخنة وباردة. كل المنتجات بأسعارها كما في القائمة الرسمية.",
 "address": "Piri Reis, Necip Fazıl Kısakürek Cd No:75, 34515 Esenyurt/İstanbul",
 "phone": "+90 555 553 52 53",
 "whatsapp": "+90 555 553 52 53",
 "email": "",
 "website": "https://app.trybany.com/ar/orange-turkey-166/",
 "sourceUrl": "https://app.trybany.com/ar/orange-turkey-166/",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسنيورت",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const orangeProductCatalog = [
 {
  "sourceId": "107v",
  "name": "لتر عصير مانغو",
  "image": "/assets/photos/orange/items/107v.jpg",
  "price": 425,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير مانغو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "107w",
  "name": "لتر عصير برتقال طبيعي",
  "image": "/assets/photos/orange/items/107w.jpg",
  "price": 280,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير برتقال طبيعي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "107x",
  "name": "لتر عصير ليمون وبرتقال",
  "image": "/assets/photos/orange/items/107x.jpg",
  "price": 280,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير ليمون وبرتقال من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "107y",
  "name": "لتر عصير فريز",
  "image": "/assets/photos/orange/items/107y.jpg",
  "price": 350,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير فريز من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "107z",
  "name": "لتر عصير فواكه طبيعي",
  "image": "/assets/photos/orange/items/107z.jpg",
  "price": 375,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير فواكه طبيعي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1080",
  "name": "لتر عصير مانغو وفريز",
  "image": "/assets/photos/orange/items/1080.jpg",
  "price": 400,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير مانغو وفريز من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "10aw",
  "name": "لتر ميلك شيك لوتس",
  "image": "/assets/photos/orange/cover.jpg",
  "price": 450,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر ميلك شيك لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "10ax",
  "name": "لتر ميلك شي بوظة عربي",
  "image": "/assets/photos/orange/cover.jpg",
  "price": 450,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر ميلك شي بوظة عربي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "10ay",
  "name": "لتر اناناس طبيعي",
  "image": "/assets/photos/orange/items/10ay.jpg",
  "price": 425,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر اناناس طبيعي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "10az",
  "name": "لتر ميلك شيك اوريو",
  "image": "/assets/photos/orange/cover.jpg",
  "price": 450,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر ميلك شيك اوريو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "10b0",
  "name": "لتر عصير طبيعي بولو",
  "image": "/assets/photos/orange/cover.jpg",
  "price": 280,
  "unit": "",
  "category": "عصائر طبيعية ( لتر )",
  "available": true,
  "featured": false,
  "description": "لتر عصير طبيعي بولو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "105v",
  "name": "Orange Box",
  "image": "/assets/photos/orange/items/105v.jpg",
  "price": 850,
  "unit": "",
  "category": "Orange Box",
  "available": true,
  "featured": false,
  "description": "Orange Box من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "17wr",
  "name": "افوكادو بالفواكه",
  "image": "/assets/photos/orange/items/17wr.jpg",
  "price": 250,
  "unit": "",
  "category": "الأفوكادو",
  "available": true,
  "featured": false,
  "description": "افوكادو بالفواكه من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljj",
  "name": "سادة",
  "image": "/assets/photos/orange/items/ljj.jpg",
  "price": 180,
  "unit": "",
  "category": "الأفوكادو",
  "available": true,
  "featured": false,
  "description": "سادة من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljl",
  "name": "تمر قشطة عسل مكسرات",
  "image": "/assets/photos/orange/items/ljl.jpg",
  "price": 250,
  "unit": "",
  "category": "الأفوكادو",
  "available": true,
  "featured": false,
  "description": "تمر قشطة عسل مكسرات من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljk",
  "name": "قشطة عسل مكسرات",
  "image": "/assets/photos/orange/items/ljk.jpg",
  "price": 225,
  "unit": "",
  "category": "الأفوكادو",
  "available": true,
  "featured": false,
  "description": "قشطة عسل مكسرات من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "105w",
  "name": "فوتوتشيني مع بوظة وكريمة",
  "image": "/assets/photos/orange/items/105w.jpg",
  "price": 210,
  "unit": "",
  "category": "الكريب",
  "available": false,
  "featured": false,
  "description": "فوتوتشيني مع بوظة وكريمة من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "105x",
  "name": "فوتوتشيني مع كريمة",
  "image": "/assets/photos/orange/items/105x.jpg",
  "price": 180,
  "unit": "",
  "category": "الكريب",
  "available": false,
  "featured": false,
  "description": "فوتوتشيني مع كريمة من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1521",
  "name": "سوشي لوتس",
  "image": "/assets/photos/orange/items/1521.jpg",
  "price": 330,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "سوشي لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1522",
  "name": "سوشي اوريو",
  "image": "/assets/photos/orange/items/1522.jpg",
  "price": 330,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "سوشي اوريو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lke",
  "name": "‎كريب شوكولا بلجيكي",
  "image": "/assets/photos/orange/items/lke.jpg",
  "price": 290,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "‎كريب شوكولا بلجيكي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkf",
  "name": "‎كريب لوتس",
  "image": "/assets/photos/orange/items/lkf.jpg",
  "price": 330,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "‎كريب لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkg",
  "name": "‎كريب شوكولا مع  فواكه",
  "image": "/assets/photos/orange/items/lkg.jpg",
  "price": 330,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "‎كريب شوكولا مع  فواكه من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lki",
  "name": "كريب بستاشيو",
  "image": "/assets/photos/orange/items/lki.jpg",
  "price": 330,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "كريب بستاشيو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkj",
  "name": "‎اورانج رول",
  "image": "/assets/photos/orange/items/lkj.jpg",
  "price": 390,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "‎اورانج رول من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "q32",
  "name": "كريب اورانج",
  "image": "/assets/photos/orange/items/q32.jpg",
  "price": 300,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "كريب اورانج من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkh",
  "name": "‎كريب اوريو",
  "image": "/assets/photos/orange/items/lkh.jpg",
  "price": 330,
  "unit": "",
  "category": "الكريب",
  "available": true,
  "featured": false,
  "description": "‎كريب اوريو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ptv",
  "name": "وافل ستيك بالشوكولا عدد 2",
  "image": "/assets/photos/orange/items/ptv.jpg",
  "price": 240,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "وافل ستيك بالشوكولا عدد 2 من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ptw",
  "name": "وافل ستيك بستاشيو عدد 2",
  "image": "/assets/photos/orange/items/ptw.jpg",
  "price": 290,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "وافل ستيك بستاشيو عدد 2 من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "pty",
  "name": "وافل بستاشيو",
  "image": "/assets/photos/orange/items/pty.jpg",
  "price": 330,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "وافل بستاشيو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ptx",
  "name": "وافل ستيك لوتس عدد 2",
  "image": "/assets/photos/orange/items/ptx.jpg",
  "price": 290,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "وافل ستيك لوتس عدد 2 من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkn",
  "name": "‎وافل شوكولا مع فواكه",
  "image": "/assets/photos/orange/items/lkn.jpg",
  "price": 330,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "‎وافل شوكولا مع فواكه من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkk",
  "name": "‎وافل شوكولا بلجيكي",
  "image": "/assets/photos/orange/items/lkk.jpg",
  "price": 290,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "‎وافل شوكولا بلجيكي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkl",
  "name": "‎وافل لوتس",
  "image": "/assets/photos/orange/items/lkl.jpg",
  "price": 330,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "‎وافل لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkm",
  "name": "‎وافل اوريو",
  "image": "/assets/photos/orange/items/lkm.jpg",
  "price": 330,
  "unit": "",
  "category": "الوافل",
  "available": true,
  "featured": false,
  "description": "‎وافل اوريو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "105z",
  "name": "بوب شوكولاته",
  "image": "/assets/photos/orange/items/105z.jpg",
  "price": 190,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "بوب شوكولاته من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lks",
  "name": "‎بان كيك شوكولا مع فواكه",
  "image": "/assets/photos/orange/items/lks.jpg",
  "price": 330,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "‎بان كيك شوكولا مع فواكه من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1060",
  "name": "بوب لوتس",
  "image": "/assets/photos/orange/items/1060.jpg",
  "price": 225,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "بوب لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1061",
  "name": "بوب بستاشيو",
  "image": "/assets/photos/orange/items/1061.jpg",
  "price": 225,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "بوب بستاشيو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkr",
  "name": "بيستاشيو بان كيك",
  "image": "/assets/photos/orange/items/lkr.jpg",
  "price": 330,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "بيستاشيو بان كيك من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkp",
  "name": "‎بان كيك شوكولا",
  "image": "/assets/photos/orange/items/lkp.jpg",
  "price": 290,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "‎بان كيك شوكولا من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "15io",
  "name": "وجبة الاطفال",
  "image": "/assets/photos/orange/items/15io.jpg",
  "price": 175,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "4 قطع ميني بان كيك مع فواكه",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkq",
  "name": "‎بان كيك لوتس",
  "image": "/assets/photos/orange/items/lkq.jpg",
  "price": 330,
  "unit": "",
  "category": "بان كيك",
  "available": true,
  "featured": false,
  "description": "‎بان كيك لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "yx2",
  "name": "ميلك شيك بوظة عربي",
  "image": "/assets/photos/orange/items/yx2.jpg",
  "price": 180,
  "unit": "",
  "category": "ميلك شيك",
  "available": true,
  "featured": false,
  "description": "ميلك شيك بوظة عربي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljm",
  "name": "اوريو",
  "image": "/assets/photos/orange/items/ljm.jpg",
  "price": 180,
  "unit": "",
  "category": "ميلك شيك",
  "available": true,
  "featured": false,
  "description": "اوريو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljn",
  "name": "لوتس",
  "image": "/assets/photos/orange/items/ljn.jpg",
  "price": 180,
  "unit": "",
  "category": "ميلك شيك",
  "available": true,
  "featured": false,
  "description": "لوتس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljo",
  "name": "نوتيلا",
  "image": "/assets/photos/orange/items/ljo.jpg",
  "price": 170,
  "unit": "",
  "category": "ميلك شيك",
  "available": true,
  "featured": false,
  "description": "نوتيلا من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "y3m",
  "name": "مانغا واناناس",
  "image": "/assets/photos/orange/items/y3m.jpg",
  "price": 150,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "مانغا واناناس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "q2w",
  "name": "اناناس مع فريز",
  "image": "/assets/photos/orange/items/q2w.jpg",
  "price": 140,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "اناناس مع فريز من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "q2x",
  "name": "برتقال وليمون",
  "image": "/assets/photos/orange/items/q2x.jpg",
  "price": 120,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "برتقال وليمون من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "q2y",
  "name": "فريز وبرتقال",
  "image": "/assets/photos/orange/items/q2y.jpg",
  "price": 120,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "فريز وبرتقال من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "qmg",
  "name": "مانغا وموز",
  "image": "/assets/photos/orange/items/qmg.jpg",
  "price": 160,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "مانغا وموز من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljt",
  "name": "بولو",
  "image": "/assets/photos/orange/items/ljt.jpg",
  "price": 110,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "بولو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lju",
  "name": "برتقال",
  "image": "/assets/photos/orange/items/lju.jpg",
  "price": 120,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "برتقال من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljv",
  "name": "فريز",
  "image": "/assets/photos/orange/items/ljv.jpg",
  "price": 140,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "فريز من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljw",
  "name": "اناناس",
  "image": "/assets/photos/orange/items/ljw.jpg",
  "price": 160,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "اناناس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljx",
  "name": "رمان وبرتقال",
  "image": "/assets/photos/orange/items/ljx.jpg",
  "price": 130,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "رمان وبرتقال من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljy",
  "name": "مانجا",
  "image": "/assets/photos/orange/items/ljy.jpg",
  "price": 160,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "مانجا من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ljz",
  "name": "برتقال مع اناناس",
  "image": "/assets/photos/orange/items/ljz.jpg",
  "price": 130,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "برتقال مع اناناس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk1",
  "name": "كيوي مع اناناس",
  "image": "/assets/photos/orange/items/lk1.jpg",
  "price": 160,
  "unit": "",
  "category": "العصائر الطبيعة",
  "available": true,
  "featured": false,
  "description": "كيوي مع اناناس من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "105y",
  "name": "موز وحليب مع قشطة وعسل ومكسرات",
  "image": "/assets/photos/orange/items/105y.jpg",
  "price": 225,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب مع قشطة وعسل ومكسرات من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "15in",
  "name": "كوكتيل دايت",
  "image": "/assets/photos/orange/items/15in.jpg",
  "price": 140,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز + حليب+ تمر  + شوفان",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk8",
  "name": "موز وحليب وفروالة",
  "image": "/assets/photos/orange/items/lk8.jpg",
  "price": 160,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب وفروالة من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk5",
  "name": "موز وحليب وتمر",
  "image": "/assets/photos/orange/items/lk5.jpg",
  "price": 160,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب وتمر من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk9",
  "name": "موز وحليب وشوكولا",
  "image": "/assets/photos/orange/items/lk9.jpg",
  "price": 160,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب وشوكولا من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk6",
  "name": "موز وحليب",
  "image": "/assets/photos/orange/items/lk6.jpg",
  "price": 140,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "موز وحليب من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk4",
  "name": "كوكتيل فواكة",
  "image": "/assets/photos/orange/items/lk4.jpg",
  "price": 150,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "كوكتيل فواكة من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lk7",
  "name": "مانجا مع الحليب",
  "image": "/assets/photos/orange/items/lk7.jpg",
  "price": 160,
  "unit": "",
  "category": "الكوكتيلات",
  "available": true,
  "featured": false,
  "description": "مانجا مع الحليب من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "15ip",
  "name": "سلطة فواكه كرانش",
  "image": "/assets/photos/orange/items/15ip.jpg",
  "price": 370,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه كرانش من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "14by",
  "name": "orange cup - كاسة أورانج",
  "image": "/assets/photos/orange/items/14by.jpg",
  "price": 225,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "orange cup - كاسة أورانج من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "q30",
  "name": "سلطة فواكه سنيكرز",
  "image": "/assets/photos/orange/items/q30.jpg",
  "price": 390,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه سنيكرز من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "q31",
  "name": "سلطة فواكه اوريو",
  "image": "/assets/photos/orange/items/q31.jpg",
  "price": 370,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه اوريو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkb",
  "name": "‎سلطة فواكه نوتيلا",
  "image": "/assets/photos/orange/items/lkb.jpg",
  "price": 370,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "‎سلطة فواكه نوتيلا من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkc",
  "name": "‎سلطة اورانج",
  "image": "/assets/photos/orange/items/lkc.jpg",
  "price": 390,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "‎سلطة اورانج من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lka",
  "name": "‎سلطة فواكه دايت",
  "image": "/assets/photos/orange/items/lka.jpg",
  "price": 370,
  "unit": "",
  "category": "سلطات الفواكه",
  "available": true,
  "featured": false,
  "description": "‎سلطة فواكه دايت من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkt",
  "name": "البوري",
  "image": "/assets/photos/orange/items/lkt.jpg",
  "price": 50,
  "unit": "",
  "category": "موهيتو",
  "available": false,
  "featured": false,
  "description": "البوري من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "14vz",
  "name": "بيور موهيتو",
  "image": "/assets/photos/orange/items/14vz.jpg",
  "price": 150,
  "unit": "",
  "category": "موهيتو",
  "available": true,
  "featured": false,
  "description": "بيور موهيتو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "14w0",
  "name": "اوشن موهيتو",
  "image": "/assets/photos/orange/items/14w0.jpg",
  "price": 150,
  "unit": "",
  "category": "موهيتو",
  "available": true,
  "featured": false,
  "description": "اوشن موهيتو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "14w1",
  "name": "فراولة موهيتو",
  "image": "/assets/photos/orange/items/14w1.jpg",
  "price": 150,
  "unit": "",
  "category": "موهيتو",
  "available": true,
  "featured": false,
  "description": "فراولة موهيتو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll5",
  "name": "ايس لاتيه",
  "image": "/assets/photos/orange/items/ll5.jpg",
  "price": 125,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "ايس لاتيه من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkw",
  "name": "شاي",
  "image": "/assets/photos/orange/items/lkw.jpg",
  "price": 65,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "شاي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lky",
  "name": "اسبريسو",
  "image": "/assets/photos/orange/items/lky.jpg",
  "price": 85,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "اسبريسو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lkz",
  "name": "اسبريسو دبل",
  "image": "/assets/photos/orange/items/lkz.jpg",
  "price": 125,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "اسبريسو دبل من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll0",
  "name": "هوت شوكليت",
  "image": "/assets/photos/orange/items/ll0.jpg",
  "price": 125,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "هوت شوكليت من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll1",
  "name": "كاباتشينو",
  "image": "/assets/photos/orange/items/ll1.jpg",
  "price": 130,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "كاباتشينو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll2",
  "name": "لاتيه كراميل",
  "image": "/assets/photos/orange/items/ll2.jpg",
  "price": 130,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "لاتيه كراميل من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll3",
  "name": "ايس كافيه",
  "image": "/assets/photos/orange/items/ll3.jpg",
  "price": 125,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "ايس كافيه من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll4",
  "name": "كارميل مكياتو",
  "image": "/assets/photos/orange/items/ll4.jpg",
  "price": 160,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "كارميل مكياتو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ll6",
  "name": "ايس موكا",
  "image": "/assets/photos/orange/items/ll6.jpg",
  "price": 125,
  "unit": "",
  "category": "المشروبات الساخنة والباردة",
  "available": true,
  "featured": false,
  "description": "ايس موكا من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "17wt",
  "name": "كاسة دبي",
  "image": "/assets/photos/orange/items/17wt.jpg",
  "price": 225,
  "unit": "",
  "category": "منتجاتنا الجديدة  😍",
  "available": true,
  "featured": false,
  "description": "كاسة دبي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "17ws",
  "name": "افوكادو بالفواكه والعسل والمكسراات",
  "image": "/assets/photos/orange/items/17ws.jpg",
  "price": 250,
  "unit": "",
  "category": "منتجاتنا الجديدة  😍",
  "available": true,
  "featured": false,
  "description": "افوكادو بالفواكه والعسل والمكسراات من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "17wu",
  "name": "كاسة براوني",
  "image": "/assets/photos/orange/items/17wu.jpg",
  "price": 225,
  "unit": "",
  "category": "منتجاتنا الجديدة  😍",
  "available": true,
  "featured": false,
  "description": "كاسة براوني من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1869",
  "name": "براوني بالبوظة",
  "image": "/assets/photos/orange/items/1869.jpg",
  "price": 225,
  "unit": "",
  "category": "منتجاتنا الجديدة  😍",
  "available": true,
  "featured": false,
  "description": "براوني بالبوظة من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "186a",
  "name": "توتي فروتي",
  "image": "/assets/photos/orange/items/186a.jpg",
  "price": 225,
  "unit": "",
  "category": "منتجاتنا الجديدة  😍",
  "available": true,
  "featured": false,
  "description": "توتي فروتي من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "186c",
  "name": "شوكولامو",
  "image": "/assets/photos/orange/items/186c.jpg",
  "price": 225,
  "unit": "",
  "category": "منتجاتنا الجديدة  😍",
  "available": true,
  "featured": false,
  "description": "شوكولامو من عصائر أورنج تركيا.",
  "imageFit": "cover",
  "options": []
 }
];

const orangeProducts = orangeProductCatalog.map((product, index) => ({
  ...product,
  id: 40001 + index,
  storeId: orangeStore.id
}));

const orangeDeliverySettings = {
  [orangeStore.id]: { mode: "distance", fixedFee: 30, ratePerKm: 15, prepMinutes: 25, maxRoundTripKm: 120 }
};
