// Generated for فلافل صاج (SAJ Falafel & Pide) — Kayabaşı, Adnan Menderes Bulvarı, 34494 Başakşehir/İstanbul.
// Levantine falafel / manakish-on-saj / pide restaurant. Source: saj.macho.menu (lamaz backend),
// native Arabic names, prices in TL. 113 products (size/portion variants merged into option groups;
// every product keeps a unique image path — the source reuses a few stock photos across similar dishes).
// NOTE: sajProductCatalog is intentionally emptied in the repo (perf) — the full catalog lives in
// Supabase and is pushed via scripts/_scrape/push-store.cjs.
const sajStore = {
 "id": 64,
 "name": "فلافل صاج",
 "category": "مطاعم",
 "image": "/assets/photos/saj/cover.jpg",
 "coverImage": "/assets/photos/saj/cover.jpg",
 "logoImage": "/assets/photos/saj/logo.png",
 "logo": "ص",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": {
  "lat": 41.1238531,
  "lng": 28.7722425
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.1238531,28.7722425",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "فلافل صاج (SAJ Falafel & Pide) — مطعم للمأكولات الشامية الشعبية في كايا باشي بباشاك شهير، إسطنبول. فلافل طازج مقرمش، مناقيش على الصاج، معجنات وفطائر شامية، لحم بعجين وصفائح، فتّات باللحمة والمكسرات، بيتزا، سندويشات بطاطا وعجّة، وأطباق مقبلات ومتبلات. مفتوح من التاسعة صباحاً حتى الثانية بعد منتصف الليل — توصيل إلى باب بيتك.",
 "address": "كايا باشي، شارع عدنان مندريس، 34494 باشاك شهير، إسطنبول، تركيا",
 "phone": "+90 501 010 50 00",
 "whatsapp": "+90 501 010 50 00",
 "email": "",
 "website": "https://www.instagram.com/saj.falafel.tr",
 "sourceUrl": "https://saj.macho.menu/ar/osxzw-2fzue-tqqym",
 "hours": "يومياً ٩:٠٠ صباحاً – ٢:٠٠ بعد منتصف الليل",
 "areas": [
  "كايا شهير",
  "باشاك شهير",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

// Full catalog used ONLY for the Supabase push; emptied in the committed repo (see note above).
const sajFullCatalog = [
 {"name":"سندويشة بطاطا خبزة صاج","price":150,"category":"بطاطا","unit":"سندويش","image":"/assets/photos/saj/3.jpg","sourceId":"3"},
 {"name":"صحن بطاطا","price":150,"category":"بطاطا","unit":"","image":"/assets/photos/saj/69.jpg","sourceId":"69","options":[{"name":"الحجم","values":["صغير","كبير"],"extra":[0,50]}]},
 {"name":"سندويشة بطاطا خبزة محمرة","price":165,"category":"بطاطا","unit":"سندويش","image":"/assets/photos/saj/166.jpg","sourceId":"166"},
 {"name":"سندويشة بطاطا مع قشقوان خبزة صاج","price":170,"category":"بطاطا","unit":"سندويش","image":"/assets/photos/saj/11.jpg","sourceId":"11"},
 {"name":"سندويشة بطاطا مع قشقوان خبزة محمرة","price":190,"category":"بطاطا","unit":"سندويش","image":"/assets/photos/saj/167.jpg","sourceId":"167"},
 {"name":"سندويشة عجة خبزة صاج","price":150,"category":"عجة","unit":"سندويش","image":"/assets/photos/saj/165.jpg","sourceId":"165"},
 {"name":"سندويشة عجة مع محمرة","price":175,"category":"عجة","unit":"سندويش","image":"/assets/photos/saj/5.jpg","sourceId":"5"},
 {"name":"وجبة عجة","price":350,"category":"عجة","unit":"طبق","image":"/assets/photos/saj/86.jpg","sourceId":"86"},
 {"name":"محمرة","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/16.jpg","sourceId":"16"},
 {"name":"زعتر","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/18.jpg","sourceId":"18"},
 {"name":"شوكولا","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/20.jpg","sourceId":"20"},
 {"name":"سبانخ","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/22.jpg","sourceId":"22"},
 {"name":"زيتون","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/23.jpg","sourceId":"23"},
 {"name":"جبنة بيروتية (سادة)","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/24.jpg","sourceId":"24"},
 {"name":"جبنة شامية","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/25.jpg","sourceId":"25"},
 {"name":"جبنة كيري","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/31.jpg","sourceId":"31"},
 {"name":"سودة (قلوبات)","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/39.jpg","sourceId":"39"},
 {"name":"جبنة أصابع","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/224.jpg","sourceId":"224"},
 {"name":"جبنة بالزعتر الأخضر","price":50,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/226.jpg","sourceId":"226"},
 {"name":"محمرة مع قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/17.jpg","sourceId":"17"},
 {"name":"زعتر مع قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/19.jpg","sourceId":"19"},
 {"name":"بطاطا مع قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/21.jpg","sourceId":"21"},
 {"name":"جبنة قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/28.jpg","sourceId":"28"},
 {"name":"جبنة مدورة (شرائح جبنة مع نعناع)","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/30.jpg","sourceId":"30"},
 {"name":"جبة كردية (سلطة زيتون مع جبنة بلدي)","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/32.jpg","sourceId":"32"},
 {"name":"شيش مع فطر وقشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/41.jpg","sourceId":"41"},
 {"name":"مكسيكانو","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/42.jpg","sourceId":"42"},
 {"name":"سجق","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/43.jpg","sourceId":"43"},
 {"name":"سجق مع قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/44.jpg","sourceId":"44"},
 {"name":"بيتزا سواريه","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/99.jpg","sourceId":"99"},
 {"name":"شيش سادة","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/100.jpg","sourceId":"100"},
 {"name":"مرتديلا مع قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/101.jpg","sourceId":"101"},
 {"name":"فطيرة لحمة خضار (غنم)","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/102.jpg","sourceId":"102"},
 {"name":"فطيرة لحمة دبس رمان (غنم)","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/103.jpg","sourceId":"103"},
 {"name":"شيش مع قشقوان","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/177.jpg","sourceId":"177"},
 {"name":"جبنة ميكس (جبنة قشقوان وبيضة)","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/178.jpg","sourceId":"178"},
 {"name":"لبنة","price":60,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/225.jpg","sourceId":"225"},
 {"name":"صفيحة شامية خضار","price":70,"category":"معجنات (فطائر)","unit":"","image":"/assets/photos/saj/111.jpg","sourceId":"111","options":[{"name":"الكمية","values":["قرص","كيلو"],"extra":[0,930]}]},
 {"name":"صفيحة شامية دبس رمان","price":70,"category":"معجنات (فطائر)","unit":"","image":"/assets/photos/saj/227.jpg","sourceId":"227","options":[{"name":"الكمية","values":["قرص","كيلو"],"extra":[0,930]}]},
 {"name":"لحم بعجين خضار (غنم)","price":75,"category":"معجنات (فطائر)","unit":"","image":"/assets/photos/saj/104.jpg","sourceId":"104","options":[{"name":"الكمية","values":["قرص","كيلو"],"extra":[0,925]}]},
 {"name":"لحم بعجين دبس رمان (غنم)","price":75,"category":"معجنات (فطائر)","unit":"","image":"/assets/photos/saj/105.jpg","sourceId":"105","options":[{"name":"الكمية","values":["قرص","كيلو"],"extra":[0,925]}]},
 {"name":"فطيرة شاورما","price":75,"category":"معجنات (فطائر)","unit":"قطعة","image":"/assets/photos/saj/229.jpg","sourceId":"229"},
 {"name":"رغيف صاج","price":7.5,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/115.jpg","sourceId":"115"},
 {"name":"منقوشة محمرة","price":100,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/45.jpg","sourceId":"45"},
 {"name":"منقوشة زعتر","price":100,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/47.jpg","sourceId":"47"},
 {"name":"منقوشة شوكولا","price":100,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/176.jpg","sourceId":"176"},
 {"name":"منقوشة محمرة مع قشقوان","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/46.jpg","sourceId":"46"},
 {"name":"منقوشة زعتر مع قشقوان","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/48.jpg","sourceId":"48"},
 {"name":"منقوشة جبنة قشقوان","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/49.jpg","sourceId":"49"},
 {"name":"منقوشة جبنة بلدية (بيضة)","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/50.jpg","sourceId":"50"},
 {"name":"منقوشة جبنة مشكلة (قشقوان وبيضة)","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/51.jpg","sourceId":"51"},
 {"name":"منقوشة سبانخ","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/112.jpg","sourceId":"112"},
 {"name":"منقوشة زعتر وجبنة بلدية","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/113.jpg","sourceId":"113"},
 {"name":"منقوشة بطاطا","price":120,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/114.jpg","sourceId":"114"},
 {"name":"منقوشة مرتديلا مع قشقوان","price":130,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/52.jpg","sourceId":"52"},
 {"name":"منقوشة سجق مع قشقوان","price":225,"category":"مناقيش عالصاج","unit":"قطعة","image":"/assets/photos/saj/174.jpg","sourceId":"174"},
 {"name":"خيار ولبن","price":50,"category":"السلطات","unit":"طبق","image":"/assets/photos/saj/57.jpg","sourceId":"57"},
 {"name":"فتوش","price":175,"category":"السلطات","unit":"طبق","image":"/assets/photos/saj/53.jpg","sourceId":"53"},
 {"name":"تبولة","price":175,"category":"السلطات","unit":"طبق","image":"/assets/photos/saj/54.jpg","sourceId":"54"},
 {"name":"سلطة شرقية","price":175,"category":"السلطات","unit":"طبق","image":"/assets/photos/saj/55.jpg","sourceId":"55"},
 {"name":"صحن زيتون","price":125,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/155.jpg","sourceId":"155"},
 {"name":"صحن مرتديلا","price":150,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/151.jpg","sourceId":"151"},
 {"name":"صحن لبنة","price":150,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/153.jpg","sourceId":"153"},
 {"name":"صحن مكدوس","price":150,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/154.jpg","sourceId":"154"},
 {"name":"صحن جبنة","price":175,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/152.jpg","sourceId":"152"},
 {"name":"بيض مقلي","price":200,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/143.jpg","sourceId":"143"},
 {"name":"بيض عيون","price":200,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/150.jpg","sourceId":"150"},
 {"name":"صحن يلانجي","price":225,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/56.jpg","sourceId":"56"},
 {"name":"صحن مسبحة (حمص ناعم)","price":225,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/61.jpg","sourceId":"61"},
 {"name":"صحن مشكل (مسبحة، متبل، بابا غنوج)","price":225,"category":"الأطباق","unit":"","image":"/assets/photos/saj/164.jpg","sourceId":"164","description":"مسبحة، متبل، بابا غنوج","options":[{"name":"الحجم","values":["صغير","وسط","كبير"],"extra":[0,25,75]}]},
 {"name":"حمص حب بزيت (بحمض)","price":240,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/65.jpg","sourceId":"65"},
 {"name":"حمص حب بلبن (بطحينة)","price":240,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/66.jpg","sourceId":"66"},
 {"name":"فول بزيت (بحمض)","price":240,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/67.jpg","sourceId":"67"},
 {"name":"فول بلبن (بطحينة)","price":240,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/68.jpg","sourceId":"68"},
 {"name":"فول مهروس بطحينة","price":240,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/141.jpg","sourceId":"141"},
 {"name":"فول مهروس بحمض","price":240,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/142.jpg","sourceId":"142"},
 {"name":"بابا غنوج","price":250,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/71.jpg","sourceId":"71"},
 {"name":"متبل","price":250,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/72.jpg","sourceId":"72"},
 {"name":"بيض مع مرتديلا","price":250,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/147.jpg","sourceId":"147"},
 {"name":"بيض مع قشقوان","price":250,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/148.jpg","sourceId":"148"},
 {"name":"بيض مع طماطم","price":250,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/149.jpg","sourceId":"149"},
 {"name":"بيض مع بطاطا","price":250,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/161.jpg","sourceId":"161"},
 {"name":"صحن مسبحة مع لحمة","price":300,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/63.jpg","sourceId":"63"},
 {"name":"بيض مع لحمة","price":300,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/146.jpg","sourceId":"146"},
 {"name":"متبل مع لحمة","price":325,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/156.jpg","sourceId":"156"},
 {"name":"صحن مسبحة مع لحمة ومكسرات","price":350,"category":"الأطباق","unit":"طبق","image":"/assets/photos/saj/64.jpg","sourceId":"64"},
 {"name":"صحن فلافل","price":90,"category":"فلافل","unit":"","image":"/assets/photos/saj/59.jpg","sourceId":"59","options":[{"name":"الحجم","values":["صغير (٦ أقراص)","كبير (١٠ أقراص)"],"extra":[0,45]}]},
 {"name":"سندويشة فلافل خبزة سياحي","price":125,"category":"فلافل","unit":"سندويش","image":"/assets/photos/saj/160.jpg","sourceId":"160"},
 {"name":"سندويشة فلافل خبزة صاج","price":135,"category":"فلافل","unit":"سندويش","image":"/assets/photos/saj/159.jpg","sourceId":"159"},
 {"name":"سندويشة فلافل خبزة محمرة","price":150,"category":"فلافل","unit":"سندويش","image":"/assets/photos/saj/158.jpg","sourceId":"158"},
 {"name":"وجبة فلافل عربي فرط","price":225,"category":"فلافل","unit":"طبق","image":"/assets/photos/saj/81.jpg","sourceId":"81"},
 {"name":"وجبة فلافل عربي صاج","price":250,"category":"فلافل","unit":"طبق","image":"/assets/photos/saj/82.jpg","sourceId":"82"},
 {"name":"وجبة فلافل عربي سياحي","price":250,"category":"فلافل","unit":"طبق","image":"/assets/photos/saj/83.jpg","sourceId":"83"},
 {"name":"وجبة فلافل عربي محمرة","price":275,"category":"فلافل","unit":"طبق","image":"/assets/photos/saj/84.jpg","sourceId":"84"},
 {"name":"فتة بسمنة","price":250,"category":"الفتات","unit":"طبق","image":"/assets/photos/saj/76.jpg","sourceId":"76"},
 {"name":"فتة بزيت زيتون","price":250,"category":"الفتات","unit":"طبق","image":"/assets/photos/saj/77.jpg","sourceId":"77"},
 {"name":"فتة بسمنة مع مكسرات","price":300,"category":"الفتات","unit":"طبق","image":"/assets/photos/saj/79.jpg","sourceId":"79"},
 {"name":"فتة بزيت مع مكسرات","price":300,"category":"الفتات","unit":"طبق","image":"/assets/photos/saj/175.jpg","sourceId":"175"},
 {"name":"فتة باللحمة","price":375,"category":"الفتات","unit":"طبق","image":"/assets/photos/saj/78.jpg","sourceId":"78"},
 {"name":"فتة باللحمة والمكسرات","price":400,"category":"الفتات","unit":"طبق","image":"/assets/photos/saj/80.jpg","sourceId":"80"},
 {"name":"خضار","price":300,"category":"بيتزا","unit":"","image":"/assets/photos/saj/116.jpg","sourceId":"116","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,90,100,200]}]},
 {"name":"مارغريتا","price":300,"category":"بيتزا","unit":"","image":"/assets/photos/saj/117.jpg","sourceId":"117","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,90,100,200]}]},
 {"name":"فطر","price":340,"category":"بيتزا","unit":"","image":"/assets/photos/saj/120.jpg","sourceId":"120","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,100,110,210]}]},
 {"name":"سجق","price":340,"category":"بيتزا","unit":"","image":"/assets/photos/saj/121.jpg","sourceId":"121","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,100,110,210]}]},
 {"name":"فطر وسجق","price":340,"category":"بيتزا","unit":"","image":"/assets/photos/saj/122.jpg","sourceId":"122","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,100,110,210]}]},
 {"name":"دجاج","price":340,"category":"بيتزا","unit":"","image":"/assets/photos/saj/123.jpg","sourceId":"123","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,100,110,210]}]},
 {"name":"فصول الأربعة","price":340,"category":"بيتزا","unit":"","image":"/assets/photos/saj/163.jpg","sourceId":"163","options":[{"name":"الحجم","values":["وسط","عائلي","محشي الأطراف (وسط)","محشي الأطراف (عائلي)"],"extra":[0,100,110,210]}]},
 {"name":"ماء","price":10,"category":"المشروبات","unit":"قطعة","image":"/assets/photos/saj/168.jpg","sourceId":"168"},
 {"name":"شاي","price":30,"category":"المشروبات","unit":"قطعة","image":"/assets/photos/saj/172.jpg","sourceId":"172"},
 {"name":"شاي مع نعناع","price":30,"category":"المشروبات","unit":"قطعة","image":"/assets/photos/saj/173.jpg","sourceId":"173"},
 {"name":"صودا","price":40,"category":"المشروبات","unit":"قطعة","image":"/assets/photos/saj/169.jpg","sourceId":"169"},
 {"name":"عيران","price":40,"category":"المشروبات","unit":"قطعة","image":"/assets/photos/saj/171.jpg","sourceId":"171"},
 {"name":"كولا","price":50,"category":"المشروبات","unit":"قطعة","image":"/assets/photos/saj/170.jpg","sourceId":"170"}
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const sajProductCatalog = [];

const sajProducts = (sajProductCatalog.length ? sajProductCatalog : sajFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1480001 + index,
  storeId: sajStore.id
}));

const sajDeliverySettings = {
  [sajStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 25, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { sajStore, sajProducts, sajDeliverySettings };
}
