// Generated for حلويات سلورة (Salloura) — Esenyurt, Istanbul. Prices on request.
const sallouraStore = {
  "id": 14,
  "name": "حلويات سلورة",
  "category": "حلويات",
  "image": "/assets/photos/salloura/cover.jpg",
  "coverImage": "/assets/photos/salloura/cover.jpg",
  "logoImage": "/assets/photos/salloura/logo.png",
  "logo": "س",
  "rating": 0,
  "reviews": 0,
  "newStore": true,
  "delivery": 30,
  "minOrder": 0,
  "time": "40 - 60 دقيقة",
  "distance": 21.5,
  "location": {
    "lat": 41.0341,
    "lng": 28.673
  },
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=Salloura+1105.+Sk.+9B+Esenyurt+Istanbul",
  "open": true,
  "featured": true,
  "hasOffer": false,
  "priceOnRequest": true,
  "description": "حلويات سلورة (Salloura) — عراقة الحلويات الحلبية منذ 1875: بقلاوة وكول وشكور ومبرومة وأصابع بالفستق والكاجو، معمول وكرابيج وكعك، وتشكيلات وعلب فاخرة. الأسعار عند الطلب عبر واتساب.",
  "address": "1105. Sk. 9B، 34517 إسنيورت، إسطنبول، تركيا",
  "phone": "+90 545 654 53 77",
  "whatsapp": "+90 545 654 53 77",
  "email": "ismfaurjw@gmail.com",
  "website": "",
  "sourceUrl": "",
  "hours": "يرجى تأكيد أوقات العمل والأسعار عبر واتساب",
  "areas": [
    "إسنيورت",
    "إسطنبول",
    "مناطق التوصيل حسب المسافة"
  ],
  "fulfillment": "توصيل واستلام",
  "subscription": "احترافي",
  "orderCount": 0,
  "officialStore": true
};

const sallouraProductCatalog = [
  {
    "sourceId": "mishkal_1200",
    "name": "تشكيلة عربية مشكّلة 1200 غرام",
    "image": "/assets/photos/salloura/products/mishkal_1200.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "علب وتشكيلات",
    "available": true,
    "featured": true,
    "description": "تشكيلة عربية مشكّلة 1200 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "mishkal_650",
    "name": "حلويات عربية مشكّلة 650 غرام",
    "image": "/assets/photos/salloura/products/mishkal_650.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "علب وتشكيلات",
    "available": true,
    "featured": true,
    "description": "حلويات عربية مشكّلة 650 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "mishkal_450",
    "name": "حلويات عربية مشكّلة 450 غرام",
    "image": "/assets/photos/salloura/products/mishkal_450.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "علب وتشكيلات",
    "available": true,
    "featured": false,
    "description": "حلويات عربية مشكّلة 450 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "mishkal_1000",
    "name": "حلويات عربية مشكّلة 1000 غرام",
    "image": "/assets/photos/salloura/products/mishkal_1000.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "علب وتشكيلات",
    "available": true,
    "featured": true,
    "description": "حلويات عربية مشكّلة 1000 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "kol_w_shkor",
    "name": "كول وشكور",
    "image": "/assets/photos/salloura/products/kol_w_shkor.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": true,
    "description": "كول وشكور من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "joja_mikserat",
    "name": "جوجة مكسرات",
    "image": "/assets/photos/salloura/products/joja_mikserat.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة",
    "available": true,
    "featured": false,
    "description": "جوجة مكسرات من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "loqmet_sultan",
    "name": "لقمة السلطان",
    "image": "/assets/photos/salloura/products/loqmet_sultan.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": true,
    "description": "لقمة السلطان من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "asabe_kaju",
    "name": "أصابع كاجو",
    "image": "/assets/photos/salloura/products/asabe_kaju.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالكاجو",
    "available": true,
    "featured": false,
    "description": "أصابع كاجو من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "mabroumeh",
    "name": "مبرومة",
    "image": "/assets/photos/salloura/products/mabroumeh.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": true,
    "description": "مبرومة من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "harisa_loz",
    "name": "هريسة لوز",
    "image": "/assets/photos/salloura/products/harisa_loz.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "هريسة",
    "available": true,
    "featured": false,
    "description": "هريسة لوز من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "harisa_fistik",
    "name": "هريسة فستق",
    "image": "/assets/photos/salloura/products/harisa_fistik.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "هريسة",
    "available": true,
    "featured": true,
    "description": "هريسة فستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "baklava_fistik",
    "name": "بقلاوة فستق",
    "image": "/assets/photos/salloura/products/baklava_fistik.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": true,
    "description": "بقلاوة فستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "joz_kaju",
    "name": "جوز كاجو",
    "image": "/assets/photos/salloura/products/joz_kaju.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالكاجو",
    "available": true,
    "featured": false,
    "description": "جوز كاجو من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "siwar_fistik",
    "name": "سوار فستق",
    "image": "/assets/photos/salloura/products/siwar_fistik.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": false,
    "description": "سوار فستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "ward_alsham",
    "name": "ورد الشام",
    "image": "/assets/photos/salloura/products/ward_alsham.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": true,
    "description": "ورد الشام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "birqa",
    "name": "بيرقة",
    "image": "/assets/photos/salloura/products/birqa.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة",
    "available": true,
    "featured": false,
    "description": "بيرقة من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "batoria",
    "name": "بتورية",
    "image": "/assets/photos/salloura/products/batoria.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": false,
    "description": "بتورية من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "dolma",
    "name": "ضولما",
    "image": "/assets/photos/salloura/products/dolma.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": false,
    "description": "ضولما من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "lsan_asfour",
    "name": "لسان العصفور",
    "image": "/assets/photos/salloura/products/lsan_asfour.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة",
    "available": true,
    "featured": false,
    "description": "لسان العصفور من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "asmaliyya",
    "name": "عصملية",
    "image": "/assets/photos/salloura/products/asmaliyya.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة",
    "available": true,
    "featured": false,
    "description": "عصملية من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "loqmet_box",
    "name": "علبة لقمة السلطان 500 غرام",
    "image": "/assets/photos/salloura/products/loqmet_box.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "علب وتشكيلات",
    "available": true,
    "featured": false,
    "description": "علبة لقمة السلطان 500 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "boqj_fistik",
    "name": "بقج فستق",
    "image": "/assets/photos/salloura/products/boqj_fistik.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": false,
    "description": "بقج فستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "maamoul_box",
    "name": "معمول طرابلسي علبة 500 غرام",
    "image": "/assets/photos/salloura/products/maamoul_box.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "معمول طرابلسي علبة 500 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "maamoul_mix",
    "name": "معمول مشكّل",
    "image": "/assets/photos/salloura/products/maamoul_mix.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": true,
    "description": "معمول مشكّل من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "moajjanat_box",
    "name": "معجنات مشكّلة 500 غرام",
    "image": "/assets/photos/salloura/products/moajjanat_box.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "معجنات مشكّلة 500 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "siniora_box",
    "name": "علبة سنيورة 500 غرام",
    "image": "/assets/photos/salloura/products/siniora_box.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "علبة سنيورة 500 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "kaak",
    "name": "كعك",
    "image": "/assets/photos/salloura/products/kaak.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "كعك من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "barazek",
    "name": "برازق",
    "image": "/assets/photos/salloura/products/barazek.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "برازق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "maamoul_trabl",
    "name": "معمول طرابلسي",
    "image": "/assets/photos/salloura/products/maamoul_trabl.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "معمول طرابلسي من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "ajwa_box",
    "name": "عجوة 500 غرام",
    "image": "/assets/photos/salloura/products/ajwa_box.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "عجوة 500 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "siniora",
    "name": "سنيورة",
    "image": "/assets/photos/salloura/products/siniora.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "سنيورة من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "karabij_box",
    "name": "كرابيج فستق 500 غرام",
    "image": "/assets/photos/salloura/products/karabij_box.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "علبة",
    "category": "معمول",
    "available": true,
    "featured": false,
    "description": "كرابيج فستق 500 غرام من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "kunafa_fistik",
    "name": "كنافة بالفستق",
    "image": "/assets/photos/salloura/products/kunafa_fistik.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "صحن",
    "category": "أطباق وكنافة",
    "available": true,
    "featured": true,
    "description": "كنافة بالفستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "halawet_jibn",
    "name": "حلاوة الجبن بالفستق",
    "image": "/assets/photos/salloura/products/halawet_jibn.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "صحن",
    "category": "أطباق وكنافة",
    "available": true,
    "featured": false,
    "description": "حلاوة الجبن بالفستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  },
  {
    "sourceId": "asabe_fistik",
    "name": "أصابع بالفستق",
    "image": "/assets/photos/salloura/products/asabe_fistik.webp",
    "price": 0,
    "priceOnRequest": true,
    "unit": "كيلو",
    "category": "بقلاوة بالفستق",
    "available": true,
    "featured": false,
    "description": "أصابع بالفستق من حلويات سلورة — حلويات حلبية فاخرة منذ 1875. السعر والتوفّر عبر واتساب.",
    "imageFit": "cover",
    "options": []
  }
];

const sallouraProducts = sallouraProductCatalog.map((product, index) => ({
  ...product,
  id: 14001 + index,
  storeId: sallouraStore.id
}));

const sallouraDeliverySettings = {
  [sallouraStore.id]: { mode: "distance", fixedFee: 30, ratePerKm: 15, prepMinutes: 30, maxRoundTripKm: 130 }
};
