// Generated for مطعم أيام شامية (Sam Gunleri) — Esenyurt, Istanbul. Full menu via API (image-bearing items only)
const samStore = {
 "id": 18,
 "name": "مطعم أيام شامية",
 "category": "مطاعم",
 "image": "/assets/photos/sam/cover.jpg",
 "coverImage": "/assets/photos/sam/cover.jpg",
 "logoImage": "/assets/photos/sam/logo.png",
 "logo": "ش",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "40 - 70 دقيقة",
 "distance": 22.0,
 "location": {
  "lat": 41.035936,
  "lng": 28.678008
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.035935792509,28.678007796407",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم أيام شامية — نكهات شامية أصيلة: الشاورما، الفروج والمشاوي والوجبات الغربية، الأطباق الشرقية والمناسف، الكبة والأسماك والمعجنات، إضافة إلى الوافل والكريب وسلطات الفواكه والعصائر والكوكتيلات الطازجة.",
 "address": "إسنيورت، إسطنبول، تركيا",
 "phone": "+90 505 173 58 70",
 "whatsapp": "+90 505 173 58 70",
 "email": "",
 "website": "https://samgunleri.com/",
 "sourceUrl": "https://samgunleri.com/",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسنيورت",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const samProductCatalog = [
 {
  "sourceId": "item",
  "name": "سندويش سوبريم",
  "image": "/assets/photos/sam/products/m000.webp",
  "price": 225,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": true,
  "description": "سندويش سوبريم من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-2",
  "name": "منسف مندي لحم كتف كامل",
  "image": "/assets/photos/sam/products/m001.webp",
  "price": 3200,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": true,
  "description": "منسف مندي لحم كتف كامل من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-3",
  "name": "سنديش تشيز برغر دجاج",
  "image": "/assets/photos/sam/products/m002.webp",
  "price": 240,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": true,
  "description": "سنديش تشيز برغر دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-4",
  "name": "ميني بان كيك لوتس",
  "image": "/assets/photos/sam/products/m003.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": true,
  "description": "ميني بان كيك لوتس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-5",
  "name": "سلطة خضار",
  "image": "/assets/photos/sam/products/m007.webp",
  "price": 170,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": true,
  "description": "سلطة خضار من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-6",
  "name": "سندويش برغر دجاج",
  "image": "/assets/photos/sam/products/m008.webp",
  "price": 225,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": true,
  "description": "سندويش برغر دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-7",
  "name": "كبسة دجاج نصف حبة",
  "image": "/assets/photos/sam/products/m010.webp",
  "price": 525,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "كبسة دجاج نصف حبة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-8",
  "name": "وجبة اطفال",
  "image": "/assets/photos/sam/products/m012.webp",
  "price": 200,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة اطفال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-9",
  "name": "كريب رول أيام شامية",
  "image": "/assets/photos/sam/products/m013.webp",
  "price": 390,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب رول أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-10",
  "name": "ميني بان كيك أطفال",
  "image": "/assets/photos/sam/products/m014.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك أطفال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-11",
  "name": "سندويش بطاطا صمون",
  "image": "/assets/photos/sam/products/m015.webp",
  "price": 130,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "سندويش بطاطا صمون من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-12",
  "name": "ميني بان كيك فواكه",
  "image": "/assets/photos/sam/products/m016.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك فواكه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-13",
  "name": "سبايسي برغر",
  "image": "/assets/photos/sam/products/m017.webp",
  "price": 245,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "سبايسي برغر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-14",
  "name": "سلطة فواكه كيندر",
  "image": "/assets/photos/sam/products/m018.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه كيندر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-15",
  "name": "سلطة فواكه تويكس",
  "image": "/assets/photos/sam/products/m019.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه تويكس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-16",
  "name": "مياه",
  "image": "/assets/photos/sam/products/m020.webp",
  "price": 15,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "مياه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-17",
  "name": "وافل ستيك شوكلا",
  "image": "/assets/photos/sam/products/m021.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل ستيك شوكلا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-18",
  "name": "سندويش كرانشي",
  "image": "/assets/photos/sam/products/m022.webp",
  "price": 225,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "سندويش كرانشي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-19",
  "name": "قشاطي أيام شامية",
  "image": "/assets/photos/sam/products/m024.webp",
  "price": 400,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "قشاطي أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-20",
  "name": "عصير فريز لتر",
  "image": "/assets/photos/sam/products/m025.webp",
  "price": 300,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير فريز لتر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-21",
  "name": "سندويش سمك فيليه",
  "image": "/assets/photos/sam/products/m027.webp",
  "price": 220,
  "unit": "",
  "category": "أسماك",
  "available": true,
  "featured": false,
  "description": "سندويش سمك فيليه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-22",
  "name": "قرص كبة مقلية",
  "image": "/assets/photos/sam/products/m028.webp",
  "price": 90,
  "unit": "",
  "category": "كبة",
  "available": true,
  "featured": false,
  "description": "قرص كبة مقلية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-23",
  "name": "ليموناضة",
  "image": "/assets/photos/sam/products/m029.webp",
  "price": 110,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "ليموناضة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "5",
  "name": "وجبة عائلي 5 أشخاص",
  "image": "/assets/photos/sam/products/m030.webp",
  "price": 1175,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "وجبة عائلي 5 أشخاص من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-24",
  "name": "بيتزا مرتديلا وسط",
  "image": "/assets/photos/sam/products/m031.webp",
  "price": 315,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا مرتديلا وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-25",
  "name": "سندويش شاورما اكسترا",
  "image": "/assets/photos/sam/products/m032.webp",
  "price": 170,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما اكسترا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-26",
  "name": "عصير برتقال",
  "image": "/assets/photos/sam/products/m033.webp",
  "price": 110,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير برتقال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-27",
  "name": "وجبة عربي اكسترا",
  "image": "/assets/photos/sam/products/m034.webp",
  "price": 315,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "وجبة عربي اكسترا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-28",
  "name": "وافل ستيك بستاشيو",
  "image": "/assets/photos/sam/products/m036.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل ستيك بستاشيو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-29",
  "name": "كولا ليمون تنك",
  "image": "/assets/photos/sam/products/m037.webp",
  "price": 40,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "كولا ليمون تنك من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-30",
  "name": "سلطة جرجير",
  "image": "/assets/photos/sam/products/m038.webp",
  "price": 170,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "سلطة جرجير من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-31",
  "name": "عيران كبير",
  "image": "/assets/photos/sam/products/m041.webp",
  "price": 30,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "عيران كبير من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-32",
  "name": "عصير المانجو",
  "image": "/assets/photos/sam/products/m042.webp",
  "price": 140,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير المانجو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-33",
  "name": "وجبة مندي شيش",
  "image": "/assets/photos/sam/products/m043.webp",
  "price": 275,
  "unit": "",
  "category": "مشاوي",
  "available": true,
  "featured": false,
  "description": "وجبة مندي شيش من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-34",
  "name": "زيرو دايت تنك",
  "image": "/assets/photos/sam/products/m044.webp",
  "price": 40,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "زيرو دايت تنك من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-35",
  "name": "سلطة فواكه كيت كات",
  "image": "/assets/photos/sam/products/m045.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه كيت كات من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-36",
  "name": "موز وحليب وفراولة",
  "image": "/assets/photos/sam/products/m046.webp",
  "price": 150,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "موز وحليب وفراولة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-37",
  "name": "وجبة اطفال",
  "image": "/assets/photos/sam/products/m047.webp",
  "price": 200,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة اطفال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-38",
  "name": "سندويش شاورما عادي",
  "image": "/assets/photos/sam/products/m049.webp",
  "price": 140,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما عادي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-39",
  "name": "نصف حبة مندي دجاج",
  "image": "/assets/photos/sam/products/m050.webp",
  "price": 525,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "نصف حبة مندي دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-40",
  "name": "سندويش شيش طاووق",
  "image": "/assets/photos/sam/products/m052.webp",
  "price": 225,
  "unit": "",
  "category": "مشاوي",
  "available": true,
  "featured": false,
  "description": "سندويش شيش طاووق من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-41",
  "name": "منسف مندي لحم كتف كامل",
  "image": "/assets/photos/sam/products/m055.webp",
  "price": 3200,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "منسف مندي لحم كتف كامل من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-42",
  "name": "كريب أوريو",
  "image": "/assets/photos/sam/products/m056.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب أوريو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-43",
  "name": "صحن بطاطا شرائح",
  "image": "/assets/photos/sam/products/m058.webp",
  "price": 125,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "صحن بطاطا شرائح من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-44",
  "name": "زيرو دايت تنك",
  "image": "/assets/photos/sam/products/m059.webp",
  "price": 40,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "زيرو دايت تنك من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-45",
  "name": "سندويش سمك فيليه",
  "image": "/assets/photos/sam/products/m060.webp",
  "price": 220,
  "unit": "",
  "category": "أسماك",
  "available": true,
  "featured": false,
  "description": "سندويش سمك فيليه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-46",
  "name": "نصف حبة مندي دجاج",
  "image": "/assets/photos/sam/products/m061.webp",
  "price": 525,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "نصف حبة مندي دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-47",
  "name": "كوكتيل موز وحليب و بستاشيو",
  "image": "/assets/photos/sam/products/m065.webp",
  "price": 150,
  "unit": "",
  "category": "كوكتيلات وميلك شيك",
  "available": true,
  "featured": false,
  "description": "كوكتيل موز وحليب و بستاشيو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-48",
  "name": "بيتزا مرتديلا وسط",
  "image": "/assets/photos/sam/products/m066.webp",
  "price": 315,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا مرتديلا وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-49",
  "name": "سلطة فواكه كرانش",
  "image": "/assets/photos/sam/products/m068.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه كرانش من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-50",
  "name": "سندويش بطاطا خبز عادي دبل",
  "image": "/assets/photos/sam/products/m070.webp",
  "price": 140,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "سندويش بطاطا خبز عادي دبل من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-51",
  "name": "أفوكادو",
  "image": "/assets/photos/sam/products/m071.webp",
  "price": 200,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "أفوكادو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-52",
  "name": "صحن بطاطا شرائح",
  "image": "/assets/photos/sam/products/m072.webp",
  "price": 125,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "صحن بطاطا شرائح من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-53",
  "name": "وجبة كوردون بلو",
  "image": "/assets/photos/sam/products/m073.webp",
  "price": 340,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة كوردون بلو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-54",
  "name": "تبولة",
  "image": "/assets/photos/sam/products/m074.webp",
  "price": 170,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "تبولة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-55",
  "name": "كولا برتقال لتر",
  "image": "/assets/photos/sam/products/m075.webp",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "كولا برتقال لتر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-56",
  "name": "افوكادو سادة",
  "image": "/assets/photos/sam/products/m077.webp",
  "price": 180,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "افوكادو سادة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-57",
  "name": "سندويش شاورما اكسترا",
  "image": "/assets/photos/sam/products/m078.webp",
  "price": 170,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما اكسترا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-58",
  "name": "وجبة دبوس",
  "image": "/assets/photos/sam/products/m079.webp",
  "price": 350,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة دبوس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-59",
  "name": "سندويش برغر لحم",
  "image": "/assets/photos/sam/products/m081.webp",
  "price": 230,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "سندويش برغر لحم من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-60",
  "name": "امبراطور صغير",
  "image": "/assets/photos/sam/products/m082.webp",
  "price": 300,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "امبراطور صغير من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-61",
  "name": "نصف حبة مندي دجاج",
  "image": "/assets/photos/sam/products/m083.webp",
  "price": 525,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "نصف حبة مندي دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-62",
  "name": "سنديش تشيز برغر دجاج",
  "image": "/assets/photos/sam/products/m085.webp",
  "price": 240,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "سنديش تشيز برغر دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-63",
  "name": "وجبة فرانشيسكو",
  "image": "/assets/photos/sam/products/m086.webp",
  "price": 325,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة فرانشيسكو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-64",
  "name": "وافل أيام شامية",
  "image": "/assets/photos/sam/products/m088.webp",
  "price": 390,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-65",
  "name": "سلطة فواكه كيت كات",
  "image": "/assets/photos/sam/products/m089.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه كيت كات من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-66",
  "name": "شاورما كيلو",
  "image": "/assets/photos/sam/products/m090.webp",
  "price": 875,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "شاورما كيلو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-67",
  "name": "بيتزا دجاج وسط",
  "image": "/assets/photos/sam/products/m091.webp",
  "price": 325,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "بيتزا دجاج وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-68",
  "name": "سندويش فاهيتا",
  "image": "/assets/photos/sam/products/m092.webp",
  "price": 225,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "سندويش فاهيتا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "1200",
  "name": "حبة كبسة أو مندي لحم 1200 غرام",
  "image": "/assets/photos/sam/products/m093.webp",
  "price": 1800,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "حبة كبسة أو مندي لحم 1200 غرام من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-69",
  "name": "سندويش كرانشي",
  "image": "/assets/photos/sam/products/m095.webp",
  "price": 225,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "سندويش كرانشي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-70",
  "name": "بيتزا خضار وسط",
  "image": "/assets/photos/sam/products/m096.webp",
  "price": 295,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا خضار وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-71",
  "name": "وجبة مندي شاورما",
  "image": "/assets/photos/sam/products/m097.webp",
  "price": 275,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "وجبة مندي شاورما من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-72",
  "name": "وافل شوكلا بلجيكي",
  "image": "/assets/photos/sam/products/m098.webp",
  "price": 260,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل شوكلا بلجيكي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-73",
  "name": "تبولة",
  "image": "/assets/photos/sam/products/m099.webp",
  "price": 170,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "تبولة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-74",
  "name": "عصير فريز لتر",
  "image": "/assets/photos/sam/products/m100.webp",
  "price": 300,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير فريز لتر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-75",
  "name": "بيتزا دجاج عائلي",
  "image": "/assets/photos/sam/products/m101.webp",
  "price": 425,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "بيتزا دجاج عائلي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-76",
  "name": "امبراطور كبير",
  "image": "/assets/photos/sam/products/m102.webp",
  "price": 350,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "امبراطور كبير من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-77",
  "name": "وجبة كوردون بلو",
  "image": "/assets/photos/sam/products/m103.webp",
  "price": 340,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة كوردون بلو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-78",
  "name": "مياه",
  "image": "/assets/photos/sam/products/m104.webp",
  "price": 15,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "مياه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-79",
  "name": "كريب أوريو",
  "image": "/assets/photos/sam/products/m106.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب أوريو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-80",
  "name": "بان كيك شوكلا دبي",
  "image": "/assets/photos/sam/products/m108.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "بان كيك شوكلا دبي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-81",
  "name": "وجبة عربي عادي",
  "image": "/assets/photos/sam/products/m110.webp",
  "price": 240,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "وجبة عربي عادي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-82",
  "name": "صحن رز كبسة سادة",
  "image": "/assets/photos/sam/products/m111.webp",
  "price": 135,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "صحن رز كبسة سادة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-83",
  "name": "سلطة فواكه مكسرات",
  "image": "/assets/photos/sam/products/m112.webp",
  "price": 350,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه مكسرات من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-84",
  "name": "عصير برتقال وجزر",
  "image": "/assets/photos/sam/products/m114.webp",
  "price": 110,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير برتقال وجزر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-85",
  "name": "صحن بطاطا شرائح",
  "image": "/assets/photos/sam/products/m115.webp",
  "price": 125,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "صحن بطاطا شرائح من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-86",
  "name": "عصير فريز لتر",
  "image": "/assets/photos/sam/products/m116.webp",
  "price": 300,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير فريز لتر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-87",
  "name": "سندويش شاورما دبل",
  "image": "/assets/photos/sam/products/m117.webp",
  "price": 190,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما دبل من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-88",
  "name": "وافل بستاشيو",
  "image": "/assets/photos/sam/products/m118.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل بستاشيو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-89",
  "name": "تفاح أخضر تنك",
  "image": "/assets/photos/sam/products/m119.webp",
  "price": 40,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "تفاح أخضر تنك من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-90",
  "name": "سندويش برغر دجاج",
  "image": "/assets/photos/sam/products/m120.webp",
  "price": 225,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "سندويش برغر دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-91",
  "name": "سلطة فواكه مكسرات",
  "image": "/assets/photos/sam/products/m121.webp",
  "price": 350,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه مكسرات من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-92",
  "name": "بيتزا شيش عائلي",
  "image": "/assets/photos/sam/products/m123.webp",
  "price": 425,
  "unit": "",
  "category": "مشاوي",
  "available": true,
  "featured": false,
  "description": "بيتزا شيش عائلي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "600",
  "name": "نصف حبة كبسة لحم 600 غرام",
  "image": "/assets/photos/sam/products/m125.webp",
  "price": 950,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "نصف حبة كبسة لحم 600 غرام من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-93",
  "name": "صحن متبل بيت نجان",
  "image": "/assets/photos/sam/products/m126.webp",
  "price": 140,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "صحن متبل بيت نجان من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-94",
  "name": "وجبة زنجر",
  "image": "/assets/photos/sam/products/m127.webp",
  "price": 325,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة زنجر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-95",
  "name": "ميني بان كيك بستاشيو",
  "image": "/assets/photos/sam/products/m128.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك بستاشيو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-96",
  "name": "قرص كبة مقلية",
  "image": "/assets/photos/sam/products/m129.webp",
  "price": 90,
  "unit": "",
  "category": "كبة",
  "available": true,
  "featured": false,
  "description": "قرص كبة مقلية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-97",
  "name": "بيتزا فاهيتا مكسيكي فرانشيسكو وسط",
  "image": "/assets/photos/sam/products/m131.webp",
  "price": 350,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا فاهيتا مكسيكي فرانشيسكو وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-98",
  "name": "ميني بان كيك أطفال",
  "image": "/assets/photos/sam/products/m133.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك أطفال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-99",
  "name": "بيتزا فاهيتا مكسيكي فرانشيسكو وسط",
  "image": "/assets/photos/sam/products/m135.webp",
  "price": 350,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا فاهيتا مكسيكي فرانشيسكو وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-100",
  "name": "صحن بطاطا شرائح",
  "image": "/assets/photos/sam/products/m136.webp",
  "price": 125,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "صحن بطاطا شرائح من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-101",
  "name": "منسف مندي لحم كتف كامل",
  "image": "/assets/photos/sam/products/m137.webp",
  "price": 3200,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "منسف مندي لحم كتف كامل من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "300",
  "name": "وجبة كبسة لحم 300 غرام",
  "image": "/assets/photos/sam/products/m140.webp",
  "price": 450,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "وجبة كبسة لحم 300 غرام من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-102",
  "name": "سلطة فواكه اللوتس",
  "image": "/assets/photos/sam/products/m141.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه اللوتس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-103",
  "name": "سلطة فواكه أوريو",
  "image": "/assets/photos/sam/products/m142.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه أوريو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-104",
  "name": "عصير منغا و أناناس",
  "image": "/assets/photos/sam/products/m143.webp",
  "price": 125,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير منغا و أناناس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-105",
  "name": "عصير بولو",
  "image": "/assets/photos/sam/products/m144.webp",
  "price": 110,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير بولو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-106",
  "name": "سنديش تشيز برغر دجاج",
  "image": "/assets/photos/sam/products/m145.webp",
  "price": 240,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "سنديش تشيز برغر دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-107",
  "name": "سبايسي برغر",
  "image": "/assets/photos/sam/products/m146.webp",
  "price": 245,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "سبايسي برغر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-108",
  "name": "قشاطي كبير",
  "image": "/assets/photos/sam/products/m147.webp",
  "price": 350,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "قشاطي كبير من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-109",
  "name": "سلطة فواكه نيوتيلا أيام شامية",
  "image": "/assets/photos/sam/products/m148.webp",
  "price": 400,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه نيوتيلا أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-110",
  "name": "تبولة",
  "image": "/assets/photos/sam/products/m150.webp",
  "price": 170,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "تبولة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-111",
  "name": "بيتزا خضار وسط",
  "image": "/assets/photos/sam/products/m151.webp",
  "price": 295,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا خضار وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-112",
  "name": "وجبة كبسة دجاج",
  "image": "/assets/photos/sam/products/m152.webp",
  "price": 275,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "وجبة كبسة دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-113",
  "name": "نصف فروج مشوي",
  "image": "/assets/photos/sam/products/m154.webp",
  "price": 250,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "نصف فروج مشوي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-114",
  "name": "كريب شوكلا دبي",
  "image": "/assets/photos/sam/products/m155.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب شوكلا دبي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-115",
  "name": "بيتزا فاهيتا مكسيكي فرانشيسكو عائلي",
  "image": "/assets/photos/sam/products/m156.webp",
  "price": 465,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "بيتزا فاهيتا مكسيكي فرانشيسكو عائلي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-116",
  "name": "قشاطي أيام شامية",
  "image": "/assets/photos/sam/products/m157.webp",
  "price": 400,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "قشاطي أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-117",
  "name": "بيتزا شيش عائلي",
  "image": "/assets/photos/sam/products/m158.webp",
  "price": 425,
  "unit": "",
  "category": "مشاوي",
  "available": true,
  "featured": false,
  "description": "بيتزا شيش عائلي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-118",
  "name": "سندويش اسكالوب",
  "image": "/assets/photos/sam/products/m159.webp",
  "price": 225,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "سندويش اسكالوب من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-119",
  "name": "وافل شوكلا دبي",
  "image": "/assets/photos/sam/products/m160.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل شوكلا دبي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-120",
  "name": "وجبة مندي دجاج",
  "image": "/assets/photos/sam/products/m161.webp",
  "price": 275,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "وجبة مندي دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-121",
  "name": "سندويش برغر دجاج",
  "image": "/assets/photos/sam/products/m162.webp",
  "price": 225,
  "unit": "",
  "category": "فروج ودجاج",
  "available": true,
  "featured": false,
  "description": "سندويش برغر دجاج من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-122",
  "name": "صحن بطاطا شرائح",
  "image": "/assets/photos/sam/products/m163.webp",
  "price": 125,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "صحن بطاطا شرائح من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-123",
  "name": "امبراطور كبير",
  "image": "/assets/photos/sam/products/m164.webp",
  "price": 350,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "امبراطور كبير من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-124",
  "name": "قطعة برك جبنة",
  "image": "/assets/photos/sam/products/m165.webp",
  "price": 50,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "قطعة برك جبنة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-125",
  "name": "قرص كبة مقلية",
  "image": "/assets/photos/sam/products/m167.webp",
  "price": 90,
  "unit": "",
  "category": "كبة",
  "available": true,
  "featured": false,
  "description": "قرص كبة مقلية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-126",
  "name": "وافل شوكلا دبي",
  "image": "/assets/photos/sam/products/m168.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل شوكلا دبي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-127",
  "name": "كريب رول أيام شامية",
  "image": "/assets/photos/sam/products/m169.webp",
  "price": 390,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب رول أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-128",
  "name": "وجبة عربي عادي",
  "image": "/assets/photos/sam/products/m170.webp",
  "price": 240,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "وجبة عربي عادي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-129",
  "name": "سلطة فواكه اللوتس",
  "image": "/assets/photos/sam/products/m171.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه اللوتس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-130",
  "name": "كريب فوتتشيني",
  "image": "/assets/photos/sam/products/m173.webp",
  "price": 325,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب فوتتشيني من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-131",
  "name": "إلجينت بوكس منيو",
  "image": "/assets/photos/sam/products/m175.webp",
  "price": 725,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "إلجينت بوكس منيو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-132",
  "name": "كولا لتر",
  "image": "/assets/photos/sam/products/m176.webp",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "كولا لتر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-133",
  "name": "امبراطور أيام شامية",
  "image": "/assets/photos/sam/products/m178.webp",
  "price": 400,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "امبراطور أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-134",
  "name": "وافل ستيك بستاشيو",
  "image": "/assets/photos/sam/products/m179.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل ستيك بستاشيو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-135",
  "name": "وافل أيام شامية",
  "image": "/assets/photos/sam/products/m180.webp",
  "price": 390,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "وافل أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-136",
  "name": "صحن متبل بيت نجان",
  "image": "/assets/photos/sam/products/m181.webp",
  "price": 140,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "صحن متبل بيت نجان من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-137",
  "name": "تبولة",
  "image": "/assets/photos/sam/products/m183.webp",
  "price": 170,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "تبولة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-138",
  "name": "صحن مسبحة مع شاورما",
  "image": "/assets/photos/sam/products/m184.webp",
  "price": 275,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "صحن مسبحة مع شاورما من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-139",
  "name": "سندويش شاورما عادي",
  "image": "/assets/photos/sam/products/m185.webp",
  "price": 140,
  "unit": "",
  "category": "شاورما",
  "available": true,
  "featured": false,
  "description": "سندويش شاورما عادي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-140",
  "name": "كوكتيل فواكه",
  "image": "/assets/photos/sam/products/m186.webp",
  "price": 140,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "كوكتيل فواكه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-141",
  "name": "كولا برتقال لتر",
  "image": "/assets/photos/sam/products/m187.webp",
  "price": 50,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "كولا برتقال لتر من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-142",
  "name": "بيتزا مرتديلا عائلي",
  "image": "/assets/photos/sam/products/m189.webp",
  "price": 375,
  "unit": "",
  "category": "مشروبات",
  "available": true,
  "featured": false,
  "description": "بيتزا مرتديلا عائلي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-143",
  "name": "قرص كبة مقلية",
  "image": "/assets/photos/sam/products/m190.webp",
  "price": 90,
  "unit": "",
  "category": "كبة",
  "available": true,
  "featured": false,
  "description": "قرص كبة مقلية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-144",
  "name": "ميني بان كيك شوكولا",
  "image": "/assets/photos/sam/products/m193.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك شوكولا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-145",
  "name": "وجبة كبسة شيش",
  "image": "/assets/photos/sam/products/m194.webp",
  "price": 275,
  "unit": "",
  "category": "مشاوي",
  "available": true,
  "featured": false,
  "description": "وجبة كبسة شيش من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-146",
  "name": "سلطة فواكه تويكس",
  "image": "/assets/photos/sam/products/m195.webp",
  "price": 325,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه تويكس من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-147",
  "name": "عصير بولو",
  "image": "/assets/photos/sam/products/m196.webp",
  "price": 110,
  "unit": "",
  "category": "عصائر طبيعية",
  "available": true,
  "featured": false,
  "description": "عصير بولو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-148",
  "name": "بيتزا فاهيتا مكسيكي فرانشيسكو وسط",
  "image": "/assets/photos/sam/products/m198.webp",
  "price": 350,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا فاهيتا مكسيكي فرانشيسكو وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-149",
  "name": "قشاطي أيام شامية",
  "image": "/assets/photos/sam/products/m199.webp",
  "price": 400,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "قشاطي أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-150",
  "name": "كريب شوكلا دبي",
  "image": "/assets/photos/sam/products/m200.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب شوكلا دبي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-151",
  "name": "أفوكادو",
  "image": "/assets/photos/sam/products/m203.webp",
  "price": 200,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "أفوكادو من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-152",
  "name": "وجبة عربي عادي",
  "image": "/assets/photos/sam/products/m204.webp",
  "price": 240,
  "unit": "",
  "category": "أطباق شرقية",
  "available": true,
  "featured": false,
  "description": "وجبة عربي عادي من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-153",
  "name": "بيتزا بالفطر وسط",
  "image": "/assets/photos/sam/products/m205.webp",
  "price": 285,
  "unit": "",
  "category": "معجنات وبيتزا",
  "available": true,
  "featured": false,
  "description": "بيتزا بالفطر وسط من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-154",
  "name": "ميني بان كيك فواكه",
  "image": "/assets/photos/sam/products/m206.webp",
  "price": 350,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك فواكه من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-155",
  "name": "سلطة فواكه نيوتيلا أيام شامية",
  "image": "/assets/photos/sam/products/m208.webp",
  "price": 400,
  "unit": "",
  "category": "سلطات فواكه",
  "available": true,
  "featured": false,
  "description": "سلطة فواكه نيوتيلا أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-156",
  "name": "صحن محمرة",
  "image": "/assets/photos/sam/products/m209.webp",
  "price": 80,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "صحن محمرة من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-157",
  "name": "سندويش فاهيتا",
  "image": "/assets/photos/sam/products/m210.webp",
  "price": 225,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "سندويش فاهيتا من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-158",
  "name": "وجبة اطفال",
  "image": "/assets/photos/sam/products/m211.webp",
  "price": 200,
  "unit": "",
  "category": "أطباق متنوعة",
  "available": true,
  "featured": false,
  "description": "وجبة اطفال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-159",
  "name": "صحن متبل بيت نجان",
  "image": "/assets/photos/sam/products/m212.webp",
  "price": 140,
  "unit": "",
  "category": "مقبلات وسلطات",
  "available": true,
  "featured": false,
  "description": "صحن متبل بيت نجان من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-160",
  "name": "كريب أيام شامية",
  "image": "/assets/photos/sam/products/m213.webp",
  "price": 400,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "كريب أيام شامية من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-161",
  "name": "صحن بطاطا أصابع",
  "image": "/assets/photos/sam/products/m214.webp",
  "price": 125,
  "unit": "",
  "category": "وجبات غربية",
  "available": true,
  "featured": false,
  "description": "صحن بطاطا أصابع من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-162",
  "name": "ميني بان كيك أطفال",
  "image": "/assets/photos/sam/products/m215.webp",
  "price": 290,
  "unit": "",
  "category": "وافل وكريب",
  "available": true,
  "featured": false,
  "description": "ميني بان كيك أطفال من مطعم أيام شامية، يُحضَّر طازجاً.",
  "imageFit": "cover",
  "options": []
 }
];

const samProducts = samProductCatalog.map((product, index) => ({
  ...product,
  id: 18001 + index,
  storeId: samStore.id
}));

const samDeliverySettings = {
  [samStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
