// Generated for سما ماركت (Sema Market) — Mehterçeşme, Esenyurt/İstanbul.
// Source: WhatsApp Business catalog (wa.me/c/905375742375), 98 products across 10 categories.
// Google Places match: place_id ChIJa4fzTiBftRQRYyfuHUyoe4A (phone matches exactly).
// Products with no price in the catalog were excluded.
const semamarketStore = {
 "id": 118,
 "name": "سما ماركت",
 "category": "سوبر ماركت",
 "image": "/assets/photos/semamarket/cover.jpg",
 "coverImage": "/assets/photos/semamarket/cover.jpg",
 "logoImage": "/assets/photos/semamarket/logo.jpg",
 "logo": "س",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": { "lat": 41.0207688, "lng": 28.6642762 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.0207688,28.6642762",
 "open": true,
 "featured": false,
 "hasOffer": false,
 "offer": "",
 "description": "سما ماركت (بيم العرب) — سوبر ماركت في حي مهتر تشيشمة بإسنيورت: قهوة وشاي ومتة، أرز ومواد غذائية، ألبان وأجبان، مخبوزات، معلبات، مشروبات، شيبس، سمنة وزيوت، بسكويت وشوكولا. توصيل حسب المسافة.",
 "address": "Mehterçeşme, 1869 Sk. No:26A, 34515 Esenyurt/İstanbul",
 "phone": "+90 537 574 23 75",
 "whatsapp": "+90 537 574 23 75",
 "email": "",
 "website": "",
 "sourceUrl": "https://wa.me/c/905375742375",
 "hours": "يومياً 10:00 ص – 10:00 م",
 "areas": ["إسنيورت", "مناطق إسطنبول حسب المسافة"],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true,
 "approvalStatus": "pending",
 "googlePlaceId": "ChIJa4fzTiBftRQRYyfuHUyoe4A",
 "googleMapsUrl": "https://maps.google.com/?cid=9258178503863314275"
};

const semamarketFullCatalog = [
  {"name":"بن العلبي اكسترا هال 200غ","price":190,"category":"قهوة","image":"/assets/photos/semamarket/p1.jpg"},
  {"name":"بن الحموي هال اكسترا 180غ","price":220,"category":"قهوة","image":"/assets/photos/semamarket/p2.jpg"},
  {"name":"بن الحموي مع هال كلاسيك 180غ","price":200,"category":"قهوة","image":"/assets/photos/semamarket/p3.jpg"},
  {"name":"بن الحموي سادة 180غ","price":170,"category":"قهوة","image":"/assets/photos/semamarket/p4.jpg"},
  {"name":"بن الشام هال اكسترا 200غ","price":190,"category":"قهوة","image":"/assets/photos/semamarket/p5.jpg"},
  {"name":"بن الشام هال اخضر 200غ","price":180,"category":"قهوة","image":"/assets/photos/semamarket/p6.jpg"},
  {"name":"قهوة محمود افندي 100غ","price":100,"category":"قهوة","image":"/assets/photos/semamarket/p7.jpg"},
  {"name":"العلبي قهوة مرة سائلة 750ml","price":140,"category":"قهوة","image":"/assets/photos/semamarket/p8.jpg"},
  {"name":"العلبي قهوة مرة سريعة التحضير 50غ","price":70,"category":"قهوة","image":"/assets/photos/semamarket/p9.jpg"},
  {"name":"محمود ارز بسمتي 900غ","price":140,"category":"مواد غذائية","image":"/assets/photos/semamarket/p10.jpg"},
  {"name":"الملوك ارز بسمتي ابيض 900غ","price":115,"category":"مواد غذائية","image":"/assets/photos/semamarket/p11.jpg"},
  {"name":"الملوك ارز بسمتي اصفر غولد 900غ","price":115,"category":"مواد غذائية","image":"/assets/photos/semamarket/p12.jpg"},
  {"name":"ارز وكن بالدو للطبخ 1كغ","price":145,"category":"مواد غذائية","image":"/assets/photos/semamarket/p13.jpg"},
  {"name":"رز الريف","price":70,"category":"مواد غذائية","image":"/assets/photos/semamarket/p14.jpg"},
  {"name":"ورق عنب سلسبيل 2كغ كامل / 800غ صافي","price":270,"category":"مواد غذائية","image":"/assets/photos/semamarket/p15.jpg"},
  {"name":"ورق عنب سلسبيل 500غ صافي","price":160,"category":"مواد غذائية","image":"/assets/photos/semamarket/p16.jpg"},
  {"name":"بيض طازج لارج 15بيضة","price":85,"category":"مواد غذائية","image":"/assets/photos/semamarket/p17.jpg"},
  {"name":"مكدوس سلسبيل جيد مطربان","price":185,"category":"مواد غذائية","image":"/assets/photos/semamarket/p18.jpg"},
  {"name":"مكدوس سلسبيل اكسترا مطربان","price":245,"category":"مواد غذائية","image":"/assets/photos/semamarket/p19.jpg"},
  {"name":"içim علبن لبن 500غرام","price":60,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p20.jpg"},
  {"name":"لبن اوزتاد كامل الدسم نصف كيلو","price":55,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p21.jpg"},
  {"name":"içim لبن 1 كغ","price":100,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p22.jpg"},
  {"name":"لبن اوزتاد كامل الدسم 1كغ","price":90,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p23.jpg"},
  {"name":"içim لبن سطل 2كغ","price":160,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p24.jpg"},
  {"name":"لبن اوزتاد 2كغ كامل الدسم","price":170,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p25.jpg"},
  {"name":"الربيع حبنة شلل اكسترا بالكيلو","price":365,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p26.jpg"},
  {"name":"ترويقة جبنة شلل اكسترا بالكيلو","price":370,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p27.jpg"},
  {"name":"ترويقة جبنة مسنرة بالكيلو","price":290,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p28.jpg"},
  {"name":"ريحان لبن مصفى كامل الدسم 500غ","price":125,"category":"اجبان والبان ومنتجات الحليب","image":"/assets/photos/semamarket/p29.jpg"},
  {"name":"خبز الشوفان","price":45,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p30.jpg"},
  {"name":"خبز الشعير","price":45,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p31.jpg"},
  {"name":"خبز قمح حبة كاملة","price":45,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p32.jpg"},
  {"name":"خبز نخالة","price":45,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p33.jpg"},
  {"name":"خبز برغر بالسمسم عدد6","price":75,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p34.jpg"},
  {"name":"خبز ساندويش فاهيتا بالسمسم عدد5","price":75,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p35.jpg"},
  {"name":"خبز صمون مدرسي","price":50,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p36.jpg"},
  {"name":"خبز ارزة اللبنان","price":25,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p37.jpg"},
  {"name":"خبز تفاحة","price":15,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p38.jpg"},
  {"name":"خبز بوف","price":15,"category":"مخبوزات بانواعها","image":"/assets/photos/semamarket/p39.jpg"},
  {"name":"غولدن فول معلب","price":25,"category":"معلبات","image":"/assets/photos/semamarket/p40.jpg"},
  {"name":"فول الصفوة معلب","price":35,"category":"معلبات","image":"/assets/photos/semamarket/p41.jpg"},
  {"name":"فول الصفوة حبة عريضة","price":40,"category":"معلبات","image":"/assets/photos/semamarket/p42.jpg"},
  {"name":"مرتديلا هنا دجاج 200غ","price":45,"category":"معلبات","image":"/assets/photos/semamarket/p43.jpg"},
  {"name":"مرتديلا هنا 380غ","price":75,"category":"معلبات","image":"/assets/photos/semamarket/p44.jpg"},
  {"name":"مرتديلا هنا دجاج 850غ","price":140,"category":"معلبات","image":"/assets/photos/semamarket/p45.jpg"},
  {"name":"طون ليو قطع كبيرة حلو","price":90,"category":"معلبات","image":"/assets/photos/semamarket/p46.jpg"},
  {"name":"طون ليو قطع كبيرة حار","price":90,"category":"معلبات","image":"/assets/photos/semamarket/p47.jpg"},
  {"name":"طون كو 160غ حار","price":65,"category":"معلبات","image":"/assets/photos/semamarket/p48.jpg"},
  {"name":"طون ليوس","price":60,"category":"معلبات","image":"/assets/photos/semamarket/p49.jpg"},
  {"name":"شاي الروحه علبة 400غرام","price":260,"category":"شاي ومتة","image":"/assets/photos/semamarket/p50.jpg"},
  {"name":"شاي الملوك علبة 400غرام","price":260,"category":"شاي ومتة","image":"/assets/photos/semamarket/p51.jpg"},
  {"name":"شاي الغزالين بنكهة البرجموت 400غ","price":360,"category":"شاي ومتة","image":"/assets/photos/semamarket/p52.jpg"},
  {"name":"شاي الوزة 400 غ","price":290,"category":"شاي ومتة","image":"/assets/photos/semamarket/p53.jpg"},
  {"name":"شاي الكبوس 200غ","price":145,"category":"شاي ومتة","image":"/assets/photos/semamarket/p54.jpg"},
  {"name":"شاي الروحه 100ظرف","price":180,"category":"شاي ومتة","image":"/assets/photos/semamarket/p55.jpg"},
  {"name":"شاي الملوك 100ظرف","price":180,"category":"شاي ومتة","image":"/assets/photos/semamarket/p56.jpg"},
  {"name":"شاي الروحه 25ظرف","price":60,"category":"شاي ومتة","image":"/assets/photos/semamarket/p57.jpg"},
  {"name":"شاي الملوك 25ظرف","price":60,"category":"شاي ومتة","image":"/assets/photos/semamarket/p58.jpg"},
  {"name":"متة خارطة","price":95,"category":"شاي ومتة","image":"/assets/photos/semamarket/p59.jpg"},
  {"name":"مالتون شراب شعير تفاح","price":40,"category":"مشروبات","image":"/assets/photos/semamarket/p60.jpg"},
  {"name":"مالتون شراب شعير سادة","price":40,"category":"مشروبات","image":"/assets/photos/semamarket/p61.jpg"},
  {"name":"مالتون رمان شراب شعير","price":40,"category":"مشروبات","image":"/assets/photos/semamarket/p62.jpg"},
  {"name":"سيرما صودا اناناس","price":17,"category":"مشروبات","image":"/assets/photos/semamarket/p63.jpg"},
  {"name":"سبرما صودا ليمون","price":17,"category":"مشروبات","image":"/assets/photos/semamarket/p64.jpg"},
  {"name":"سيرما صودا بطيخ وفريز","price":17,"category":"مشروبات","image":"/assets/photos/semamarket/p65.jpg"},
  {"name":"سيرما صودا تفاح","price":17,"category":"مشروبات","image":"/assets/photos/semamarket/p66.jpg"},
  {"name":"فانتا كنز 330ml","price":45,"category":"مشروبات","image":"/assets/photos/semamarket/p67.jpg"},
  {"name":"ريدبول مسروب طاقة 250مل","price":70,"category":"مشروبات","image":"/assets/photos/semamarket/p68.jpg"},
  {"name":"وينير شرائح عائلي خل وملح","price":25,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p69.jpg"},
  {"name":"وينير شرائح عائلي باربيكيو","price":25,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p70.jpg"},
  {"name":"وينير شرائح عائلي حد وليمون","price":25,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p71.jpg"},
  {"name":"وينير شرائح عائلي كاتشب","price":25,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p72.jpg"},
  {"name":"وينير ديربي بوري باربيكيو","price":25,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p73.jpg"},
  {"name":"وينير شرائح كاتشب","price":20,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p74.jpg"},
  {"name":"وينير شرائح خل","price":20,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p75.jpg"},
  {"name":"وينير شرائح باربكيو","price":20,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p76.jpg"},
  {"name":"وينير شرائح حد وليمون","price":20,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p77.jpg"},
  {"name":"ويلز رقائق بطاطا كاتشب","price":35,"category":"شيبس بانواعه","image":"/assets/photos/semamarket/p78.jpg"},
  {"name":"زيت زيتون سلسبيل الاصلي لتر","price":420,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p79.jpg"},
  {"name":"زيت زيتون سلسبيل الاصلي نصف لتر","price":230,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p80.jpg"},
  {"name":"زيت زيتون اصلي 1لتر","price":350,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p81.jpg"},
  {"name":"وطن زيت عباد الشمس 500مل","price":85,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p82.jpg"},
  {"name":"سونار زيت دوار الشمس 850ml","price":120,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p83.jpg"},
  {"name":"وطن زيت عباد الشمس 1000مل","price":145,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p84.jpg"},
  {"name":"ترويقة سمن بقري 500غ","price":480,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p85.jpg"},
  {"name":"زبدة بريما 250غ","price":35,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p86.jpg"},
  {"name":"الادلبي زبدة نباتية 200غ","price":30,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p87.jpg"},
  {"name":"سمنة الخير نباتي 1 لتر","price":200,"category":"سمنة وزيوت","image":"/assets/photos/semamarket/p88.jpg"},
  {"name":"ETİ كارام","price":31,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p89.jpg"},
  {"name":"اولكر الباني","price":22,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p90.jpg"},
  {"name":"سنيكرز 50غ","price":45,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p91.jpg"},
  {"name":"تويكس 50غ","price":50,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p92.jpg"},
  {"name":"ETİ براوني كيك","price":27,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p93.jpg"},
  {"name":"بومباستيك كيك","price":30,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p94.jpg"},
  {"name":"ETİ جانغا","price":27,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p95.jpg"},
  {"name":"ETİ جانغا شوكولا بيضاء","price":27,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p96.jpg"},
  {"name":"ETİ جانغا دارك","price":27,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p97.jpg"},
  {"name":"ETİ جانغا غولد","price":27,"category":"بسكويت وشوكولا","image":"/assets/photos/semamarket/p98.jpg"},
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const semamarketProductCatalog = [];

const semamarketProducts = (semamarketProductCatalog.length ? semamarketProductCatalog : semamarketFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1980001 + index,
  storeId: semamarketStore.id
}));

const semamarketDeliverySettings = {
  [semamarketStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 30, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { semamarketStore, semamarketProducts, semamarketDeliverySettings };
}
