// Generated for مطعم تهامة اليمن (Tihama) — Esenyurt, Istanbul. Source: menux.app/tihama
const tihamaStore = {
 "id": 16,
 "name": "مطعم تهامة اليمن",
 "category": "مطاعم",
 "image": "/assets/photos/tihama/cover.jpg",
 "coverImage": "/assets/photos/tihama/cover.jpg",
 "logoImage": "/assets/photos/tihama/logo.png",
 "logo": "ت",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "45 - 75 دقيقة",
 "distance": 23.0,
 "location": {
  "lat": 41.0171359,
  "lng": 28.6387955
 },
 "mapUrl": "https://maps.app.goo.gl/QH4G7gAKGjiiNBzy8",
 "open": true,
 "featured": true,
 "hasOffer": true,
 "offer": "عروض اليوم على العصائر الطبيعية",
 "description": "مطعم تهامة اليمن — مطبخ يمني أصيل: مندي ومدفون اللحم والدجاج، قلايات ومشاوي، أطباق جانبية ومقبلات وسلطات، أسماك ومخبازة طازجة، وعصائر طبيعية. تشكيلة ذبائح وولائم للمناسبات.",
 "address": "إسنيورت، إسطنبول، تركيا",
 "phone": "+90 531 866 02 20",
 "whatsapp": "+90 531 866 02 20",
 "email": "",
 "website": "https://menux.app/tihama/",
 "sourceUrl": "https://menux.app/tihama/",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسنيورت",
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const tihamaProductCatalog = [
 {
  "sourceId": "item-5",
  "name": "رز بخاري",
  "image": "/assets/photos/tihama/products/item-001.webp",
  "price": 160,
  "unit": "",
  "category": "جديدنا",
  "available": true,
  "featured": true,
  "description": "رز بخاري من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-6",
  "name": "عصيد يمني",
  "image": "/assets/photos/tihama/products/item-002.webp",
  "price": 270,
  "unit": "",
  "category": "جديدنا",
  "available": true,
  "featured": true,
  "description": "عصيد يمني من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-7",
  "name": "عصير جزر طبيعي",
  "image": "/assets/photos/tihama/products/item-003.webp",
  "price": 120,
  "unit": "",
  "category": "جديدنا",
  "available": true,
  "featured": true,
  "description": "عصير جزر طبيعي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-8",
  "name": "صحن حمص",
  "image": "/assets/photos/tihama/products/item-004.webp",
  "price": 170,
  "unit": "",
  "category": "المقبلات والسلطات",
  "available": true,
  "featured": false,
  "description": "صحن حمص من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-9",
  "name": "سلطة تهامة",
  "image": "/assets/photos/tihama/products/item-005.webp",
  "price": 260,
  "unit": "",
  "category": "المقبلات والسلطات",
  "available": true,
  "featured": false,
  "description": "سلطة مشكلة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-10",
  "name": "سلطة عربية",
  "image": "/assets/photos/tihama/products/item-006.webp",
  "price": 170,
  "unit": "",
  "category": "المقبلات والسلطات",
  "available": true,
  "featured": false,
  "description": "سلطة عربية من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-11",
  "name": "سلطة فتوش",
  "image": "/assets/photos/tihama/products/item-007.webp",
  "price": 190,
  "unit": "",
  "category": "المقبلات والسلطات",
  "available": true,
  "featured": false,
  "description": "سلطة فتوش من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-12",
  "name": "سلطة جرجير",
  "image": "/assets/photos/tihama/products/item-008.webp",
  "price": 170,
  "unit": "",
  "category": "المقبلات والسلطات",
  "available": true,
  "featured": false,
  "description": "سلطة جرجير من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-13",
  "name": "فرولة بالحليب",
  "image": "/assets/photos/tihama/products/item-009.webp",
  "price": 160,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "فرولة بالحليب من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-14",
  "name": "مانجو سادة",
  "image": "/assets/photos/tihama/products/item-010.webp",
  "price": 180,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "مانجو سادة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-15",
  "name": "كوكتيل",
  "image": "/assets/photos/tihama/products/item-011.webp",
  "price": 190,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "كوكتيل من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-16",
  "name": "ليمون",
  "image": "/assets/photos/tihama/products/item-012.webp",
  "price": 140,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "ليمون من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-17",
  "name": "أناناس",
  "image": "/assets/photos/tihama/products/item-013.webp",
  "price": 170,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "أناناس من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-20",
  "name": "مانجو بالموز",
  "image": "/assets/photos/tihama/products/item-016.webp",
  "price": 180,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "مانجو بالموز من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-21",
  "name": "ليمون بالنعناع",
  "image": "/assets/photos/tihama/products/item-017.webp",
  "price": 150,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "ليمون بالنعناع من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-22",
  "name": "برتقال كبس",
  "image": "/assets/photos/tihama/products/item-018.webp",
  "price": 190,
  "unit": "",
  "category": "العصائر",
  "available": true,
  "featured": false,
  "description": "برتقال كبس من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-23",
  "name": "رز ساده (مندي -زربيان -برياني)",
  "image": "/assets/photos/tihama/products/item-019.webp",
  "price": 160,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "رز ساده (مندي -زربيان -برياني) من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-24",
  "name": "مرق لحم",
  "image": "/assets/photos/tihama/products/item-020.webp",
  "price": 70,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "شوربة لحم ساخنة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-25",
  "name": "زبادي",
  "image": "/assets/photos/tihama/products/item-021.webp",
  "price": 80,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "زبادي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-26",
  "name": "لبن خيار",
  "image": "/assets/photos/tihama/products/item-022.webp",
  "price": 100,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "لبن خيار من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-27",
  "name": "سحاوق جبن",
  "image": "/assets/photos/tihama/products/item-023.webp",
  "price": 90,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "سحاوق جبن من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-28",
  "name": "سحاوق أحمر",
  "image": "/assets/photos/tihama/products/item-024.webp",
  "price": 40,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "سحاوق أحمر من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-29",
  "name": "خبز ملوح دبل",
  "image": "/assets/photos/tihama/products/item-025.webp",
  "price": 105,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "خبز ملوح دبل من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-30",
  "name": "خبز رطب",
  "image": "/assets/photos/tihama/products/item-026.webp",
  "price": 85,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "خبز رطب من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-31",
  "name": "خبز رطب بالعسل",
  "image": "/assets/photos/tihama/products/item-027.webp",
  "price": 109,
  "unit": "",
  "category": "اطباق جانبية",
  "available": true,
  "featured": false,
  "description": "خبز رطب بالعسل من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-32",
  "name": "فحسة",
  "image": "/assets/photos/tihama/products/item-028.webp",
  "price": 490,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "لحم بقري عجل مطبوخ مع خلطة بهارات يمنية مميزة، يُقدم في طاجن فخار مع مرق غني ونكهة تراثية أصيلة. يُفضل تناوله مع الخبز الطازج.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-33",
  "name": "سلتة تهامة",
  "image": "/assets/photos/tihama/products/item-029.webp",
  "price": 439,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "مكس فحسة وسلتة يقدم مع الخبز الملوح",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-34",
  "name": "سلتة",
  "image": "/assets/photos/tihama/products/item-030.webp",
  "price": 369,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "مكونه من خضار ومرق لحم ولحم مفروم",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-35",
  "name": "تونة حرضة",
  "image": "/assets/photos/tihama/products/item-031.webp",
  "price": 290,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "تونة حرضة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-36",
  "name": "بامية سادة",
  "image": "/assets/photos/tihama/products/item-032.webp",
  "price": 240,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "بامية سادة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-37",
  "name": "مشكل فرن",
  "image": "/assets/photos/tihama/products/item-033.webp",
  "price": 290,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "مشكل فرن من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-38",
  "name": "فاصوليا حرضة",
  "image": "/assets/photos/tihama/products/item-034.webp",
  "price": 240,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فاصوليا حرضة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-39",
  "name": "فول تهامة",
  "image": "/assets/photos/tihama/products/item-035.webp",
  "price": 250,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فول تهامة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-40",
  "name": "فول حرضة",
  "image": "/assets/photos/tihama/products/item-036.webp",
  "price": 240,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فول حرضة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-41",
  "name": "فاصوليا ناشف",
  "image": "/assets/photos/tihama/products/item-037.webp",
  "price": 240,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فاصوليا ناشف من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-42",
  "name": "فاصوليا بالبيض",
  "image": "/assets/photos/tihama/products/item-038.webp",
  "price": 240,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "فاصوليا بالبيض من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-43",
  "name": "شكشوكة",
  "image": "/assets/photos/tihama/products/item-039.webp",
  "price": 240,
  "unit": "",
  "category": "القلايات",
  "available": true,
  "featured": false,
  "description": "شكشوكة من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-44",
  "name": "لحم حضرمي",
  "image": "/assets/photos/tihama/products/item-040.webp",
  "price": 660,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم حضرمي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-45",
  "name": "لحم مدفون",
  "image": "/assets/photos/tihama/products/item-041.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم مدفون من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-46",
  "name": "لحم زربيان",
  "image": "/assets/photos/tihama/products/item-042.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم زربيان من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-47",
  "name": "لحم برياني",
  "image": "/assets/photos/tihama/products/item-043.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم برياني من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-48",
  "name": "برم لحم",
  "image": "/assets/photos/tihama/products/item-044.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "لحم مسلوق بالبهارات اليمنية الخاصة يقدم مع الرز المندي",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-49",
  "name": "بامية لحم",
  "image": "/assets/photos/tihama/products/item-045.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "بامية لحم من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-50",
  "name": "صانونة لحم",
  "image": "/assets/photos/tihama/products/item-046.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "صانونة لحم من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-51",
  "name": "عقدة لحم",
  "image": "/assets/photos/tihama/products/item-047.webp",
  "price": 650,
  "unit": "",
  "category": "اللحوم",
  "available": true,
  "featured": false,
  "description": "عقدة لحم من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-52",
  "name": "دجاج مندي",
  "image": "/assets/photos/tihama/products/item-048.webp",
  "price": 379,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "نصف دجاجة متبلة بتتبيلة خاصة، مطهية في حفرة المندي فوق الأرز المدخن والمطبوخ ف حفرة المندي كذلك تُقدم مع صوص السحاوق",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-53",
  "name": "دجاج مدفون",
  "image": "/assets/photos/tihama/products/item-049.webp",
  "price": 379,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج مدفون من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-54",
  "name": "دجاج زربيان",
  "image": "/assets/photos/tihama/products/item-050.webp",
  "price": 379,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج زربيان من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-55",
  "name": "دجاج برياني",
  "image": "/assets/photos/tihama/products/item-051.webp",
  "price": 379,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج برياني من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-56",
  "name": "ربع دجاج مندي او برياني او زربيان او مدفون",
  "image": "/assets/photos/tihama/products/item-052.webp",
  "price": 230,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "ربع دجاج",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-57",
  "name": "عقدة دجاج",
  "image": "/assets/photos/tihama/products/item-053.webp",
  "price": 329,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "عقدة دجاج من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-58",
  "name": "بامية دجاج",
  "image": "/assets/photos/tihama/products/item-054.webp",
  "price": 329,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "بامية دجاج من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-59",
  "name": "صانونة دجاج",
  "image": "/assets/photos/tihama/products/item-055.webp",
  "price": 329,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "صانونة دجاج من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-60",
  "name": "مقلقل دجاج",
  "image": "/assets/photos/tihama/products/item-056.webp",
  "price": 379,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "مقلقل دجاج من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-61",
  "name": "دجاج فحم مضبي",
  "image": "/assets/photos/tihama/products/item-057.webp",
  "price": 389,
  "unit": "",
  "category": "الدجاج",
  "available": true,
  "featured": false,
  "description": "دجاج على الفحم متبل بالطريقة اليمينة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-62",
  "name": "سمك موفا",
  "image": "/assets/photos/tihama/products/item-058.webp",
  "price": 519,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "سمكة الليفريك اللذيذة المطبوخه بالتنور تقدم مع صوص السحاوق الجبن والخبز الرطب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-63",
  "name": "صانونة سمك",
  "image": "/assets/photos/tihama/products/item-059.webp",
  "price": 499,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "صانونة سمك من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-64",
  "name": "عقدة سمك",
  "image": "/assets/photos/tihama/products/item-060.webp",
  "price": 499,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "عقدة سمك من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-65",
  "name": "صانونة جمبري",
  "image": "/assets/photos/tihama/products/item-061.webp",
  "price": 499,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "صانونة جمبري من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-66",
  "name": "عقدة جمبري",
  "image": "/assets/photos/tihama/products/item-062.webp",
  "price": 499,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "عقدة جمبري من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-67",
  "name": "جمبري مقلي",
  "image": "/assets/photos/tihama/products/item-063.webp",
  "price": 499,
  "unit": "",
  "category": "الاسماك",
  "available": true,
  "featured": false,
  "description": "جمبري مقلي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-68",
  "name": "فتة تهامة عرائسي",
  "image": "/assets/photos/tihama/products/item-064.webp",
  "price": 270,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "موز - تمر - قشطة - جبن شيدر - خبز تنور - حبة البركة _ حبة السمسم - عسل - مكسرات حسب الطلب",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-69",
  "name": "عريكة ملكي",
  "image": "/assets/photos/tihama/products/item-065.webp",
  "price": 240,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "عريكة ملكي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-70",
  "name": "عريكة عادي",
  "image": "/assets/photos/tihama/products/item-066.webp",
  "price": 219,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "عريكة عادي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-71",
  "name": "معصوب ملكي",
  "image": "/assets/photos/tihama/products/item-067.webp",
  "price": 240,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "معصوب ملكي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-72",
  "name": "معصوب عادي",
  "image": "/assets/photos/tihama/products/item-068.webp",
  "price": 219,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "معصوب عادي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-73",
  "name": "فتة موز",
  "image": "/assets/photos/tihama/products/item-069.webp",
  "price": 219,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "فتة موز من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-74",
  "name": "فتة تمر",
  "image": "/assets/photos/tihama/products/item-070.webp",
  "price": 205,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "فتة تمر من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-75",
  "name": "فتة عسل",
  "image": "/assets/photos/tihama/products/item-071.webp",
  "price": 200,
  "unit": "",
  "category": "المخبازة",
  "available": true,
  "featured": false,
  "description": "فتة عسل من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-76",
  "name": "كولا تركي",
  "image": "/assets/photos/tihama/products/item-072.webp",
  "price": 75,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "كولا تركي من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-77",
  "name": "ماء",
  "image": "/assets/photos/tihama/products/item-073.webp",
  "price": 30,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "ماء من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-78",
  "name": "ايران",
  "image": "/assets/photos/tihama/products/item-074.webp",
  "price": 60,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "ايران من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-79",
  "name": "مندرين برتقال او تفاح",
  "image": "/assets/photos/tihama/products/item-075.webp",
  "price": 75,
  "unit": "",
  "category": "المشروبات",
  "available": true,
  "featured": false,
  "description": "مندرين برتقال او تفاح من مطعم تهامة اليمن.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-80",
  "name": "هريسة قباطي",
  "image": "/assets/photos/tihama/products/item-076.webp",
  "price": 90,
  "unit": "",
  "category": "حلويات يمنية",
  "available": true,
  "featured": false,
  "description": "حلوه يمنية مشهورة مكوناتها المكسرات والفول السوداني",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-81",
  "name": "ذبيحة مندي كاملة",
  "image": "/assets/photos/tihama/products/item-077.webp",
  "price": 9200,
  "unit": "",
  "category": "الذبائح والولائم",
  "available": true,
  "featured": false,
  "description": "ذبيحة جدي وزنها 8 كيلو يفضل الطلب قبلها ب 4ساعات او يوم كامل تكفي ل 14 شخص الى 15 شخص ياتي مع الطلب 4 سلطة خضراء و4 علبة صوص كبيرة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-82",
  "name": "نصف ذبيحة مندي",
  "image": "/assets/photos/tihama/products/item-078.webp",
  "price": 4600,
  "unit": "",
  "category": "الذبائح والولائم",
  "available": true,
  "featured": false,
  "description": "نصف تيس جدي مندي وزنه 4 كيلو تكفي 7 الى 8 اشخاص ياتي مع الطلب2 سلطة خضراء و2 علبة صوص كبيرة",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "item-83",
  "name": "ربع ذبيحة مندي",
  "image": "/assets/photos/tihama/products/item-079.webp",
  "price": 2400,
  "unit": "",
  "category": "الذبائح والولائم",
  "available": true,
  "featured": false,
  "description": "ربع تيس جدي مندي وزنه 2 كيلو يكفي 4 اشخاص كبار ياتي مع الطلب سلطة خضراء وعلبة صوص كبيرة",
  "imageFit": "cover",
  "options": []
 }
];

const tihamaProducts = tihamaProductCatalog.map((product, index) => ({
  ...product,
  id: 16001 + index,
  storeId: tihamaStore.id
}));

const tihamaDeliverySettings = {
  [tihamaStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
