// Generated for مطعم يمن شيف (Yemen Chef) — Istanbul. Source: yemenchef.minidine.com (minidine)
const yemenchefStore = {
 "id": 20,
 "name": "مطعم يمن شيف",
 "category": "مطاعم",
 "image": "/assets/photos/yemenchef/cover.jpg",
 "coverImage": "/assets/photos/yemenchef/cover.jpg",
 "logoImage": "/assets/photos/yemenchef/logo.png",
 "logo": "ي",
 "rating": 0,
 "reviews": 0,
 "newStore": true,
 "delivery": 35,
 "minOrder": 200,
 "time": "40 - 70 دقيقة",
 "distance": 20,
 "location": {
  "lat": 41.007737,
  "lng": 28.681519
 },
 "mapUrl": "https://maps.app.goo.gl/nnu6pz4w4Drj62R2A",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "description": "مطعم يمن شيف — المطبخ اليمني الأصيل في إسطنبول: المندي والمظبي والحنيذ، وجبات اللحوم والدجاج، الأطباق البحرية، الماكولات بالرز، السلطات والمقبلات والمعجنات والحلويات والعصائر. أسماء الأطباق كما في القائمة الرسمية للمطعم.",
 "address": "إسطنبول، تركيا",
 "phone": "+90 530 665 04 61",
 "whatsapp": "+90 530 665 04 61",
 "email": "",
 "website": "https://yemenchef.minidine.com/",
 "sourceUrl": "https://yemenchef.minidine.com/ar/categories/?branch=yemen-chef",
 "hours": "يومياً — يرجى التأكيد عبر الاتصال",
 "areas": [
  "إسطنبول",
  "مناطق التوصيل حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true
};

const yemenchefProductCatalog = [
 {
  "sourceId": "rbaa-dgag-lbn-balkhyar-shaok-mshrob",
  "name": "ربع دجاج +سحاوق + عصير مانجا",
  "image": "/assets/photos/yemenchef/items/item-001.jpeg",
  "price": 270,
  "unit": "قطعة",
  "category": "العروض",
  "available": true,
  "featured": false,
  "description": "ربع دجاج +سحاوق + عصير مانجا من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ns-dgag-lbn-balkhyar-shaok-mshrob",
  "name": "نص دجاج + صانونة دجاج +خبز ملوح + سحاوق + 3 مانجا",
  "image": "/assets/photos/yemenchef/items/item-002.jpeg",
  "price": 790,
  "unit": "قطعة",
  "category": "العروض",
  "available": true,
  "featured": false,
  "description": "نص دجاج + صانونة دجاج +خبز ملوح + سحاوق + 3 مانجا من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ogbtyn-lhm-ns-dgag-slt-shaok",
  "name": "وجبتين لحم + اثنين مرق + سلطه عربي + سحاوق + 2 مشروب",
  "image": "/assets/photos/yemenchef/items/item-003.jpeg",
  "price": 1350,
  "unit": "قطعة",
  "category": "العروض",
  "available": true,
  "featured": false,
  "description": "وجبتين لحم + اثنين مرق + سلطه عربي + سحاوق + 2 مشروب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "zrbyan-lhm",
  "name": "زربيان لحم",
  "image": "/assets/photos/yemenchef/items/item-004.jpeg",
  "price": 640,
  "unit": "قطعة",
  "category": "وجبات اللحوم",
  "available": true,
  "featured": false,
  "description": "زربيان لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mdghot-lhm",
  "name": "مضغوط لحم",
  "image": "/assets/photos/yemenchef/items/item-005.jpg",
  "price": 640,
  "unit": "قطعة",
  "category": "وجبات اللحوم",
  "available": true,
  "featured": false,
  "description": "مضغوط لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mndy-lhm",
  "name": "مندي لحم",
  "image": "/assets/photos/yemenchef/items/item-006.jpg",
  "price": 640,
  "unit": "قطعة",
  "category": "وجبات اللحوم",
  "available": false,
  "featured": false,
  "description": "مندي لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lhm-hdrmy",
  "name": "لحم حضرمي",
  "image": "/assets/photos/yemenchef/items/item-007.jpg",
  "price": 640,
  "unit": "قطعة",
  "category": "وجبات اللحوم",
  "available": false,
  "featured": false,
  "description": "لحم حضرمي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mdfon-lhm",
  "name": "مدفون لحم",
  "image": "/assets/photos/yemenchef/items/item-008.jpg",
  "price": 640,
  "unit": "قطعة",
  "category": "وجبات اللحوم",
  "available": false,
  "featured": false,
  "description": "مدفون لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "brm-lhm",
  "name": "برم لحم",
  "image": "/assets/photos/yemenchef/items/item-009.jpg",
  "price": 640,
  "unit": "قطعة",
  "category": "وجبات اللحوم",
  "available": true,
  "featured": false,
  "description": "برم لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bamy-lhm",
  "name": "بامية لحم",
  "image": "/assets/photos/yemenchef/items/item-010.jpg",
  "price": 435,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "بامية لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "sanon-lhm",
  "name": "صانونة لحم",
  "image": "/assets/photos/yemenchef/items/item-011.jpg",
  "price": 435,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "صانونة لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "dk-lhm",
  "name": "دقة لحم",
  "image": "/assets/photos/yemenchef/items/item-012.jpg",
  "price": 430,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "دقة لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lhm-sghar",
  "name": "لحم صغار",
  "image": "/assets/photos/yemenchef/items/item-013.jpg",
  "price": 430,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "لحم صغار من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aakdo-lhm",
  "name": "عقدة لحم",
  "image": "/assets/photos/yemenchef/items/item-014.jpg",
  "price": 435,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "عقدة لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mthloth-lhm",
  "name": "مثلوث لحم",
  "image": "/assets/photos/yemenchef/items/item-015.jpg",
  "price": 430,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "مثلوث لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kbdh",
  "name": "كبده",
  "image": "/assets/photos/yemenchef/items/item-016.jpg",
  "price": 430,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "كبده من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ft-lhm",
  "name": "فتة لحم",
  "image": "/assets/photos/yemenchef/items/item-017.jpg",
  "price": 420,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "فتة لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fhs",
  "name": "فحسة",
  "image": "/assets/photos/yemenchef/items/item-018.jpg",
  "price": 430,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "فحسة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kbab-snaaany",
  "name": "كباب صنعاني",
  "image": "/assets/photos/yemenchef/items/item-019.jpg",
  "price": 485,
  "unit": "قطعة",
  "category": "ادامات لحوم",
  "available": true,
  "featured": false,
  "description": "كباب صنعاني من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mndy-dgag",
  "name": "مندي دجاج",
  "image": "/assets/photos/yemenchef/items/item-020.jpg",
  "price": 320,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "مندي دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mdfon-dgag",
  "name": "مدفون دجاج",
  "image": "/assets/photos/yemenchef/items/item-021.jpg",
  "price": 320,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "مدفون دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mdby-dgag",
  "name": "مضبي دجاج",
  "image": "/assets/photos/yemenchef/items/item-022.jpg",
  "price": 335,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": false,
  "featured": false,
  "description": "مضبي دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mdghot-dgag",
  "name": "مضغوط دجاج",
  "image": "/assets/photos/yemenchef/items/item-023.jpg",
  "price": 320,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "مضغوط دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "zrbyan-dgag",
  "name": "زربيان دجاج",
  "image": "/assets/photos/yemenchef/items/item-024.jpeg",
  "price": 320,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "زربيان دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "syny-dgagtyn",
  "name": "صينية 2 دجاج",
  "image": "/assets/photos/yemenchef/items/item-025.jpeg",
  "price": 1200,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "صينية 2 دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "syny-thlath-dgagat",
  "name": "صينية 3 دجاجات",
  "image": "/assets/photos/yemenchef/items/item-026.jpeg",
  "price": 1800,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "صينية 3 دجاجات من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "rbaa-ogb-dgag",
  "name": "ربع وجبة دجاج",
  "image": "/assets/photos/yemenchef/items/item-027.jpg",
  "price": 190,
  "unit": "قطعة",
  "category": "وجبات الدجاج",
  "available": true,
  "featured": false,
  "description": "ربع وجبة دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "sanot-dgag",
  "name": "صانونة دجاج",
  "image": "/assets/photos/yemenchef/items/item-028.jpg",
  "price": 310,
  "unit": "قطعة",
  "category": "ادامات دجاج",
  "available": true,
  "featured": false,
  "description": "صانونة دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aakdo-dgag",
  "name": "عقدة دجاج",
  "image": "/assets/photos/yemenchef/items/item-029.jpg",
  "price": 310,
  "unit": "قطعة",
  "category": "ادامات دجاج",
  "available": true,
  "featured": false,
  "description": "عقدة دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ft-dgag-2",
  "name": "فتة دجاج",
  "image": "/assets/photos/yemenchef/items/item-030.jpg",
  "price": 295,
  "unit": "قطعة",
  "category": "ادامات دجاج",
  "available": true,
  "featured": false,
  "description": "فتة دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bamy-dgag",
  "name": "بامية دجاج",
  "image": "/assets/photos/yemenchef/items/item-031.jpg",
  "price": 310,
  "unit": "قطعة",
  "category": "ادامات دجاج",
  "available": true,
  "featured": false,
  "description": "بامية دجاج من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "rz-sadh",
  "name": "رز ساده",
  "image": "/assets/photos/yemenchef/items/item-032.jpg",
  "price": 120,
  "unit": "قطعة",
  "category": "ماكولات بالرز",
  "available": true,
  "featured": false,
  "description": "رز ساده من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mgmsh",
  "name": "مجمش",
  "image": "/assets/photos/yemenchef/items/item-033.jpg",
  "price": 485,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "مجمش من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mks-shyf-alymn",
  "name": "مكس شيف اليمن",
  "image": "/assets/photos/yemenchef/items/item-034.jpg",
  "price": 490,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "مكس شيف اليمن من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fol",
  "name": "فول",
  "image": "/assets/photos/yemenchef/items/item-035.jpeg",
  "price": 220,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فول من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fol-maa-albyd",
  "name": "فول مع البيض",
  "image": "/assets/photos/yemenchef/items/item-036.jpeg",
  "price": 230,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فول مع البيض من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fol-baldk",
  "name": "فول بالدقة",
  "image": "/assets/photos/yemenchef/items/item-037.jpeg",
  "price": 290,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فول بالدقة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fasolya-hrdh",
  "name": "فاصوليا حرضه",
  "image": "/assets/photos/yemenchef/items/item-038.jpg",
  "price": 220,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فاصوليا حرضه من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fasolya-maa-algbn",
  "name": "فاصوليا مع الجبن",
  "image": "/assets/photos/yemenchef/items/item-039.jpg",
  "price": 235,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فاصوليا مع الجبن من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fasolya-nashf",
  "name": "فاصوليا ناشف",
  "image": "/assets/photos/yemenchef/items/item-040.jpg",
  "price": 220,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فاصوليا ناشف من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fasolya-maa-albyd-nashf",
  "name": "فاصوليا مع البيض ناشف",
  "image": "/assets/photos/yemenchef/items/item-041.jpg",
  "price": 235,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فاصوليا مع البيض ناشف من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shkshok",
  "name": "شكشوكة",
  "image": "/assets/photos/yemenchef/items/item-042.jpg",
  "price": 240,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "شكشوكة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "byd-aayon",
  "name": "بيض عيون",
  "image": "/assets/photos/yemenchef/items/item-043.jpeg",
  "price": 150,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "بيض عيون من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "byd-sadh",
  "name": "بيض ساده",
  "image": "/assets/photos/yemenchef/items/item-044.jpeg",
  "price": 150,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "بيض ساده من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slth",
  "name": "سلته",
  "image": "/assets/photos/yemenchef/items/item-045.jpg",
  "price": 320,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "سلته من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mks-slth-ofhs",
  "name": "مكس (سلته وفحسة)",
  "image": "/assets/photos/yemenchef/items/item-046.jpg",
  "price": 470,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "مكس (سلته وفحسة) من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mkl-frn",
  "name": "مشكل فرن",
  "image": "/assets/photos/yemenchef/items/item-047.jpg",
  "price": 250,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "مشكل فرن من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mshkl-aaady",
  "name": "مشكل عادي",
  "image": "/assets/photos/yemenchef/items/item-048.jpg",
  "price": 230,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "مشكل عادي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ft-mrk",
  "name": "فتة مرق",
  "image": "/assets/photos/yemenchef/items/item-049.jpg",
  "price": 180,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "فتة مرق من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bmamy",
  "name": "بامية",
  "image": "/assets/photos/yemenchef/items/item-050.jpg",
  "price": 220,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "بامية من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bzalya",
  "name": "بزاليا",
  "image": "/assets/photos/yemenchef/items/item-051.jpg",
  "price": 220,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "بزاليا من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bzalya-baltonh",
  "name": "بزاليا بالتونه",
  "image": "/assets/photos/yemenchef/items/item-052.jpg",
  "price": 320,
  "unit": "قطعة",
  "category": "مأكولات متنوعه",
  "available": true,
  "featured": false,
  "description": "بزاليا بالتونه من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-srfys",
  "name": "سلطة سرفيس",
  "image": "/assets/photos/yemenchef/items/item-053.jpeg",
  "price": 100,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة سرفيس من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shfot",
  "name": "شفوت",
  "image": "/assets/photos/yemenchef/items/item-054.jpg",
  "price": 150,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "شفوت من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-ftosh",
  "name": "سلطة فتوش",
  "image": "/assets/photos/yemenchef/items/item-055.jpg",
  "price": 170,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة فتوش من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-thr",
  "name": "سلطة ذرة",
  "image": "/assets/photos/yemenchef/items/item-056.jpg",
  "price": 165,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة ذرة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaok-akhdr",
  "name": "سحاوق اخضر",
  "image": "/assets/photos/yemenchef/items/item-057.jpg",
  "price": 45,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سحاوق اخضر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaok-gbn-dbl",
  "name": "سحاوق جبن دبل",
  "image": "/assets/photos/yemenchef/items/item-058.jpeg",
  "price": 100,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سحاوق جبن دبل من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mrk-lhm",
  "name": "مرق لحم",
  "image": "/assets/photos/yemenchef/items/item-059.jpg",
  "price": 30,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "مرق لحم من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lbn-balkhyar",
  "name": "لبن بالخيار",
  "image": "/assets/photos/yemenchef/items/item-060.jpg",
  "price": 55,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "لبن بالخيار من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-grgr",
  "name": "سلطة جرجر",
  "image": "/assets/photos/yemenchef/items/item-061.jpg",
  "price": 150,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة جرجر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mshkl-slt",
  "name": "مشكل سلطة",
  "image": "/assets/photos/yemenchef/items/item-062.jpg",
  "price": 250,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "مشكل سلطة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bsbas-akhdr",
  "name": "بسباس اخضر",
  "image": "/assets/photos/yemenchef/items/item-063.jpeg",
  "price": 40,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "بسباس اخضر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-aarby",
  "name": "سلطة عربية",
  "image": "/assets/photos/yemenchef/items/item-064.jpg",
  "price": 155,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة عربية من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "hlb-1",
  "name": "حلبة",
  "image": "/assets/photos/yemenchef/items/item-065.jpeg",
  "price": 40,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "حلبة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-tbolh",
  "name": "سلطة تبوله",
  "image": "/assets/photos/yemenchef/items/item-066.jpg",
  "price": 185,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة تبوله من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ktaa-gbn",
  "name": "قطعة جبن",
  "image": "/assets/photos/yemenchef/items/item-067.jpeg",
  "price": 40,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "قطعة جبن من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-yonany",
  "name": "سلطة يونانية",
  "image": "/assets/photos/yemenchef/items/item-068.jpg",
  "price": 180,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة يونانية من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mtbl",
  "name": "متبل",
  "image": "/assets/photos/yemenchef/items/item-069.jpg",
  "price": 170,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "متبل من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "slt-thyny",
  "name": "سلطة طحينية",
  "image": "/assets/photos/yemenchef/items/item-070.jpg",
  "price": 165,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سلطة طحينية من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaok-ahmr",
  "name": "سحاوق احمر",
  "image": "/assets/photos/yemenchef/items/item-071.jpg",
  "price": 20,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سحاوق احمر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shaok-gbn",
  "name": "سحاوق جبن",
  "image": "/assets/photos/yemenchef/items/item-072.jpg",
  "price": 55,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "سحاوق جبن من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "zbady-1",
  "name": "زبادي",
  "image": "/assets/photos/yemenchef/items/item-073.jpg",
  "price": 40,
  "unit": "قطعة",
  "category": "سلطات ومقبلات",
  "available": true,
  "featured": false,
  "description": "زبادي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "sanon-smk",
  "name": "صانونة سمك",
  "image": "/assets/photos/yemenchef/items/item-074.jpg",
  "price": 470,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "صانونة سمك من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "smk-mkly",
  "name": "سمك مقلي",
  "image": "/assets/photos/yemenchef/items/item-075.jpg",
  "price": 495,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "سمكه وزن 800 جرام",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aakd-smk",
  "name": "عقدة سمك",
  "image": "/assets/photos/yemenchef/items/item-076.jpg",
  "price": 470,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "عقدة سمك من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "gmbry-mkly",
  "name": "جمبري مقلي",
  "image": "/assets/photos/yemenchef/items/item-077.jpeg",
  "price": 470,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "جمبري مقلي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "tonh-hrdh",
  "name": "تونه حرضه",
  "image": "/assets/photos/yemenchef/items/item-078.jpg",
  "price": 250,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "تونه حرضه من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aakd-gmbry",
  "name": "عقدة جمبري",
  "image": "/assets/photos/yemenchef/items/item-079.jpg",
  "price": 470,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "عقدة جمبري من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "sanon-gmbry",
  "name": "صانونة جمبري",
  "image": "/assets/photos/yemenchef/items/item-080.jpg",
  "price": 470,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "صانونة جمبري من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "smk-mof",
  "name": "سمك موفى",
  "image": "/assets/photos/yemenchef/items/item-081.jpg",
  "price": 495,
  "unit": "قطعة",
  "category": "الاطباق البحرية",
  "available": true,
  "featured": false,
  "description": "سمكه وزن 800 جرام",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "rbt-khbz-sory",
  "name": "ربطة خبز سوري",
  "image": "/assets/photos/yemenchef/items/item-082.jpg",
  "price": 37,
  "unit": "قطعة",
  "category": "معجنات",
  "available": true,
  "featured": false,
  "description": "ربطة خبز سوري من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mloh-sghyr",
  "name": "ملوح صغير",
  "image": "/assets/photos/yemenchef/items/item-083.jpg",
  "price": 40,
  "unit": "قطعة",
  "category": "معجنات",
  "available": true,
  "featured": false,
  "description": "ملوح صغير من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mloh-kbyr",
  "name": "ملوح كبير",
  "image": "/assets/photos/yemenchef/items/item-084.jpg",
  "price": 80,
  "unit": "قطعة",
  "category": "معجنات",
  "available": true,
  "featured": false,
  "description": "ملوح كبير من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "khbz-rtb",
  "name": "خبز رطب",
  "image": "/assets/photos/yemenchef/items/item-085.jpg",
  "price": 60,
  "unit": "قطعة",
  "category": "معجنات",
  "available": true,
  "featured": false,
  "description": "خبز رطب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aaryk-mlky",
  "name": "عريكة ملكي",
  "image": "/assets/photos/yemenchef/items/item-086.jpg",
  "price": 210,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "عريكة ملكي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mks-zbydy-ft-tmr",
  "name": "مكس (عريكة + فتة زبيدي )",
  "image": "/assets/photos/yemenchef/items/item-087.jpeg",
  "price": 210,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "مكس (عريكة + فتة زبيدي ) من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fth-zbydy",
  "name": "فته زبيدي",
  "image": "/assets/photos/yemenchef/items/item-088.jpg",
  "price": 175,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فته زبيدي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fn-moz",
  "name": "فتة موز",
  "image": "/assets/photos/yemenchef/items/item-089.jpg",
  "price": 150,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فتة موز من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aaryk-aaady",
  "name": "عريكة عادي",
  "image": "/assets/photos/yemenchef/items/item-090.webp",
  "price": 180,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "عريكة عادي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mks-maasob-oaarykh",
  "name": "مكس معصوب وعريكه",
  "image": "/assets/photos/yemenchef/items/item-091.jpg",
  "price": 220,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "مكس معصوب وعريكه من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mhlby-krmyla",
  "name": "مهلبية كرميلا",
  "image": "/assets/photos/yemenchef/items/item-092.jpeg",
  "price": 95,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "مهلبية كرميلا من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ft-aasl",
  "name": "فتة عسل",
  "image": "/assets/photos/yemenchef/items/item-093.jpg",
  "price": 150,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فتة عسل من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maasob-mlky",
  "name": "معصوب ملكي",
  "image": "/assets/photos/yemenchef/items/item-094.jpg",
  "price": 210,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "معصوب ملكي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ksht-1",
  "name": "قشطة",
  "image": "/assets/photos/yemenchef/items/item-095.jpeg",
  "price": 75,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "قشطة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "ft-tmr",
  "name": "فتة تمر",
  "image": "/assets/photos/yemenchef/items/item-096.jpg",
  "price": 150,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "فتة تمر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maasob-aaady",
  "name": "معصوب عادي",
  "image": "/assets/photos/yemenchef/items/item-097.jpg",
  "price": 180,
  "unit": "قطعة",
  "category": "حلويات",
  "available": true,
  "featured": false,
  "description": "معصوب عادي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "koktyl",
  "name": "كوكتيل",
  "image": "/assets/photos/yemenchef/items/item-098.jpg",
  "price": 190,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "كوكتيل من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afokado-balhlyb-oalaasl",
  "name": "افوكادو بالحليب والعسل",
  "image": "/assets/photos/yemenchef/items/item-099.jpg",
  "price": 190,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "افوكادو بالحليب والعسل من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mango-balhlyb",
  "name": "مانجو بالحليب",
  "image": "/assets/photos/yemenchef/items/item-100.jpg",
  "price": 155,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "مانجو بالحليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lymon-balnaanaaa",
  "name": "ليمون بالنعناع",
  "image": "/assets/photos/yemenchef/items/item-101.jpg",
  "price": 140,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "ليمون بالنعناع من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fraol",
  "name": "فراولة",
  "image": "/assets/photos/yemenchef/items/item-102.jpg",
  "price": 165,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "فراولة من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afokado-balmksrat",
  "name": "افوكادو بالمكسرات",
  "image": "/assets/photos/yemenchef/items/item-103.webp",
  "price": 220,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "افوكادو بالمكسرات من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afokado",
  "name": "افوكادو",
  "image": "/assets/photos/yemenchef/items/item-104.jpg",
  "price": 175,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "افوكادو من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "brtkal-kbs",
  "name": "برتقال كبس",
  "image": "/assets/photos/yemenchef/items/item-105.jpg",
  "price": 150,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "برتقال كبس من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lymon",
  "name": "ليمون",
  "image": "/assets/photos/yemenchef/items/item-106.jpg",
  "price": 130,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "ليمون من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aasyr-fymto",
  "name": "عصير فيمتو",
  "image": "/assets/photos/yemenchef/items/item-107.jpg",
  "price": 125,
  "unit": "قطعة",
  "category": "عصائر",
  "available": false,
  "featured": false,
  "description": "عصير فيمتو من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fraol-balhlyb",
  "name": "فراولة بالحليب",
  "image": "/assets/photos/yemenchef/items/item-108.jpg",
  "price": 175,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "فراولة بالحليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "moz-balhlyb",
  "name": "موز بالحليب",
  "image": "/assets/photos/yemenchef/items/item-109.jpg",
  "price": 155,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "موز بالحليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "afokado-balhlyb",
  "name": "افوكادو بالحليب",
  "image": "/assets/photos/yemenchef/items/item-110.jpg",
  "price": 180,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "افوكادو بالحليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mango-frysh",
  "name": "مانجو فريش",
  "image": "/assets/photos/yemenchef/items/item-111.jpg",
  "price": 140,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "مانجو فريش من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "lymon-balhlyb",
  "name": "ليمون بالحليب",
  "image": "/assets/photos/yemenchef/items/item-112.jpg",
  "price": 140,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "ليمون بالحليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aaraysy",
  "name": "عرايسي",
  "image": "/assets/photos/yemenchef/items/item-113.jpg",
  "price": 235,
  "unit": "قطعة",
  "category": "عصائر",
  "available": true,
  "featured": false,
  "description": "عرايسي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "brad-shay-aadny",
  "name": "براد شاي عدني",
  "image": "/assets/photos/yemenchef/items/item-114.jpeg",
  "price": 290,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "براد شاي عدني من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "bn-balhlyb",
  "name": "بن بالحليب",
  "image": "/assets/photos/yemenchef/items/item-115.jpg",
  "price": 100,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "بن بالحليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shay-hlyb",
  "name": "شاي حليب",
  "image": "/assets/photos/yemenchef/items/item-116.jpg",
  "price": 65,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي حليب من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "brad-shay-ahmr-1",
  "name": "براد شاي احمر",
  "image": "/assets/photos/yemenchef/items/item-117.png",
  "price": 150,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "براد شاي احمر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "thlag-shay-aadny",
  "name": "ثلاجة شاي عدني",
  "image": "/assets/photos/yemenchef/items/item-118.webp",
  "price": 450,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "ثلاجة شاي عدني من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "brad-ahmr",
  "name": "ثلاجة  احمر",
  "image": "/assets/photos/yemenchef/items/item-119.jpg",
  "price": 250,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "ثلاجة  احمر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "shay-ahmr",
  "name": "شاي احمر",
  "image": "/assets/photos/yemenchef/items/item-120.jpg",
  "price": 30,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "شاي احمر من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kho-trky-24",
  "name": "قهوة تركي",
  "image": "/assets/photos/yemenchef/items/item-121.webp",
  "price": 95,
  "unit": "قطعة",
  "category": "مشروبات ساخنة",
  "available": true,
  "featured": false,
  "description": "قهوة تركي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "aayran-kbyr",
  "name": "عيران كبير",
  "image": "/assets/photos/yemenchef/items/item-122.jpg",
  "price": 40,
  "unit": "قطعة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "عيران كبير من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mshrob-brtkal",
  "name": "فانتا تركي",
  "image": "/assets/photos/yemenchef/items/item-123.jpg",
  "price": 50,
  "unit": "قطعة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "فانتا تركي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "mshrob-lymon",
  "name": "سبرايت تركي",
  "image": "/assets/photos/yemenchef/items/item-124.webp",
  "price": 50,
  "unit": "قطعة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "سبرايت تركي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kola-trky",
  "name": "كولا تركية",
  "image": "/assets/photos/yemenchef/items/item-125.jpg",
  "price": 50,
  "unit": "قطعة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "كولا تركية من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "maaa-19",
  "name": "ماء",
  "image": "/assets/photos/yemenchef/items/item-126.jpg",
  "price": 15,
  "unit": "قنينة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "ماء من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "fmto-tot",
  "name": "فمتو توت",
  "image": "/assets/photos/yemenchef/items/item-127.jpg",
  "price": 50,
  "unit": "قطعة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "فمتو توت من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "kola-zyro-trky",
  "name": "كولا زيرو تركية",
  "image": "/assets/photos/yemenchef/items/item-128.jpeg",
  "price": 50,
  "unit": "قطعة",
  "category": "مشروبات بارده",
  "available": true,
  "featured": false,
  "description": "كولا زيرو تركية من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "thbyh",
  "name": "ذبيحة مندي",
  "image": "/assets/photos/yemenchef/items/item-129.jpg",
  "price": 11000,
  "unit": "قطعة",
  "category": "وجبات ولائم",
  "available": true,
  "featured": false,
  "description": "ذبيحة مندي من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 },
 {
  "sourceId": "hb-moz-1",
  "name": "حبة موز",
  "image": "/assets/photos/yemenchef/items/item-130.jpg",
  "price": 45,
  "unit": "قطعة",
  "category": "اضافات",
  "available": true,
  "featured": false,
  "description": "حبة موز من مطعم يمن شيف.",
  "imageFit": "cover",
  "options": []
 }
];

const yemenchefProducts = yemenchefProductCatalog.map((product, index) => ({
  ...product,
  id: 30001 + index,
  storeId: yemenchefStore.id
}));

const yemenchefDeliverySettings = {
  [yemenchefStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 15, prepMinutes: 35, maxRoundTripKm: 120 }
};
