// Generated for زمزم ماركت (Zemzem Market) — Fly Garden, Yeşilkent, Esenyurt/İstanbul.
// Arabic/Egyptian supermarket. Source: WhatsApp Business catalog (wa.me/c/905534400275),
// 161 products across 16 categories, full-res images. Coords/rating/hours from Google Maps
// (Place ID ChIJ_yXMTTtftRQR5xkwIunAi2o, 4.8/19 reviews).
const zamzamStore = {
 "id": 96,
 "name": "زمزم ماركت",
 "category": "سوبر ماركت",
 "image": "/assets/photos/zamzam/cover.jpg",
 "coverImage": "/assets/photos/zamzam/cover.jpg",
 "logoImage": "/assets/photos/zamzam/logo.png",
 "logo": "ز",
 "rating": 4.8,
 "reviews": 19,
 "newStore": true,
 "delivery": 35,
 "minOrder": 150,
 "time": "30 - 60 دقيقة",
 "distance": 0,
 "location": {
  "lat": 41.0215683,
  "lng": 28.6603221
 },
 "mapUrl": "https://www.google.com/maps/search/?api=1&query=41.0215683,28.6603221",
 "open": true,
 "featured": true,
 "hasOffer": false,
 "offer": "",
 "description": "زمزم ماركت — سوبر ماركت عربي في اسنيورت يقدّم منتجات عربية ومصرية أصيلة: أجبان وألبان، بن وقهوة، حلويات بيتي، تمور ومكسرات، سمن وعسل، مجمدات، بهارات، منتجات عناية، وزينة رمضان. توصيل لمناطق إسطنبول.",
 "address": "Fly Garden Residence, Yeşilkent, 1953. Sk. No:42A, 34510 Esenyurt/İstanbul",
 "phone": "+90 553 440 02 75",
 "whatsapp": "+90 553 440 02 75",
 "email": "",
 "website": "",
 "sourceUrl": "https://wa.me/c/905534400275",
 "hours": "يومياً من الساعة 9:00 صباحاً حتى منتصف الليل",
 "areas": [
  "اسنيورت",
  "مناطق إسطنبول حسب المسافة"
 ],
 "fulfillment": "توصيل واستلام",
 "subscription": "احترافي",
 "orderCount": 0,
 "officialStore": true,
 "googlePlaceId": "ChIJ_yXMTTtftRQR5xkwIunAi2o",
 "googleRating": 4.8,
 "googleReviewsCount": 19,
 "googleMapsUrl": "https://maps.google.com/?cid=7677442097316633063"
};

const zamzamFullCatalog = [
  {"name": "جبن رودس حليب طبيعي ١٠٠%", "price": 240.0, "category": "قسم الاجبان", "unit": "500 جرام", "image": "/assets/photos/zamzam/p001.jpg"},
  {"name": "جبن رودس حليب طبيعي ١٠٠%", "price": 130.0, "category": "قسم الاجبان", "unit": "250 جرام", "image": "/assets/photos/zamzam/p002.jpg"},
  {"name": "جبن فيتا بطعم الفلمنك", "price": 65.0, "category": "قسم الاجبان", "unit": "250 جرام", "image": "/assets/photos/zamzam/p003.jpg"},
  {"name": "كرواسون", "price": 24.0, "category": "قسم الاجبان", "unit": "قطعة", "image": "/assets/photos/zamzam/p004.jpg", "description": "شكولاتة و جبنة"},
  {"name": "قرص بالسكر", "price": 25.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p005.jpg"},
  {"name": "بقسماط", "price": 85.0, "category": "مخبوزات", "unit": "قطعة", "image": "/assets/photos/zamzam/p006.jpg"},
  {"name": "جبنة اسطنبولي", "price": 250.0, "category": "قسم الاجبان", "unit": "300 جرام", "image": "/assets/photos/zamzam/p007.jpg"},
  {"name": "جبنة ملح خفيف", "price": 110.0, "category": "قسم الاجبان", "unit": "٢٥٠ جرام", "image": "/assets/photos/zamzam/p008.jpg"},
  {"name": "جبن دوبل كريم", "price": 200.0, "category": "قسم الاجبان", "unit": "350 جرام", "image": "/assets/photos/zamzam/p009.jpg"},
  {"name": "Buldak", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p010.jpg"},
  {"name": "3X Spicy", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p011.jpg"},
  {"name": "Ramen", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p012.jpg"},
  {"name": "شاور جيل كريمي", "price": 180.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p013.jpg"},
  {"name": "معطر الغرفة بالعود الملكي", "price": 245.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p014.jpg"},
  {"name": "مناديل مبللة للمناطق الحساسة", "price": 115.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p015.jpg"},
  {"name": "خلود", "price": 225.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p016.jpg", "description": "معطر الجو والمفروشات برائحة المسك"},
  {"name": "أنسام", "price": 225.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p017.jpg", "description": "معطر جسم مسك وعود"},
  {"name": "سما", "price": 225.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p018.jpg", "description": "رائحة المانجو"},
  {"name": "بن العلبي", "price": 195.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p019.jpg", "description": "مع هال"},
  {"name": "بن العلبي", "price": 175.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p020.jpg", "description": "بدون هال"},
  {"name": "بن الشام", "price": 160.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p021.jpg", "description": "قهوة كولومبي"},
  {"name": "حلاوة سبريد", "price": 145.0, "category": "حلاوة و طحينة", "unit": "قطعة", "image": "/assets/photos/zamzam/p022.jpg"},
  {"name": "مربى البوادى", "price": 95.0, "category": "البوادى", "unit": "قطعة", "image": "/assets/photos/zamzam/p023.jpg"},
  {"name": "عسل أسود", "price": 165.0, "category": "عسل طبيعي", "unit": "650 جرام", "image": "/assets/photos/zamzam/p024.jpg"},
  {"name": "كوكي مكس", "price": 350.0, "category": "الصعيدي", "unit": "قطعة", "image": "/assets/photos/zamzam/p025.jpg"},
  {"name": "كنافة سيجار الصعيدي", "price": 340.0, "category": "الصعيدي", "unit": "قطعة", "image": "/assets/photos/zamzam/p026.jpg", "description": "مع الصوصات"},
  {"name": "ميكس جولد الصعيدي", "price": 350.0, "category": "الصعيدي", "unit": "500 غرام", "image": "/assets/photos/zamzam/p027.jpg"},
  {"name": "شرائح جوافة مجمدة", "price": 160.0, "category": "مجمدات", "unit": "1 KG", "image": "/assets/photos/zamzam/p028.jpg"},
  {"name": "بازلاء بالجزر", "price": 65.0, "category": "مجمدات", "unit": "٤٠٠ جرام", "image": "/assets/photos/zamzam/p029.jpg"},
  {"name": "ملوخية مفرومة مجمدة", "price": 65.0, "category": "مجمدات", "unit": "٤٠٠ جرام", "image": "/assets/photos/zamzam/p030.jpg"},
  {"name": "جبنة", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p031.jpg"},
  {"name": "لب أبيض مصري", "price": 155.0, "category": "منتجات من مصر", "unit": "الربع", "image": "/assets/photos/zamzam/p032.jpg"},
  {"name": "بيتيفور وسابليه", "price": 330.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p033.jpg"},
  {"name": "كرتونة مفتل القصيم", "price": 650.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p034.jpg"},
  {"name": "طقم مفارش رمضان استخدام واحد", "price": 170.0, "category": "زينة رمضان", "unit": "٣ رول", "image": "/assets/photos/zamzam/p035.jpg"},
  {"name": "موتزاريلا مصري", "price": 190.0, "category": "قسم الاجبان", "unit": "نص كيلو", "image": "/assets/photos/zamzam/p036.jpg"},
  {"name": "معكرونة ARBELLA", "price": 25.0, "category": "منتجات من مصر", "unit": "الكيس", "image": "/assets/photos/zamzam/p037.jpg"},
  {"name": "اسبراي مزيل عرق", "price": 195.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p038.jpg"},
  {"name": "قهوة فلسطينية BH", "price": 250.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p039.jpg", "description": "إكسترا هال"},
  {"name": "سمن بلدي جاموسي", "price": 460.0, "category": "سمن وزبدة", "unit": "500 جرام", "image": "/assets/photos/zamzam/p040.jpg"},
  {"name": "سمن بلدي جاموسي", "price": 780.0, "category": "سمن وزبدة", "unit": "850 جرام", "image": "/assets/photos/zamzam/p041.jpg"},
  {"name": "سمن بلدي بقري", "price": 735.0, "category": "سمن وزبدة", "unit": "850 جرام", "image": "/assets/photos/zamzam/p042.jpg"},
  {"name": "عسل بالمكسرات", "price": 340.0, "category": "عسل طبيعي", "unit": "نصف كيلو", "image": "/assets/photos/zamzam/p043.jpg"},
  {"name": "دومتى جبن فيتا بطعم الزيتون", "price": 65.0, "category": "قسم الاجبان", "unit": "250 جرام", "image": "/assets/photos/zamzam/p044.jpg"},
  {"name": "طحينة", "price": 100.0, "category": "حلاوة و طحينة", "unit": "400 جرام", "image": "/assets/photos/zamzam/p045.jpg"},
  {"name": "طحينة", "price": 160.0, "category": "حلاوة و طحينة", "unit": "750 جرام", "image": "/assets/photos/zamzam/p046.jpg"},
  {"name": "كاسات اللوتس", "price": 100.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p047.jpg"},
  {"name": "بسبوسة بالسمن البلدي", "price": 160.0, "category": "سمن وزبدة", "unit": "قطعة", "image": "/assets/photos/zamzam/p048.jpg", "description": "النص كيلو"},
  {"name": "سينابون كراميل", "price": 90.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p049.jpg"},
  {"name": "طقم الحبايب", "price": 290.0, "category": "زينة رمضان", "unit": "قطعة", "image": "/assets/photos/zamzam/p050.jpg"},
  {"name": "لوحة ثلاثية رمضان", "price": 200.0, "category": "زينة رمضان", "unit": "قطعة", "image": "/assets/photos/zamzam/p051.jpg"},
  {"name": "مشمش مجفف", "price": 185.0, "category": "تمور وفواكه مجففة", "unit": "طبق ٣٥٠ جرام", "image": "/assets/photos/zamzam/p052.jpg"},
  {"name": "خروب مجروش", "price": 320.0, "category": "تمور وفواكه مجففة", "unit": "الكيلو", "image": "/assets/photos/zamzam/p053.jpg"},
  {"name": "جبنة بالقشطة", "price": 160.0, "category": "قسم الاجبان", "unit": "٤٠٠ جرام", "image": "/assets/photos/zamzam/p054.jpg"},
  {"name": "زبدة جاموسي بايازيد", "price": 690.0, "category": "منتجات بيازيد", "unit": "كيلو", "image": "/assets/photos/zamzam/p055.jpg"},
  {"name": "كنافة مجففة كورنيه", "price": 140.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p056.jpg"},
  {"name": "مخلل مصري", "price": 60.0, "category": "منتجات من مصر", "unit": "ربع كيلو", "image": "/assets/photos/zamzam/p057.jpg"},
  {"name": "جبن موزاريلا Rifal", "price": 360.0, "category": "قسم الاجبان", "unit": "1 كيلو", "image": "/assets/photos/zamzam/p058.jpg"},
  {"name": "جبنة رومي قابلة للدهن قتيلو", "price": 165.0, "category": "قسم الاجبان", "unit": "٢٤٠ جرام", "image": "/assets/photos/zamzam/p059.jpg"},
  {"name": "عجينة طعمية", "price": 75.0, "category": "مخبوزات", "unit": "٥٠٠ جرام", "image": "/assets/photos/zamzam/p060.jpg"},
  {"name": "شاي العروسة", "price": 45.0, "category": "منتجات من مصر", "unit": "100 جرام", "image": "/assets/photos/zamzam/p061.jpg"},
  {"name": "جبنة الكواترو", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p062.jpg"},
  {"name": "لمسة", "price": 225.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p063.jpg", "description": "رائحة البحر"},
  {"name": "بيسكو ميكس", "price": 330.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p064.jpg"},
  {"name": "توابل البطاطس و الفشار", "price": 90.0, "category": "منتجات من مصر", "unit": "50 جرام", "image": "/assets/photos/zamzam/p065.jpg"},
  {"name": "شاي الكابوس خرز", "price": 130.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p066.jpg"},
  {"name": "Ajvar Sos", "price": 56.0, "category": "مجمدات", "unit": "صوص الفلفل والباذنجان والثوم 350 جرام", "image": "/assets/photos/zamzam/p067.jpg"},
  {"name": "شامبو بدون سلفات", "price": 230.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p068.jpg"},
  {"name": "قشطة قيمر", "price": 40.0, "category": "قسم الاجبان", "unit": "قطعة", "image": "/assets/photos/zamzam/p069.jpg"},
  {"name": "المراعي 24 قطعة", "price": 125.0, "category": "منتجات من مصر", "unit": "300 جرام", "image": "/assets/photos/zamzam/p070.jpg"},
  {"name": "حلاوة سبريد بالكراميل", "price": 145.0, "category": "حلاوة و طحينة", "unit": "قطعة", "image": "/assets/photos/zamzam/p071.jpg"},
  {"name": "دومتي جبن اسطنبولي", "price": 65.0, "category": "قسم الاجبان", "unit": "250 جرام", "image": "/assets/photos/zamzam/p072.jpg"},
  {"name": "كنافة عش غراب", "price": 140.0, "category": "حلويات بيتي", "unit": "٤٥ قطعة", "image": "/assets/photos/zamzam/p073.jpg"},
  {"name": "صلصال فوم", "price": 70.0, "category": "منتجات من مصر", "unit": "١٢ لون مع ادواته", "image": "/assets/photos/zamzam/p074.jpg"},
  {"name": "هابانيرو ليمون", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p075.jpg"},
  {"name": "بهارات سنا", "price": 35.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p076.jpg", "description": "مجموعة بهارات سنا"},
  {"name": "فورمة بسبوسة مكسرات الصعيدي", "price": 450.0, "category": "الصعيدي", "unit": "قطعة", "image": "/assets/photos/zamzam/p077.jpg"},
  {"name": "لوشن للجسم", "price": 230.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p078.jpg"},
  {"name": "كسكسي", "price": 240.0, "category": "منتجات من مصر", "unit": "كيلو", "image": "/assets/photos/zamzam/p079.jpg"},
  {"name": "سبونج جاهز", "price": 220.0, "category": "منتجات من مصر", "unit": "النص", "image": "/assets/photos/zamzam/p080.jpg"},
  {"name": "فانوس مضئ", "price": 85.0, "category": "زينة رمضان", "unit": "قطعة", "image": "/assets/photos/zamzam/p081.jpg"},
  {"name": "كنافة رولات", "price": 160.0, "category": "حلويات بيتي", "unit": "نص كيلو", "image": "/assets/photos/zamzam/p082.jpg"},
  {"name": "حلاوة سبريد بالشيكولاتة و البندق", "price": 145.0, "category": "حلاوة و طحينة", "unit": "قطعة", "image": "/assets/photos/zamzam/p083.jpg"},
  {"name": "تورتة ريد فيلفت", "price": 390.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p084.jpg"},
  {"name": "مفرش سفرة كبير مطعم بخط عربي", "price": 370.0, "category": "زينة رمضان", "unit": "قطعة", "image": "/assets/photos/zamzam/p085.jpg"},
  {"name": "كاربونارا", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p086.jpg"},
  {"name": "علبة لبان سمارة حجم صغير", "price": 185.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p087.jpg"},
  {"name": "بن الحموي", "price": 230.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p088.jpg", "description": "إكسترا هال"},
  {"name": "مايونيز", "price": 45.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p089.jpg"},
  {"name": "فول أخضر مجمد", "price": 75.0, "category": "مجمدات", "unit": "400 جرام", "image": "/assets/photos/zamzam/p090.jpg"},
  {"name": "تمر سكري رطب", "price": 550.0, "category": "تمور وفواكه مجففة", "unit": "كرتونة من ٣ ل٤ كيلو", "image": "/assets/photos/zamzam/p091.jpg"},
  {"name": "شاي العروسة", "price": 110.0, "category": "منتجات من مصر", "unit": "250 جرام", "image": "/assets/photos/zamzam/p092.jpg"},
  {"name": "لب سوبر مصري", "price": 145.0, "category": "منتجات من مصر", "unit": "250 جرام", "image": "/assets/photos/zamzam/p093.jpg"},
  {"name": "كاسات الريد فيلفت", "price": 90.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p094.jpg"},
  {"name": "سمن بلدي بقري", "price": 435.0, "category": "سمن وزبدة", "unit": "500 جرام", "image": "/assets/photos/zamzam/p095.jpg"},
  {"name": "توابل البطاطس والفشار", "price": 140.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p096.jpg", "description": "طعم البيتزا . الكباب .شطة وليمون .بسطرمة"},
  {"name": "المراعي 8 قطع", "price": 45.0, "category": "منتجات من مصر", "unit": "100 جرام", "image": "/assets/photos/zamzam/p097.jpg"},
  {"name": "برازق فرط", "price": 275.0, "category": "حلويات بيتي", "unit": "الكيلو ب275", "image": "/assets/photos/zamzam/p098.jpg"},
  {"name": "فول الشهية", "price": 25.0, "category": "منتجات من مصر", "unit": "400 جرام", "image": "/assets/photos/zamzam/p099.jpg"},
  {"name": "سابليه مكس الصعيدي", "price": 440.0, "category": "الصعيدي", "unit": "35 قطعة", "image": "/assets/photos/zamzam/p100.jpg"},
  {"name": "دوم مجروش", "price": 350.0, "category": "تمور وفواكه مجففة", "unit": "الكيلو", "image": "/assets/photos/zamzam/p101.jpg"},
  {"name": "بهارات مصرية", "price": 50.0, "category": "مجمدات", "unit": "قطعة", "image": "/assets/photos/zamzam/p102.jpg", "description": "حواوشي،محشي،تندوري،كفتة الحاتي، ملوخية،أسماك،مشويات ،بشاميل"},
  {"name": "بيتي فور الصعيدي", "price": 350.0, "category": "الصعيدي", "unit": "قطعة", "image": "/assets/photos/zamzam/p103.jpg"},
  {"name": "بسبوسة", "price": 80.0, "category": "حلويات بيتي", "unit": "الربع", "image": "/assets/photos/zamzam/p104.jpg"},
  {"name": "أيس كريم دريم", "price": 50.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p105.jpg"},
  {"name": "سمنة جنة", "price": 240.0, "category": "سمن وزبدة", "unit": "صافي ٧٠٠ جرام", "image": "/assets/photos/zamzam/p106.jpg"},
  {"name": "بامية ڤيجي ترك", "price": 75.0, "category": "مجمدات", "unit": "400 جرام", "image": "/assets/photos/zamzam/p107.jpg"},
  {"name": "فورمة كنافة مخلوطة مكسرات", "price": 450.0, "category": "الصعيدي", "unit": "قطعة", "image": "/assets/photos/zamzam/p108.jpg"},
  {"name": "حلاوة محروسه زمان 300 جرام", "price": 90.0, "category": "حلاوة و طحينة", "unit": "300 جرام", "image": "/assets/photos/zamzam/p109.jpg"},
  {"name": "تمر سكري", "price": 125.0, "category": "تمور وفواكه مجففة", "unit": "نصف كيلو", "image": "/assets/photos/zamzam/p110.jpg"},
  {"name": "سمبوسة قرمش", "price": 115.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p111.jpg"},
  {"name": "سمبوسة العزة", "price": 125.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p112.jpg"},
  {"name": "مولتن كيك دريم", "price": 195.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p113.jpg"},
  {"name": "ميست للجسم والشعر", "price": 240.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p114.jpg"},
  {"name": "حلاوة مهروسة زمان", "price": 1000.0, "category": "حلاوة و طحينة", "unit": "5 كيلو", "image": "/assets/photos/zamzam/p115.jpg"},
  {"name": "برازق", "price": 185.0, "category": "حلويات بيتي", "unit": "العلبة", "image": "/assets/photos/zamzam/p116.jpg"},
  {"name": "حلاوة مهروسة زمان", "price": 320.0, "category": "حلاوة و طحينة", "unit": "1800 جرام", "image": "/assets/photos/zamzam/p117.jpg"},
  {"name": "عجوة", "price": 85.0, "category": "تمور وفواكه مجففة", "unit": "قطعة", "image": "/assets/photos/zamzam/p118.jpg"},
  {"name": "علبة لبان سمارة بالعسل", "price": 185.0, "category": "عسل طبيعي", "unit": "قطعة", "image": "/assets/photos/zamzam/p119.jpg"},
  {"name": "مورتة  طبيعي ١٠٠% قتيلو", "price": 130.0, "category": "قسم الاجبان", "unit": "٢٥٠ جرام", "image": "/assets/photos/zamzam/p120.jpg"},
  {"name": "زيت جوز الهند", "price": 250.0, "category": "منتجات من مصر", "unit": "330 mle", "image": "/assets/photos/zamzam/p121.jpg"},
  {"name": "جَميد", "price": 100.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p122.jpg"},
  {"name": "مشبك دمياطي", "price": 85.0, "category": "حلويات بيتي", "unit": "القرص", "image": "/assets/photos/zamzam/p123.jpg"},
  {"name": "كاتشب", "price": 75.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p124.jpg"},
  {"name": "سينابون كراميل ومكسرات", "price": 120.0, "category": "حلويات بيتي", "unit": "قطعة", "image": "/assets/photos/zamzam/p125.jpg"},
  {"name": "بن الحموي", "price": 185.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p126.jpg", "description": "إكسترا هال غامق"},
  {"name": "قلقاس محمد", "price": 75.0, "category": "منتجات من مصر", "unit": "400 جرام", "image": "/assets/photos/zamzam/p127.jpg"},
  {"name": "ندى", "price": 225.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p128.jpg", "description": "رائحة الفواكة المشكلة"},
  {"name": "سمنة بقري طبيعي بيتي", "price": 310.0, "category": "سمن وزبدة", "unit": "قطعة", "image": "/assets/photos/zamzam/p129.jpg"},
  {"name": "حلاوة الجبن", "price": 100.0, "category": "قسم الاجبان", "unit": "قطعة", "image": "/assets/photos/zamzam/p130.jpg"},
  {"name": "معكرونة Filiz", "price": 30.0, "category": "منتجات من مصر", "unit": "الكيس", "image": "/assets/photos/zamzam/p131.jpg"},
  {"name": "باذنجان مشوي مجمد", "price": 140.0, "category": "مجمدات", "unit": "1 KG", "image": "/assets/photos/zamzam/p132.jpg"},
  {"name": "باتون ساليه", "price": 85.0, "category": "منتجات من مصر", "unit": "كيس", "image": "/assets/photos/zamzam/p133.jpg"},
  {"name": "علبة لبان سمارة كبيرة", "price": 180.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p134.jpg"},
  {"name": "حبل مثلثات", "price": 15.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p135.jpg"},
  {"name": "جبنة طبيعي كاسات باندا", "price": 135.0, "category": "قسم الاجبان", "unit": "قطعة", "image": "/assets/photos/zamzam/p136.jpg"},
  {"name": "زبدة بقري بايازيد", "price": 690.0, "category": "منتجات بيازيد", "unit": "كيلو", "image": "/assets/photos/zamzam/p137.jpg"},
  {"name": "سمنة جاموسي", "price": 650.0, "category": "سمن وزبدة", "unit": "كيلو", "image": "/assets/photos/zamzam/p138.jpg"},
  {"name": "كعب غزال", "price": 100.0, "category": "حلويات بيتي", "unit": "العلبة", "image": "/assets/photos/zamzam/p139.jpg"},
  {"name": "حلاوة محروسة ابناء العم 350 جرام", "price": 120.0, "category": "حلاوة و طحينة", "unit": "350 جرام", "image": "/assets/photos/zamzam/p140.jpg"},
  {"name": "جبنة قريش", "price": 150.0, "category": "قسم الاجبان", "unit": "نصف كيلو", "image": "/assets/photos/zamzam/p141.jpg"},
  {"name": "شاي الكابوس ناعم", "price": 125.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p142.jpg"},
  {"name": "مزيل عرق رول-أون مبيض", "price": 245.0, "category": "مسك وعود", "unit": "قطعة", "image": "/assets/photos/zamzam/p143.jpg"},
  {"name": "فراولة مجمدة يلديز", "price": 165.0, "category": "مجمدات", "unit": "كيلو", "image": "/assets/photos/zamzam/p144.jpg"},
  {"name": "معمول", "price": 185.0, "category": "حلويات بيتي", "unit": "العلبة", "image": "/assets/photos/zamzam/p145.jpg"},
  {"name": "بن الحموي", "price": 150.0, "category": "بن", "unit": "قطعة", "image": "/assets/photos/zamzam/p146.jpg", "description": "قهوة سادة بيور"},
  {"name": "شطة فليفلة", "price": 95.0, "category": "منتجات من مصر", "unit": "قطعة", "image": "/assets/photos/zamzam/p147.jpg", "description": "بدر و هنية"},
  {"name": "عسلية مصرية", "price": 30.0, "category": "حلويات بيتي", "unit": "الحبة", "image": "/assets/photos/zamzam/p148.jpg"},
  {"name": "قشطة بطعم العسل", "price": 50.0, "category": "عسل طبيعي", "unit": "قطعة", "image": "/assets/photos/zamzam/p149.jpg"},
  {"name": "جبن براميلي", "price": 215.0, "category": "قسم الاجبان", "unit": "350 جرام", "image": "/assets/photos/zamzam/p150.jpg"},
  {"name": "فول الصفوة", "price": 29.0, "category": "منتجات من مصر", "unit": "400 جرام", "image": "/assets/photos/zamzam/p151.jpg"},
  {"name": "شطة جلوريا", "price": 90.0, "category": "منتجات من مصر", "unit": "474 مل", "image": "/assets/photos/zamzam/p152.jpg"},
  {"name": "ثوم مقشر", "price": 220.0, "category": "منتجات من مصر", "unit": "كيلو", "image": "/assets/photos/zamzam/p153.jpg"},
  {"name": "مكدوس سوري", "price": 320.0, "category": "منتجات من مصر", "unit": "٩٥٠ جرام", "image": "/assets/photos/zamzam/p154.jpg"},
  {"name": "مربى مشمش", "price": 45.0, "category": "تمور وفواكه مجففة", "unit": "380 جرام", "image": "/assets/photos/zamzam/p155.jpg"},
  {"name": "برجر جاست فروزن جواه جبنة", "price": 400.0, "category": "مجمدات", "unit": "قطعة", "image": "/assets/photos/zamzam/p156.jpg"},
  {"name": "كريمة بطعم القشطة", "price": 50.0, "category": "قسم الاجبان", "unit": "قطعة", "image": "/assets/photos/zamzam/p157.jpg"},
  {"name": "دومتي جبن فيتا", "price": 65.0, "category": "قسم الاجبان", "unit": "250 جرام", "image": "/assets/photos/zamzam/p158.jpg"},
  {"name": "لبنة بايازيد", "price": 152.0, "category": "منتجات بيازيد", "unit": "٤٠٠ جرام", "image": "/assets/photos/zamzam/p159.jpg"},
  {"name": "2X Spicy", "price": 150.0, "category": "اندومي كوري", "unit": "قطعة", "image": "/assets/photos/zamzam/p160.jpg"},
  {"name": "شاي عدني", "price": 185.0, "category": "منتجات من مصر", "unit": "علبة", "image": "/assets/photos/zamzam/p161.jpg"},
];

// Repo-bundled catalog is emptied for fast first paint; products load from Supabase.
const zamzamProductCatalog = [];

const zamzamProducts = (zamzamProductCatalog.length ? zamzamProductCatalog : zamzamFullCatalog).map((product, index) => ({
  ...product,
  available: true,
  id: 1780001 + index,
  storeId: zamzamStore.id
}));

const zamzamDeliverySettings = {
  [zamzamStore.id]: { mode: "distance", fixedFee: 35, ratePerKm: 20, prepMinutes: 30, maxRoundTripKm: 120 }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { zamzamStore, zamzamProducts, zamzamDeliverySettings };
}